### ISSUE TITLE
Emscripten 1.39.18 miscompiles WebAssembly Debugging extension

### ISSUE THREAD

**Issue by bmeurer** [emscripten-core/emscripten#11563] opened 2020-07-07 06:31 UTC
Downstream issue: [chromium:1100880](https://crbug.com/1100880)

Since version 1.39.18, compiling the WebAssembly Debugging extension with Emscripten crashes in the LLVM backend. The crash happens in `SelectionDAGISel::CodeGenAndEmitDAG` and is an `indirect_call` to an invalid function table index.

The LLVM backend is used in the extension to JIT-compile WebAssembly code.

@pfaffe was able to bisect the problem to this single change:

- 2020-06-12 dschuff@chromium.org Disable LIBCXX_ABI_OPTIMIZED_FUNCTION (#11403)

**Comment by tlively** [comment] 2020-07-07 17:55
Would it be possible to extract and share the LLVM bitcode that caused the crash or to share some other reproducer? cc @dschuff as this might be a known issue fixed upstream.

**Comment by pfaffe** [comment] 2020-07-20 09:08
Looks like https://github.com/WebAssembly/binaryen/pull/2953 fixed the issue and we can close this!

**Closed** 2020-07-20 16:25 UTC
