### ISSUE TITLE
UNREACHABLE executed at …/binaryen/src/wasm-interpreter.h:503!

### ISSUE THREAD

**Issue by nemequ** [emscripten-core/emscripten#14629] opened 2021-07-12 14:26 UTC
With tot, I'm running into an error when attempting to link a project:

```
# /opt/emsdk/upstream/emscripten/em++ -Weverything -Werror -O3 -msimd128 -g  CMakeFiles/run-tests.dir/run-tests.c.o CMakeFiles/run-tests.dir/x86/run-tests.c.o CMakeFiles/run-tests.dir/x86/avx512/run-tests.c.o CMakeFiles/run-tests.dir/arm/run-tests.c.o CMakeFiles/run-tests.dir/arm/neon/run-tests.c.o CMakeFiles/run-tests.dir/arm/sve/run-tests.c.o CMakeFiles/run-tests.dir/wasm/run-tests.c.o CMakeFiles/run-tests.dir/wasm/simd128/run-tests.c.o CMakeFiles/run-tests.dir/wasm/relaxed-simd/run-tests.c.o CMakeFiles/run-tests.dir/mips/run-tests.c.o CMakeFiles/run-tests.dir/mips/msa/run-tests.c.o -o run-tests.js  libmunit.a  libsimde-test-native.a  libsimde-test-emul.a
unimp
UNREACHABLE executed at /b/s/w/ir/cache/builder/emscripten-releases/binaryen/src/wasm-interpreter.h:503!
em++: error: '/opt/emsdk/upstream/bin/wasm-opt --post-emscripten --no-exit-runtime -O3 --low-memory-unused --zero-filled-memory --strip-producers run-tests.wasm -o run-tests.wasm -g --mvp-features --enable-simd' failed (received SIGABRT (-6))
```

I've uploaded the necessary files to reproduce here: https://www.dropbox.com/s/icpw84ntntbkbh1/simde-unreachable.tar.xz?dl=0

Once you've extracted it, just cd into the simde-unreachable directory, then execute the command above (substituting the path to you em++ if necessary, of course).  After a couple seconds you should get the crash.

If you would prefer the code, it is in this branch: https://github.com/simd-everywhere/simde/tree/emscripten-unreachable.  To compile, something like this should trigger the issue:

```c
mkdir build
cd build
CFLAGS='-Weverything -Werror -O3 -msimd128' CXXFLAGS='-Weverything -Werror -O3 -msimd128' /opt/emsdk/upstream/emscripten/emcmake ../test -G Ninja
ninja
```

**Comment by kripken** [comment] 2021-07-13 18:39
I can reproduce this error locally. The crash is in `--precompute`, in one of the SIMD `unimp` aborts in visitUnary in the wasm interpreter.

@tlively has LLVM started to emit SIMD differently, and Binaryen not been updated to it yet?

**Comment by kripken** [comment] 2021-07-13 18:44
(specific opcode: `BitmaskVecI64x2`)

**Comment by tlively** [comment] 2021-07-13 20:00
I don't think LLVM has started doing anything different with that instruction recently, but it's kind of a niche instruction so I'm not surprised that no one has run precompute on it before.

There are a decent number of SIMD instructions that we haven't implemented in the interpreter yet, but this looks like the only one that doesn't return a v128. The reason none of the other unimplemented instructions have had this issue is that precompute skips visiting expressions that have type v128.

I'll write a PR implementing this instruction in the interpreter.

**Comment by kripken** [comment] 2021-07-13 20:03
@tlively Thanks!

(If it's not trivial, then another option would be to throw the NonPrecomputable exception.)

**Comment by kripken** [comment] 2021-07-13 21:17
Fixed by https://github.com/WebAssembly/binaryen/pull/3982 - thanks @tlively !

**Comment by kripken** [comment] 2021-07-13 21:25
Actually this still crashes. Now the unimplemented opcode is `ExtAddPairwiseSVecI16x8ToI32x4`.

**Comment by kripken** [comment] 2021-07-13 21:35
Should be fixed by https://github.com/WebAssembly/binaryen/pull/3983

**Comment by kripken** [comment] 2021-07-13 22:00
Ac

**Comment by kripken** [comment] 2021-07-13 22:01
Actually even that is not enough. Nest expressions don't go through that code path. Basically, we need to either implement all these SIMD things, or to throw NonPrecomputable in all of them.

@nemequ for now, you can link with `-O2` instead of `-O3` and that should work.

**Comment by mr-c** [comment] 2024-03-21 09:55
Hello from 2024; I'm no longer able to reproduce this using `tot`

**Comment by tlively** [comment] 2024-03-21 16:53
Ok, I'll go ahead and close it. I think at some point we added full interpreter support for SIMD in Binaryen, which would have fixed this bug.

**Closed by tlively** 2024-03-21 16:53 UTC

**Comment by mr-c** [comment] 2024-03-22 13:38
Yep, I git bisected the fix to https://chromium.googlesource.com/emscripten-releases/+/55cccf8d1ce62c3d15d5988a21955c6141f6c678
which includes
https://github.com/webassembly/binaryen/commit/f09bb989a154 "[Simd] Add extending pairwise adds to interpreter (https://github.com/WebAssembly/binaryen/pull/4022)"
and
https://github.com/WebAssembly/binaryen/commit/ac05f9cef1085f62f40990e5fbbfdf32c0860409 "[SIMD] Add extend + mul simd operations to interpreter (https://github.com/WebAssembly/binaryen/pull/4021)"

So emscripten [version 2.0.27](https://github.com/emscripten-core/emscripten/releases/tag/2.0.27) was the first normal release with the fix.
