### ISSUE TITLE
CMAKE_CROSSCOMPILING_EMULATOR issue with Emscripten.cmake toolchain file

### ISSUE THREAD

**Issue by Luthaf** [emscripten-core/emscripten#10028] opened 2019-12-13 13:20 UTC
I wanted to use `CMAKE_CROSSCOMPILING_EMULATOR` to run my tests using the right emulator automatically. It is set to the path of `node` by [Emscripten.cmake](https://github.com/emscripten-core/emscripten/blob/ad7d20e71528d0afc9b3464dd05c9f5c53df0d44/cmake/Modules/Platform/Emscripten.cmake#L349-L354). 

However, there seems to be a problem either with cmake or the above file. Using code like this

```cmake
cmake_minimum_required(VERSION 3.0)

project(cross-emulator C)

file(WRITE hello.c "#include <stdio.h>\n int main(void){ printf(\"hello world\\n\");}")

add_executable(hello hello.c)

enable_testing()
add_test(NAME hello
    COMMAND ${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:hello>
)
```

Running ctest fails with 

```
UpdateCTestConfiguration  from :/home/fraux/code/tests/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/fraux/code/tests/build/DartConfiguration.tcl
Test project /home/fraux/code/tests/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: hello
Could not find executable "/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/node"
Looked in the following places:
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/Release/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/Release/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/Debug/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/Debug/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/MinSizeRel/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/MinSizeRel/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/RelWithDebInfo/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/RelWithDebInfo/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/Deployment/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/Deployment/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/Development/node"
"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/Development/node"

1: Test command:  "/home/fraux/code/tests/build/hello.js"
Unable to find executable: "/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/node"
1/1 Test #1: hello ............................***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
	  1 - hello (Not Run)
Errors while running CTest
```

Notice how the path to node is surrounded by quotes: `"/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/node"` vs `/local/scratch/fraux/code/chemfiles/chemfiles/build/emsdk/node/12.9.1_64bit/bin/node`.

I was able to fix this by removing the `FILEPATH` type for the variable, i.e.:

```cmake
find_program(NODE_JS_EXECUTABLE NAMES nodejs node)
if(NODE_JS_EXECUTABLE)
  set(CMAKE_CROSSCOMPILING_EMULATOR "${NODE_JS_EXECUTABLE}")
endif()
```

I don't know how much of this is related to cmake and how much is related to emscripten, but I wanted to report the issue anyway :smiley: 

-----

cmake -- version: cmake version 3.10.2
emcc --version: emcc (Emscripten gcc/clang-like replacement) 1.39.2 (commit 04d13b99d0630496139fa8f424c62aad65588c7b)

**Comment by Luthaf** [comment] 2019-12-13 13:35
I have been using `set(CMAKE_CROSSCOMPILING_EMULATOR "/usr/bin/wine" CACHE FILEPATH "Path to the emulator for the target system.")` with no issue, so the problem might come from the output of `find_program`.

**Comment by Luthaf** [comment] 2019-12-13 13:56
More investigation: the issue is that `CMAKE_CROSSCOMPILING_EMULATOR` is also set, with type STRING, when using `emconfigure cmake`

https://github.com/emscripten-core/emscripten/blob/ad7d20e71528d0afc9b3464dd05c9f5c53df0d44/emconfigure.py#L51

Commenting out the line above fixes my issues. Is there a reason why CMAKE_CROSSCOMPILING_EMULATOR can be defined in two different places here?

**Comment by encelo** [comment] 2020-04-25 11:17
It used to work for me in the past but recently I'm facing the same issue: CTest complains about not finding the `node` executable even if the path string seems correct.

I'm on Arch Linux using CMake 3.1.7.1, `releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit` and node-12.9.1-64bit.

**Comment by sbc100** [comment] 2020-04-25 17:04
Great!  Thanks for investigating.  I wonder if that is broken across the board (i.e. on different platforms / cmake versions / python versions.  I also wonder how long it been broken.  I guess we are not testing this :(

Actually I wonder if the problem is value of you NODE_JS variable, the first element should not contains quotes.   Where is your NODE value set?  Normally this is your `.emscripten` config file.  Can you see what value you have there?  And maybe `print(NODE_JS)` to see what the array looks like.

**Comment by encelo** [comment] 2020-04-25 21:12
The first line in my `.emscripten` config file is:
`NODE_JS = '/home/encelo/emsdk/node/12.9.1_64bit/bin/node'`.

If I put a `print(NODE_JS)` statement in the `shared.py` script I get: `['/home/encelo/emsdk/node/12.9.1_64bit/bin/node']`.

**Comment by ngzhian** [comment] 2020-05-24 18:53
I think the line in shared.py overwrites the one in Emscripten.cmake.
I tried changing the double quotes to single quotes and it worked.
So, another fix can be:

```
 if not has_substr(args, '-DCMAKE_CROSSCOMPILING_EMULATOR'):
      node_js = NODE_JS[0].replace('"', '\"')
-     args.append('-DCMAKE_CROSSCOMPILING_EMULATOR="%s"' % node_js)
+     args.append('-DCMAKE_CROSSCOMPILING_EMULATOR=\'%s\'' % node_js)
```
In order to handle whitespaces in `node_js`.

Alternatively, we can append 2 elements, like so
```
 if not has_substr(args, '-DCMAKE_CROSSCOMPILING_EMULATOR'):
      node_js = NODE_JS[0].replace('"', '\"')
-     args.append('-DCMAKE_CROSSCOMPILING_EMULATOR="%s"' % node_js)
+     args.append('-D', 'CMAKE_CROSSCOMPILING_EMULATOR=%s' % node_js)
```
`Popen` will take care of the escaping it for us.
https://cmake.org/cmake/help/latest/manual/cmake.1.html#options

**Comment by sbc100** [comment] 2020-05-25 03:07
Does simply removing the quotes work for you too?   (I"m not sure why removing the quotes would require additionally splitting into two args).

Its also not clear to my why this line useful: `node_js = NODE_JS[0].replace('"', '\"')`

**Comment by sbc100** [comment] 2020-05-25 03:10
Also, I imagine we have tests for this .. i wonder why we are not seeing this issue during tests?

**Comment by ngzhian** [comment] 2020-05-29 05:16
Yup removing the quotes worked for me

**Comment by justin-hackin** [comment] 2020-11-29 15:38
I also encountered issues with my CMakeCache.txt file containing escaped-quotes surrounding node executable in Ubuntu 20.04 and found I could hack around the problem by removing them. In my installation (latest), the file path for the fix was different: `emsdk/emscripten/tools/building.py`

**Comment by sbc100** [comment] 2020-11-29 16:23
Seems like an easy fix if anyone wants to upload a patch.   Marking as goog first bug.

**Closed** 2021-05-19 20:28 UTC
Labels: good first bug, help wanted
