### ISSUE TITLE
EXPORT_ES6 and MODULARIZE not compatible with USE_PTHREADS

### ISSUE THREAD

**Issue by theosib** [emscripten-core/emscripten#11278] opened 2020-05-28 17:44 UTC
I'm trying to work with multiple WASM programs at once, I need multiple instances of the same WASM program at once, and this is just a small part of a much larger project, so I need to encapsulate WASM as an ES6 module. Unfortunately, EXPORT_ES6 and MODULARIZE seem to be incompatible with pthreads, which makes this a show-stopper for me. Whenever I try to create a new thread, the auto-generated JS code throws the following error:

```
Uncaught (in promise) TypeError: Cannot add property ready, object is not extensible
    at Module.<anonymous> (test.js:32)
    at test.worker.js:71
(anonymous) @ test.js:32
(anonymous) @ test.worker.js:71
Promise.then (async)
onmessage @ test.worker.js:72
```

This is the auto-generated code where it throws the error:

```
var readyPromiseResolve, readyPromiseReject;
Module['ready'] = new Promise(function(resolve, reject) {
  readyPromiseResolve = resolve;
  readyPromiseReject = reject;
});
```

I have provided a minimal test case to demonstrate this problem. And if it matters, I'm using Chrome.

If I don't set USE_PTHREADS, it works fine. If I don't set EXPORT_ES6 and MODULARIZE, it works fine. In the sample code, I launch the thread from main, but I get the same error if I launch it later from a C function called by JS.

[module-pthread.zip](https://github.com/emscripten-core/emscripten/files/4697334/module-pthread.zip)

**Comment by kripken** [comment] 2020-06-01 20:06
What is the object it throws that on?

If it's the exports object, then @sbc100 was doing work to fix that, but I'm not sure if it's all landed.

If it's another object, then it may be a different issue.

**Comment by sbc100** [comment] 2020-06-01 21:49
I don't thinks this looks related to my recent changes, since they were focused on the Module['asm'] object which is immutable.    This looks like the issue is with Module object itself.

I'm afraid I've never really poked around with the EXPORT_ES6 option.

**Comment by VirtualTim** [comment] 2020-06-04 08:32
I'm building with those options, but I'm only on Emscripten 1.39.6.
Do you see the same thing on that version?

**Comment by sbc100** [comment] 2021-01-30 00:26
I believe this was addressed in #12469.. is that right @kripken ?  Can this be closed now?

**Comment by kripken** [comment] 2021-01-30 00:39
I don't think this is that issue - the problem there is fixed by using an export name, but here the issue is that we cannot modify the exports, `object is not extensible`. I think we had a plan to fix that by copying the exports to a new object, for the places we need to modify them (the instrumentations etc.).

I don't remember if that landed, but it might have - @theosib perhaps you can try your testcase again?

**Comment by sbc100** [comment] 2021-01-30 00:58
I just had a report that looked very similar that was fixed by adding EXPORT_NAME:

```
Uncaught (in promise) TypeError: Cannot add property ready, object is not extensible
    at Module.<anonymous> (test.js:32)
    at test.worker.js:71
(anonymous) @ test.js:32
(anonymous) @ test.worker.js:71
```

Are you saying this is not that same issue?   This issue was fixed as soon as they added EXPORT_NAME.  (they were using a version of the SDK that pre-dated your error message so it wasn't forcing them do add EXPORT_NAME).

**Comment by kripken** [comment] 2021-01-30 01:12
Interesting - well, I'm not sure. Maybe the export name issue causes that other error in a way I am not familiar with.

I tried the testcase here now, and after adding an export name and editing the HTML, I indeed do not see an error. So looks like it's fixed...

**Closed by kripken** 2021-01-30 01:12 UTC
