### ISSUE TITLE
SDL_FINGERUP bug when multitouch on iPad

### ISSUE THREAD

**Issue by adeshar00** [emscripten-core/emscripten#5012] opened 2017-03-09 01:20 UTC
When compiled with emscripten, I get strange behavior from the below code on my iPad: if I put two fingers down on the screen and then lift one of them, two SDL_FINGERUP events are detected, and then if I move the remaining finger there will be a SDL_FINGERDOWN event followed by an SDL_FINGERMOTION event.

If you'd like to test it on your own iOS device to see if you get the same behavior, you can do so here:
https://adeshar00.github.io/touchtest
(Here's a version without the prints on move events)
https://adeshar00.github.io/touchtest/nomove.html

My iPad is an iPad 2, model# A1395, iOS version 9.3.2, and I see this behavior both in Safari and Chrome.  At first I suspected that this might have been an issue with the iPad itself (I don't have this problem on my Android phone), but when I ran the demo on the following page with my iPad, it worked as expected (only one "touchend" event is triggered when I lift one of the two fingers):
http://tomicloud.com/2012/03/multi-touch-demo

Here's the code:
```
#include <SDL2/SDL.h>
#include <emscripten.h>


void mainloop()
{
    SDL_Event event;
    while(SDL_PollEvent(&event))
    {
        switch(event.type)
        {
            case SDL_FINGERDOWN:
                printf("DOWN Id: %d\n", event.tfinger.fingerId);
                break;

            case SDL_FINGERUP:
                printf("UP   Id: %d\n", event.tfinger.fingerId);
                break;

            case SDL_FINGERMOTION:
                printf("MOVE Id: %d\n", event.tfinger.fingerId);
                break;
        }
    }
}

int main(int a, char* g[])
{
    SDL_Init(SDL_INIT_VIDEO);

    SDL_CreateWindow( "Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 480, 360, 0);

    emscripten_set_main_loop(mainloop, 0, 1);

    return 0;
}
```

**Comment by arielm** [comment] 2018-01-08 22:18
I was able to reproduce the issue on iOS 10 and 11 with Safari. There's definitely a problem with touch-end events not being released properly in multi-touch mode.

Here's a quick and dirty hack: in [this chunk of library_html5.js](https://github.com/kripken/emscripten/blob/9bb8c0b39e10595196e571ee4f801fe5b557550e/src/library_html5.js#L856-L868), comment the 1st and 3rd loops.

Not ideal, I know, but okay as long as you don't need "onTarget" nor access to the "non changed touches on screen".

**Comment by bsokol** [comment] 2018-04-18 00:15
I found the same problem today. After a small investigation, I made the fix for this issue:

In library_html5.js file replace this fragment:

```
    var touches = {};
        for(var i = 0; i < e.touches.length; ++i) {
          var touch = e.touches[i];
          touches[touch.identifier] = touch;
        }
        for(var i = 0; i < e.changedTouches.length; ++i) {
          var touch = e.changedTouches[i];
          touches[touch.identifier] = touch;
          touch.changed = true;
        }
```

with:

```
        var touches = {};
        for(var i = 0; i < e.touches.length; ++i) {
          var touch = e.touches[i];
          touches[touch.identifier] = touch;
	  touch.changed = 0;
        }
        for(var i = 0; i < e.changedTouches.length; ++i) {
          var touch = e.changedTouches[i];
          touches[touch.identifier] = touch;
          touch.changed = 1;
        }

```
@kripken, is there any chance to apply this fix in next release?

**Comment by kripken** [comment] 2018-04-23 16:47
Thanks @bsokol! Can you please open a PR with that, and we'll discuss the details there? Would definitely be good to get this in.

**Comment by jminor** [comment] 2019-02-12 05:57
FYI, I just tested this on iOS 12.1.1 with Safari, Chrome and Firefox and I am unable to reproduce the problem. I used the first two demos linked in the original post by @adeshar00 and both behaved as I would expect. Each finger touch and release was detected as normal without any unexpected double events.

**Closed** 2020-02-19 07:00 UTC
Labels: wontfix
