### ISSUE TITLE
Flaky test: test_pthread_proxying_cpp 

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#18353] opened 2022-12-12 15:52 UTC
Looks like test_pthread_proxying_cpp is flaky on the CI too, probably similar to #18307 / #18314.

**Comment by RReverser** [comment] 2022-12-12 16:31
Probably related to https://github.com/emscripten-core/emscripten/issues/16569 too, although there it was reported only to hang with wasm2js. cc @tlively

**Comment by tlively** [comment] 2022-12-12 16:36
Thanks, taking a look now.

**Comment by kleisauke** [comment] 2022-12-12 16:42
Interesting, so this also affects Node.js and the new proxying API. Perhaps we could experiment with removing those `std::cout` calls (to make sure it doesn't conflict with the `printf`-locks introduced in commit fdd486fef25872e2c04c0505923093f7ac201c1e)?

**Comment by RReverser** [comment] 2022-12-12 18:49
> (to make sure it doesn't conflict with the `printf`-locks introduced in commit [fdd486f](https://github.com/emscripten-core/emscripten/commit/fdd486fef25872e2c04c0505923093f7ac201c1e))?

@kleisauke Interesting catch. It started failing pretty suddenly and pretty frequently, so a recent change being a culprit seems likely.

**Comment by kleisauke** [comment] 2022-12-12 18:58
FWIW, issue #16136 was the first one that reported this flaky behavior, a couple months after that commit was landed. At the time, I thought it only affected the browser tests (unfortunately, all those CI logs disappeared due to the retention time on CircleCI).

**Comment by kleisauke** [comment] 2022-12-12 19:37
Given these tests started to fail more frequently, it could also be related to commit a37b4b2c5571864523d35dff59e2c54afaf8e3e6 and/or the current `libc.need_locks` logic.

I once had a idea to do this during compile-time, see for e.g. commit 27c2a3a854a8544c7a64b0c8e1cc77adc0d94cd5. However, I abandoned it because that could lead to redundant file locking if no pthreads are running. Although in retrospect, I think this could resolve a similar issue in the Wasm Workers API (which I reproduced in PR #18201).

**Comment by kleisauke** [comment] 2022-12-12 19:51
... let me know if help is needed with testing/implementation.  Note that the above assumptions were made for triage purposes (and given that race conditions/deadlocks are generally difficult to debug).

**Comment by tlively** [comment] 2022-12-12 19:52
I assume that this is due to my change to this test a few days ago (#18350), and not anything to do with musl or other system libraries.

**Comment by RReverser** [comment] 2022-12-12 19:56
Whew, I started worrying this is due to my recent changes to Node.js pthreads.

**Comment by sbc100** [comment] 2022-12-12 20:26
> Interesting, so assuming this is related to these linked issues, it also affects Node.js and the new proxying API.
> 
> Perhaps we could experiment with removing those `std::cout` calls (to make sure it doesn't conflict with the `printf`-locks introduced in commit [fdd486f](https://github.com/emscripten-core/emscripten/commit/fdd486fef25872e2c04c0505923093f7ac201c1e))?

BTW a good way to avoid the C stdio subsystem completely in such tests its to use `emscripten_log` and/or `emscripten_err` which are defined in `<emscripten/console.h>`

**Closed** 2022-12-13 00:57 UTC
