### ISSUE TITLE
Asynchronous fetch problem

### ISSUE THREAD

**Issue by diegurrio** [emscripten-core/emscripten#11590] opened 2020-07-08 20:01 UTC
Asynchronous fetch in combination with a future hangs when we check for the result. If we don't check (call get()) for the result, everything works.

**Example**
```
void downloadSucceeded(emscripten_fetch_t *fetch) {
    WARN("Finished downloading %llu bytes from URL %s.\n", fetch->numBytes, fetch->url);
    auto promise = reinterpret_cast<std::promise<bool>*>(fetch->userData);
    promise->set_value(true);
    delete promise;
    emscripten_fetch_close(fetch); // Free data associated with the fetch.
}

void downloadFailed(emscripten_fetch_t *fetch) {
    WARN("Downloading %s failed, HTTP failure status code: %d.\n", fetch->url, fetch->status);
    auto promise = reinterpret_cast<std::promise<bool>*>(fetch->userData);
    promise->set_value(false);
    delete promise;
    emscripten_fetch_close(fetch); // Also free data on failure.
}
void someFunction() {
    std::promise<bool>* fetchPromise = new std::promise<bool>();
    emscripten_fetch_attr_t attr;
    emscripten_fetch_attr_init(&attr);
    strcpy(attr.requestMethod, "GET");
    attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
    attr_.userData = &fetchPromise;
    attr.onsuccess = downloadSucceeded;
    attr.onerror = downloadFailed;
    emscripten_fetch(&attr, "http://raw.githubusercontent.com/emscripten-core/emscripten/master/system/include/emscripten/fetch.h");

    std::future<bool> future = fetchPromise->get_future();
    if (future.get()) {     // Wait for result
        printf("We are good");
    }
}
```

**Comment by TroyTae** [comment] 2020-07-21 12:58
I made some test code that passed integer pointer instead of promise.
(https://github.com/TroyTae/emscripten/blob/issue-11590/tests/fetch/test_async_xhr.cpp)
But passed argument is different with my prediction.
<img width="820" alt="스크린샷 2020-07-21 오후 8 06 58" src="https://user-images.githubusercontent.com/20078201/88057267-cf364b00-cb9c-11ea-8a29-bef5cff12621.png">

@kripken 
Could you tell me the location of the code that passes the `userData`?

**Comment by kripken** [comment] 2020-07-21 17:21
@TroyTae I'm not sure, but most of the fetch code is in `src/Fetch.js, src/library_fetch.js, system/lib/fetch/emscripten_fetch.cpp`.

**Comment by TroyTae** [comment] 2020-07-23 09:15
@kripken 
Thank you for your help!
I confirmed that calls func emscripten_fetch(`emscripten_fetch.cpp`) and func emscripten_start_fetch(`Fetch.js`).
And `fetch` is passed by func `dynCall_vi`:
https://github.com/emscripten-core/emscripten/blob/0cddccb13a2ef11bd3ac8040485716aacef4a093/src/Fetch.js#L500
Can you teach me what is the `dynCall_vi`?

**Comment by TroyTae** [comment] 2020-07-23 09:20
Test update: https://github.com/TroyTae/emscripten/blob/issue-11590/tests/fetch/test_async_xhr.cpp
I tried to pass char pointer instead of integer pointer.
And it passed well 😨
![image](https://user-images.githubusercontent.com/20078201/88270725-0c234e80-cd11-11ea-86f5-82cc53f7a542.png)

**Comment by kripken** [comment] 2020-07-23 19:58
`dynCall_vi` is a call with a function pointer. Specifically with the signature "vi" which means it's a void function with one i32 argument. All dynCall functions take the function pointer as the first parameter, then the rest of the arguments, so it's `dynCall_vi(functionPtr, param0)`.

**Comment by TroyTae** [comment] 2020-07-24 02:00
![image](https://user-images.githubusercontent.com/20078201/88354463-ee4efb80-cd9b-11ea-876b-d9aade6d9578.png)
Native code..;; I have no idea how can I debug this.
But I can't bother you anymore.
I'll leave my code, please help if anyone knows about this issue 😭

**Comment by Penguin-Guru** [comment] 2020-08-26 06:51
Not sure if this helps but I tried adding the EMSCRIPTEN_FETCH_PERSIST_FILE attribute and gears.png does appear in Chromium's Dev Tools. The file seems to be transferred correctly but assert fails on line 23 of "sync_fetch_in_main_thread.cpp". Not sure how to reference that on here. I just installed a few hours ago so this should be current.

**Closed** 2022-04-18 00:21 UTC
Labels: good first bug, help wanted, wontfix
