### ISSUE TITLE
Unsuspected Asyncify 'handleSleep' behavior 

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#14977] opened 2021-08-31 06:56 UTC
Using Asyncify in multithreading environment caused strange behavior of handling async JS function.

I have wrote simple application for visualizing problem:
1. test.c
```#include <stdio.h>
#include <time.h>
#include <pthread.h>
#include <emscripten.h>
extern void test();

 void * thread_start(void *arg){
  clock_t t;
  t = clock();
  test();
  t = clock() - t;
  double time_taken = ((double)t)/CLOCKS_PER_SEC; 
  
  printf("test() took %f seconds to execute \n", time_taken);
}
  
int main()
{
	pthread_t id;

  pthread_create(&id, NULL, thread_start, NULL);

  for (;;) {
    emscripten_sleep(1000);
  }

  return 0;
}
```
2. libary_test.js
```mergeInto(LibraryManager.library, {
  test__proxy: 'sync',
  test: function() {
    return Asyncify.handleAsync(() => {
       return new Promise(resolve => setTimeout(resolve, 50000));
    });
  }
});
```
3. Compile command:
`emcc test.c  --js-library ./library_test.js  -s ASYNCIFY -sUSE_PTHREADS=1 -s 'ASYNCIFY_IMPORTS=["test","emscripten_receive_on_main_thread_js"]'  -o test.html`

P.S If compile with flag '-s PROXY_TO_PTHREAD', all works fine. Why ?

**Comment by sbc100** [comment] 2021-08-31 12:37
Can you explain the strange behaviour you are seeing?  What do you expect to happen vs what actually happens?

BWT, Is there some reason why you are adding `emscripten_receive_on_main_thread_js` to `ASYNCIFY_IMPORTS`.    If that was needed to marked as supporting ASYNCIFY I would expect it to be already be listed in: https://github.com/emscripten-core/emscripten/blob/30863fba797cb3ead67a44479927be26172cb7a1/emcc.py#L98

**Comment by DiachenkoIgor** [comment] 2021-08-31 15:26
1. Sorry for obscurity. Method 'test' don't wait time (50 seconds) and return almost immediately after call.
2. Emcc return error if don't add `emscripten_receive_on_main_thread_js`.

**Comment by sbc100** [comment] 2021-08-31 15:40
Can you remove the line `test__proxy: 'sync',`  ?  This is telling emscripten to proxy the call back to the main thread and is most likely the cause of your problem.  Do you need the JS to run on the main thread?

**Comment by DiachenkoIgor** [comment] 2021-09-01 06:51
Thank you for quick answer.
1. In the real project JS have to be executed in main thread because it have state.
2. I want to understand what mechanism caused to wake up timeout before time. Because of this I receive undefined behavior.

**Comment by sbc100** [comment] 2021-09-01 09:41
I think combining `ASYNICIFY` with main thread proxying is not something we current support.  Perhaps @kripken, @juj, @RReverser might know more.

**Comment by kripken** [comment] 2021-09-13 23:54
This configuration is not tested yet that I can see, so there may be bugs here. One thing that comes to mind is that even if a thread "pauses" using asyncify, it might be woken up by another thread's message arriving - and we do not have special integration to handle that. In fact I'm not sure what that integration would look like, as waiting to handle the message seems fairly dangerous.

More generally, I think we should probably not work to support asyncify + pthreads. Instead, we should enable things more things in pthreads mode to replace asyncify there. What I mean is, when you use `PROXY_TO_PTHREAD` then you run on a worker and you can block there, so you can block on an async file read and so forth, using atomics instead of asyncify.

@DiachenkoIgor , I'm curious what asyncify features you use in this pthreads build?

**Comment by DiachenkoIgor** [comment] 2021-09-20 09:18
@kripken I'm sorry for long absense. I use Asyncify for handle synchronous socket operations (custom implementation written on js).

**Comment by kripken** [comment] 2021-09-20 20:27
I see, thanks @DiachenkoIgor 

In that case, I think you can avoid asyncify and use the sync-to-async helper stuff here: https://github.com/emscripten-core/emscripten/pull/14666 - with that, one worker can block while another does an async socket operation.

**Closed** 2022-09-08 07:42 UTC

**Comment by davedoesdev** [comment] 2023-07-01 17:28
Is sync-to-async still available? I'm finding my asyncified function is called twice when I use `handleSleep`.
