### ISSUE TITLE
Template static variable failing in new upstream Clang

### ISSUE THREAD

**Issue by cwoffenden** [emscripten-core/emscripten#8728] opened 2019-06-01 15:16 UTC
We're trying out the new upstream Clang compiler and bumped into `error: undefined symbol: ` (with an empty string) when using the same template static variable in different compilation units. The minimum reproducible example comprises `temp.h` the template:
```C++
template<typename T>
class Temp
{
public:
    static Temp const ZERO;
    
    Temp(T val = T(0)) : val(val) {}
    
    T val;
};

template<typename T>
Temp<T> const Temp<T>::ZERO;
```
Then the two users of the template `unit1.cpp` and `unit2.cpp`:
```C++
#include "temp.h"

float getVal1() {
    return Temp<float>::ZERO.val;
}
```
```C++
#include "temp.h"

float getVal2() {
    return Temp<float>::ZERO.val;
}
```
Add `main.cpp` so we can compile and compare with regular Clang or GCC:
```C++
int main() {
    return 0;
}
```
Compile using  `emcc *.cpp` and see the resulting error:
```
error: undefined symbol: 
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
shared:ERROR: '/Volumes/Data/Work/Emscripten/node/8.9.1_64bit/bin/node /Volumes/Data/Work/Emscripten/emscripten/incoming/src/compiler.js /tmp/tmpQjOhfV.txt /Volumes/Data/Work/Emscripten/emscripten/incoming/src/library_pthread_stub.js' failed (1)
```
It's failing here on macOS but equally fails on Windows. Setting the `ERROR_ON_UNDEFINED_SYMBOLS` flag as suggested creates invalid wasm that fails in the browser with `TypeError: import object field '' is not an Object`. Tested with the latest `sdk-wasm-master-64bit` current as of this morning but initially seen when first testing the upstream compiler a few days ago.

Files of the above also attached: [example.zip](https://github.com/emscripten-core/emscripten/files/3243900/example.zip)

**Comment by kripken** [comment] 2019-06-01 16:11
Sorry, `sdk-wasm-master-64bit` does not support the LLVM wasm backend (despite the name - it's an old asm2wasm build). Instead, please test with `latest-upstream`.

Do our docs mention `sdk-wasm-master-64bit` somewhere as how to install the llvm wasm backend? If so please let us know where so we can fix that.

**Comment by kripken** [comment] 2019-06-01 16:16
Oh wait, maybe those do point to an upstream location, but the manifest suggests it's the wrong upstream (llvm before the monorepo).

Not sure if we should fix that location or just remove that mode. Depends on where it's been documented, I guess - I can't seem to find any docs on it?

**Comment by cwoffenden** [comment] 2019-06-01 17:56
On macOS, installing `latest-upstream` fails with the same error, shown here with the `-v` option to verify the Clang and Emscripten versions:
```
dunkel:Test carl$ emcc -v *.cpp
shared:INFO: (Emscripten: Running sanity checks)
clang version 9.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project eafe8ef6f2b44baf5a84658caca90c2f9c1849ca)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Volumes/Data/Work/Emscripten/upstream/bin
 "/Volumes/Data/Work/Emscripten/upstream/bin/clang-9" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -main-file-name main.cpp -mrelocation-model static -mthread-model posix -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -fvisibility hidden -dwarf-column-info -debugger-tuning=gdb -target-linker-version 409.12 -momit-leaf-frame-pointer -v -coverage-notes-file /tmp/emscripten_temp_fVilvu/main_0.gcno -nostdsysteminc -nobuiltininc -resource-dir /Volumes/Data/Work/Emscripten/upstream/lib/clang/9.0.0 -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=38 -D __EMSCRIPTEN_tiny__=33 -D _LIBCPP_ABI_VERSION=2 -D unix -D __unix -D __unix__ -internal-isystem /include/wasm32-emscripten/c++/v1 -internal-isystem /include/c++/v1 -Werror=implicit-function-declaration -std=c++03 -fdeprecated-macro -fdebug-compilation-dir /Volumes/Data/Work/Native/Test -ferror-limit 19 -fmessage-length 80 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fno-common -fdiagnostics-show-option -fcolor-diagnostics -nobuiltininc -nostdsysteminc -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libcxx -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libcxxabi/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/compat -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SSE -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libc -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libc/musl/arch/emscripten -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/local/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SDL -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_fVilvu/main_0.o -x c++ main.cpp
clang -cc1 version 9.0.0 based upon LLVM 9.0.0svn default target x86_64-apple-darwin18.6.0
ignoring nonexistent directory "/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SSE"
ignoring nonexistent directory "/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libcxx
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libcxxabi/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/compat
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libc
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libc/musl/arch/emscripten
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/local/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SDL
End of search list.
clang version 9.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project eafe8ef6f2b44baf5a84658caca90c2f9c1849ca)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Volumes/Data/Work/Emscripten/upstream/bin
 "/Volumes/Data/Work/Emscripten/upstream/bin/clang-9" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -main-file-name unit1.cpp -mrelocation-model static -mthread-model posix -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -fvisibility hidden -dwarf-column-info -debugger-tuning=gdb -target-linker-version 409.12 -momit-leaf-frame-pointer -v -coverage-notes-file /tmp/emscripten_temp_fVilvu/unit1_1.gcno -nostdsysteminc -nobuiltininc -resource-dir /Volumes/Data/Work/Emscripten/upstream/lib/clang/9.0.0 -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=38 -D __EMSCRIPTEN_tiny__=33 -D _LIBCPP_ABI_VERSION=2 -D unix -D __unix -D __unix__ -internal-isystem /include/wasm32-emscripten/c++/v1 -internal-isystem /include/c++/v1 -Werror=implicit-function-declaration -std=c++03 -fdeprecated-macro -fdebug-compilation-dir /Volumes/Data/Work/Native/Test -ferror-limit 19 -fmessage-length 80 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fno-common -fdiagnostics-show-option -fcolor-diagnostics -nobuiltininc -nostdsysteminc -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libcxx -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libcxxabi/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/compat -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SSE -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libc -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libc/musl/arch/emscripten -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/local/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SDL -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_fVilvu/unit1_1.o -x c++ unit1.cpp
clang -cc1 version 9.0.0 based upon LLVM 9.0.0svn default target x86_64-apple-darwin18.6.0
ignoring nonexistent directory "/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SSE"
ignoring nonexistent directory "/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libcxx
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libcxxabi/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/compat
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libc
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libc/musl/arch/emscripten
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/local/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SDL
End of search list.
clang version 9.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project eafe8ef6f2b44baf5a84658caca90c2f9c1849ca)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Volumes/Data/Work/Emscripten/upstream/bin
 "/Volumes/Data/Work/Emscripten/upstream/bin/clang-9" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -main-file-name unit2.cpp -mrelocation-model static -mthread-model posix -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -fvisibility hidden -dwarf-column-info -debugger-tuning=gdb -target-linker-version 409.12 -momit-leaf-frame-pointer -v -coverage-notes-file /tmp/emscripten_temp_fVilvu/unit2_2.gcno -nostdsysteminc -nobuiltininc -resource-dir /Volumes/Data/Work/Emscripten/upstream/lib/clang/9.0.0 -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=38 -D __EMSCRIPTEN_tiny__=33 -D _LIBCPP_ABI_VERSION=2 -D unix -D __unix -D __unix__ -internal-isystem /include/wasm32-emscripten/c++/v1 -internal-isystem /include/c++/v1 -Werror=implicit-function-declaration -std=c++03 -fdeprecated-macro -fdebug-compilation-dir /Volumes/Data/Work/Native/Test -ferror-limit 19 -fmessage-length 80 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fno-common -fdiagnostics-show-option -fcolor-diagnostics -nobuiltininc -nostdsysteminc -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libcxx -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libcxxabi/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/compat -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SSE -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libc -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libc/musl/arch/emscripten -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/local/include -isystem/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SDL -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_fVilvu/unit2_2.o -x c++ unit2.cpp
clang -cc1 version 9.0.0 based upon LLVM 9.0.0svn default target x86_64-apple-darwin18.6.0
ignoring nonexistent directory "/Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SSE"
ignoring nonexistent directory "/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libcxx
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libcxxabi/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/compat
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/libc
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/lib/libc/musl/arch/emscripten
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/local/include
 /Volumes/Data/Work/Emscripten/emscripten/incoming/system/include/SDL
End of search list.
 "/Volumes/Data/Work/Emscripten/upstream/bin/wasm-ld" -o /tmp/emscripten_temp_fVilvu/a.out.wasm --allow-undefined --import-memory --import-table --lto-O0 /tmp/emscripten_temp_fVilvu/main_0.o /tmp/emscripten_temp_fVilvu/unit1_1.o /tmp/emscripten_temp_fVilvu/unit2_2.o /Users/carl/.emscripten_cache/wasm-obj/libcompiler_rt.a /Users/carl/.emscripten_cache/wasm-obj/libc.a /Users/carl/.emscripten_cache/wasm-obj/libc-wasm.a /Users/carl/.emscripten_cache/wasm-obj/libdlmalloc.a /Users/carl/.emscripten_cache/wasm-obj/libpthreads_stub.a /Users/carl/.emscripten_cache/wasm-obj/libcompiler_rt_wasm.a /Users/carl/.emscripten_cache/wasm-obj/libc_rt_wasm.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "/Volumes/Data/Work/Emscripten/upstream/bin/wasm-emscripten-finalize" /tmp/emscripten_temp_fVilvu/a.out.wasm -o /tmp/emscripten_temp_fVilvu/a.out.wasm.o.wasm --detect-features --global-base=1024 --initial-stack-pointer=5243904
error: undefined symbol: 
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
shared:ERROR: '/Volumes/Data/Work/Emscripten/node/8.9.1_64bit/bin/node /Volumes/Data/Work/Emscripten/emscripten/incoming/src/compiler.js /tmp/tmpiQCwzI.txt /Volumes/Data/Work/Emscripten/emscripten/incoming/src/library_pthread_stub.js' failed (1)
```
Regarding `sdk-wasm-master-64bit`, unless I'm mistaken, I installed `upstream-clang-master-64bit` and `emscripten-incoming-64bit` separately, which then showed as `sdk-wasm-master-64bit` installed. If memory serves it was the only way that worked for me when installing on Windows, so I'd replicated the same on Mac (I later worked out this is down to `emsdk update` overwriting with an older version).

**Comment by kripken** [comment] 2019-06-01 20:06
Thanks!

Ok, I can confirm this is a bug. @sbc100 it looks like a wasm-ld bug, as `unit1.o` and `unit2.o` (if we compile the above files to objects) have
```
 - func[1] sig=1 <__cxx_global_var_init>
```
After wasm-ld, one of those functions survives, and the other becomes an import with empty module and name,
```
 (import "" "" (func $__cxx_global_var_init))
```
which leads to an error in emcc.

(Separately, I opened https://github.com/emscripten-core/emsdk/pull/257 to clean up the incorrect stuff on the emsdk, like `upstream-clang`.)

**Comment by sbc100** [comment] 2019-06-07 17:54
Should be fixed as of: https://reviews.llvm.org/D62983

**Closed by sbc100** 2019-06-07 17:54 UTC
