### ISSUE TITLE
install latest error

### ISSUE THREAD

**Issue by Y0QIN** [emscripten-core/emscripten#9651] opened 2019-10-16 11:51 UTC
git pull
then
./emsdk install 1.38.48
Error: No tool or SDK found by name 'sdk-releases-fastcomp-1290d9deb93d67c4649999a8f2c8d9167d38dc04-64bit'

**Comment by VirtualTim** [comment] 2019-10-17 01:30
Just so you're aware, there's also an Emscripten docker image. Depending on your build system that might be easier to use?
https://hub.docker.com/r/trzeci/emscripten/tags

**Comment by Y0QIN** [comment] 2019-10-17 03:36
@VirtualTim since my linux is 32bit system,I have nerver try docker before. I will try it later in my spare time

**Comment by Y0QIN** [comment] 2019-10-17 03:49
@kripken 
the console log of my first time run cmd `git pull`:
remote: Enumerating objects: 130, done.
remote: Counting objects: 100% (130/130), done.
remote: Total 347 (delta 130), reused 130 (delta 130), pack-reused 217
接收对象中: 100% (347/347), 235.29 KiB | 7.00 KiB/s, done.
处理 delta 中: 100% (220/220), 完成 17 个本地对象.
来自 https://github.com/juj/emsdk
   040e49a..c564225  master     -> origin/master
 * [新分支]          always_embedded -> origin/always_embedded
 * [新分支]          cleanup    -> origin/cleanup
 * [新分支]          embedded   -> origin/embedded
 * [新分支]          mac        -> origin/mac
 * [新分支]          node_update_script -> origin/node_update_script
 * [新分支]          show-activated-paths -> origin/show-activated-paths
 * [新分支]          update_python -> origin/update_python
更新 040e49a..c564225
Fast-forward
 .circleci/config.yml                              |   90 ++
 .flake8                                           |   22 +-
 .gitignore                                        |   58 +-
 .travis.yml                                       |   19 -
 Dockerfile                                        |   32 -
 README.md                                         |  138 +--
 bin/elevate.exe                                   |  Bin 6144 -> 0 bytes
 docker/Dockerfile                                 |  235 +++++
 docker/Makefile                                   |   21 +
 docker/README.md                                  |  135 +++
 docker/entrypoint                                 |   27 +
 docker/test_dockerimage.sh                        |   19 +
 emscripten-releases-tags.txt                      |   22 +
 emsdk                                             | 2595 +-----------------------------------------------------
 emsdk.bat                                         |    2 +-
 emsdk.ps1                                         |    2 +-
 emsdk.py                                          | 2961 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 emsdk_env.csh                                     |   36 +
 emsdk_env.fish                                    |    2 +-
 emsdk_env.sh                                      |    7 +-
 emsdk_manifest.json                               | 3520 ++++++++++++++++++++++++++++++++++++++-----------------------------------
 binaryen-tags.txt => legacy-binaryen-tags.txt     |    0
 emscripten-tags.txt => legacy-emscripten-tags.txt |    0
 llvm-tags-32bit.txt                               |    0
 llvm-tags-64bit.txt                               |   75 ++
 test.bat                                          |    6 +
 test.py                                           |  204 +++++
 test.sh                                           |   11 +
 upstream/lkgr.json                                |  108 ---
 29 files changed, 5727 insertions(+), 4620 deletions(-)
 create mode 100644 .circleci/config.yml
 delete mode 100644 .travis.yml
 delete mode 100644 Dockerfile
 delete mode 100644 bin/elevate.exe
 create mode 100644 docker/Dockerfile
 create mode 100644 docker/Makefile
 create mode 100644 docker/README.md
 create mode 100755 docker/entrypoint
 create mode 100755 docker/test_dockerimage.sh
 create mode 100644 emscripten-releases-tags.txt
 create mode 100755 emsdk.py
 create mode 100755 emsdk_env.csh
 rename binaryen-tags.txt => legacy-binaryen-tags.txt (100%)
 rename emscripten-tags.txt => legacy-emscripten-tags.txt (100%)
 create mode 100644 llvm-tags-32bit.txt
 create mode 100644 llvm-tags-64bit.txt
 create mode 100755 test.bat
 create mode 100755 test.py
 create mode 100755 test.sh
 delete mode 100644 upstream/lkgr.json

And today I clone from github and reinstall. And it happend the same problem again.
following :
~/emsdk# ./emsdk install latest
Error: No tool or SDK found by name 'sdk-releases-fastcomp-1290d9deb93d67c4649999a8f2c8d9167d38dc04-64bit'.

and the release-tags.txt:
{
  "latest": "1.38.48",
  "releases": {
    "1.38.48": "1290d9deb93d67c4649999a8f2c8d9167d38dc04",
    "1.38.47": "bc367c257409d676e71c5511383228b7aabf1689",
    "1.38.46": "c89919d252f7cea00d944bdf3bd630cd3c7e7388",
    "1.38.45": "f3030d9fffcc9e1287cb6b8e72982e94ece31d71",
    "1.38.44": "e5fd171371c3dcb8806a337f2dfa9b70f598f456",
    "1.38.43": "737d4a07be76c15124adf3c6ef2c218123f7a67f",
    "1.38.42": "05f8c01394ddd0838d3cb484ba8ca97a3efc1ac9",
    "1.38.41": "5c6785a63993ae7a4d5362b32b0be9c85138fb96",
    "1.38.40": "7b4b328af02eafbc857b8ca1e3d9b12dddc56ef7",
    "1.38.39": "f42b12c45fd3f4c20de1321402fbc28f8fd21df1",
    "1.38.38": "80bff2784f8500c1305ca69ba1d9fc84df0e401c",
    "1.38.37": "0ca6c49e30bc09c3ccefc867df4196a4b4183441",
    "1.38.36": "d46be49c2aab975333423122239892bd46f52bba",
    "1.38.35": "98f49919f25e06fa557cbcb1321d4c10e60c87ca",
    "1.38.34": "048cf9424790cc525a7ea6da340820aae226f3b9",
    "1.38.33": "3b8cff670e9233a6623563add831647e8689a86b"
  }
}

**Comment by Y0QIN** [comment] 2019-10-17 03:57
@kripken This is strange. It's also the first time that I have encountered that the tool name has an encryption suffix displayed in the tags.txt file after the update .

**Comment by VirtualTim** [comment] 2019-10-17 04:04
If you do decide to try docker my quick 1 minute install guide is:
1. Install docker
2. Run `docker run -it --rm -p 8080:8080 -v /path/to/your/sourcecode:/src -w /path/to/your/sourcecode/buildscript -u emscripten trzeci/emscripten:sdk-tag-1.38.48-64bit bash`
3. Run your build script
4. Run the server like `emrun --hostname $(hostname -I) --port 8080 /path/to/output`

**Comment by Y0QIN** [comment] 2019-10-17 05:23
@VirtualTim Thank you very much　. I will give feedback when I try docker.

**Comment by kripken** [comment] 2019-10-17 22:16
Thanks @Y0QIN , from
```
~/emsdk# ./emsdk install latest
Error: No tool or SDK found by name 'sdk-releases-fastcomp-1290d9deb93d67c4649999a8f2c8d9167d38dc04-64bit'.
```
it looks like there's a newline in the middle. I investigated for a while and didn't find a good answer for why one might exist, but opening the tot file in an editor and saving it with an extra newline is enough to reproduce the problem. A fix is in https://github.com/emscripten-core/emsdk/pull/375

**Closed** 2019-10-17 22:26 UTC

**Comment by Y0QIN** [comment] 2019-10-18 01:51
@kripken I try again, sadly it happed again.
But I try on my windows it successed.
my linux system is an 32bit one ,and I found I can't connect with chromium.googlesource.com when I user the bash, maybe that make the difference?

**Comment by kripken** [comment] 2019-10-18 01:58
Oh, I missed that your linux system is 32-bit. We only have 64-bit binary builds, sorry about that. For 32-bit linux you'll need to build from source.

**Comment by Y0QIN** [comment] 2019-10-18 06:16
@kripken and I try install sdk-incoming-32bit 
and it occour the following problem:
```
/root/emsdk/clang/fastcomp/src/cmake/config.guess: 71: /root/emsdk/clang/fastcomp/src/cmake/config.guess: Syntax error: word unexpected (expecting "in")
CMake Error at cmake/modules/GetHostTriple.cmake:24 (message):
  Failed to execute /root/emsdk/clang/fastcomp/src/cmake/config.guess
Call Stack (most recent call first):
  cmake/config-ix.cmake:401 (get_host_triple)
  CMakeLists.txt:579 (include)


-- Configuring incomplete, errors occurred!
See also "/root/emsdk/clang/fastcomp/build_incoming_32/CMakeFiles/CMakeOutput.log".
See also "/root/emsdk/clang/fastcomp/build_incoming_32/CMakeFiles/CMakeError.log".
CMake invocation failed due to exception!
Working directory: /root/emsdk/clang/fastcomp/build_incoming_32
Command '['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=Release', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_TESTS=OFF', '-DLLVM_ENABLE_ASSERTIONS=OFF', '/root/emsdk/clang/fastcomp/src']' returned non-zero exit status 1.
Installation failed!
```

**Comment by kripken** [comment] 2019-10-18 16:19
@Y0QIN Maybe those `.log` files have more information? If not, then trying to run that cmake command (the one mentioned on the last line) yourself manually may easier to debug.

In general, building fastcomp is the same as building LLVM + normally, so the upstream docs may be helpful. You just need to add `-DLLVM_TARGETS_TO_BUILD=X86;JSBackend` as mentioned on that line, which adds the fastcomp asm.js backend.

**Comment by sbc100** [comment] 2019-10-18 17:20
Can I ask why you are trying to developer on a 32-bit linux machine?

**Comment by Y0QIN** [comment] 2019-10-19 06:51
@sbc100 the linux computer is the company's working computer, the operating system cannot be upgraded in a short time.So I try in windows.Would there be any difference between the wasmjs files that I compiled on windows and linux
