### ISSUE TITLE
Link failing with attempt to add bitcode file after LTO

### ISSUE THREAD

**Issue by tklajnscek** [emscripten-core/emscripten#16836] opened 2022-04-28 10:19 UTC
Happens with 2.0.34 onward, latest I tried is 3.1.9, haven't tried earlier ones

When we compile our project with `-flto` we get:
```
[build] wasm-ld: error: D:\SDK\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libc.a(fputc.o): attempt to add bitcode file after LTO.
```

I've looked at the relevant LLVM change log here https://reviews.llvm.org/rGb062fe181625bd1944ca9ca2a58246ffd7cd3536
And the previous issues #11545 and #15506

We don't use `fputc`, so it's most likely being generated by this transform https://github.com/llvm/llvm-project/blob/35cc2ec4ed4a7a0862e62ad009d561f61e2d12c3/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp#L2887

`fwrite(S,1,1,F) -> fputc(S[0],F)`

Adding a reference to it with `Wl,-u,fputc` fixes the issue, but I thought this has been fixed since #11545 is closed. 

Does the non-LTO symbol list in `system_libs.py` need updating maybe to keep up with any transforms that may emit these symbols late? Or is there another fix for this on the horizon?

**Comment by tklajnscek** [comment] 2022-04-28 10:19
Forgot to tag @sbc100 since you've worked on this as far as I can tell :)

**Comment by sbc100** [comment] 2022-04-28 15:24
Yes the non-LTO symbol list in system_libs.py almost certainly needs updating.  Sadly, I don't know of a good way to manage it automatically.

**Comment by tklajnscek** [comment] 2022-04-28 19:13
Thanks for the lightning fast turnaround on this! ❤️

**Comment by tmm1** [comment] 2022-05-10 00:40
I experienced a similar problem with emscripten v3.1.3:

>wasm-ld: error: /project/bin/.emscripten_cache/sysroot/lib/wasm32-emscripten/lto/libnoexit.a(atexit_dummy.o): attempt to add bitcode file after LTO.

which was fixed by adding `-Wl,-u,atexit -Wl,-u,__cxa_atexit`

**Comment by sbc100** [comment] 2022-05-10 01:21
Fix for `__cxa_atexit` is in #16923

**Comment by kleisauke** [comment] 2023-05-21 13:59
I'm experiencing a similar issue with Emscripten >= v3.1.37:
```
wasm-ld: error: /src/build/emcache/sysroot/lib/wasm32-emscripten/lto/libc-mt.a(htonl.o): attempt to add bitcode file after LTO.
```
(Let me know if you want to track this in a separate issue instead)

**Comment by sbc100** [comment] 2023-05-22 02:22
@kleisauke at its core the issue must be the same:  Something during codegen generated a new undefined symbol, and that symbol is bitcode symbol, and it is now too late to include new bitcode symbols.  Whether we should open new issues each time we find an issue like this is not clear.

In order to figure out how the new reference to `htonl` (thankfully the only symbol defined by `libc-mt.a(htonl.o)`, can you try linking with `-Wl,--trace-symbol=htonl`?

**Comment by kleisauke** [comment] 2023-05-22 08:42
With `-Wl,--trace-symbol=htonl`, I see:
```
/src/build/emcache/sysroot/lib/wasm32-emscripten/lto/libc-mt.a: lazy definition of htonl
/tmp/tmpf838iejolibemscripten_js_symbols.so: exported htonl due to import of getaddrinfo
```

And with `-Wl,--trace-symbol=getaddrinfo`:
```
/src/build/target/lib/libgio-2.0.a(ginetsocketaddress.c.o): reference to getaddrinfo
/src/build/target/lib/libgio-2.0.a(gthreadedresolver.c.o): reference to getaddrinfo
/tmp/tmpkyzt2pqglibemscripten_js_symbols.so: importing getaddrinfo
```

**Comment by kleisauke** [comment] 2023-05-22 15:13
Here's a somewhat complex reproducer:
```console
$ git clone https://github.com/kleisauke/wasm-vips.git
$ cd wasm-vips/
$ npm run build -- --enable-lto --disable-jxl --disable-avif --disable-svg --disable-modules
```

I'm working on a minimal reproducible example.

**Comment by kleisauke** [comment] 2023-05-23 08:45
Reduced to:

`main.c`
```c
#include <netdb.h>
#include <stdio.h>
#include <sys/socket.h>

int main() {
    struct addrinfo hints = {}, *infoptr;
    hints.ai_family = AF_INET;

    int result = getaddrinfo("www.example.com", NULL, &hints, &infoptr);
    if (result) {
        fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(result));
        return -1;
    }

    struct addrinfo *p;
    char host[INET_ADDRSTRLEN];

    for (p = infoptr; p != NULL; p = p->ai_next) {
        getnameinfo(p->ai_addr, p->ai_addrlen, host, sizeof(host), NULL, 0,
                    NI_NUMERICHOST);

        // https://github.com/emscripten-core/emscripten/blob/3.1.39/src/library.js#L1763-L1766
        puts(host);
    }

    freeaddrinfo(infoptr);
    return 0;
}
```

```console
$ emcc -flto main.c
...
wasm-ld: error: /src/build/emcache/sysroot/lib/wasm32-emscripten/lto/libc-debug.a(ntohs.o): attempt to add bitcode file after LTO.
wasm-ld: error: /src/build/emcache/sysroot/lib/wasm32-emscripten/lto/libc-debug.a(htons.o): attempt to add bitcode file after LTO.
wasm-ld: error: /src/build/emcache/sysroot/lib/wasm32-emscripten/lto/libc-debug.a(htonl.o): attempt to add bitcode file after LTO.
```

**Comment by sbc100** [comment] 2023-05-23 22:49
I found a fix on wasm-ld side but it sadly introduces some code size regression in our tests .. so I will need some more time to investigate.

**Comment by FrostKiwi** [comment] 2023-06-04 15:48
Want to confirm the same issue here when enabling `LTO`, though with a different file being the cause:
`wasm-ld: error: C:\msys64\home\NomadLover\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libc.a(fileno.o): attempt to add bitcode file after LTO.`

Running `emcc --clear-cache` for good measure. `-Wl,-u,atexit -Wl,-u,__cxa_atexit` Makes no difference. (To be fair, it isn't the same error as in )
<details><summary>Full command</summary>

`emcc: error: 'C:/msys64/home/NomadLover/emsdk/upstream/bin\wasm-ld.exe -o out/index.wasm -u fileno.o obj/gl_basic.o obj/gui.o obj/init.o obj/input.o obj/main.o obj/nuklear.o obj/nuklear_sdl_gles2.o obj/render_loop.o -LC:\msys64\home\NomadLover\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto C:\msys64\home\NomadLover\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libSDL2_image_jpg.a C:\msys64\home\NomadLover\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libjpeg.a C:\msys64\home\NomadLover\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libSDL2.a -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\msys64\tmp\tmpjp795kezlibemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=malloc --export-if-defined=free --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=malloc --export=free --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024' failed (returned 1)`
</details>

**Comment by sbc100** [comment] 2023-06-05 02:28
BTW as a temporary workaround you should be able to do `-Wl,-u,htonl` or `-Wl,-u,fileno` in order to force the linker to include those symbols prior to LTO.

**Comment by FrostKiwi** [comment] 2023-06-06 05:27
@sbc100 
Thanks!
`-Wl,-u,htonl` did not work. `-Wl,-u,fileno` worked. (It was the file causing the issue in the first place)

**Comment by sbc100** [comment] 2023-06-06 14:12
Right, the `-Wl,-u,htonl` was for @kleisauke because that is the symbol he was dealing this.  This is general issue that can effect any symbol that is reverse dependency of a JS file, so that exact symbol depends on which functions you are using.

**Comment by caiiiycuk** [comment] 2023-06-23 15:10
Have same issue with dosbox/dosbox-x and latest emscripten, addede this as workaround:
```
		"-Wl,-u,htons" # https://github.com/emscripten-core/emscripten/issues/16836
		"-Wl,-u,ntohs" # https://github.com/emscripten-core/emscripten/issues/16836
```

**Comment by sergeyext** [comment] 2023-06-30 21:51
I have same issue with 3.1.42:

```
wasm-ld: error: /home/sergey/code/emsdk-new/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc.a(scalbnf.o): attempt to add bitcode file after LTO.
```

**Comment by luc4smoreira** [comment] 2023-07-03 13:35
I have the same issue with 3.1.42 compiling a game using Godot Game Engine for web. Here is a part of the error message I received:

[100%] progress_finish(["progress_finish"], [])
[100%] Linking Static Library ==> core/libcore.javascript.opt.a
Ranlib Library         ==> core/libcore.javascript.opt.a
[100%] Linking Program        ==> bin/godot.javascript.opt.js
wasm-ld: error: /Users/lucasmiranda/dev/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc.a(scalbnf.o): attempt to add bitcode file after LTO.


I downgraded to the version 3.1.40  compiled again and it worked.

**Comment by SanderMertens** [comment] 2023-09-27 08:25
I ran into the same issue on 3.1.4.6:
```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.46 (19607820c447a13fd8d0b7680c56148427d6e1b8)
```

Error message:
```
error: <path>/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc.a(ntohs.o): attempt to add bitcode file after LTO.
```

Adding `-Wl,-u,ntohs` to the linker flags fixed it.

**Comment by sbc100** [comment] 2023-09-27 16:27
@SanderMertens I'd love to try to figure out what is going on here?  Can you try adding `-Wl,--trace-symbol=htons`?  

Is there some way you can share a reproducer for this issue?

**Comment by kleisauke** [comment] 2023-09-27 16:38
> Is there some way you can share a reproducer for this issue?

I think the reproducer mentioned in https://github.com/emscripten-core/emscripten/issues/16836#issuecomment-1558826632 is still relevant here.

**Comment by sbc100** [comment] 2023-09-27 16:46
Sorry, yes you are correct, I failed to refresh my mental cache of this issue.

**Comment by sbc100** [comment] 2023-10-04 16:25
Re-opening, even though the ntohs is somewhat different under the hood.

**Comment by RReverser** [comment] 2023-10-17 02:09
Interestingly, I'm running into the original issue (?) with 3.1.47:

> wasm-ld: error: /emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc-mt.a(ntohs.o): attempt to add bitcode file after LTO (ntohs)

**Comment by RReverser** [comment] 2023-10-17 02:09
Ah one difference seems to be that this is `libc-mt` not `libc` or `libc-debug`, but that shouldn't matter, right?

**Comment by RReverser** [comment] 2023-10-17 02:12
Nvm, I see the issue from reproducer in https://github.com/emscripten-core/emscripten/issues/16836#issuecomment-1558826632 wasn't resolved, so yeah, mine is not different.

**Comment by adamscott** [comment] 2024-02-04 20:23
While investigating godotengine/godot#87611, [I found out](https://github.com/godotengine/godot/issues/87611#issuecomment-1925894581) that our LTO issues begin with emscripten 3.1.47 about the symbol `_emscripten_run_callback_on_thread`.

I used `-Wl,--trace-symbol=_emscripten_run_callback_on_thread` and it gives me this:
```
/home/adamscott/dev/apps/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libhtml5.a: lazy definition of _emscripten_run_callback_on_thread
/tmp/tmplsjsxa_2libemscripten_js_symbols.so: exported _emscripten_run_callback_on_thread due to import of emscripten_set_canvas_element_size
wasm-ld: error: /home/adamscott/dev/apps/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libhtml5.a(callback.o): attempt to add bitcode file after LTO (_emscripten_run_callback_on_thread)
/tmp/tmplsjsxa_2libemscripten_js_symbols.so: exported _emscripten_run_callback_on_thread due to import of emscripten_webgl_do_create_context
em++: error: '/home/adamscott/dev/apps/emsdk/upstream/bin/wasm-ld -o bin/godot.web.template_release.dev.wasm32.wasm --trace-symbol=_emscripten_run_callback_on_thread platform/web/audio_driver_web.web.template_release.dev.wasm32.o platform/web/display_server_web.web.template_release.dev.wasm32.o platform/web/http_client_web.web.template_release.dev.wasm32.o platform/web/javascript_bridge_singleton.web.template_release.dev.wasm32.o platform/web/web_main.web.template_release.dev.wasm32.o platform/web/os_web.web.template_release.dev.wasm32.o platform/web/api/web_tools_editor_plugin.web.template_release.dev.wasm32.o platform/web/web_runtime.web.template_release.dev.wasm32.o main/libmain.web.template_release.dev.wasm32.a modules/libmodules.web.template_release.dev.wasm32.a modules/libmodule_ktx.web.template_release.dev.wasm32.a modules/libmodule_msdfgen.web.template_release.dev.wasm32.a modules/libmodule_theora.web.template_release.dev.wasm32.a modules/libmodule_vorbis.web.template_release.dev.wasm32.a modules/libmodule_basis_universal.web.template_release.dev.wasm32.a modules/libmodule_bmp.web.template_release.dev.wasm32.a modules/libmodule_csg.web.template_release.dev.wasm32.a modules/libmodule_dds.web.template_release.dev.wasm32.a modules/libmodule_enet.web.template_release.dev.wasm32.a modules/libmodule_freetype.web.template_release.dev.wasm32.a modules/libmodule_gdscript.web.template_release.dev.wasm32.a modules/libmodule_gltf.web.template_release.dev.wasm32.a modules/libmodule_gridmap.web.template_release.dev.wasm32.a modules/libmodule_hdr.web.template_release.dev.wasm32.a modules/libmodule_jpg.web.template_release.dev.wasm32.a modules/libmodule_jsonrpc.web.template_release.dev.wasm32.a modules/libmodule_mbedtls.web.template_release.dev.wasm32.a modules/libmodule_meshoptimizer.web.template_release.dev.wasm32.a modules/libmodule_minimp3.web.template_release.dev.wasm32.a modules/libmodule_mobile_vr.web.template_release.dev.wasm32.a modules/libmodule_multiplayer.web.template_release.dev.wasm32.a modules/libmodule_navigation.web.template_release.dev.wasm32.a modules/libmodule_noise.web.template_release.dev.wasm32.a modules/libmodule_ogg.web.template_release.dev.wasm32.a modules/libmodule_regex.web.template_release.dev.wasm32.a modules/libmodule_squish.web.template_release.dev.wasm32.a modules/libmodule_svg.web.template_release.dev.wasm32.a modules/libmodule_text_server_adv.web.template_release.dev.wasm32.a modules/libmodule_tga.web.template_release.dev.wasm32.a modules/libmodule_upnp.web.template_release.dev.wasm32.a modules/libmodule_vhacd.web.template_release.dev.wasm32.a modules/libmodule_webp.web.template_release.dev.wasm32.a modules/libmodule_webrtc.web.template_release.dev.wasm32.a modules/libmodule_websocket.web.template_release.dev.wasm32.a modules/libmodule_webxr.web.template_release.dev.wasm32.a modules/libmodule_zip.web.template_release.dev.wasm32.a platform/libplatform.web.template_release.dev.wasm32.a drivers/libdrivers.web.template_release.dev.wasm32.a scene/libscene.web.template_release.dev.wasm32.a servers/libservers.web.template_release.dev.wasm32.a core/libcore.web.template_release.dev.wasm32.a modules/text_server_adv/libharfbuzz_builtin.web.template_release.dev.wasm32.a modules/text_server_adv/libgraphite_builtin.web.template_release.dev.wasm32.a modules/text_server_adv/libicu_builtin.web.template_release.dev.wasm32.a modules/freetype/libfreetype_builtin.web.template_release.dev.wasm32.a modules/msdfgen/libmsdfgen_builtin.web.template_release.dev.wasm32.a -L/home/adamscott/dev/apps/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto /home/adamscott/dev/apps/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/crtbegin.o -lGL-mt-webgl2-ofb -lal -lhtml5 -lbulkmemory -lstubs-debug -lc-mt-debug -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-debug-mt-noexcept -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmplsjsxa_2libemscripten_js_symbols.so --import-memory --shared-memory --strip-debug --export-if-defined=main --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=_emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=_emscripten_thread_free_data --export=emscripten_main_runtime_thread_id --export=emscripten_main_thread_process_queued_calls --export=_emscripten_run_on_main_thread_js --export=emscripten_stack_set_limits --export=__get_temp_ret --export=__set_temp_ret --export=__funcs_on_exit --export=__wasm_call_ctors --export=_emscripten_thread_init --export=_emscripten_thread_exit --export-table -z stack-size=5242880 --initial-memory=33554432 --max-memory=2147483648 --no-entry --stack-first --table-base=1' failed (returned 1)
```

Tried afterwards with `-Wl,-u,_emscripten_run_callback_on_thread` and it compiles successfully on 3.1.53.

cc. @mgerhardy because their commits relate to the same symbol.

**Comment by Swarkin** [comment] 2024-05-25 20:42
i have this as well
`wasm-ld: error: C:\Users\Me\Documents\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libc-debug.a(htonl.o): attempt to add bitcode file after LTO (htonl)`
any solutions?

**Comment by sbc100** [comment] 2024-05-28 16:11
The workaround suggested above is to add `-Wl,-u,htonl`.  Does that work for you?

**Comment by Swarkin** [comment] 2024-05-28 18:48
yes that seems to compile fine but resulted in a small increase in file size? the docs i was following say lto should decrease file size significantly but thats out of scope for this issue

**Comment by sbc100** [comment] 2024-05-28 18:54
> yes that seems to compile fine but resulted in a small increase in file size? the docs i was following say lto should decrease file size significantly but thats out of scope for this issue

It can go both ways.   LTO can increase inlining since it can inline between compilation units, which can result in a larger file (but potentially with better performance).    The other reason LTO can be less of a win with wasm that other platforms is that we already do wasm-opt which is a form a LTO, even when llvm LTO is not enabled.

**Comment by sbc100** [comment] 2024-08-04 15:29
I finally have a fix for this on the llvm side: https://github.com/llvm/llvm-project/pull/101894

**Closed** 2024-08-06 22:12 UTC
