### ISSUE TITLE
MAIN_THREAD_ASYNC_EM_ASM garbles arguments when used in secondary thread

### ISSUE THREAD

**Issue by theosib** [emscripten-core/emscripten#11350] opened 2020-06-04 20:33 UTC
I am attempting to use MAIN_THREAD_ASYNC_EM_ASM to call some JS code from WASM code (C++). For testing purposes, it's just this:

```
    MAIN_THREAD_ASYNC_EM_ASM({
        console.log("Testing: " + $0 + " " + $1 + " " + $2);
    }, 10, 20, 30);
```

When I use MAIN_THREAD_ASYNC_EM_ASM on the main thread, it works fine. If I do this from a secondary thread, however, the arguments get garbled (changed to random other numbers). In the test case (attached), only the last one is garbled, but in my own application, they're ALL garbled. If I switch to MAIN_THREAD_EM_ASM, then it works fine. If I modify the loop in `thread_func` to return (exit the thread) immediately after the first call to `call_jscode`, it also works fine.

The output I get from the test case looks like this:

```
Starting
test.html:15 Module started
test.js:2872 Calling JS code from main thread
test.js:2168 Testing: 10 20 30
test.js:2872 Launching thread
test.js:2872 Sending signal
test.js:2872 Calling JS code from thread entry point
test.js:2168 Testing: 10 20 1135
test.js:2872 Calling JS code from thread loop
test.js:2168 Testing: 10 20 1126
test.js:2872 Waiting
```

It should be `Testing: 10 20 30` every time, but the last argument gets substituted with something random.

[module-pthread.zip](https://github.com/emscripten-core/emscripten/files/4732559/module-pthread.zip)

**Comment by theosib** [comment] 2020-06-04 21:16
I did some poking around. `emscripten_asm_const_async_on_main_thread` appears to allocate stack space for the arguments so it can pass them to the main thread through the heap. Then it immediately frees that space before returning, so the values are sitting in unallocated space. If anything disturbs the stack before the message is received by the main thread, the values get hosed. I don't think it should be done that way, because it's like getting a pointer to a local variable and then returning.

Instead, either the arguments should be passed in a JS object through the postMessage, or the values should be allocated on the heap in the secondary thread and then freed after use in the main thread.

**Comment by theosib** [comment] 2020-06-04 21:23
The culprit is in the JS runtime, here:

```  function _emscripten_proxy_to_main_thread_js(index, sync) {
      // Additional arguments are passed after those two, which are the actual
      // function arguments.
      // The serialization buffer contains the number of call params, and then
      // all the args here.
      // We also pass 'sync' to C separately, since C needs to look at it.
      var numCallArgs = arguments.length - 2;
      if (numCallArgs > 20-1) throw 'emscripten_proxy_to_main_thread_js: Too many arguments ' + numCallArgs + ' to proxied function idx=' + index + ', maximum supported is ' + (20-1) + '!';
      // Allocate a buffer, which will be copied by the C code.
      var stack = stackSave();
      // First passed parameter specifies the number of arguments to the function.
      var args = stackAlloc(numCallArgs * 8);
      var b = args >> 3;
      for (var i = 0; i < numCallArgs; i++) {
        HEAPF64[b + i] = arguments[2 + i];
      }
      var ret = _emscripten_run_in_main_runtime_thread_js(index, numCallArgs, args, sync);
      stackRestore(stack);
      return ret;
    }```

Notice how it allocates stack space, copies values onto the heap, frees the space, and returns. Someone on Discord said that the sync version does it this way, but it's not appropriate for the async version.

**Comment by kripken** [comment] 2020-06-05 17:09
Good find @theosib ! Yes, I think that should call `malloc` and later `free` in an appropriate way. Would you like to open a PR with that?

**Comment by theosib** [comment] 2020-06-05 20:52
Thanks, kripken. I'll talk to the guys on Discord to see if I can find out how to get a dev environment set up for emscripten. I think it would be best if I figured out how to do this from emsdk so that I can also do appropriate testing. I also just don't know enough about how to do the things you mentioned from within the JS runtime, so I have a lot of learning to do. Sooner or later, I need to do this so I can give something back to the project, but the learning curve right now will not allow me to create a PR in a timely manner. Thanks!

**Comment by kripken** [comment] 2020-06-09 00:09
I understand @theosib , no problem.

Meanwhile I looked at the code here a little more, and I'm not sure there's a bug. Yes, `emscripten_proxy_to_main_thread_js` allocates on the stack, but that is just for the call to `_emscripten_run_in_main_runtime_thread_js`. That method does the actual proxying, and its it's async it allocates using malloc. That looks ok?

**Comment by theosib** [comment] 2020-06-09 15:12
I thought the version I had was a very recent build. All I know is that I could reproducibly get the arguments passed wrong for the ASYNC call.

**Comment by kripken** [comment] 2020-06-09 23:07
Interesting. I'd try to debug this some more, then - it sounds like there is a real bug there, it just isn't the stack issue we initially thought it might be.

**Comment by cloudis31** [comment] 2020-07-09 17:27
I'm actually having a similar issue. I don't know the internals of emscripten as well, so can't really help there right now, but thought i'd provide my issue in case it helps.

I have a worker thread which calls MAIN_THREAD_ASYNC_EM_ASM for each job it completes. It seemed to be working great, until work was being added faster than it was completed. In those cases, it seems that the calls to MAIN_THREAD_ASYNC_EM_ASM is stacking up, and instead of the js callback getting the unique parameters for each callback, it's called multiple times with the same parameters.

![image](https://user-images.githubusercontent.com/17791038/87070186-0b050400-c1de-11ea-89bb-39e8c86f5f09.png)

I send batches for the thread to work on, and log the batch id to the console in js. when the thread completes a batch, it calls MAIN_THREAD_ASYNC_EM_ASM, providing the batch id it just completed. in the callback, i log again the batch id that was just finished.

In the screenshot above, you can see i send batches with id's 3-9. the thread then calls the js callback 7 times for batch id 9.

Now whats weird (to me, probably just because i don't understand the underlying implementation yet), is that if i do a printf statement in the thread before i call MAIN_THREAD_ASYNC_EM_ASM, everything is working perfectly fine, because i'm assuming that printf must be waiting for the main thread or something, where it can then call MAIN_THREAD_ASYNC_EM_ASM, and the MAIN_THREAD_ASYNC_EM_ASM calls are not stacking up or something.

Here's a screenshot when i call printf before MAIN_THREAD_ASYNC_EM_ASM on the thread:

![image](https://user-images.githubusercontent.com/17791038/87070921-1dcc0880-c1df-11ea-9f8e-c5414cf1f074.png)

I was just looking for why this might be happening until i ran into this github issue and decided to post in case its helpful

For now my workaround is going to be the put the finished work into a queue and call a "tick()" function on the main thread which will call MAIN_THREAD_ASYNC_EM_ASM (or one of the other types of js calls) for each finished batch, since it seems to be calling js functions just fine on the main thread.

I'd prefer to not have the tick() or update() function every frame so i'll keep digging around to see if i can find anything else (and checking back here)

**Comment by kripken** [comment] 2020-07-09 22:53
@cloudis31 Hard to say if that is the same issue or not, but it could be!

I took another look at the original testcase here now. What looks like the issue is that, yes, there is a stack allocation as @theosib said, but it is not in `_emscripten_proxy_to_main_thread_js` which we initially thought was the culprit. That function allocates stack and releases it immediately after it is copied. But `EM_ASM*` functions are variadic - so LLVM puts their arguments on the C stack, and passes a final argument which is a pointer to that data. `_emscripten_proxy_to_main_thread_js` gets that and treats it just like any integer or pointer. But the LLVM code unwinds the stack, potentially corrupting the data.

So there are two stack allocations here, which made things confusing. One is ok, one is not. I think #11602 fixes this, at least it fixes the original testcase here. But as this is a racy problem, it's hard to be sure. Please test that PR @theosib and @cloudis31 - thanks!

**Comment by kripken** [comment] 2020-07-15 21:40
That PR landed, so you can test this with `emsdk install tot` (tip of tree build) in an hour or so from now.

**Closed** 2020-07-15 21:40 UTC
