### ISSUE TITLE
std::atomic<std::shared_ptr<T>> not compiling with emcc 3.1.42 / clang 17.0.0

### ISSUE THREAD

**Issue by dsamo** [emscripten-core/emscripten#21733] opened 2024-04-09 23:11 UTC
When compiling this with `emcc -std=c++20 test.cpp` it should be working. However, I get an error as if I am compiling with c++17 and below.

```
#include <memory>
#include <atomic>

struct A
{
	void bar()
	{
		foo = nullptr;
	}

	std::atomic<std::shared_ptr<int>> foo; // error: _Atomic cannot be applied to type 'std::shared_ptr<int>' which is 
                                               // not trivially copyable
};

int main()
{
	A a;
	a.bar();
	return 0;
}
```
Afaik clang >= 15 can compile this in c++ 20. Am I missing something here? Environment:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.42 (6ede0b8fc1c979bb206148804bfb48b472ccc3da)
clang version 17.0.0 (https://github.com/llvm/llvm-project f3b64887de61020c09404bfee97b2fadd30df10a)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Comment by sbc100** [comment] 2024-04-09 23:18
This seems to be an issue with libc++.  Emscripten uses libc++ from the llvm project so its possible this could be an upstream bug. 

You can reproduce this using normal clang++ if you pass `-stdlib=libc++` (but it doesn't reproduce under glibc):

```
$ clang++ -stdlib=libc++ ./test.cpp -std=c++20
In file included from ./test.cpp:1:
In file included from /usr/include/c++/v1/memory:898:
In file included from /usr/include/c++/v1/__memory/shared_ptr.h:42:
/usr/include/c++/v1/atomic:916:37: error: _Atomic cannot be applied to type 'std::shared_ptr<int>' which is not trivially copyable
  916 |   _LIBCPP_DISABLE_EXTENSION_WARNING _Atomic(_Tp) __a_value;
      |                                     ^
/usr/include/c++/v1/atomic:1426:35: note: in instantiation of template class 'std::__cxx_atomic_base_impl<std::shared_ptr<int>>' requested here
 1426 | struct __cxx_atomic_impl : public _Base {
      |                                   ^
/usr/include/c++/v1/atomic:1523:36: note: in instantiation of template class 'std::__cxx_atomic_impl<std::shared_ptr<int>>' requested here
 1523 |     mutable __cxx_atomic_impl<_Tp> __a_;
      |                                    ^
/usr/include/c++/v1/atomic:1717:14: note: in instantiation of template class 'std::__atomic_base<std::shared_ptr<int>>' requested here
 1717 |     : public __atomic_base<_Tp>
      |              ^
./test.cpp:11:36: note: in instantiation of template class 'std::atomic<std::shared_ptr<int>>' requested here
   11 |         std::atomic<std::shared_ptr<int>> foo; // error: _Atomic cannot be applied to type 'std::shared_ptr<int>' which is 
      |                                           ^
In file included from ./test.cpp:1:
In file included from /usr/include/c++/v1/memory:898:
In file included from /usr/include/c++/v1/__memory/shared_ptr.h:42:
/usr/include/c++/v1/atomic:1427:19: error: static assertion failed due to requirement 'is_trivially_copyable<std::shared_ptr<int>>::value': std::atomic<T> requires that 'T' be a trivially copyable type
 1427 |     static_assert(is_trivially_copyable<_Tp>::value,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/atomic:1523:36: note: in instantiation of template class 'std::__cxx_atomic_impl<std::shared_ptr<int>>' requested here
 1523 |     mutable __cxx_atomic_impl<_Tp> __a_;
      |                                    ^
/usr/include/c++/v1/atomic:1717:14: note: in instantiation of template class 'std::__atomic_base<std::shared_ptr<int>>' requested here
 1717 |     : public __atomic_base<_Tp>
      |              ^
./test.cpp:11:36: note: in instantiation of template class 'std::atomic<std::shared_ptr<int>>' requested here
   11 |         std::atomic<std::shared_ptr<int>> foo; // error: _Atomic cannot be applied to type 'std::shared_ptr<int>' which is 
      |                                           ^
2 errors generated.
```

**Comment by sbc100** [comment] 2024-04-09 23:22
This does indeed look like it should be supported in C++20 so perhaps this is just a missing feature in libc++.  Could you file an issue with llvm upstream? 

Context: https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic2

**Comment by sbc100** [comment] 2024-04-09 23:28
It looks like there is an open pull request in llvm so maybe you can watch that issue: https://github.com/llvm/llvm-project/pull/78317

**Comment by dsamo** [comment] 2024-04-09 23:36
> It looks like there is an open pull request in llvm so maybe you can watch that issue: https://github.com/llvm/llvm-project/pull/78317

Hmm, 3 months old and an attempt for implementation using soon deprecated features and not lock free. Not very promising 😅. Anyways, will keep an eye, thanks for looking into this.

**Comment by sbc100** [comment] 2024-04-10 00:36
Closing this issue as dup of https://github.com/llvm/llvm-project/pull/78317

**Closed by sbc100** 2024-04-10 00:36 UTC
