### ISSUE TITLE
Joining a thread after using emscripten_set_main_loop deadlocks

### ISSUE THREAD

**Issue by goldwaving** [emscripten-core/emscripten#22310] opened 2024-08-01 15:15 UTC
Can `std::thread::join()` be used in the main thread after calling `emscripten_set_main_loop` and `emscripten_cancel_main_loop` in a child thread?

If not, what is the correct way to ensure the thread is terminated before deleting it?  Using `join` seems to be deadlocking.

**Comment by sbc100** [comment] 2024-08-01 20:09
`emscripten_cancel_main_loop` should indeed make the thread joinable.

Building with `-sRUNTIME_DEBUG` may help you see what the issue is?

If the problem persists, perhaps you could build a small example showing that this doesn't work as expected?

**Comment by goldwaving** [comment] 2024-08-13 13:17
Thanks for the reply.  `-sRUNTIME_DEBUG` doesn't show anything unusual.  I've reduced it down to the following test case.  Perhaps there is something I'm not understanding about the way emscripten works with `set/cancel_main_loop`.  If `TEST_LOOP` is defined, "Joined" is never reached.  However using a direct loop works (undefine `TEST_LOOP`).

```c++
#include <iostream>
#include <chrono>
#include <thread>
#include <emscripten.h>

using namespace std::chrono;

static bool term = false;
std::thread mainthread;

#define TEST_LOOP
void loop()
{
	std::cout << "Second loop" << std::endl;

	if ( term )
	{
		// This should exit the thread and allow join to complete below, but it doesn't work
		emscripten_cancel_main_loop();
		std::cout << "Terminating" << std::endl;
	}
}

void secondfn()
{
#ifdef TEST_LOOP
	emscripten_set_main_loop( loop, 5, false );
#else
	while ( ! term )
	{
		this_thread::sleep_for( 200ms );
		std::cout << "Second loop" << std::endl;
	}
	std::cout << "Terminating" << std::endl;
#endif
}

void mainfn()
{
	std::thread t( secondfn );
	this_thread::sleep_for( 2s );
	term = true;
	std::cout << "Joining" << std::endl;
	t.join();
	std::cout << "Joined" << std::endl;
}

void uiloop()
{
}

int main()
{
	mainthread = std::thread( mainfn );
	emscripten_set_main_loop( uiloop, 0, false );
	return 0;
}
```

**Comment by sbc100** [comment] 2024-08-13 16:01
Thanks for the repro case.  This uncovered a bug in the browser main loop handling.  I'm working on a fix now but you for a temporary fix you can set `-sEXIT_RUNTIME`.

**Comment by sbc100** [comment] 2024-08-14 15:41
That certainly sounds like a separate issue.

**Comment by goldwaving** [comment] 2024-08-14 19:26
After creating a test case, it turns out that the memory allocation issue was caused by a thread using `Module.HEAP*` instead of just `HEAP*`, so it was not using [`GROWABLE_HEAP_*` as required](https://emscripten.org/docs/porting/pthreads.html#special-considerations).

**Comment by sbc100** [comment] 2024-08-14 20:26
> After creating a test case, it turns out that the memory allocation issue was caused by a thread using `Module.HEAP*` instead of just `HEAP*`, so it was not using [`GROWABLE_HEAP_*` as required](https://emscripten.org/docs/porting/pthreads.html#special-considerations).

Great news! 

I'm still working a fix for this issue.

**Closed** 2024-08-22 23:18 UTC

**Comment by goldwaving** [comment] 2024-09-10 20:41
Something seems to have been broken between 3.1.65 and 3.1.66.  When I create my loop now, the first memory allocation fails with a segfault:
```
abort
segfault
$func102673
$pthread_setspecific
$_mi_prim_thread_associate_default_heap
$mi_thread_init
$mi_heap_get_default
$_mi_malloc_generic
$mi_malloc
$operator_new_impl(unsigned long)
$operator new(unsigned long)
```

**Comment by sbc100** [comment] 2024-09-10 21:15
Can you include the full backtrace?  Is the `new` call coming from the main loop callback?

Could you trry building with `-sPTHREADS_DEBUG`?  Or perhaps you should share a failing example?  (Does the code above now work?)

**Comment by goldwaving** [comment] 2024-09-11 15:22
Joining now works, but it appears the thread is terminated prematurely in some cases when using `emscripten_pause_main_loop`.  The code below fails with a memory error.  Also in certain cases `join` succeeds even before `emscripten_cancel_main_loop` is called.

```c++
#include <iostream>
#include <chrono>
#include <thread>
#include <emscripten.h>
#include <emscripten/eventloop.h>

using namespace std::chrono;

static bool term = false;
std::thread mainthread;

// Remove this define for expected behaviour
#define FAILS

void loop();
extern "C" EMSCRIPTEN_KEEPALIVE void callback(void *)
{
	std::cout << "Callback" << std::endl;
	loop();
}

EM_JS( void, set_timeout, (void), {
	setTimeout( ()=>Module._callback(0), 200 );
} );

void loop()
{
	std::cout << "Second loop" << std::endl;

	if ( term )
	{
		emscripten_cancel_main_loop();
		std::cout << "Terminating" << std::endl;
		return;
	}
	char *d = new char[1000000];
	delete [] d;

	// Pausing the loop seems to cause the thread to terminate in some cases
	static bool paused = false;
	if ( ! paused )
	{
		paused = true;
		emscripten_pause_main_loop();
	}

#ifdef FAILS
	set_timeout();
#else
	emscripten_set_timeout( callback, 200, nullptr );
#endif
}

void mainfn()
{
	std::thread t( [] { emscripten_set_main_loop( loop, 10, false ); } );
	this_thread::sleep_for( 2s );
	term = true;
	std::cout << "Joining" << std::endl;
	t.join();
	std::cout << "Joined" << std::endl;
};

void uiloop()
{
}

int main()
{
	mainthread = std::thread( mainfn );
	emscripten_set_main_loop( uiloop, 0, false );
	return 0;
}
```

**Comment by sbc100** [comment] 2024-09-11 16:58
I see, I assume we are treating `emscripten_pause_main_loop` the same as `emscripten_cancel_main_loop` in terms of keeping the runtime alive.

One was to work around this an make sure your thread stays alive would be to call `emscripten_runtime_keepalive_push()` from the thread you want to keep alive.
