### ISSUE TITLE
regression from 2.0.30: llvm assertian failure: Assertion `!ToFreeze && "freeze() not called with ToFreeze being set"' failed.

### ISSUE THREAD

**Issue by mr-c** [emscripten-core/emscripten#15149] opened 2021-09-27 16:53 UTC
Hello,
https://github.com/simd-everywhere/simde ran into an [error](https://github.com/simd-everywhere/simde/issues/920) in CI. Below is a reproducible example from running the instructions at https://github.com/simd-everywhere/simde/tree/master/docker + `simde-reset-build.sh emscripten; ninja -C emscripten test`

Both CI and this example use `emsdk install tot`
```
/opt/emsdk/upstream/emscripten/emcc -Itest/arm/neon/qtbl-emul-c.js.p -Itest/arm/neon -I../../../usr/local/src/simde/test/arm/neon -I. -I../../../usr/local/src/simde -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -g -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -DSIMDE_NO_NATIVE -MD -MQ test/arm/neon/qtbl-emul-c.js.p/qtbl.c.o -MF test/arm/neon/qtbl-emul-c.js.p/qtbl.c.o.d -o test/arm/neon/qtbl-emul-c.js.p/qtbl.c.o -c ../../../usr/local/src/simde/test/arm/neon/qtbl.c
clang: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/lib/Transforms/Vectorize/VectorCombine.cpp:808: ScalarizationResult::~ScalarizationResult(): Assertion `!ToFreeze && "freeze() not called with ToFreeze being set"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=31 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/opt/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -Itest/arm/neon/qtbl-emul-c.js.p -Itest/arm/neon -I../../../usr/local/src/simde/test/arm/neon -I. -I../../../usr/local/src/simde -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -g -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -DSIMDE_NO_NATIVE -MD -MQ test/arm/neon/qtbl-emul-c.js.p/qtbl.c.o -MF test/arm/neon/qtbl-emul-c.js.p/qtbl.c.o.d -c ../../../usr/local/src/simde/test/arm/neon/qtbl.c -o test/arm/neon/qtbl-emul-c.js.p/qtbl.c.o
1.	<eof> parser at end of file
2.	Optimizer
 #0 0x0000147b17f41c53 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x1a50c53)
 #1 0x0000147b17f3fa5e llvm::sys::RunSignalHandlers() (/opt/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x1a4ea5e)
 #2 0x0000147b17f40fcd llvm::sys::CleanupOnSignal(unsigned long) (/opt/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x1a4ffcd)
 #3 0x0000147b17e712f3 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x0000147b17e7149e CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #5 0x0000147b164da8e0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x138e0)
 #6 0x0000147b124abe71 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:50:1
 #7 0x0000147b12495536 abort ./stdlib/abort.c:81:7
 #8 0x0000147b1249541f get_sysdep_segment_value ./intl/loadmsgcat.c:509:8
 #9 0x0000147b1249541f _nl_load_domain ./intl/loadmsgcat.c:970:34
#10 0x0000147b124a47f2 (/lib/x86_64-linux-gnu/libc.so.6+0x357f2)
#11 0x0000147b1940a7ce (anonymous namespace)::VectorCombine::run()::$_1::operator()(llvm::Instruction&) const VectorCombine.cpp:0:0
#12 0x0000147b19406ca8 (anonymous namespace)::VectorCombine::run() VectorCombine.cpp:0:0
#13 0x0000147b194068a3 llvm::VectorCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x2f158a3)
#14 0x0000147b1a26c73d llvm::detail::PassModel<llvm::Function, llvm::VectorCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilder.cpp:0:0
#15 0x0000147b180f9811 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x1c08811)
#16 0x0000147b1a24e91d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilder.cpp:0:0
#17 0x0000147b180fe424 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x1c0d424)
#18 0x0000147b1a24ec8d llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) PassBuilder.cpp:0:0
#19 0x0000147b180f8214 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x1c07214)
#20 0x0000147b1504c09f (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) BackendUtil.cpp:0:0
#21 0x0000147b1504641a clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x28b341a)
#22 0x0000147b153a8410 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) CodeGenAction.cpp:0:0
#23 0x0000147b140205a4 clang::ParseAST(clang::Sema&, bool, bool) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x188d5a4)
#24 0x0000147b1598c700 clang::FrontendAction::Execute() (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x31f9700)
#25 0x0000147b159079cf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x31749cf)
#26 0x0000147b15a0d298 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x327a298)
#27 0x00000000002145c8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/emsdk/upstream/bin/clang+0x2145c8)
#28 0x000000000021216d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#29 0x0000147b155de102 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) Job.cpp:0:0
#30 0x0000147b17e71207 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x1980207)
#31 0x0000147b155ddc57 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x2e4ac57)
#32 0x0000147b155a94c8 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x2e164c8)
#33 0x0000147b155a9797 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x2e16797)
#34 0x0000147b155c34c1 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x2e304c1)
#35 0x0000000000211734 main (/opt/emsdk/upstream/bin/clang+0x211734)
#36 0x0000147b12496e4a __libc_start_main ./csu/../csu/libc-start.c:314:16
#37 0x000000000020ef3a _start (/opt/emsdk/upstream/bin/clang+0x20ef3a)
clang-14: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project 4b37462aab4e5f5f1ffdb04294e87b990d189751)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /opt/emsdk/upstream/bin
clang-14: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /tmp/qtbl-a007ed.c
clang-14: note: diagnostic msg: /tmp/qtbl-a007ed.sh
clang-14: note: diagnostic msg: 

********************
```
[qtbl-a007ed.sh.gz](https://github.com/emscripten-core/emscripten/files/7238023/qtbl-a007ed.sh.gz)
[qtbl-a007ed.c.gz](https://github.com/emscripten-core/emscripten/files/7238024/qtbl-a007ed.c.gz)

**Comment by mr-c** [comment] 2021-09-27 16:59
When I `./emsdk install latest` instead of `tot` then there is no compiler failure.

**Comment by kripken** [comment] 2021-09-27 22:36
This sounds like a very recent regression in LLVM. Please file an issue there https://bugs.llvm.org/ and link to it from here.

**Comment by mr-c** [comment] 2021-09-28 09:00
@kripken Thanks for the sanity check. I've reported this upstream to https://bugs.llvm.org/show_bug.cgi?id=51992

**Comment by kripken** [comment] 2021-09-28 19:18
Great, thanks @mr-c ! And looks like the response there was very quick, and this is fixed already, so closing.

**Closed by kripken** 2021-09-28 19:18 UTC

**Comment by mr-c** [comment] 2021-09-28 19:37
@kripken Thanks for the encouragement! When can we expect `tot` to pull in this fix?

**Comment by kripken** [comment] 2021-09-28 23:17
There is a tot build from 2 hours ago that contains all recent LLVM changes, so I think it should be there now.

**Comment by mr-c** [comment] 2021-09-29 12:48
@kripken So fast, super! I can confirm the fix locally; thanks again!
