### ISSUE TITLE
wasm-ld: error: unknown file type:

### ISSUE THREAD

**Issue by MaeThird** [emscripten-core/emscripten#19466] opened 2023-05-29 02:21 UTC
**Version of emscripten/emsdk:**

> 

root@a206427d23c4:/# emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.39-git
clang version 16.0.4
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /native/emcc-docker/llvm-project-llvmorg-16.0.4/output/bin

> 

**Failing command line in full:**

Just compile the "hello world" example to get the output. It seems that the 'wasm-ld' can't recognize the stub object which is in the form of `xxxlibemscripten_js_symbols.so` added by `create_stub_object` in `building.py` anymore.

```
root@a206427d23c4:/native/emcc-docker# emcc ./t0.c
wasm-ld: error: unknown file type: /tmp/tmpc5kyiwfilibemscripten_js_symbols.so
emcc: error: '/native/emcc-docker/llvm-project-llvmorg-16.0.4/output/bin/wasm-ld -o a.out.wasm /tmp/emscripten_temp_1nrrovxj/t0_0.o -L/native/emcc-docker/emscripten-3.1.39/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmpc5kyiwfilibemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first' failed (returned 1)
root@a206427d23c4:/native/emcc-docker# cat t0.c
#include <stdio.h>
int main() {
  printf("hello, world!\n");
  return 0;
}
root@a206427d23c4:/native/emcc-docker#
```
emscripten is 3.1.39

**Comment by sbc100** [comment] 2023-05-30 17:04
The version of wasm-ld you are using is too old and doesn't include support for the `libemscripten_js_symbols.so` stub library which was added here: https://reviews.llvm.org/D145308

In general, emscripten requires a build from llvm from tip-of-tree and we don't support old/stable releases such as 16.0.4.   See https://github.com/emscripten-core/emscripten/issues/11362 for more on this.

**Comment by willcohen** [comment] 2023-05-31 20:12
@MaeThird I put in a backport request for the next LLVM 16 point release for these changes at https://github.com/llvm/llvm-project/issues/63040.

**Comment by sbc100** [comment] 2023-05-31 20:34
If you want to try to push for backporting things that emscripten depends on then feel free, but that fact remains that we only tests againt llvm tip-of-tree (currently LLVM 17) and we explicitly depend on it here: https://github.com/emscripten-core/emscripten/blob/6de3b76b7ebbb641e1e06bd0bf45b12b9d4615b1/tools/shared.py#L52

Running emscripten against any other version llvm is not officially supported at this time.

**Comment by willcohen** [comment] 2023-05-31 20:44
Got it -- the policy makes sense for trying to keep things moving on the development side. The backports seem like a happy medium for anyone else who's trying to use stable versions to have to deal with, and this new-ish little workflow they've got going seems pretty painfree all things considered.

**Comment by sbc100** [comment] 2023-05-31 20:53
I'm guessing that llvm folks who are in charge the backporting will be likely to push back against larger changes to things like new command line flags, but I guess we will see.

I would be worried about the potential extra support burden we would get from supporting this effort, but anyone who is explicitly ignoring the version check warning in emcc knows what they are signing up for I guess?

**Comment by sbc100** [comment] 2023-05-31 20:54
I think we can probably close this issue out now?

**Comment by willcohen** [comment] 2023-05-31 20:57
Totally fair. For whatever it's worth, if llvm doesn't want to go this road, I'll probably still try to get smaller backports of this in nixpkgs just so nix can keep emscripten up to date since that's their general goal and there's almost no chance they'll be able to keep LLVM at tip, given that it's busy building everything else in the system. Usually nixpkgs users at least know to bother the nix people when stuff is acting wonky, so hopefully I'm not sending anyone your way!

Anyway, thanks for the clarifications -- not trying to add more work on your side, and yes, I think this can be closed. I can confirm for posterity that the two mentioned commits backported do seem to get things working again with 3.1.40.

**Comment by sbc100** [comment] 2023-05-31 21:07
BTW, if you would like to discuss this further please mention your use case in #11362 (if it hasn't been already mentioned).  There is certainly some appetite out there for supporting LLVM stable releases, you are not the only ones.

**Closed** 2023-05-31 21:08 UTC

**Comment by laterbuy** [comment] 2024-09-29 14:32
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.66 (1f519517284660f4b31ef9b7f921bf6ba66c4041)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 7543d09b852695187d08aa5d56d50016fea8f706)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\soft\emsdk\upstream\bin

**Comment by laterbuy** [comment] 2024-09-29 14:32
>emcc test.c
wasm-ld: error: unknown file type: C:\Users\NOVA00~1\AppData\Local\Temp\tmpkuqqjq9llibemscripten_js_symbols.so
emcc: error: 'D:/soft/emsdk/upstream/bin\wasm-ld.exe -o a.out.wasm C:\Users\NOVA00~1\AppData\Local\Temp\emscripten_temp_ibhz6bjj\test_0.o -LD:\soft\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\Users\NOVA00~1\AppData\Local\Temp\tmpkuqqjq9llibemscripten_js_symbols.so --strip-debug --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export=_emscripten_stack_restore --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1' failed (returned 1)

**Comment by laterbuy** [comment] 2024-09-29 14:32
can not complie
