### ISSUE TITLE
Shell Environment and SINGLE_FILE base 64 decoding failure.

### ISSUE THREAD

**Issue by sanjaychugh** [emscripten-core/emscripten#19845] opened 2023-07-12 04:10 UTC
Hello, I was on `3.1.41` and yesterday I updated to `3.1.43` and now the same command line doesn't work when using the javascript output at runtime.
I am testing WebAssembly with emscripten for the Android JavascriptEngine.
This requires me to compile with the `-sENVIRONMENT=shell` option.

With `3.1.41` the output single js file had a function `base64Decode` which was called from the `intArrayFromBase64` function. With 3.1.43 after compiling the output js file does not have the `base64Decode` function and instead the `intArrayFromBase64` function calls the `"atob"` function.
So when I execute the javascript in the Android JavascriptEngine I get a error decoding the base64 data for the wasm code.

I can see the changes made for `3.1.43 `unfortunately I am unable to sort out if I need to set another option now to get this to work as before or if this is a bug or change in behaviour etc?

Please include the following in your bug report:

**Version of `emscripten/emsdk:** 3.1.43

Please include the output `emcc -v` here
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.43 (a6b8143cf3c1171db911750359456b15a8deece7)
clang version 17.0.0 (https://github.com/llvm/llvm-project 71513a71cdf380efd6a44be6939e2cb979a62407)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/sanjay/src/wasm/emsdk/upstream/bin
```

**Failing command line in full:**
`emcc hello.cpp -sENVIRONMENT=shell -sEXPORTED_RUNTIME_METHODS=ccall,cwrap -sSINGLE_FILE -o hello.js`
If this is compile or link-time failure please include the full failing command
along with its entire output.

**Full link command and output with `-v` appended:**
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.
```
"/home/sanjay/src/wasm/emsdk/upstream/bin/clang" --version
 "/home/sanjay/src/wasm/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN --sysroot=/home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -v hello.cpp -c -o /tmp/emscripten_temp_c6w7p2tv/hello_0.o
clang version 17.0.0 (https://github.com/llvm/llvm-project 71513a71cdf380efd6a44be6939e2cb979a62407)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/sanjay/src/wasm/emsdk/upstream/bin
 (in-process)
 "/home/sanjay/src/wasm/emsdk/upstream/bin/clang-17" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name hello.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/sanjay/src/wasm/emsdk/test -resource-dir /home/sanjay/src/wasm/emsdk/upstream/lib/clang/17 -D EMSCRIPTEN -isysroot /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /home/sanjay/src/wasm/emsdk/upstream/lib/clang/17/include -internal-isystem /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include -fdeprecated-macro -fdebug-compilation-dir=/home/sanjay/src/wasm/emsdk/test -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_c6w7p2tv/hello_0.o -x c++ hello.cpp
clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
 /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /home/sanjay/src/wasm/emsdk/upstream/lib/clang/17/include
 /home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 "/home/sanjay/src/wasm/emsdk/upstream/bin/wasm-ld" -o hello.wasm /tmp/emscripten_temp_c6w7p2tv/hello_0.o -L/home/sanjay/src/wasm/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmpxizmjk6_libemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first
 "/home/sanjay/src/wasm/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers hello.wasm -o hello.wasm --detect-features
 "/home/sanjay/src/wasm/emsdk/node/16.20.0_64bit/bin/node" /home/sanjay/src/wasm/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpkvp_yb7i.json
 "/home/sanjay/src/wasm/emsdk/upstream/bin/llvm-objcopy" hello.wasm hello.wasm --remove-section=.debug* --remove-section=producers
```

**Comment by kripken** [comment] 2023-07-12 17:57
@sbc100 perhaps fallout from #19792 ?

**Comment by kripken** [comment] 2023-07-12 17:58
(If it's not that, then @sanjaychugh perhaps [bisecting](https://emscripten.org/docs/contributing/developers_guide.html#bisecting) would be useful here.)

**Comment by sbc100** [comment] 2023-07-12 18:41
This was causes by #19606.  With that change we only polyful atob when we think we need to.   I guess we should include the polyfill when `shell` is possibly targeted.. I'll take a look.

**Comment by sbc100** [comment] 2023-07-12 22:19
Fix is in https://github.com/emscripten-core/emscripten/pull/19851

**Comment by creaktive** [comment] 2023-07-14 11:35
I have the same issue, but I'm not using `-sENVIRONMENT=shell`. Tried your fix, however the problem with decoding Base64 persists.
Here's my command line:
```bash
emcc -ffast-math -flto -std=c++14 -pedantic -Werror -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-declarations -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-overflow=5 -Wswitch-default -Wno-unused   \
                -O3 \
                --bind \
                --post-js js/pianolizer-wrapper.js \
                -s BINARYEN_ASYNC_COMPILATION=0 \
                -s EXPORTED_FUNCTIONS="['_malloc']" \
                -s SINGLE_FILE=1 \
                -s WASM=1 \
                -o js/pianolizer-wasm.js \
                cpp/pianolizer.cpp
```

**Comment by sbc100** [comment] 2023-07-25 10:10
@creaktive, what platform are you running the generated JS on?  Is it a browser?  If so, which one?

What error are you seeing?

**Closed** 2023-07-25 22:01 UTC

**Comment by Wol** [comment] 2023-07-31 16:54
I'm also seeing this after upgrading to version 3.1.44. Happens in Chrome 115 when importing it into an AudioWorkletProcessor which runs in the `AudioWorkletGlobalScope` which from what I can tell doesn't have the `atob` function available in it. The version I upgraded from had the polyfill for `atob` which worked fine.

My emcc call is:

`
emcc --bind -O1 \
  -s WASM=1 \
	-s BINARYEN_ASYNC_COMPILATION=0 \
	-s RESERVED_FUNCTION_POINTERS=10 \
	-s SINGLE_FILE=1 \
	SimpleKernel.cc \
	-o simple-kernel.wasmmodule.js \
	--post-js ./em-es6-module.js
`

**Comment by sbc100** [comment] 2023-07-31 17:04
Sounds like the polyfill should also be included when `AUDIO_WORKLET` is set.   Do you want to send a PR to that effect @Wol?

**Comment by Wol** [comment] 2023-08-01 08:12
At the moment neither of us are using the `AUDIO_WORKLET` flag in the Makefile (I'll be honest that I didn't realise emscripten had a direct implementation for it!).

I'm currently using my own wrapper which creates the `AudioWorkletProcessor` and am manually loading the emscripten code from that, so I don't have `AUDIO_WORKLET` set. 

I'll try giving the `AUDIO_WORKLET` version a try and see if I can make that work instead.

**Comment by sbc100** [comment] 2023-08-01 11:53
Wait, so you were able to load the emscripten output inside and audio worklet without setting `-sAUDIO_WORKLET` at build time?   That is surprising to me.   @juj, is that expected?

I guess we at least need some kind of way to know at build time if that target might be a worklet.    I think `-sAUDIO_WORKLET` makes the most sense as a way to signal this.  We could also add `worklet` to the possible `-sENVIRONMENT` flags, but that seems maybe redundant in face of `-sAUDIO_WORKLET`.

**Comment by sbc100** [comment] 2023-08-01 11:56
Is there some easy way to tell if `atob` is supposed to exist in an AudioWorklet?   I can see that its supposed it exist in workers in general: https://developer.mozilla.org/en-US/docs/Web/API/atob#browser_compatibility.. but does that mean it should also exist in an AudioWorklet?   i.e. is it a bug that its not available?

**Comment by creaktive** [comment] 2023-08-01 14:00
I just checked, and my thing works alright when it is loaded as a regular `Worker`. `atob()` is only missing if I load it as `AudioWorkletProcessor` (unfortunately, this is the primary usage case).
Worklets are really tricky. They implement a subset of functionality to begin with, and then different browsers implement slightly different subsets. In the end, people have to resort to [abominations like this](https://github.com/WebAudio/web-audio-api-v2/issues/109#issuecomment-756634198) for compatibility reasons...

**Comment by Wol** [comment] 2023-08-01 14:12
@sbc100 - The base example is from https://github.com/GoogleChromeLabs/web-audio-samples/tree/main/src/audio-worklet/design-pattern/wasm/  if you want to have a look at the code structure I'm using. the `wasm-worklet-processor.js` file is wrapping the emcc compiled kernel. 

`atob` is available for Service Workers on WorkerGlobalScope - https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope
`atob` is also available in a DOM Window - https://developer.mozilla.org/en-US/docs/Web/API/Window

The issue is that the Worklets run in  `AudioWorkletGlobalScope` which doesn't list `atob` on it. I guess that sort of makes sense at a certain point as you're not meant to be base64 decoding data in an audio worklet, so I could sort of understand why it isn't there. Obviously this case is just a single one-time load, not a per audio frame thing, so doesn't cause any issues.

I've worked around the issue so far with just doing an `include 'polyfill.js'` at the top of the file before I include the `wasmmodule.js` file which brings atob back into the relevant scope at the time it's run.

**Comment by juj** [comment] 2023-08-02 06:14
> Wait, so you were able to load the emscripten output inside and audio worklet without setting -sAUDIO_WORKLET at build time? That is surprising to me. @juj, is that expected?

I would not recommend that people go down that path - they will end up reimplementing much of what `-sAUDIO_WORKLET` implements.

> We could also add worklet to the possible -sENVIRONMENT flags, but that seems maybe redundant in face of -sAUDIO_WORKLET.

Agree, `audioworklet` could be part of `-sENVIRONMENT`, if we take the manual loading in an audio worklet to be a feature, but I would recommend against it - I don't think that is a worthwhile use case (although happy to be convinced otherwise, if people do have a convincing rationale).

> Is there some easy way to tell if atob is supposed to exist in an AudioWorklet?

I don't know which WebIDL interface should bring in `atob`, but at least `AudioWorkletGlobalScope` should be inheriting from regular `WorkletGlobalScope`, which suggests that it should have everything that a Worker has. Marked down an issue to the Web Audio folks, link above ^.

**Comment by Wol** [comment] 2023-08-02 08:50
@juj Just to clarify that WorkletGlobalScope (Worklet, not Worker), doesn't seem to have any methods or properties on it - https://developer.mozilla.org/en-US/docs/Web/API/WorkletGlobalScope so I wasn't expecting `atob` to be there at least based on the mozilla docs. `WorkerGlobalScope` is the one which has `atob`, but the Worklets don't inherit from that. 

> I would not recommend that people go down that path - they will end up reimplementing much of what -sAUDIO_WORKLET implements.

Might be worth doing a PR into the GoogleChromeLabs web audio repo as their wasm example is just putting the emscripten code into their own audio worklet!

**Comment by sbc100** [comment] 2023-08-02 15:14
OK, so it sounds like the fixes we need are:

1. Update the GoogleChromeLabs example to use `-sAUDIO_WORKLET`.
2. Update the `atob` pollyfil to be included when `-sAUDIO_WORKLET` is used.
3. Perhaps assert in debug builds if detect we are running in an AudioWorklet but `-sAUDIO_WORKLET`  was not specified.
