### ISSUE TITLE
Turning on optimizations leads to incorrect bitwise AND results

### ISSUE THREAD

**Issue by jcao219** [emscripten-core/emscripten#14561] opened 2021-06-30 07:34 UTC
I noticed a program ([butteraugli](https://github.com/google/butteraugli)) behaving differently when compiled with emscripten `-O0` vs `-O1`.

While investigating, I realized it may be a bug with emscripten. I tried to reduce it to this test case (I appreciate help in reducing it further):

## arith.cpp:
Edit: See next comment for a further reduced test case.
```cpp
#include <stdio.h>
#include <cassert>
#include <cstdlib>
#include <memory>

constexpr size_t kCacheLineSize = 64;
constexpr size_t kPointerSize = sizeof(void *);

void *allocate() {
  size_t bytes = 2048;
  char *const allocated = static_cast<char *>(malloc(bytes + kCacheLineSize));
  const uintptr_t misalignment =
      reinterpret_cast<uintptr_t>(allocated) & (kCacheLineSize - 1);
  // malloc is at least kPointerSize aligned, so we can store the "allocated"
  // pointer immediately before the aligned memory.
  assert(misalignment % kPointerSize == 0);
  char *const aligned = allocated + kCacheLineSize - misalignment;
  memcpy(aligned - kPointerSize, &allocated, kPointerSize);
  return aligned;
}

void deallocate(void *aligned_pointer) {
  char *const aligned = static_cast<char *>(aligned_pointer);
  // The following checks for alignment:
  assert(reinterpret_cast<uintptr_t>(aligned) % kCacheLineSize == 0);
  char *allocated;
  memcpy(&allocated, aligned - kPointerSize, kPointerSize);
  free(allocated);
}

int main() {
  void *ptrs[10];
  for (int i = 0; i < 10; i++) {
    void *ptr = allocate();
    ptrs[i] = ptr;
    printf("Allocated %p\n", ptrs[i]);
  }
  for (int i = 0; i < 10; i++) {
    printf("Aligned (= 0)? %lu\n", reinterpret_cast<uintptr_t>(ptrs[i]) % kCacheLineSize);
    deallocate(ptrs[i]);
  }
  return 0;
}
```

built with a Docker container, `docker build -t emscript . && docker run -it --rm -v $PWD:/src emscript`:

## Dockerfile
```
FROM emscripten/emsdk:2.0.24
ENV FLAGS "-O1 -std=c++17 -g2 -s ALLOW_MEMORY_GROWTH=1"
WORKDIR /src
CMD emcc ${FLAGS} -o arith.js arith.cpp;
```

## -O1 output
Building with `-O1` or above results in this output:
```cpp
> node arith.js
Allocated 0x500d88
Allocated 0x5015c0
Allocated 0x501e08
Allocated 0x502680
Allocated 0x502ec8
Allocated 0x503700
Allocated 0x503f48
Allocated 0x504780
Allocated 0x504fc8
Allocated 0x505800
Aligned (= 0)? 8
Assertion failed: reinterpret_cast<uintptr_t>(aligned) % kCacheLineSize == 0, at: arith.cpp,25,deallocate
exception thrown: RuntimeError: abort(Assertion failed: reinterpret_cast<uintptr_t>(aligned) % kCacheLineSize == 0, at: arith.cpp,25,deallocate). Build with -s ASSERTIONS=1 for more info.,RuntimeError: abort(Assertion failed: reinterpret_cast<uintptr_t>(aligned) % kCacheLineSize == 0, at: arith.cpp,25,deallocate). Build with -s ASSERTIONS=1 for more info.
```
Returning a result that is not zero modulo `kCacheLineSize` shouldn't be possible, based on the code in allocate.

## -O0 output
whereas with optimizations turned off:
```cpp
> node arith.js
Allocated 0x500dc0
Allocated 0x501600
Allocated 0x501e40
Allocated 0x5026c0
Allocated 0x502f00
Allocated 0x503740
Allocated 0x503f80
Allocated 0x5047c0
Allocated 0x505000
Allocated 0x505840
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
```

**Comment by jcao219** [comment] 2021-06-30 16:17
I was able to reduce it further to this test case:

```cpp
#include <stdio.h>
#include <cassert>
#include <cstdlib>
#include <bitset>
#include <memory>

constexpr size_t kCacheLineSize = 64;
constexpr size_t kPointerSize = sizeof(void *);

void *allocate() {
  size_t bytes = 2048;
  char *const allocated = static_cast<char *>(malloc(bytes + kCacheLineSize));

  // The problem is in the following bitwise operation:
  const uintptr_t misalignment = reinterpret_cast<uintptr_t>(allocated) & (kCacheLineSize - 1);
  printf("allocated:          %s &\n", std::bitset<64>(reinterpret_cast<uintptr_t>(allocated)).to_string().c_str());
  printf("kCacheLineSize - 1: %s\n", std::bitset<64>(kCacheLineSize - 1).to_string().c_str());
  printf("-----------------------------------------------------------------------------------\n");
  printf("misalignment:       %s\n\n", std::bitset<64>(misalignment).to_string().c_str());
  return allocated + kCacheLineSize - misalignment; // should be 0 modulo 64.
}

int main() {
  void *ptrs[10];
  for (int i = 0; i < 10; i++) {
    void *ptr = allocate();
    ptrs[i] = ptr;
  }
  for (int i = 0; i < 10; i++) {
    printf("Aligned (= 0)? %lu\n", reinterpret_cast<uintptr_t>(ptrs[i]) % kCacheLineSize);
  }
  return 0;
}
```

Compiling with `-O0` results in correct bitwise AND operations:
```
allocated:          0000000000000000000000000000000000000000010100000000110111011000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000011000

allocated:          0000000000000000000000000000000000000000010100000001011000100000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000100000

allocated:          0000000000000000000000000000000000000000010100000001111001101000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000101000

allocated:          0000000000000000000000000000000000000000010100000010011010110000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000110000

allocated:          0000000000000000000000000000000000000000010100000010111011111000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000111000

allocated:          0000000000000000000000000000000000000000010100000011011101000000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000000000

allocated:          0000000000000000000000000000000000000000010100000011111110001000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000001000

allocated:          0000000000000000000000000000000000000000010100000100011111010000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000010000

allocated:          0000000000000000000000000000000000000000010100000101000000011000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000011000

allocated:          0000000000000000000000000000000000000000010100000101100001100000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000100000

Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
Aligned (= 0)? 0
```

Compiling with `-O1` results in this:

```
> node .\arith.js
allocated:          0000000000000000000000000000000000000000010100000000110110111000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000110000

allocated:          0000000000000000000000000000000000000000010100000001011000000000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000000000

allocated:          0000000000000000000000000000000000000000010100000001111001001000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000000000

allocated:          0000000000000000000000000000000000000000010100000010011010010000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000010000

allocated:          0000000000000000000000000000000000000000010100000010111011011000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000010000

allocated:          0000000000000000000000000000000000000000010100000011011100100000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000100000

allocated:          0000000000000000000000000000000000000000010100000011111101101000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000100000

allocated:          0000000000000000000000000000000000000000010100000100011110110000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000110000

allocated:          0000000000000000000000000000000000000000010100000100111111111000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000110000

allocated:          0000000000000000000000000000000000000000010100000101100001000000 &
kCacheLineSize - 1: 0000000000000000000000000000000000000000000000000000000000111111
-----------------------------------------------------------------------------------
misalignment:       0000000000000000000000000000000000000000000000000000000000000000

Aligned (= 0)? 8
Aligned (= 0)? 0
Aligned (= 0)? 8
Aligned (= 0)? 0
Aligned (= 0)? 8
Aligned (= 0)? 0
Aligned (= 0)? 8
Aligned (= 0)? 0
Aligned (= 0)? 8
Aligned (= 0)? 0
```

Notice that the `misalignment = allocated & (kCacheLineSize - 1)` calculations are incorrect half of the time.

**Comment by tlively** [comment] 2021-06-30 22:54
Oh interesting, @sbc100, this looks like it could be an example of LLVM making assumptions about the alignment of pointers coming out of `malloc` that do not agree with our implementation. We recently decided on a path forward for fixing our alignment issues, right?

**Comment by sbc100** [comment] 2021-06-30 23:02
Oh really, so it could be another case of #10072.

If that is correct then adding `-fno-builtin` would make the problem go away.  Can you confirm if this is true?

**Comment by sbc100** [comment] 2021-06-30 23:04
Confirmed, `-fno-builtin` makes the issue go away.  Therefore this is a duplicate of #10072.   Closing as dup.

**Comment by sbc100** [comment] 2021-06-30 23:05
Quite impressive that llvm is taking advantage of that!

**Closed by sbc100** 2021-06-30 23:04 UTC
