### ISSUE TITLE
linker error

### ISSUE THREAD

**Issue by MetaMemoryT** [emscripten-core/emscripten#8819] opened 2019-06-18 17:19 UTC
Traceback (most recent call last):
  File "/Users/sean/p/emsdk/fastcomp/emscripten/emcc.py", line 3420, in <module>
    sys.exit(run(sys.argv))
  File "/Users/sean/p/emsdk/fastcomp/emscripten/emcc.py", line 1907, in run
    final = shared.Building.link(linker_inputs, DEFAULT_FINAL, force_archive_contents=force_archive_contents, just_calculate=just_calculate)
  File "/Users/sean/p/emsdk/fastcomp/emscripten/tools/shared.py", line 1978, in link
    Building.read_link_inputs([x for x in files if not x.startswith('-')])
  File "/Users/sean/p/emsdk/fastcomp/emscripten/tools/shared.py", line 1757, in read_link_inputs
    object_names_in_archives = pool.map(extract_archive_contents, archive_names)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
tools.shared.Py2CalledProcessError: Command '['/Users/sean/p/emsdk/fastcomp/fastcomp/bin/llvm-ar', 'xo', '/Users/sean/.emscripten_cache/asmjs/libcompiler_rt.a']' returned non-zero exit status -9

**Comment by sbc100** [comment] 2019-06-18 17:24
What does `file /Users/sean/.emscripten_cache/asmjs/libcompiler_rt.a` say?

What does running `/Users/sean/p/emsdk/fastcomp/fastcomp/bin/llvm-ar t /Users/sean/.emscripten_cache/asmjs/libcompiler_rt.a` report?

Does deleting that file fix the issue?

**Comment by pikilipita** [comment] 2019-06-20 16:38
Same issue here ( osx 10.11.6 ),
in my case, you first question says:
/Users/xxxxxx/.emscripten_cache/asmjs/libcompiler_rt.a: current ar archive random library

and the second one:
divdc3.c.o
divsc3.c.o
muldc3.c.o
mulsc3.c.o

this is a new issue since I updated, using emscripten 1.38.28 was fine

**Comment by MetaMemoryT** [comment] 2019-06-22 23:36
I get the same output as the previous comment.

**Comment by sbc100** [comment] 2019-06-24 16:52
What if you run `'/Users/sean/p/emsdk/fastcomp/fastcomp/bin/llvm-ar xo /Users/sean/.emscripten_cache/asmjs/libcompiler_rt.a` by hand?  Does it work?

Is there anything else you see in the output that might tell you why llvm-ar is failing?

**Comment by robozo** [comment] 2019-07-01 06:50
Similar problem here, updated from emscripten 1.38.25 to most recent 1.38.37, now get llvm-ar "returned non-zero exit status -9" as above.  Tried running by hand, as suggested by sbc100, got
dyld: Symbol not found: _futimens
  Referenced from: /Users/rob/emscript/emsdk/fastcomp/fastcomp/bin/../lib/libLLVM.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
OK, I'm running Mac OSX 10.12, and do not plan on running anything later.  Looks like recent emscripten uses that libLLVM.dylib.  Found
https://github.com/emscripten-core/emscripten/issues/5418
which, if I understand, claims that the issue is fixed for later emscripten versions, but there seems to still be a problem.  Am not sure how to proceed, revert?  Any advice appreciated!

**Comment by sbc100** [comment] 2019-07-01 19:11
Should be fixed by https://github.com/WebAssembly/waterfall/pull/546.

Its really shame that the error isn't better reported though.  I might take a look at that.

**Comment by robozo** [comment] 2019-07-02 18:50
Many thanks!  however I'm an enscripten beginner, and haven't been able to incorporate the "waterfall" into my local code.  I tried
% emsdk update-tags
% emsdk install latest
% emsdk activate latest
looked like something happened, and SDL2 works fine.
But when building with FreeType, llvm-ar tries to extract libfreetype.a, and calls libLLVM.dylib
which hasn't been updated, so we get the "_futimes not found" error as before.

Sorry to be using an old mac OS, but after years of being good about running old programs,
OSX has recently become unfriendly, I just have too much stuff that will stop running.
I thought about stealing "futimes" from a newer system, but found a few people who had
bricked their machines by messing around with /usr/lib/libSystem.B.dylib.
% mv libSystem.B.dylib _libSystem.B.dylib
then mv, ssh, etc don't work any more.  oops!
Maybe it's finally time to move to some linux flavor...

**Comment by sbc100** [comment] 2019-07-02 19:10
This should be fixed once that waterfall change is used to build a new release.   I'm not sure how long this will take but hopefully not more than a day or so.

In the mean time you can use emsdk to build llvm and/or fastcomp yourself on your local machine to work around the issue.

The problem will only exist in the pre-built binaryies, not in binaryies you build yourself.

**Comment by robozo** [comment] 2019-07-02 22:12
Sorry to ask another simple question, but if I understand, in order to build a new libLLVM.dylib
I should pull in the newest clang, but when I run
% emsdk install clang-incoming-64bit
there are a bunch of errors.

Traceback (most recent call last):
  File "/Users/rob/emscript/emsdk/emsdk", line 928, in xcode_sdk_version
    return subprocess.check_output(['xcrun', '--show-sdk-version']).strip().split('.')
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rob/emscript/emsdk/emsdk", line 2683, in <module>
    sys.exit(main())
  File "/Users/rob/emscript/emsdk/emsdk", line 2665, in main
    success = tool.install()
  File "/Users/rob/emscript/emsdk/emsdk", line 1536, in install
    success = build_llvm_tool(self)
  File "/Users/rob/emscript/emsdk/emsdk", line 980, in build_llvm_tool
    if OSX and (not os.environ.get('LLVM_CMAKE_ARGS') or 'HAVE_FUTIMENS' not in os.environ.get('LLVM_CMAKE_ARGS')) and xcode_sdk_version() < [10, 13]:
  File "/Users/rob/emscript/emsdk/emsdk", line 930, in xcode_sdk_version
    return subprocess.checkplatform.mac_ver()[0].split('.')
AttributeError: module 'subprocess' has no attribute 'checkplatform'

OK,  it looks like 'emsdk' is pulling in a module from somewhere, "import subprocess", which is missing something.  I don't know python, and couldn't find where the source of 'subprocess' is.

Am i missing something obvious?  Again, thanks for your time, and I'll get educated eventually!

**Comment by robozo** [comment] 2019-07-03 00:34
OK, I'm running Python 2.7.15 and there are several 'subprocess.py' on the disk, none of them
have a 'checkplatform' in them.  I can see that 'emsdk' calls platform.mac_ver()  to get the system,
and I could try editing the offending line
return subprocess.checkplatform.mac_ver()[0].split('.')
to see what it does, but I might be just creating a mess...

**Comment by sbc100** [comment] 2019-07-03 00:58
`subprocess.checkplatform.mac_ver` looks like a bug.  It looks like the author meant to write just `platform.mac_ver`.

It also looks like this is a python3 related issue.  You could try running "python2 emsdk ..".

In order to fix the issue you try changing that function to be this and see if that works?

```
def xcode_sdk_version():
  try:
    version = subprocess.check_output(['xcrun', '--show-sdk-version'], universal_newlines=True).strip()
  except subprocess.CalledProcessError:
    version = subprocess.checkplatform.mac_ver()[0]
  return version.split(',')
```

**Comment by robozo** [comment] 2019-07-03 02:47
Thanks, I edited 'emsdk' to get rid of the test, and just add manually add
args += ['-DHAVE_FUTIMENS=0']
(what kind of crazy language is python?  Tab Errors?  I thought javascript was bad)
Now
% emsdk install clang-incoming-64bit
Works!  It ran for an hour, then
% emsdk activate clang-incoming-64bit
then ran my makefile, the machine imported a bunch of stuff, and cranked away for another
quarter-hour, but it actually produced a working index.asm and index.js!

I'm amazed this stuff works.  Thanks again for your help, now to try actually getting stuff done...
Can appreciate why people can find supporting old Mac OSX annoying...

**Closed** 2020-08-01 03:40 UTC
Labels: wontfix
