### ISSUE TITLE
WebGL Build - Exception: llvm-ar failed on archive libcxx.a!

### ISSUE THREAD

**Issue by jupiterbjy** [emscripten-core/emscripten#11174] opened 2020-05-16 14:57 UTC
Tried unity 5, 2019.3.13f1 and 2020.1 b4, b8. Only unity 5 aren't having this issue. Reinstalled at least 3 times per versions with fresh new projects yet still have exact same issue.

Both Unity 2019 and 2020 beta are having llvm-ar issue on extremely simple unity project with only few boxes with 3 scripts. Will attach project file if needed.
I can compile fine with PC Standalone platform on any of those versions.

Line:

> Exception: llvm-ar failed on archive C:\Program Files\Unity\Hub\2019.3.13f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten_FastComp_Win\cache\asmjs\libcxx.a!

Full log:
[log from 2020.1 b4](https://pastebin.com/CusTAM7r) - other versions also show same results.

**Comment by sbc100** [comment] 2020-05-16 16:10
I looks like it might be related to #11126.   This change only landed in an emscripten release yesterday though when 1.39.16 was released.     With the change, the default location of the cache is now inside the emscripten directory, and perhaps that is causing an issue with unity? 

if that is the cause though, I'm surprised you are seeing already since I imagine unity is using specific pinned version of emscripten (older than one day).    Can you tell what version it is including by running `emcc --version`?

Does the file in question exist? `Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten_FastComp_Win\cache\asmjs\libcxx.a`?    How big is it?  Does running `llvm-mn ..` on it show anything?

**Comment by sbc100** [comment] 2020-05-16 16:13
@juj I hope #11126 isn't going to be too much of problem for unity.  If I'm correct and that is causing there issue there are couple of solutions:

1. Ship a cache directory pre-populated so it never needs to written to (this is what we are doing with emsdk now, shipping all the libraries pre-built).
2. Set the cache directory back to the user's home-directory using using `CACHE = os.path.expanduser('~/.emscripten_cache')` in the config file.

**Comment by jupiterbjy** [comment] 2020-05-17 00:23
Found identical [libcxx.a](https://drive.google.com/open?id=1dXEdnCRQ1eHRC7GOnUYwlZMHzvEtOFYG) in both installation. I suspect emcc --version is environmental variable for emscripten? I don't see any interactive console in unity to input it.

**Comment by sbc100** [comment] 2020-05-17 01:25
Actually I could be https://github.com/emscripten-core/emsdk/pull/501.. depending on how unity integrates with emsdk.  I'm sure @juj will know right away.

**Comment by jupiterbjy** [comment] 2020-05-17 05:45
Seeing it already merged, I can't just build and put new versions of emscripten, right? It's surprising unity still use 1.38 in 2020.1 beta 8.

**Comment by juj** [comment] 2020-05-20 18:50
@jupiterbjy Please open an issue about this to Unity side bug trackers.. it does seem like the installation did not complete fully, resulting in missing files.

Because Unity installs to C:\Program Files, which is a Windows protected directory, it cannot do file writing to Emscripten subdirectory. #11126 will certainly break our world, and everyone else's who install an SDK under Program Files (I recall Unreal Engine and Godot do the same). Although I think that is not the issue that @jupiterbjy is seeing, as Unity is still on an older Emscripten version.

**Comment by sbc100** [comment] 2020-05-20 19:01
Regarding read-only installs.   I discuss that in #9543.   For packagers such as hombrew, or linux installations, or something like unity that installs in a read-only location, those packagers will need to to explicitly set `CACHE = ` in thier config file (to either point to read/write location or to $HOME like the old default).   I think the benefit of using embedded-by-default for git users and emsdk users is worth it.

In the long term I hope the packagers (including emsdk) can avoid the need to writable cache directory at all but shipping everything pre-built...  But we are not quite there yet.

**Comment by jupiterbjy** [comment] 2020-05-21 09:29
I installed on other directory, and WebGL - emscripten - builds without error on unity 5.x.x on same root installation folder. And already opened a issue on unity side first, but since I got no reply for week I decided to ask here too.
It can't be only me experiencing this issue.

Is it possible to build fastcomp_win from source and overwrite ones unity is using?

And, can anyone double check integrity of that libcxx.a I've linked above? Since 6th installation still gives  same file I highly doubt it's damaged.

This is on win10 x64, if it was not shown on full log.

**Closed** 2021-07-09 11:28 UTC
Labels: wontfix
