### ISSUE TITLE
llvm-build crashed due to incorrect decoding of working path

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#4856] opened 2017-01-12 22:28 UTC
```
  Unexpected failure executing llvm-build: Traceback (most recent call last):

    File "/home/user/文档/emsdk_portable/clang/fastcomp/src/utils/llvm-build/llvm-build", line 6, in <module>
      llvmbuild.main()
    File "/home/user/文档/emsdk_portable/clang/fastcomp/src/utils/llvm-build/llvmbuild/main.py", line 932, in main
      source_root, llvmbuild_source_root)
    File "/home/user/文档/emsdk_portable/clang/fastcomp/src/utils/llvm-build/llvmbuild/main.py", line 91, in load_from_path
      LLVMProjectInfo.load_infos_from_path(llvmbuild_source_root))
    File "/home/user/文档/emsdk_portable/clang/fastcomp/src/utils/llvm-build/llvmbuild/main.py", line 83, in recurse
      for item in recurse(os.path.join(subpath, subdir)):
    File "/home/user/文档/emsdk_portable/clang/fastcomp/src/utils/llvm-build/llvmbuild/main.py", line 70, in recurse
      llvmbuild_path = os.path.join(llvmbuild_source_root + subpath,

  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11:
  ordinal not in range(128)
```

Have to ensure each part of string is unicode, decoded with file system encoding.

**Comment by dschuff** [comment] 2017-01-12 22:48
This appears to be a bug in llvmbuild, which is part of LLVM upstream rather than emscripten proper. Does the problem reproduce with the unmodified upstream LLVM from llvm.org? If so then you can file a bug there (I can help if you want). If not, then it may have been fixed since the last time we merged upstream code into fastcomp, and we can look in more detail.

**Comment by LYF610400210** [comment] 2017-01-12 23:04
```bash
$ sha256sum '/home/user/emsdk_portable/clang/fastcomp/src/utils/llvm-build/llvmbuild/main.py' 
6a8aabe64ade3de5583b5a71d32928f13756b1fd389d98264f00326a0a499379  /home/user/emsdk_portable/clang/fastcomp/src/utils/llvm-build/llvmbuild/main.py

$ sha256sum '/home/user/下载/llvm-3.9.1.src/utils/llvm-build/llvmbuild/main.py' 
6a8aabe64ade3de5583b5a71d32928f13756b1fd389d98264f00326a0a499379  /home/user/下载/llvm-3.9.1.src/utils/llvm-build/llvmbuild/main.py
```
Files are identical.

**Closed** 2021-07-08 02:32 UTC
Labels: wontfix
