### ISSUE TITLE
Emscripten/EmSDK on the Web? (Emscriptify Emscripten?)

### ISSUE THREAD

**Issue by void4** [emscripten-core/emscripten#7046] opened 2018-08-24 17:43 UTC
Is it possible to run Emscripten on the Web, via Javascript or Wasm?
I want to compile C source to .wasm binaries *on the client side*, without having a server.
Has this been done before?

**Comment by curiousdannii** [comment] 2018-08-25 09:00
Not yet, and probably not for a while. It's theoretically possible, but would take lots of work to put together, as there would need to be WASM versions of Emscripten, Clang, Node, and Python. It would also be several hundred MB.

**Comment by kripken** [comment] 2018-08-26 18:04
Yeah, things like clang and python are fairly large, so this would not be lightweight. It could work, though - there are recent ports of most of those, like [clang](https://github.com/tbfleming/cib) and [python](https://github.com/iodide-project/pyodide), so if someone wanted to look into gluing those up and figuring out any issues, that could be a fun project.

Another option is to run linux in a CPU emulator like [Fabrice Bellard's](https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/buildroot-x86.cfg) - that would be slower than direct ports, but might take less work.

**Comment by rudi-cilibrasi** [comment] 2021-09-12 03:27
i think a wasm native compiler of c/c++ would be the ultimate virtual machine. is there still a reason this is hard two years later?

**Comment by kripken** [comment] 2021-09-13 20:47
I think this is a duplicate of https://github.com/emscripten-core/emscripten/issues/6432 , closing in favor of that.

**Comment by kripken** [comment] 2021-11-08 17:47
Closing in favor of #6432 (I apparently clicked the wrong button before).

See the update there, this has been accomplished, https://github.com/emscripten-core/emscripten/issues/6432#issuecomment-963407064

**Closed by kripken** 2021-11-08 17:47 UTC
