### ISSUE TITLE
[feature request] Support _setjmp in Emscripten and LLVM

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#14999] opened 2021-09-06 12:14 UTC
I've gotten this message and program crash. Do I need to link in `setjmp` somehow with special linking flags? Normally it should be available from C runtime (glibc, musl, etc)

It is defined at https://github.com/emscripten-core/emscripten/blob/main/system/lib/libc/musl/include/setjmp.h#L34, but under some conditions which I don't fully understand:
```cpp
#if defined(_XOPEN_SOURCE) || defined(_GNU_SOURCE) \
 || defined(_BSD_SOURCE)
int _setjmp (jmp_buf);
_Noreturn void _longjmp (jmp_buf, int);
#endif
```

Is `_XOPEN_SOURCE`, `_GNU_SOURCE`, `_BSD_SOURCE` defined during compilation of Emscripten?

At linking time it's 
```
2021-09-06T11:15:58.7244402Z warning: undefined symbol: _longjmp (referenced by top-level compiled C/C++ code)
2021-09-06T11:15:58.7247878Z warning: undefined symbol: _setjmp (referenced by top-level compiled C/C++ code)
```

**Comment by vadimkantorov** [comment] 2021-09-06 17:45
`-s SUPPORT_LONGJMP=1` at the linking step does not help

**Comment by vadimkantorov** [comment] 2021-09-06 18:17
Do I just need to add `-D_GNU_SOURCE` to my `emcc` compilation or `em++` linking steps?

**Comment by sbc100** [comment] 2021-09-08 13:33
This is not related to the header or to _GNU_SOURCE since its not a compile time issue, but a link time issue.

setjmp and longjmp should be lowered away during compilation so they should not exist as undefined symbols at link time (unless you build with `-sSUPPORT_LONGJMP=0`.

Can you share a reproduction case perhaps?  Is there anything strange about how you are referencing those symbols?   Are you building with LTO?

**Comment by sbc100** [comment] 2021-09-08 13:34
@aheejin any idea how this might happen?

**Comment by vadimkantorov** [comment] 2021-09-08 15:07
I've first tried without `-sSUPPORT_LONGJMP=0`, and then with. Both cases had this `_setjmp` problem. I'm building with `-Oz`, so likely without LTO

These symbols resurfaced after compiling LuaTeX. I wonder if this is related to Lua's mechanism of exception mechanism. I"m not sure why I got this crash of missing symbol, maybe it tried to throw an exception

**Comment by sbc100** [comment] 2021-09-08 15:21
Lua does use setjmp longjmp yes, but that should work just fine.  Indeed we have several tests that link against lua in our test suite.

Can you see where the symbol reference is coming from my using `-Wl,--trace-symbol=setjmp` ?

**Comment by kripken** [comment] 2021-09-08 15:37
Does this codebase maybe take the address of setjmp?

**Comment by vadimkantorov** [comment] 2021-09-08 15:42
> -Wl,--trace-symbol=setjmp

Do I add this to linking step?

**Comment by sbc100** [comment] 2021-09-08 15:45
Yes

**Comment by aheejin** [comment] 2021-09-08 19:35
Can you modify your code to use `setjmp` instead of `_setjmp`? Our Wasm LLVM backend transforms `setjmp` calls to a sequence of code but it only processes `setjmp` and not `_setjmp`..

**Comment by vadimkantorov** [comment] 2021-09-08 19:45
I didn't find any calls in LuaTex source that use `_setjmp`, but it appears after object generation

**Comment by aheejin** [comment] 2021-09-08 19:50
@kripken 
> Does this codebase maybe take the address of setjmp?

Possible. We don't support indirect calls of `setjmp`. We actually explicitly error out at compilation time, but that logic was disrupted recently and I fixed it to properly error out yesterday. In the meantime it can surface as a linker error. But anyway if this is the case we don't support it anyway.

**Comment by aheejin** [comment] 2021-09-08 19:52
@vadimkantorov 
> I didn't find any calls in LuaTex source that use `_setjmp`, but it appears after object generation. Just in case I used a define to rename `_setjmp` to `setjmp`, but to no effect...

I can make our Wasm backend to handle not only `setjmp` but also `_setjmp`, but if we are unclear when that call is generated I'm not sure if it would work. What do you exactly mean with "appears after object generation"?

**Comment by vadimkantorov** [comment] 2021-09-08 20:14
I mean that I can find plenty of `setjmp` calls in the source code, but no `_setjmp` calls

**Comment by aheejin** [comment] 2021-09-08 20:41
Can we have the full command line?

**Comment by vadimkantorov** [comment] 2021-09-08 20:45
It's https://github.com/busytex/busytex github actions Build pipeline. It takes 1.5-2hours to build :( and it's the last step that's failing. I'm trying the trace-symbol=_setjmp stuff. If it doesn't help I'll download all temp object files to find the ones using _setjmp.

**Comment by aheejin** [comment] 2021-09-08 21:35
What is the `emcc` command line are you using? That might help.
Also you can try compiling with `--profiling-funcs`, which preserves all internal function names in the object files.

**Comment by vadimkantorov** [comment] 2021-09-09 07:05
So `_setjmp` is coming from Lua indeed:
`2021-09-08T21:59:56.3999522Z build/wasm/texlive/libs/lua53/.libs/libtexlua53.a(ldo.o): reference to _setjmp`

**Comment by vadimkantorov** [comment] 2021-09-09 07:08
It is used in Lua when POSIX env is detected:
https://github.com/TeX-Live/texlive-source/blob/trunk/libs/lua53/lua53-src/src/ldo.c#L67

**Comment by vadimkantorov** [comment] 2021-09-09 07:19
I'm trying now to define `_setjmp` as `setjmp` at the stage of building Lua, but it should be good for Emscripten to support _setjmp directly...

**Comment by sbc100** [comment] 2021-09-09 07:44
Ah, it had not occurred to be that the leading underscore was now the one that emscripten often adds. 

It looks like the lua version that we have under test test is not the same as upstream in how it decided to use the underscore versions:

Upstream:
https://github.com/lua/lua/blob/9db4bfed6bb9d5828c99c0f24749eedf54d70cc2/ldo.c#L63-L77

Our version:
https://github.com/emscripten-core/emscripten/blob/1267242815c355d7a0b86a7c667790dc4bdcdcda/tests/third_party/lua/src/ldo.c#L58-L70

It does seems like we should support these versions, but it believe that fix that would mean and llvm changes (since its llvm that processes the calls to setjmp/longjmp, right @aheejin?) so you might want to fix a local fix for now such as not defining `LUA_USE_POSIX` or patching `ldo.c`.

**Comment by vadimkantorov** [comment] 2021-09-09 07:51
Google search suggests that LLVM is already doing something special about _setjmp/setjmp, but maybe only if it detects MSVC defines...

**Comment by sbc100** [comment] 2021-09-09 07:58
IIRC that code in this file would need to handle the alternative names: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/WebAssembly/WebAssemblyLowerEmscriptenEHSjLj.cpp

But it doesn't looks like it does today: https://github.com/llvm/llvm-project/blob/9d4896f50e441ea5b9e8ae78ebe328e006cb6b67/llvm/lib/Target/WebAssembly/WebAssemblyLowerEmscriptenEHSjLj.cpp#L405

**Comment by vadimkantorov** [comment] 2021-09-09 08:07
Coincidentally, currently there is some ongoing SjLj work: https://github.com/emscripten-core/emscripten/pull/14976

**Comment by vadimkantorov** [comment] 2021-09-09 08:08
> I'm trying now to define `_setjmp` as `setjmp` at the stage of building Lua, but it should be good for Emscripten to support _setjmp directly, in case some library wants to detect POSIX. I guess that's why they are guarded as _GNU_SOURCE / _BSD_SOURCE in musl

Also, there may be more functions like this that are guarded under _GNU_SOURCE

**Comment by aheejin** [comment] 2021-09-13 02:24
Tried to add support for `_setjmp` and `_longjmp` in https://reviews.llvm.org/D109669. Will let you know when it lands.

#14976 is a different kind of SjLj support. The current SjLj support uses code transformation that uses JavaScript's `throw`-`catch`, which works but code size increase is large and the performance is not very good. #14976 adds support for a new kind of SjLj handling, which uses [Wasm EH proposal](https://github.com/WebAssembly/exception-handling). This proposal is not yet merged into the standard and the work is still in progress, but VM support in V8 and FireFox is near completion V8's support is planned to land in stable within a few months, so you may try that after that. But this SjLj support using Wasm EH is currently experimental and not well tested against big applications, so things might break. In that case we appreciate bug reports too. :)

**Closed** 2021-09-13 21:46 UTC

**Comment by aheejin** [comment] 2021-09-16 22:09
The `_setjmp`/`_longjmp` support is included in the latest emsdk release, in case you use released versions: https://github.com/emscripten-core/emsdk/releases/tag/2.0.30
