### ISSUE TITLE
WebGL FPS regression after updating emcc 1.38.33 -> 1.39.8

### ISSUE THREAD

**Issue by klishevich** [emscripten-core/emscripten#10753] opened 2020-03-22 14:35 UTC
After I updated version of emcc from 1.38.33 to 1.39.8, I noticed that frames per second dropped twice from 42 FPS to 21 FPS. I am using MacBook Pro 2015 with macOS Catalina.

**There is a detailed description how I did compare.**

1) This is the chart I got using wasm build with emcc 1.39.8. In the left bottom corner FPS is 21.

<img width="917" alt="Screenshot 2020-03-22 at 17 08 08" src="https://user-images.githubusercontent.com/1125328/77251745-2e249b80-6c61-11ea-806a-8a093529cb14.png">

2) My emcc version

```
mike@mars SciChart % emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.8
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 9dc84e9b02d1e402503906099d42fbae4da7d8d9)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Users/mike/projWebCharts/emsdk/upstream/bin
shared:INFO: (Emscripten: Running sanity checks)
```

3) My wasm was built with the script **build-wasm.sh**

```
emcc --bind  --closure-compiler 1 -s WASM=1 -s MODULARIZE=1 -s ASSERTIONS=1 -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0 -std=c++11 \
-I../../Twister3D/Twister/api \
-I../../Twister3D/Twister/src \
-I../../Twister3D/TwisterFoundation/api \
-I../../Twister3D/TwisterFoundation/src \
-I../../Twister3D/External/pvrTexTool/Include \
-I../../Core.Cpp/src/SciChart.Core/api \
-I../../Core.Cpp/src/SciChart.Charting.2D.Native/api \
-I../../Core.Cpp/src/SciChart.Charting.3D.Native/api \
-I../../SharedLicensing/src/Abt.Licensing.Native/api \
-s USE_WEBGL2=1 \
-s USE_SDL=2 \
-s USE_FREETYPE=1 \
-s ALLOW_MEMORY_GROWTH=1 \
-DTSR_PLATFORM_WEB \
-DTSR_SDL_ENABLED \
-DOPENGLES2_RENDERER \
-DNDEBUG \
-DTSR_REFLECTION_MEMBERS_METHODS_DISABLED \
-DTSR_REFLECTION_CORE_TYPES_DISABLED \
-DTSR_DEBUG_DRAW_DISABLED \
-DTSR_IMMEDIATE_DRAW_DISABLED \
@TSRFoundation.list \
@TSREngine.list \
@SciChart.Charting.Native.2D.list \
@SciChart.Charting.Native.3D.list \
../../WPF/src/Examples/SciChart.Native.Demo/SCRTLightSample.cpp \
../../WPF/src/Examples/SciChart.Native.Demo/SCRTSampleChartInterface.cpp \
../../WPF/src/Examples/SciChart.Native.Demo/SciChartBindings.cpp \
-o build/SCRTSample2D.js \
--preload-file assets/TSRAssets.web.pkg \
--preload-file assets/SCRTAssets.web.pkg \
--preload-file assets/SCRTNAssets.web.pkg 
```

4) Next I downgrade to emcc version 1.38.33

```
mike@mars emsdk % ./emsdk install 1.38.33
Installing SDK 'sdk-releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit'..
Installing tool 'node-12.9.1-64bit'..
The contents of file 'node-v12.9.1-darwin-x64.tar.gz' already exist in destination '/Users/mike/projWebCharts/emsdk/node/12.9.1_64bit', skipping.
Done installing tool 'node-12.9.1-64bit'.
Installing tool 'releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit'..
Downloading: /Users/mike/projWebCharts/emsdk/zips/3b8cff670e9233a6623563add831647e8689a86b-wasm-binaries.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/3b8cff670e9233a6623563add831647e8689a86b/wasm-binaries.tbz2, 178422382 Bytes
Unpacking '/Users/mike/projWebCharts/emsdk/zips/3b8cff670e9233a6623563add831647e8689a86b-wasm-binaries.tbz2' to '/Users/mike/projWebCharts/emsdk/fastcomp'
Done installing tool 'releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit'.
Running post-install step: npm ci ...
Done running: npm ci
Done installing SDK 'sdk-releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit'.
mike@mars emsdk % ./emsdk activate 1.38.33
Writing .emscripten configuration file to user home directory /Users/mike/
Backing up old Emscripten configuration file in /Users/mike/.emscripten.old
The Emscripten configuration file /Users/mike/.emscripten has been rewritten with the following contents:

NODE_JS = '/Users/mike/projWebCharts/emsdk/node/12.9.1_64bit/bin/node'
LLVM_ROOT = '/Users/mike/projWebCharts/emsdk/fastcomp/fastcomp/bin'
BINARYEN_ROOT = '/Users/mike/projWebCharts/emsdk/fastcomp'
EMSCRIPTEN_ROOT = '/Users/mike/projWebCharts/emsdk/fastcomp/emscripten'
EMSCRIPTEN_NATIVE_OPTIMIZER = '/Users/mike/projWebCharts/emsdk/fastcomp/bin/optimizer'
TEMP_DIR = '/var/folders/04/t1mclcq1275f1gm54mxwky780000gn/T'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.

   /Users/mike/projWebCharts/emsdk:/Users/mike/projWebCharts/emsdk/node/12.9.1_64bit/bin:/Users/mike/projWebCharts/emsdk/fastcomp/emscripten

Set the following tools as active:
   node-12.9.1-64bit
   releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit
```

5) My emcc version now

```
mike@mars emsdk % emcc -v
cache:INFO: generating system asset: is_vanilla.txt... (this will be cached in "/Users/mike/.emscripten_cache/is_vanilla.txt" for subsequent builds)
cache:INFO:  - ok
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.33
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp 1b4148f39a69c7fc62edadd85e4122b68694dfb7) (emscripten 1.38.31 : 1.38.31)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Users/mike/projWebCharts/emsdk/fastcomp/fastcomp/bin
shared:WARNING: (Emscripten: system change: 1.38.33|/Users/mike/projWebCharts/emsdk/fastcomp/fastcomp/bin|6.0 vs 1.39.8|/Users/mike/projWebCharts/emsdk/fastcomp/fastcomp/bin|6.0, clearing cache)
shared:ERROR: Emscripten, llvm and clang build versions do not match, this is dangerous (1.38.33, 1.38.31, 1.38.31)
shared:ERROR: Make sure to rebuild llvm and clang after updating repos
shared:INFO: (Emscripten: Running sanity checks)
```

6) I run my build-wasm.sh script again

```
mike@mars SciChart % ./build-wasm.sh 
cache:INFO: generating system asset: is_vanilla.txt... (this will be cached in "/Users/mike/.emscripten_cache/is_vanilla.txt" for subsequent builds)
cache:INFO:  - ok
system_libs:WARNING: local copy of port is not correct, retrieving from remote server
system_libs:WARNING: retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_17.zip
system_libs:WARNING: unpacking port: sdl2
cache:INFO: generating port: libSDL2.bc... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libSDL2.bc" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating port: libfreetype.a... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libfreetype.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++_noexcept.a... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libc++_noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi.bc... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libc++abi.bc" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc.bc... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc-wasm.bc... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libc-wasm.bc" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libdlmalloc.bc... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libdlmalloc.bc" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libgl-webgl2.bc... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libgl-webgl2.bc" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libpthreads_stub.bc... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libpthreads_stub.bc" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc-extras.bc... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/libc-extras.bc" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/Users/mike/.emscripten_cache/asmjs/generated_struct_info.json" for subsequent builds)
cache:INFO:  - ok
emcc:INFO: Enabling --no-heap-copy because -s ALLOW_MEMORY_GROWTH=1 is being used with file_packager.py (pass --no-heap-copy to suppress this notification)
```

7) I start my web app and get twice as much FPS 42 (left bottom corner)!
<img width="913" alt="Screenshot 2020-03-22 at 17 11 46" src="https://user-images.githubusercontent.com/1125328/77252105-38479980-6c63-11ea-86bd-14610efe4781.png">

**Comment by sbc100** [comment] 2020-03-22 16:04
The main difference between those two releases is that the older one uses the fastcomp backend and the newer one uses upstream llvm.

You could confirm that is the reason by installing latest-fastcomp to see if that is indeed the cause.

**Comment by klishevich** [comment] 2020-03-22 17:46
thank you @sbc100, I have installed latest-fastcomp backend and got 40 FPS. 

```
mike@mars emsdk % emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.8
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp b4837f88af2d240abb550c0bbd47f3b8ffe5985a) (emscripten 1.38.31 : 1.38.31)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Users/mike/projWebCharts/emsdk/fastcomp/fastcomp/bin
shared:INFO: (Emscripten: Running sanity checks)
```

I can confirm that **switching to upstream llvm backend results in reducing FPS by half from 40 to 20 FPS** in my WebGL App.

**Comment by kripken** [comment] 2020-03-22 18:43
Thanks @klishevich - ok, sounds like you are hitting an unknown slow path in upstream then, that we need to fix.

To diagnose it, a good starting point is to create `--profiling` builds of upstream and fastcomp, and provide them to us with clear instructions for how to run them and to measure perf. Or instead of providing the builds you can run browser profilers yourself, basically just profile for a while and then compare the two profiles. Given a 2X slowdown, the difference will hopefully be very noticeable (some function taking much more time in upstream).

**Comment by klishevich** [comment] 2020-03-22 20:51
I did some profiling and found out that problem is Animation Frame Fired function call, in line with `requestAnimationFrame(a);` from js file, generated by emscripten.

```js
function ye(a) {
  if ("function" === typeof requestAnimationFrame) {
    requestAnimationFrame(a);
  } else {
    var b = Date.now();
    if (0 === bf) {
      bf = b + 1000 / 60;
    } else {
      for (; b + 2 >= bf;) {
        bf += 1000 / 60;
      }
    }
    setTimeout(a, Math.max(bf - b, 0));
  }
}
```

These are my profiling screenshots. 

<img width="1440" alt="Screenshot 2020-03-22 at 23 37 26" src="https://user-images.githubusercontent.com/1125328/77260229-d2293980-6c97-11ea-8f12-c5958637f209.png">
<img width="1440" alt="Screenshot 2020-03-22 at 23 40 30" src="https://user-images.githubusercontent.com/1125328/77260236-d6eded80-6c97-11ea-825c-1e17a40b5663.png">

@kripken I hope it helps

**Comment by kripken** [comment] 2020-03-22 21:04
I'm confused. 0.1/0.4 ms is indeed a large difference, but it's just a tiny fraction of the entire frame. It might be noise. It's better to look at the heavy functions that take lots of time (and you may want to invert the call stacks, which sometimes help). In a 2x slowdown like this, you might find a function in upstream that takes 50% of the total time, for example.

(Also, that quoted  function should be identical in both backends - do you see any difference in it?)

Note that the quoted code you provided seems to be closure minified, so I'm not sure if `--profiling` was used in your build, which is useful for profiling.

If you can't provide the builds, providing the profiles might help.

Btw, re-reading the above, it looks like you just provided the link command. In the upstream backend the compile command for the source files matters a lot, as we compile to wasm code in the object files, instead of during link. You can make upstream do the same as fastcomp by compiling (make sure to recompile all source files) and linking with `-flto`. Does that make a difference?

**Comment by klishevich** [comment] 2020-03-23 08:42
I did build with `-flto --llvm-lto 1` flag but got same 20 FPS for upstream.

This is my build with `--profiling` flag and I still think that the reason is `requestAnimationFrame()` function. 

<img width="961" alt="Screenshot 2020-03-23 at 11 26 32" src="https://user-images.githubusercontent.com/1125328/77296772-552eac00-6cf9-11ea-8dc5-66165cbf278d.png">

I have attached profiles for upstream and fastcomp with  `--profiling`.

[profiles.zip](https://github.com/emscripten-core/emscripten/files/4368036/profiles.zip)

P.S. @kripken if that does not help, I can provide builds with example app to reproduce the problem but because it is used inside our react app I need to create separate example for that.

**Comment by kripken** [comment] 2020-03-24 17:49
Thanks for the profiles @klishevich !

I don't see anything obviously different between the builds. That's odd given the big FPS difference. Two things you might want to try are another profiler (like firefox - it may have different "blind spots") and to add manual timing computations in your code.

I did see that embind may be on the hot path here. @jgravelle-google do you know if there are any significant differences in how that works on the wasm backend, that could affect performance?

**Comment by kripken** [comment] 2020-03-24 18:18
Actually reading the profiles again I think I may have found something. The profiles are confusing because two functions end up used a lot, 60% and 40% respectively - but the two are reversed! So the profiles are not actually identical in names, just in shape.

The interesting part is here (`X => Y` means it took X time in fastcomp and Y in upstream):
```
TextureManager.createTexture 12% => 32%
  SCRTFFillTexture 0.6% => 11%
    TSRGLES2Texture::FillPixelData 0.6% => 11%
```
That last one is a huge difference that is likely the culprit here. On fastcomp it just has a `glTexImage2D` call under it, but in upstream I this:
```
std::__2::vector<unsigned int, std::__2::allocator<unsigned int> >::~vector()
  std::__2::__vector_base<unsigned int, std::__2::allocator<unsigned int> >::~__vector_base()
    std::__2::__vector_base<unsigned int, std::__2::allocator<unsigned int> >::clear()
      std::__2::__vector_base<unsigned int, std::__2::allocator<unsigned int> >::__destruct_at_end(unsigned int*)
        std::__2::allocator<unsigned int>::destroy(unsigned int*)

std::__2::vector<unsigned int, std::__2::allocator<unsigned int> >::resize(unsigned long)
  std::__2::vector<unsigned int, std::__2::allocator<unsigned int> >::__append(unsigned long)
    std::__2::__split_buffer<unsigned int, std::__2::allocator<unsigned int>&>::__construct_at_end(unsigned long)
```
So there is basically a lot of `std::vector` work going on here - destroying, resizing, appending. That work doesn't seem to happen in fastcomp, or else in fastcomp it was optimized out.

I'm not sure why a `std::vector<unsigned int>` would spend time in destroy, which calls the destructor IIUC. Is there some chance the fastcomp version had the source file compiled with optimizations enabled, but upstream did not? I would verify that `-O3` (or similar) was passed when compiling that source file, and during link.

If that's not it, then as a next step I'd suggest investigating that `TSRGLES2Texture::FillPixelData` function. If nothing can obviously explain this in the source, maybe adding some time measurements around things can help narrow this down. Also looking in the emitted code may help. Best would be if you can make a standalone benchmark from that function, which also shows the huge difference, and provide that.

**Comment by kripken** [comment] 2020-03-24 20:26
Investigating some more: When compiling source files with `-O0` there is a surprising difference between fastcomp and upstream here. With upstream we end up with calls to `std::vector` things in this testcase:
```c
#include <vector>

int main() {
  std::vector<int> x;
  x.push_back(10);
  x.resize(0);
  x.resize(10);
  x.push_back(20);
  x.push_back(30);
  x.push_back(40);
  x.resize(10);
  x.resize(0);
}
```
In fastcomp the calls seems to be inlined - they are just branches to another basic block in the same function. And things look much more optimized because of that.

This appears to be a difference of fastcomp vs upstream. It happens even when passing the exact same flags to both compilers. It happens at the LLVM IR level.

My guess is that somewhere in the last 2 years (since fastcomp and upstream diverged) upstream stopped doing something it used to do on unoptimized code. Like maybe it stopped inlining `always_inline` methods in that case.

Anyway, the result is that unoptimized code is slower in upstream. Compiling with optimizations should avoid that though.

**Comment by briancullinan** [comment] 2020-03-28 17:25
@klishevich don't mean to throw a wrench in to this, but you aren't using emscripten OpenAL sound respatialize are you? I found that to have performance issues but I don't know of a better way.

**Comment by klishevich** [comment] 2020-03-28 17:28
Hi @briancullinan  no I am not using OpenAL

**Comment by klishevich** [comment] 2020-03-28 21:23
Thank you @kripken for the information it was very helpful. Using optimisation flag `-O2` I have solved the problem for upstream backend, confirm for version **1.39.11**.

Also I found the bottleneck in my code where I create textures from canvas 2D context. To pass vector from js to c++ I was copying values one by one into UIntVector. And it worked slowly in upstream backend without optimisation. 
But lately I have changed the code to pass vector from js using ccall:
```ts
const imageData = this.ctx.getImageData(0, 0, textureWidth, textureHeight);
const clampedCharArray = imageData.data;
webAssemblyContext.SCRTSetActiveTexture(bitmapTexture);
buffer = webAssemblyContext._malloc(clampedCharArray.length);
webAssemblyContext.HEAP8.set(clampedCharArray, buffer);
const result = this.webAssemblyContext.ccall(
  "SCRTFillActiveTextureCharArray",
  null,
  ["number", "number", "number"],
  [textureWidth, textureHeight, buffer]
);
webAssemblyContext._free(buffer);
```

Also I was to add EXPORTED_FUNCITONS into my build-wasm.sh script:
```
-s EXPORTED_FUNCTIONS="['_addNums', '_main', '_SCRTFillActiveTextureCharArray']" \
-s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" 
```

**Comment by kripken** [comment] 2020-03-30 00:52
Great! Yes, doing a single call like that can be a lot faster.

Closing as I think all issues here have been figured out, let us know if there's anything else.

**Closed by kripken** 2020-03-30 00:52 UTC
