### ISSUE TITLE
emcc.bat: command line is too long

### ISSUE THREAD

**Issue by yglukhov** [emscripten-core/emscripten#4438] opened 2016-07-14 13:31 UTC
Since `emcc.bat` uses `cmd.exe`, there is a limit for command line length of 8191 characters. [More info](https://support.microsoft.com/en-us/kb/830473). This issue makes it a pain to do a drop-in replacement of gcc with emcc in build systems. Some simple `emcc.exe` that does exactly what `emcc.bat` currently does should fix the issue.

**Comment by kripken** [comment] 2016-07-14 16:45
What version is this on? I think we've had improvements since the last stable release.

**Comment by Tormund** [comment] 2016-07-15 09:23
Same problem on emscripten versions 1.36.0 and 1.35.0
Windows 10 Enterprise

**Comment by juj** [comment] 2016-07-18 21:33
The linked article reads like the issue is not specific to `.bat` files, so moving to a `.exe` file would not likely fix the problem. Perhaps `.bat` files might have a shorter limit than `.exe` files, but the issue would still persist.

Emscripten uses the first workaround specified in the article, these files are called response files in Emscripten, and the syntax is same as for e.g. [MSBuild](https://msdn.microsoft.com/en-us/library/ms404301.aspx). That is, when building

    em++ tests/hello_world.cpp -o program.html

one can instead do

    echo tests/hello_world.cpp -o program.html > cmdline.rsp
    em++ @cmdline.rsp

to pass the parameters to the compiler. Multiple response files may be used, and regular command line arguments can be mixed with response files, so

    em++ -o program.html @cmdline1.rsp @cmdline2.rsp

would be valid. The contents of the response files are expanded in place to preserve the order.

Response files are caller's responsibility, the callee does not delete them when finished. So caller should remember to delete the files after the `em++` process has finished, `em++` itself does not delete the response files it consumes.

The cmdline length issue is not specific to Emscripten, for example gcc.exe also has the same issue and uses the [same response file workaround](https://gcc.gnu.org/wiki/Response_Files) as Emscripten does, so using an `emcc.exe` would likely not offer a solution.

Can you try using response files to work around the issue?

**Comment by phoenixx2** [comment] 2018-07-06 01:07
I would like to say that using a response file allowed emcc to link against large table of files.  Thanks for that workaround.

**Closed** 2019-09-26 09:10 UTC
Labels: windows, wontfix
