### ISSUE TITLE
Generate html file with Bazel Emscripten toolchain

### ISSUE THREAD

**Issue by Nerdyvedi** [emscripten-core/emscripten#13657] opened 2021-03-14 17:17 UTC
Hi,
I want to generate html file in addition to wasm and javascript "glue code". I am using bazel emscripten toolchain.

I want to do something like the following
`emcc hello.c -s WASM=1 -o hello.html
`But not able to understand what changes I need to make in the Bazel build file to get the html file as well.

I added linkopts = [ "-o hello.html"], to the BUILD file.
But getting the following error

> emcc.py did not appear to output any known files!

Thanks

**Comment by sbc100** [comment] 2021-03-14 19:14
Looks like a duplicate of https://github.com/emscripten-core/emsdk/issues/759.  Can we close this one?

**Closed** 2021-03-14 19:29 UTC
