### ISSUE TITLE
Assertion failed: target_thread, at: library_pthread.c,347,emscripten_async_queue_call_on_thread

### ISSUE THREAD

**Issue by legend-chen** [emscripten-core/emscripten#7684] opened 2018-12-15 09:13 UTC
I actually spend a long time to figure out what happened, since i just updating sdk from 1.38.11 to 1.38.21.

The projects compiled by 1.38.21 with USE_PTHREADS and emscripten_webgl_create_context run correctly, but it failed with USE_PTHREADS and SDL. 

please test sdl_gl_mapbuffers.c (in emscripten's tests)
```
sdl_gl_mapbuffers:
	emcc $@.c -g3 -o $@.html -s USE_PTHREADS=1 -s FULL_ES3=1 -lSDL -lGL 
```
maybe not InitWebGLTls in 1.38.21\system\lib\gl\webgl1.c

**Comment by legend-chen** [comment] 2018-12-15 09:20
It is right with USE_PTHREADS and emscripten_webgl_create_context 
```
gl_textures:
	emcc $@.cpp -g3 -o $@.html -s TOTAL_MEMORY=134217728 -s USE_PTHREADS=1 -lGL -lSDL
```

**Comment by legend-chen** [comment] 2018-12-17 06:33
I am trying to get over the issue with extral emscripten html5 codes.  it works at least .
```
  EmscriptenWebGLContextAttributes attr;
  emscripten_webgl_init_context_attributes(&attr);
  EMSCRIPTEN_WEBGL_CONTEXT_HANDLE ctx = emscripten_webgl_create_context(0, &attr);
  emscripten_webgl_make_context_current(ctx);
```

**Comment by feliwir** [comment] 2018-12-17 08:09
Getting a similar error:
```
exception thrown: abort("Assertion failed: target_thread, at: /home/mbits/Development/emsdk/emscripten/1.38.21/system/lib/pthread/library_pthread.c,347,emscripten_async_queue_call_on_thread") at Error
    at jsStackTrace (http://localhost:6931/mRayWebClient.js:1262:13)
    at stackTrace (http://localhost:6931/mRayWebClient.js:1279:12)
    at abort (http://localhost:6931/mRayWebClient.js:19737:44)
    at ___assert_fail (http://localhost:6931/mRayWebClient.js:2076:7)
    at _emscripten_async_queue_call_on_thread (wasm-function[36432]:77)
    at _emscripten_async_queue_on_thread_ (wasm-function[36433]:826)
    at _glBufferData (wasm-function[36525]:212)
```

**Comment by feliwir** [comment] 2018-12-18 13:35
@legend-chen any idea how to resolve this for SDL? Since that already creates a context for me.

**Comment by kripken** [comment] 2018-12-18 17:38
cc @juj

**Comment by legend-chen** [comment] 2018-12-19 02:10
@feliwir what I do is just creating a empty ctx before initing sdl, but this behavior is not always effective in all my projects. and I expect available updating to fix this. good luck!

**Comment by legend-chen** [comment] 2018-12-19 02:16
@feliwir what I do is just creating a empty ctx before initing sdl, but this behavior is not always effective in all my projects. and I expect available updating to fix this. good luck!

sometimes maybe need to do some settings to ctx.
```
EmscriptenWebGLContextAttributes attr;
emscripten_webgl_init_context_attributes(&attr);
attr.majorVersion = 2; attr.minorVersion = 0;
EMSCRIPTEN_WEBGL_CONTEXT_HANDLE ctx = emscripten_webgl_create_context(0, &attr);
emscripten_webgl_make_context_current(ctx);
```

**Comment by jakogut** [comment] 2019-09-11 19:23
@kripken Can we reopen this? I'm encountering the same issue using SDL2 with proxy to pthread. This is currently a blocker for supporting SDL2 outside of the main thread. I have a branch with a test here: https://github.com/jakogut/emscripten/tree/sdl2-proxy-apis.

The problem is resolved with this patch:
``` patch
diff --git a/tests/sdl2_gl_frames_swap.c b/tests/sdl2_gl_frames_swap.c
index aff19e881..f2283609b 100644
--- a/tests/sdl2_gl_frames_swap.c
+++ b/tests/sdl2_gl_frames_swap.c
@@ -6,7 +6,8 @@
  */
 
 #include <SDL.h>
-#include <emscripten.h>
+#include <emscripten/emscripten.h>
+#include <emscripten/html5.h>
 
 SDL_Window* window;
 SDL_Renderer* renderer;
@@ -30,6 +31,11 @@ void frame()
 
 int main()
 {
+    EmscriptenWebGLContextAttributes attr;
+    emscripten_webgl_init_context_attributes(&attr);
+    EMSCRIPTEN_WEBGL_CONTEXT_HANDLE ctx = emscripten_webgl_create_context(0, &attr);
+    emscripten_webgl_make_context_current(ctx);
+
     SDL_Init(SDL_INIT_VIDEO);
     window = SDL_CreateWindow("test", 0, 0, 640, 480, SDL_WINDOW_OPENGL);
     renderer = SDL_CreateRenderer(window, 0, SDL_RENDERER_ACCELERATED);

```

Without the patch, running the test produces the following error:

```JavaScript
Pthread aborting at Error
    at abort (http://localhost:8888/something.js:11945:70)
    at ___assert_fail (http://localhost:8888/something.js:1870:7)
    at emscripten_async_queue_call_on_thread (wasm-function[1373]:63)
    at emscripten_async_queue_on_thread_ (wasm-function[1389]:313)
    at glBufferData (wasm-function[1185]:139)
    at Draw (wasm-function[268]:197)
    at main (wasm-function[270]:295)
    at Module._main (http://localhost:8888/something.js:11257:32)
    at ___call_main (http://localhost:8888/something.js:2205:24)
    at __emscripten_thread_main (wasm-function[1390]:20)
```

Maybe something related to context creation isn't being properly proxied?

**Comment by kripken** [comment] 2019-09-11 21:16
Reopening.

Not sure what's going on here. I know @Beuc was looking at SDL2 with proxying, maybe this looks familiar?

**Comment by Beuc** [comment] 2019-09-11 21:32
I didn't experiment much, I saw that `screen` wasn't proxied, asked for the progress status on the mailing list and directly @juj but got no answers, glad to see there is some activity. I don't remember hitting an assertion error.

**Closed** 2020-10-11 06:24 UTC
Labels: wontfix
