### ISSUE TITLE
'iostream' file not found error and emcc linker not showing in visual studio 2010

### ISSUE THREAD

**Issue by lamasuma** [emscripten-core/emscripten#3591] opened 2015-06-30 13:42 UTC
hi,

I am trying to install emscripten with visual basic 2010, have installed vs-tool and env variables, emscripten and clang etc. emscripten works using command line.

When I compile/build in visual studio I get the following message

1>------ Build started: Project: enproj, Configuration: Emscripten Clang ------
1>Build started
1>InitializeBuildStatus:
1>  Touching "Clang\Emscripten\enproj.unsuccessfulbuild".
1>ClCompile:
1>  myprog.cpp
1>D:\VS2010\enproj\enproj\myprog.cpp(1,10): fatal error : 'iostream' file not found
1>  #include <iostream>
1>           ^
1>  1 error generated.
1>
1>Build FAILED.

Thus iostream file is not found. I don't know why.

Another thing is that in the visual studio properties/configuration, the emcc linker option is not there but clang C/C++ is there.

How can I solve the problems?

Thanks

**Comment by juj** [comment] 2015-06-30 23:54
Is this duplicate of https://github.com/juj/vs-tool/issues/42 ?

**Comment by lamasuma** [comment] 2015-07-01 02:38
Yes, i didn't know the emscripten and vs-tool section were the same. 

However, there the iostream message which is not mentioned in the vs-tool section as I thought that it was due to emcc linker.

**Closed** 2019-09-07 03:40 UTC
Labels: wontfix
