### ISSUE TITLE
Wasm EH: Export exception/tag

### ISSUE THREAD

**Issue by bkotsopoulossc** [emscripten-core/emscripten#16033] opened 2022-01-14 22:49 UTC
I've been trying to use wasm exception handling with a recent version of emscripten.

```
 % ./upstream/emscripten/emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.0 (3fd52e107187b8a169bb04a02b9f982c8a075205)
```

The old EH spec introduced a new thing called a "Tag" [here](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md), and the newer one has the same concept but calls it an "exception" [here](https://webassembly.github.io/exception-handling/core/binary/modules.html), but it essentially seems the same.

When I build with `-fwasm-exceptions`, the resulting module has a tag section, which is good. But if I inspect the exports, I don't see the exported tag/exception entry from [here](https://webassembly.github.io/exception-handling/core/binary/modules.html#export-section). This export is important to be able to catch a wasm exception in JS, and get access to the exception pointer. Without this, I don't see any way to get access to the C++ exception contents.

Is this expected, that the exception export is missing? What is required to add it?

**Comment by sbc100** [comment] 2022-01-18 01:42
I would hope that you could just export it by adding it to `EXPORTED_FUNCTIONS` (this settings is somewhat misnamed and really means "exported symbols"... also remember to add an extra "_" to the beginning of the C symbol name to it would be `EXPORTED_FUNCTIONS=___cpp_exception`).      If that doesn't work (I've never tried it) you can try `--Wl,--export=__cpp_exception` (without any extra underscore).

**Comment by bkotsopoulossc** [comment] 2022-01-18 01:51
For the first, I get:
```
emcc: error: undefined exported symbol: "___cpp_exception" [-Wundefined] [-Werror]
```

For the second, I get:
```
clang-14: error: unsupported option '--Wl,--export=__cpp_exception'
emcc: error: '/Users/brad.kotsopoulos/Snapchat/Dev/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=0 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/Users/brad.kotsopoulos/Snapchat/Dev/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -fwasm-exceptions --Wl,--export=__cpp_exception bazel/hello-world/hello-world.cc -c -o /var/folders/8y/8sw1v9j96w53_tyy9wc6dq9h0000gp/T/emscripten_temp_9udtby74/hello-world_0.o' failed (returned 1)
```

**Comment by sbc100** [comment] 2022-01-18 16:57
There is only one leading `-` in `-Wl,--export=__cpp_exception`

**Comment by aheejin** [comment] 2022-01-20 05:36
> The old EH spec introduced a new thing called a "Tag" [here](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md), and the newer one has the same concept but calls it an "exception" [here](https://webassembly.github.io/exception-handling/core/binary/modules.html), but it essentially seems the same.

As I said in the EH repo, the latter is not the newer one. It is outdated at the moment; please refer to [the explainer](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md).

> When I build with `-fwasm-exceptions`, the resulting module has a tag section, which is good. But if I inspect the exports, I don't see the exported tag/exception entry from [here](https://webassembly.github.io/exception-handling/core/binary/modules.html#export-section). This export is important to be able to catch a wasm exception in JS, and get access to the exception pointer. Without this, I don't see any way to get access to the C++ exception contents.

Does https://github.com/emscripten-core/emscripten/issues/16033#issuecomment-1015617238 work?

**Comment by bkotsopoulossc** [comment] 2022-01-20 17:20
Yes that did! Maybe for convenience, we auto-export the symbol if `-fwasm-exceptions` are defined? It's hard to image a use case for exceptions where you absolutely do not want the export right? Also I wonder if we could rename/alias it in the export table so it's called something simple like `exception`?

**Comment by sbc100** [comment] 2022-01-20 17:49
Excuse my ignorance, but can you show me how the exported tag is used from JS?  How does it enable extracting the pointer?

**Comment by bkotsopoulossc** [comment] 2022-01-20 18:02
Like so:
```
const instantiatedWasm = await WebAssembly.instantiateStreaming(...)

// ...

try {
  Module.someThingThatThrows()
} catch (e)
  if (e instanceof WebAssembly.Exception) {
    // get access to a pointer on the wasm heap that represents the C++ exception object
    const wasmExceptionPtr = e.getArg(new WebAssembly.Tag({ parameters: ["some_special_syntax"] }), 0)

    // call some custom hook back into wasm to access the underlying exception object based on the pointer
    const message = Module.getExceptionMessage(wasmExceptionPtr)
    console.log(message)
  }
}
```

**Comment by bkotsopoulossc** [comment] 2022-01-20 18:04
Like so:
```
const instantiatedWasm = await WebAssembly.instantiateStreaming(...)

// ...

try {
  Module.someThingThatThrows()
} catch (e)
  if (e instanceof WebAssembly.Exception) {
    // get access to a pointer on the wasm heap that represents the C++ exception object
    const wasmExceptionPtr = e.getArg(instantiatedWasm.instance.exports.__cpp_exception, 0)

    // call some custom hook back into wasm to access the underlying exception object based on the pointer
    const message = Module.getExceptionMessage(wasmExceptionPtr)
    console.log(message)
  }
}
```

**Comment by sbc100** [comment] 2022-01-20 18:06
I see, thanks.  So that tag is requires to extract the pointer.

I think there may be users who only care about exceptions in C++ and don't need/want to do this kind of catching from the JS side, so maybe exporting by default is not what we want, but I guess we should see how common that is.   

Certainly there should be an easy way to export this for users that want access to it.  I think if we make adding it `EXPORTED_FUNCTIONS` work that would make the most sense.

**Comment by bkotsopoulossc** [comment] 2022-01-20 18:12
My opinion is that wanting the ability to catch an exception in JS from wasm is more common than not, but hard to say. 

The only way you _wouldn't_ be interested in catching in a C++ codebase is if you had a try-catch on the c++ side for every API call that caught every type of exception and didn't re-throw.

But, maybe it's just a matter of documenting it here https://emscripten.org/docs/porting/exceptions.html#webassembly-exception-handling-proposal. This took me a bit of digging around to figure out how these things are supposed to piece together

**Comment by bkotsopoulossc** [comment] 2022-01-26 16:15
> So that tag is requires to extract the pointer.

Exactly. At least that is my understanding. However, I tried to use the same trick documented [here](https://emscripten.org/docs/porting/Debugging.html#handling-c-exceptions-from-javascript) from JS. With emscripten EH, taking the pointer from JS, calling back into wasm and casting it from int->exception_ptr allows you to access the underlying exception. With wasm EH, this exact same technique gives `memory access out of bounds`. So I'm not sure if there is something different about the pointer, or where it points in the heap, or if I need to add/subtract some offset or something, or if the exception object has been de-allocated, or something. We expect this to work, right?

**Comment by sbc100** [comment] 2022-01-26 17:01
Wasm EH is still very new.. I'm not sure we have any examples yet of how to extract the underlying C++ pointer from JS.. but in theory it should be possible, at least in the long term.

Perhaps there is already test that does this but I'm not aware of it?  If not perhaps we could modify of of the existing tests to show how this can work?  @aheejin?

**Comment by bkotsopoulossc** [comment] 2022-01-26 18:03
There's a test to get the pointer out [here](https://github.com/v8/v8/blob/17a99fec258bcc07ea9fc5e4fabcce259751db03/test/mjsunit/wasm/exceptions-api.js#L202-L225), but the pointer isn't used for anything in particular. I'm mostly interested in using the pointer back in wasm to access the exception object

**Comment by sbc100** [comment] 2022-01-26 18:06
Sounds like we just need to extend that test to show the pointer is valid (points to a C++ object in wasm memory).

**Comment by aheejin** [comment] 2022-02-02 23:17
Sorry for the delayed response! Can you post the reproducer and the command line you built the program with, which runs successfully with Emscripten EH but not with Wasm EH?

**Comment by donalffons** [comment] 2022-05-13 06:46
This is affecting me as well, so I made a simple reproducer based on the discussion here (@aheejin): https://github.com/donalffons/emscripten-wasm-exceptions

The differences between `-fexceptions` and `-fwasm-exceptions` are in the file `/emscripten/build.sh`...
```sh

# using -fwasm-exceptions
emcc \
  --bind embind-main.cpp \
  -s EXPORT_ES6=1 \
  -s USE_ES6_IMPORT_META=0 \
  -fwasm-exceptions \
  -Wl,--export=__cpp_exception \
  -o ./build/main.js

# using -fexceptions
# emcc \
#   --bind embind-main.cpp \
#   -s EXPORT_ES6=1 \
#   -s USE_ES6_IMPORT_META=0 \
#   -fexceptions \
#   -o ./build/main.js
```

...and in the file `/javascript/myWorker.js`
```js
  try {
    m.throwSomething();
  } catch (e) {
    // using -fwasm-exceptions
    console.log("Exception Message:", m.getExceptionMessage(e.getArg(m.asm.__cpp_exception, 0)));

    // using -fexceptions
    // console.log("Exception Message:", m.getExceptionMessage(e));
  }
 ```

The version with `-fexceptions` can extract the message, the version with `-fwasm-exceptions` fails with `memory access out of bounds`.
Would be great, if we could get this to work :+1:!

**Comment by Krelborn** [comment] 2022-05-13 07:44
Just adding my +1 to this issue. We have some serious performance issues that are greatly improved by turning on Wasm exceptions but this is blocking us from doing that.

**Comment by zhanglin-wu** [comment] 2022-05-17 13:28
+1

**Comment by aheejin** [comment] 2022-05-17 16:15
Sorry for the delays! I'm looking at this.

**Comment by Krelborn** [comment] 2022-05-18 07:29
@aheejin that's great thanks!

Another thing I've noticed is that the __cpp_exception is only visible for debug builds. We're using CMake for our builds. If I compile the Debug config I see the tag on the asm object, but with Release it's not available.

Looking at the Wasm instance I can see its not listed in the exports so I guess its stripped during optimisation.

**Comment by aheejin** [comment] 2022-05-31 23:21
Closing this, given that #17064 landed. As I described in that PR, using this to extract thrown values still requires multiple options, which is inconvenient at the moment, but it is at least possible. Refer to the example test to see how it is used and which options should be turned on: https://github.com/emscripten-core/emscripten/blob/2a3bb65cdea614451e4dc6227ae8e338902bfd1d/tests/test_core.py#L1636-L1713
(The test uses `EM_ASM`, but  you can do the same thing with normal JS code as well)

I'm planning to make this easier to use, possibly creating a single option that adds all necessary imports and exports the tag, but I'd like to let you know that using this is at least possible now. I'll CC this issue again when the one-stop option is added later too.

**Comment by aheejin** [comment] 2022-05-31 23:27
You can use these methods to access the tag and thrown values, and print `what()` message (if any) for an exception: 
- `getCppExceptionTag`
- `getCppExceptionThrownValue`
- `getExceptionMessage`
https://github.com/emscripten-core/emscripten/blob/2a3bb65cdea614451e4dc6227ae8e338902bfd1d/src/library_exceptions.js#L396-L447

Note that `getExceptionMessage` uses `getCppExceptionThrownValue` and `getCppExceptionThrownValue` uses `getCppExceptionTag`, so in case you don't need direct access to the tag and thrown values and the only thing you want is to print the message, you only need to call `getExceptionMessage`.

**Comment by Krelborn** [comment] 2022-06-01 13:18
Thanks for looking at this.

I still can't get it working. I've tried enabling the settings suggested in the test but I get undefined symbol errors.

```
error: undefined symbol:  (referenced by top-level compiled C/C++ code)
warning: Link with `-sLLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _ may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

I've posted a simple demo repo here to show what I'm doing where I try to compile your test C++ code and run it in a browser.

https://github.com/Krelborn/emcc-exceptions/blob/b742880ddd0114d2669cc84971455a73f539dc88/package.json#L8

**Comment by donalffons** [comment] 2022-06-03 14:07
I have updated my [reproducer](https://github.com/donalffons/emscripten-wasm-exceptions), which is now partly working. Extracting the exception message works fine now. But I cannot access the thrown exception object. Each time I try to cast (what I think should be) the thrown exception pointer, I get a memory error:
```js
console.log("thrown value", m.getCppExceptionThrownValue(e)); // 5259312
console.log("Exception Message 1:", m.getExceptionMessage(e)); // exception of type SomeException: Something went wrong

// This doesn't work
console.log("Exception Message 2:", m.myGetExceptionMessage(m.getCppExceptionThrownValue(e))); // Uncaught (in promise) RuntimeError: memory access out of bounds
```

**Comment by donalffons** [comment] 2022-06-03 17:33
...found the explanation in [this comment](https://github.dev/emscripten-core/emscripten/blob/4ac187a4be104fd25b0b2ae2922cf62a61dfa27d/system/lib/libcxxabi/src/cxa_exception_emscripten.cpp#L52). It looks like there are several function calls required to access the underlying exception object, which seem to be currently inaccessible from outside Emscripten?!

**Comment by aheejin** [comment] 2022-06-06 05:46
@donalffons Yes, what's thrown is different from Wasm EH vs. Emscripten EH. In Emscripten EH, the thrown value is a pointer to `__cxa_exception`. In Wasm EH, the thrown object is a [`WebAssembly.Exception`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception) object, which contains an actual thrown value, which is a pointer to `__cxa_exception->unwindHeader` (of type `_Unwind_Exception`). So neither Emscripten EH nor Wasm EH actually throws a direct pointer to the memory that contains the value that user throws. What Wasm EH does is the same as what x86 / ARM does on Linux, because we use the same libc++abi routines.

Here is the memory layout of the user-thrown value, `__cxa_exception` header, and `_Unwind_Exception`:
https://github.com/emscripten-core/emscripten/blob/df8782c195da6761f9fce976fc4fc79687b45f0f/system/lib/libcxxabi/src/cxa_exception.cpp#L26-L35

So we provide three layers of functions, but if your intention is to print the exception message, you only need to use `getExceptionMessage`.

`getCppExceptionTag`: Returns the exported C++ exception tag
https://github.com/emscripten-core/emscripten/blob/df8782c195da6761f9fce976fc4fc79687b45f0f/src/library_exceptions.js#L397-L399

`getCppExceptionThrownValue`: Given an `WebAssembly.Exception` object, returns an actual thrown value, which is a pointer to `__cxa_exception->unwindHeader`. This calls `getCppExceptionTag`.
https://github.com/emscripten-core/emscripten/blob/df8782c195da6761f9fce976fc4fc79687b45f0f/src/library_exceptions.js#L401-L404

`getExceptionMessage`: Given an `WebAssembly.Exception` object, returns a string of the exception message. This calls `getCppExceptionValue`.
https://github.com/emscripten-core/emscripten/blob/df8782c195da6761f9fce976fc4fc79687b45f0f/src/library_exceptions.js#L419-L427

> It looks like there are several function calls required to access the underlying exception object, which seem to be currently inaccessible from outside Emscripten?!

Not necessarily. From JS, if you use [`WebAssembly.Exception.getArg`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception/getArg) function, you can access the thrown value. The methods added in #17064 do that for you. This was recently added and not very easy to use and not well documented yet, which I think will improve in near future, but I wanted to at least post here that it's available for use.

**Comment by aheejin** [comment] 2022-06-06 06:55
@Krelborn I wasn't able to reproduce your error. I don't have docker in my machine, so just ran the command line in your package.json directly:
```
emcc src/main.cpp --bind -fwasm-exceptions -s EXPORT_ES6=1 -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE="['\$getExceptionMessage', '\$incrementExceptionRefcount', '\$decrementExceptionRefcount']" -s EXPORTED_FUNCTIONS="['_main', 'getExceptionMessage', '___get_exception_message', '___cpp_exception', '___increment_wasm_exception_refcount', '___decrement_wasm_exception_refcount']" -sENVIRONMENT=node -o main.js
```

This compiles for me. Can you do the same and check if it works? If not, can you post your reproducer with your source file and command line (without docker)?

**Comment by Krelborn** [comment] 2022-06-06 08:38
@aheejin massive thanks for the sanity check! Looks like a problem with escaping the `\$` combination in the npm script rather than a problem with the compiler. I've moved the build command to a node script and it's now working in my example project.

As @donalffons comments, the next problem seems to be accessing the underlying exception object. getExceptionMessage works up to a point, but because it adds type information to the string returned by std::exception::what (), we can't use the message in the UI as is. Also, we include other metadata in our exception class (usually at leaste a numeric code) so we want a way to unpackage this easily and return the information to JavaScript.

I've been looking at the implementation of getExceptionMessage to see if I can implement this myself, but it seems to rely on private functions and types to get the real value from the pointer to the unwind header, so it doesn't look possible at the moment. In the meantime we could work around it by extracting the raw message from the string but it's a bit fragile.

Anyway, great progress so far! I think even in the current state we'll be looking to adopt this as soon as it's available.

**Comment by aheejin** [comment] 2022-06-06 09:53
@donalffons @Krelborn I think the current `getCppExceptionValue` is confusing, because it returns the pointer to the unwind header. I think I'll change the function so that it will return the actual thrown object, as in the Emscripten EH. You think it's a good idea? By the way, sorry for the confusion!

**Comment by aheejin** [comment] 2022-06-06 10:27
I made `getCppExceptionValue` return the actual thrown value in #17157. Thanks for pointing out the confusing part. Note that the exported functions you need to set in `EXPORTED_FUNCTIONS` changed a little: See the test in test_core.py. I think all these settings will eventually be turned on and off by a single option (#17114), so please bear with the inconvenience in the meantime.

**Comment by Krelborn** [comment] 2022-06-06 10:51
@aheejin yes definitely a better idea to make it return the original object as this is what the client code is really interested in rather than the internals of the EH implementation.

Thanks for the quick response!

**Comment by Krelborn** [comment] 2022-06-13 09:38
@aheejin I've tested this now and can report that I can now get access to the original C++ exception object using a cast in the way we expected. Thanks.

**Closed** 2022-06-13 16:32 UTC
