### ISSUE TITLE
Call emscripten_sleep from js / use FileReaderSync

### ISSUE THREAD

**Issue by Deamon87** [emscripten-core/emscripten#3641] opened 2015-07-24 09:58 UTC
Is it possible? 

I want to redirect the FS calls to a particular file to HTML5 FileReader. But since FileReader is async, I need to put an execution to "sleep" until read operation is completed. 

Right now it's my understanding, that to call emscripten_sleep from js I will need to create cpp file, define  there some function with emscripten_sleep in it, expose it to js and call it from js instead of emscripten_sleep. But will this work?

**Comment by kripken** [comment] 2015-07-24 17:39
emscripten_sleep relies on something like the emterpreter to run the code on the stack, which only works for compiled code. For normal JS, you can use generators. I think there is some tool that can automatically use them for you, but i don't remember its name.

**Comment by regular** [comment] 2015-07-29 14:53
Any solution for this?
I plan to implement a `stdin` device in a WebWorker that is feed via postMessage() and I guess I run into the same issue. When _read() is called on the device, the JS code needs to yield in order to give the worker's `onmessage` handler a chance to receive new data from the main script. I want the main script to be able to truly stream data into the worker in parallel with the worker executing a CLI tool translated by emscripten.

**Comment by kripken** [comment] 2015-07-29 18:26
The emterpreter is the current solution for things like that. Pthreads might also solve it, but browser support is still limited to Firefox nightly for now.

**Comment by Deamon87** [comment] 2015-07-31 09:24
Ok, i figured out how emscripten and emterpreter works.

The emscripten_sleep is not a simple functions. With -s EMTERPRETIFY=1, the linker looks for emscripten_sleep and cuts the execution flow on that point. So it would be possible to save\load stack on it. Because of just this calling emscripten_sleep from js will have no effect.

Further analysis showed, that custom stream_ops(open,read,llseek) are called from non-emscripten compiled js code. That code do not deal with heap\stack and, what more important, implies that stream_ops operations are synchronous. I have not found any way to make that code work in async manner while dealing only with stream_ops code.

So I took another approach and decided to result of emscrtipten in a webworker. The guys who developed standards decided, that it's ok to have FileReaderSync in worker but forbade it's use in main browser thread.

I think we can close this

**Comment by kripken** [comment] 2015-07-31 17:16
How do you intend to use FileReaderSync? I wonder if we could make a filesystem that uses it automatically - parallel to MEMFS, NODEFS, etc., maybe WORKERFS?

**Comment by regular** [comment] 2015-07-31 17:50
Can I EMTERPRETIFY_WHITELIST stdio functions? I guess then what I could do is
- compile with -s EMTERPRETIFY_ASYNC=1
- throw an exception in my stdin device's read function to get a call stack
- EMTERPRETIFY_WHITELIST all c functions on that call stack
- insert an invocation of `emscripten_sleep(0)` at the beginning of the syscall called by _read() or in _read itself to run the wroker's event loop for one tick and potentially receive fresh data from the main script

Does that sound about right?

**Comment by kripken** [comment] 2015-07-31 20:41
The emterpreter can only run compiled code, so if those stdio functions are compiled - like printf now is, after the musl-syscall branch merged - then it could work. But if non-compiled code, like a syscall, ends up executed, that would be a problem.

**Comment by Deamon87** [comment] 2015-08-05 14:01
You can see an example of FileReaderSync use here: https://github.com/Deamon87/StormLib.js/blob/jsport/src/js/preRun.js#L290

With addFileToRep I register a new device to emscripten file system. In "open" function I create a new FileReaderSync instance and in "read" function I delegate loading of content to it.

One important line is 379. This way I make emscripten think that device is a file, not a link\directory or anything else.

**Comment by kripken** [comment] 2015-08-06 17:08
I'm confused, that uses NODEFS and FileReaderSync? So it's for node.js, not workers?

**Comment by Kagami** [comment] 2015-08-10 20:16
I think `WORKERFS` with buffered access to File/Blob objects via `FileReaderSync` would be a very useful feature.

@kripken do you or maybe someone else have plans on this? If nobody interested in it, I can try to work on it, though my knowledge of Emscripten codebase is very poor.

Here is checklist of things I wish to know:
- [ ] Browser compatibility? For the quick look: non-ancient Firefox & Chrome, IE 10+. Safari? Are there some known bugs or limitations?
- [ ] Memory consumption. Will it allow to work with big (1G+) files if target application read only small chunks of them?
- [ ] Some hints/expected pitfails please? Are MEMFS/NODEFS implementations good way to start on hacking new FS? Are there some other examples?
- [ ] @kripken do you have any particular expectations on how it should behave?

**Comment by Kagami** [comment] 2015-08-10 20:32
Also, I don't quite understand, why it should be another FS instead of just some function like `FS.createBlobFile` in library_fs.js?

**Comment by kripken** [comment] 2015-08-10 20:36
It would be great if you could work on this. It shouldn't require much prior knowledge of emscripten, just looking at the MEMFS/NODEFS etc. files in `src/*` should give an idea of how to write a new filesystem. And of course feel free to ask questions about anything.

 * I believe Blobs are extremely well supported in browsers. However, I can't seem to find information on FileReaderSync. I guess we'd need to just check browsers.
 * Yes, Blobs were designed in order to allow huge files to be used in chunks. It should be possible for a 1GB file that you only do `read()` on a small chunk to just load that chunk from disk.
 * MEMFS/NODEFS are good starting points. IDBFS might be even smaller, I would start with the smallest.
 * I think this has to be an FS because it has special behavior. In MEMFS, the default FS, we load the entire file into memory, so `FS.createBlobFile` could not use MEMFS if it wants to be efficient.
 * Perhaps the simplest thing is to allow a Blob to be mounted as a single file. Makes sense to start with that I think.

**Comment by Kagami** [comment] 2015-08-10 20:47
Thanks, that's great! I'll let you know once I implement some basic prototype.

**Comment by Deamon87** [comment] 2015-08-10 23:15
@Kagami On your checklist:
1) Do not have exact info, but I beilive it is supported by browsers since 2011.
I ran into this bug on FireFox: https://bugzilla.mozilla.org/show_bug.cgi?id=823484 When you get filelist from &lt;input type=&quot;file&quot; multiple&gt; and pass it to webworker, Firefox will deny to clone the object, while Chrome will work as expected. Solution is to pass to worker one file at one time 

Also, the c "off64_t" type is "singned int" in emscripten. Because of this, the files over 2 GB are not properly supported from the box. llseek function will get negative position, when program will request data beyond 2gb offset. My solution was for negative positions do "position = ((position << 32) >> 32)"

2) It works perfectly. Memory is not consumed for all file, only for the part that was read into memory.

Hope this will help

**Comment by Kagami** [comment] 2015-08-10 23:28
@Deamon87 cool, thanks.
One more question. If we pass big `File` object to the worker via `postMessage`, browser shouldn't read it entirely into memory, just pass the reference, right? Spec [says](http://www.w3.org/TR/html5/infrastructure.html#safe-passing-of-structured-data) that underlying data is the same in case of `Blob` but I haven't checked it in real browser yet.

**Comment by Deamon87** [comment] 2015-08-10 23:45
@Kagami Yes, browser do not load all file into memory, even though `File` is `Blob`. `File` here is a reference. I was succesfully reading from 3 GB file and js memory consumption was around 30 MB(that includes emscripten compiled code)

**Comment by Kagami** [comment] 2015-08-28 18:26
>Because of this, the files over 2 GB are not properly supported from the box

I think I can reproduce it now. 2G+ files are incorrectly processed by my application, but everything seems to be ok with <2G. Though your hack will only support files up to 2^32 bytes = 4G which might be not enough in my use case.

@kripken @Deamon87 does Emscripten support 32bit+ file sizes/seek positions/etc. in VFS? JavaScript can operate with integers up to 2^53 without losing precision.

**Comment by Deamon87** [comment] 2015-09-01 13:26
It all comes down to how "off64_t" data type is defined. This data type is os dependent and I could not find a way to make it be "long long" instead of  "signed int" while compiling with emscripten.

**Comment by kripken** [comment] 2015-09-01 22:51
Looks like `lib/libc/musl/arch/emscripten/bits/alltypes.h` defines `off_t` as 32-bit. Changing that to 64-bit (and rebuilding libc, etc.) might work, as our syscall does receive a 64-bit input.

**Comment by Kagami** [comment] 2015-09-06 18:03
I started writing test-case and just realized that `lseek` accepts `off_t` per POSIX which is `long int` per spec. So Emscripten plays fine here.

But! Manpage of `lseek64` mentions one interesting  preprocessor flag:

```
       lseek(2)  uses the type off_t.  This is a 32-bit signed type on 32-bit architectures, unless one compiles
       with

           #define _FILE_OFFSET_BITS 64

       in which case it is a 64-bit signed type.
```

which is what FFmpeg in my case actually relies on. It seems to be [not quite standard](https://stackoverflow.com/questions/4357570/use-file-offset64-vs-file-offset-bits-64) but widespread enough.

@kripken do you mind if we would set `off_t` to `long long int` if that flag is defined? (Btw, `off_t` should be `long int` by default actually but I guess it's 32 bit in both cases anyway.)

**Comment by Kagami** [comment] 2015-09-06 18:07
Btw, could you please explain, what's the simplest way of rebuilding Emscripten's libc while working on new feature in order to test it?

**Comment by Kagami** [comment] 2015-09-06 18:23
`off64_t` need to be fixed too. Now it's synonym of `off_t` everywhere across the headers for some reason.

**Comment by kripken** [comment] 2015-09-06 21:23
We would need to measure performance if we switch that to 64-bit. The concern is that libc internally does a lot of additions of offsets, and 64-bit adds are much slower than 32-bit given JS has no 64-bit integers.

To force a rebuild of libc, you can just clear the cache `emcc --clear-cache`. You can also just delete `libc.bc` from `~/.emscripten_cache`.

**Comment by Kagami** [comment] 2015-09-06 21:40
>The concern is that libc internally does a lot of additions of offsets

Do you mean it uses `off64_t` internally a lot? I just think it's wrong to provide 32bit synonym for type intended to be 64bit - it breaks programs which rely on that. In case of `off_t` + `_FILE_OFFSET_BITS` it's up to the user to define that flag or not.

Though we can add Emscripten option which would be required to allow 64bit offsets in both of this cases. Something like `-s ALLOW_64BIT_OFFSETS=1`. What do you think?

**Comment by kripken** [comment] 2015-09-08 20:42
I agree it would be better to be more standard, but when I measured this it seemed to be a problem, back then. Perhaps it's no longer a concern, we could try again.

**Closed** 2019-09-07 03:41 UTC
Labels: wontfix
