### ISSUE TITLE
uname syscall can't be linked after 2.0.31 -> 2.0.32 upgrade

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#15670] opened 2021-11-30 17:34 UTC
Getting a new linking error after upgrading from 2.0.27 to 3.0.0:

```
wasm-ld: error: /src/deps/.emcache/sysroot/lib/wasm32-emscripten/lto/libc-mt.a(uname.o): undefined symbol: __syscall_uname
```

~~Trying to pin it down to specific version upgrade, currently looks like it's somewhere between 2.0.31 and 2.0.34.~~

Looks like it started in 2.0.32 release.

**Comment by sbc100** [comment] 2021-11-30 17:38
The full failing `wasm-ld` command would be useful.   That symbol is supposed to exist in `-lstubs` which should get linked in by default (unless you are building with `STRICT` .. or `ALLOW_UNIMPLEMENTED_SYSCALLS=0`).

**Comment by RReverser** [comment] 2021-11-30 18:20
Here's the command:

```
wasm-ld: error: /src/deps/.emcache/sysroot/lib/wasm32-emscripten/lto/libc-mt.a(uname.o): undefined symbol: __syscall_uname
emcc: error: '/emsdk/upstream/bin/wasm-ld -o test-gphoto2.wasm test-gphoto2.o .libs/test-gphoto2.htmlS.o ../libgphoto2_port/.libs/libusb1.a -L/src/deps/.emcache/sysroot/lib /src/deps/.emcache/sysroot/lib/libusb-1.0.a ../camlibs/.libs/libptp2.a /src/deps/libgphoto2/libgphoto2/.libs/libgphoto2.a ../libgphoto2/.libs/libgphoto2.a /src/deps/libgphoto2/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.a ../libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.a /src/deps/.emcache/sysroot/lib/libltdl.a -L/src/deps/.emcache/sysroot/lib/wasm32-emscripten/lto /src/deps/.emcache/sysroot/lib/wasm32-emscripten/lto/crtbegin.o --whole-archive -lembind-rtti --no-whole-archive -lc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-mt-noexcept -ldlmalloc-mt -lc_rt_wasm-mt -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpjaek0w92.undefined --import-memory --shared-memory --export-if-defined=main --export-if-defined=emscripten_stack_get_base --export-if-defined=emscripten_stack_get_end --export-if-defined=emscripten_stack_set_limits --export-if-defined=stackSave --export-if-defined=stackRestore --export-if-defined=stackAlloc --export-if-defined=__wasm_call_ctors --export-if-defined=__errno_location --export-if-defined=__emscripten_init_main_thread --export-if-defined=_emscripten_call_on_thread --export-if-defined=_emscripten_main_thread_futex --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=emscripten_current_thread_process_queued_calls --export-if-defined=_emscripten_allow_main_runtime_queued_calls --export-if-defined=emscripten_get_global_libc --export-if-defined=emscripten_main_browser_thread_id --export-if-defined=emscripten_main_thread_process_queued_calls --export-if-defined=emscripten_run_in_main_runtime_thread_js --export-if-defined=emscripten_sync_run_in_main_thread_2 --export-if-defined=emscripten_sync_run_in_main_thread_4 --export-if-defined=emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=pthread_testcancel --export-if-defined=memalign --export-if-defined=malloc --export-if-defined=free --export-if-defined=ntohs --export-if-defined=htons --export-if-defined=_get_tzname --export-if-defined=_get_daylight --export-if-defined=_get_timezone --export-if-defined=__dl_seterr --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-table -z stack-size=5242880 --initial-memory=16777216 --entry=main --max-memory=2147483648 --global-base=1024' failed (returned 1)
```

**Comment by sbc100** [comment] 2021-11-30 18:26
Sorry, do you have the full emcc command too?

**Comment by sbc100** [comment] 2021-11-30 18:29
The stubs library should get added right before libc:

https://github.com/emscripten-core/emscripten/blob/9839e7e5b0755077ceeb07fefcb049926576a473/tools/system_libs.py#L1715-L1718

Its a mystery to my how it is not there in the wasm-ld command you shared.

**Comment by RReverser** [comment] 2021-11-30 18:44
So apparently it was due to me using `ALLOW_UNIMPLEMENTED_SYSCALLS=0`. It's still unclear why it worked before and why it broke now, and whether it's something we want to fix - @sbc100 feel free to close issue if it's not.

**Comment by sbc100** [comment] 2021-11-30 19:03
It looks like as part of https://github.com/emscripten-core/emscripten/pull/15209 I marked `__syscall_uname` I effectively marked unimplemented where it was previously not.  

Its seems debatable whether or not we should consider this system a stub (i.e. unimplemented) or a real implementation.

**Comment by RReverser** [comment] 2021-11-30 19:18
It seems all other stubs return error codes? If so, this probably can be considered to be a real implementation...

**Comment by sbc100** [comment] 2021-11-30 19:26
Many of the stubs are more like fakes and return dummy data rather than an error.  e.g. `__syscall_getpid`  `__syscall_sync` `__syscall_getrusage`.

If a developer is interested in saving on code size normally they don't want such fakes and it would make sense instead to remove the call sites.  

In your case are you passing `ALLOW_UNIMPLEMENTED_SYSCALLS=0` because you don't want to code size bloat that would results in including the fakes?   i.e. would it be worth your time to find the uname callsite and remove it?

**Comment by RReverser** [comment] 2021-11-30 19:36
> because you don't want to code size bloat that would results in including the fakes

That was the goal, but only if it's possible without changes to the code. As it turned out later, it isn't due to https://github.com/emscripten-core/emscripten/issues/14824.

That is, I want those syscalls to be detected as unsupported much earlier, at the `configure` stage, so that the project could switch to a better implementation and exclude the stubs at compilation time. This would save code size without breaking functionality or requiring me to change code of a 3rd-party library.

Until that's implemented, I'd rather have stubs that keep the code working at the cost of small code size increase.

**Comment by sbc100** [comment] 2021-11-30 19:39
OK, so for you, the solution is probably to remove `ALLOW_UNIMPLEMENTED_SYSCALLS=0`, at least until it works for your use case.

**Comment by sbc100** [comment] 2021-11-30 19:40
i.e. you are actually depending in the stubs/fakes so you should not be passing `ALLOW_UNIMPLEMENTED_SYSCALLS=0`, right?

**Comment by RReverser** [comment] 2021-11-30 19:48
> OK, so for you, the solution is probably to remove `ALLOW_UNIMPLEMENTED_SYSCALLS=0`, at least until it works for your use case.

Yeah that's what I did for now. As I said, just leaving the issue open for you to decide because I'm not sure if it's the intended behaviour for other users or not.

**Comment by sbc100** [comment] 2021-11-30 19:54
Yes, I think this is intended behaviour.  There were a few syscalls that transitioned to unimplemented syscalls as part of #15209.   I should probably have make a list of them and called them out in the changelog.

It is expected that the link will fail if you use `__syscall_uname` (or any "unimplemented" syscall) along with `ALLOW_UNIMPLEMENTED_SYSCALLS=0`.   I don't think revisiting the decision on uname is going to be useful, or a solution to your wider issue.   So I think we can probably close this out (unless you think it worth going back and documenting the precise list of syscalls that changed status recently?)

**Comment by RReverser** [comment] 2021-11-30 20:02
Fair enough. The breakage seems problematic, and perhaps something we need to call out more explicitly in the future, but not much point in going back on this one.

**Closed** 2021-11-30 20:02 UTC
