### ISSUE TITLE
Optimized ChucK code has function signature error

### ISSUE THREAD

**Issue by aknuds1** [emscripten-core/emscripten#3063] opened 2014-12-09 21:51 UTC
When including optimized (-O3) [ChucK](https://github.com/aknuds1/chuck) code in my [app](http://104.131.177.17/), it invariably breaks when loaded, with the following error message:

```
Invalid function pointer '0' called with signature 'ii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
```

The code doesn't break if I compile without optimization. It also doesn't break if I include it in a static HTML page for some reason, only in my SPA apps (I've tried with both Meteor and a simple React app). I'm using Emscripten 1.27.0, and have built with -O3, -g, -s ASSERTIONS=2 and -s SAFE_HEAP=3.

I've tested with Chrome, Safari and Firefox on OS X. You can try for yourselves at http://104.131.177.17/ (just check the console after loading the page).
# How to Reproduce
1. Check out [ChucK](https://github.com/aknuds1/chuck)
2. Enter chuck/src
3. Build chuck.js (-O3 -g -s SAFE_HEAP=3 -s ASSERTIONS=2): `make -j8 CHUCK_EM_ASSERTIONS=2 CHUCK_EM_SAFEHEAP=3 CHUCK_OPT_DEBUG=1 emscripten`

After this procedure, chuck/js/lib/chuck.js and chuck/js/lib/chuck.js.mem should be built. However, in order to trigger the failure, chuck.js must be included in a JavaScript application it seems, f.ex. http://104.131.177.17. It seems a bit overkill to provide the instructions to build this application as well, since you can just try my deployment of it (the deployed chuck.js is [here](http://104.131.177.17/bower_components/chuck/lib/chuck.js)). I can provide instructions to build that app as well though, if it'll help.

**Comment by NWilson** [comment] 2015-04-11 06:40
Is this still a problem? If not, maybe we could close this issue -- but if it is a problem, could you post the full stack trace of where it's crashing? If you look in the source code at that point, it will be using a function pointer, and if that pointer was ever cast, that would be the problem.

In any case, it's probably not a bug in emscripten at this point.

**Comment by aknuds1** [comment] 2015-04-12 10:09
@NWilson I haven't worked on it in a while, but I would imagine it's still a problem. The main problem really, was as I commented here that the source map is non-sense. If you see my last comment above, that sums it up.

I can try again when I have the time, fingers crossed that source maps are fixed.

**Closed** 2019-09-07 05:41 UTC
Labels: wontfix
