### ISSUE TITLE
Add a flag for providing additional params to fetch calls

### ISSUE THREAD

**Issue by a-shruti** [emscripten-core/emscripten#16217] opened 2022-02-07 13:54 UTC
In the generated glue js code, there doesn't seem to be a way to provide additional parameters to the fetch API.  Could something be introduced for the same?

For instance, if someone wanted to [provide a timeout](https://stackoverflow.com/questions/46946380/fetch-api-request-timeout) for the fetching of WASM binary (see below).

```
function instantiateAsync() {
    if (!wasmBinary &&
        typeof WebAssembly.instantiateStreaming === 'function' &&
        !isDataURI(wasmBinaryFile) &&
        // Don't use streaming for file:// delivered objects in a webview, fetch them synchronously.
        !isFileURI(wasmBinaryFile) &&
        typeof fetch === 'function') {
      fetch(wasmBinaryFile, { credentials: 'same-origin' }).then(function (response) {
        var result = WebAssembly.instantiateStreaming(response, info);
        return result.then(receiveInstantiatedSource, function(reason) {
            // We expect the most common failure cause to be a bad MIME type for the binary,
            // in which case falling back to ArrayBuffer instantiation should work.
            err('wasm streaming compile failed: ' + reason);
            err('falling back to ArrayBuffer instantiation');
            return instantiateArrayBuffer(receiveInstantiatedSource);
          });
      });
    } else {
      return instantiateArrayBuffer(receiveInstantiatedSource);
    }
}
```
Thanks!

**Comment by kripken** [comment] 2022-02-11 23:11
Sounds reasonable, see https://github.com/emscripten-core/emscripten/pull/16263

**Comment by a-shruti** [comment] 2022-02-14 05:35
Thanks a bunch!

**Comment by sbc100** [comment] 2022-02-15 19:11
I found an existing issue that I think this is a duplicate of: #15569

**Comment by sbc100** [comment] 2022-02-22 18:06
Duplicate of #15569

**Closed by sbc100** 2022-02-22 18:06 UTC
