### ISSUE TITLE
Some tests fail: Unknown option '--no-stack-ir'

### ISSUE THREAD

**Issue by yurivict** [emscripten-core/emscripten#22408] opened 2024-08-20 03:23 UTC
```
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir test_longjmp_i64.wasm -o test_longjmp_i64.wasm -g --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_longjmp_i64_emscripten (test_core.core3.test_longjmp_i64_emscripten) ... FAIL
cache:INFO:  - ok
cache:INFO: generating system asset: symbol_lists/7e50393e8b66f80ebeb981b98f8f8047cd8cb55b.json... (this will be cached in "/usr/ports/devel/emscripten/work/emscripten-3.1.64/cache/symbol_lists/7e50393e8b66f80ebeb981b98f8f8047cd8cb55b.json" for subsequent builds)
Unknown option '--no-stack-ir'
em++: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir test_i64_val.wasm -o test_i64_val.wasm --mvp-features --enable-bulk-memory --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_embind_i64_val (test_core.core3.test_embind_i64_val) ... FAIL
cache:INFO:  - ok
cache:INFO: generating system asset: symbol_lists/81dc1b946b72e29904353c5899b15e6f9619df5f.json... (this will be cached in "/usr/ports/devel/emscripten/work/emscripten-3.1.64/cache/symbol_lists/81dc1b946b72e29904353c5899b15e6f9619df5f.json" for subsequent builds)
Unknown option '--no-stack-ir'
em++: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir test_i64_invoke_bigint.wasm -o test_i64_invoke_bigint.wasm --mvp-features --enable-bulk-memory --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_i64_invoke_bigint (test_core.core3.test_i64_invoke_bigint) ... FAIL
cache:INFO:  - ok
cache:INFO: generating system asset: symbol_lists/a8c35ec8aa23f6fa9a4eb19b37f8f1926985746b.json... (this will be cached in "/usr/ports/devel/emscripten/work/emscripten-3.1.64/cache/symbol_lists/a8c35ec8aa23f6fa9a4eb19b37f8f1926985746b.json" for subsequent builds)
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir test_i64_llabs.wasm -o test_i64_llabs.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_i64_llabs (test_core.core3.test_i64_llabs) ... FAIL
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir main.wasm -o main.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_dylink_i64_reversed (test_core.core3.test_dylink_i64_reversed) ... FAIL
cache:INFO:  - ok
cache:INFO: generating system asset: symbol_lists/a4bd1f709df40b2cf4a774a30ef35828a67d2194.json... (this will be cached in "/usr/ports/devel/emscripten/work/emscripten-3.1.64/cache/symbol_lists/a4bd1f709df40b2cf4a774a30ef35828a67d2194.json" for subsequent builds)
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir test_longjmp_i64.wasm -o test_longjmp_i64.wasm -g --mvp-features --enable-exception-handling --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_longjmp_i64_wasm (test_core.core3.test_longjmp_i64_wasm) ... FAIL
Unknown option '--no-stack-ir'
em++: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir liblib.wasm -o liblib.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
Unknown option '--no-stack-ir'
None
None
test_dylink_i64_invoke_bigint (test_core.core3.test_dylink_i64_invoke_bigint) ... FAIL
em++: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir liblib.wasm -o liblib.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_dylink_i64_invoke (test_core.core3.test_dylink_i64_invoke) ... FAIL
cache:INFO:  - ok
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir liblib.wasm -o liblib.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_dylink_i64_c_reversed (test_core.core3.test_dylink_i64_c_reversed) ... FAIL
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir main.wasm -o main.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_dylink_i64_c_bigint_reversed (test_core.core3.test_dylink_i64_c_bigint_reversed) ... FAIL
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir js_library_i64_params.wasm -o js_library_i64_params.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_js_library_i64_params (test_core.core3.test_js_library_i64_params) ... FAIL
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir main.wasm -o main.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_dylink_i64_c_bigint (test_core.core3.test_dylink_i64_c_bigint) ... FAIL
Unknown option 'Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir liblib.wasm -o liblib.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir liblib.wasm -o liblib.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
Unknown option '--no-stack-ir'
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir js_library_i64_params.wasm -o js_library_i64_params.wasm --mvp-features --enable-bulk-memory --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir main.wasm -o main.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_dylink_i64_b (test_core.core3.test_dylink_i64_b) ... FAIL
None
None
test_dylink_i64_c (test_core.core3.test_dylink_i64_c) ... FAIL
test_double_i64_conversion (test_core.core3.test_double_i64_conversion) ... skipped 'is_wasm2js : tests 64-bit conversions'
None
None
test_js_library_i64_params_bigint (test_core.core3.test_js_library_i64_params_bigint) ... FAIL
None
None
test_dylink_i64_b_reversed (test_core.core3.test_dylink_i64_b_reversed) ... FAIL
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir test_i64_zextneg.wasm -o test_i64_zextneg.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir liblib.wasm -o liblib.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_i64_zextneg (test_core.core3.test_i64_zextneg) ... FAIL
None
None
test_dylink_i64 (test_core.core3.test_dylink_i64) ... FAIL
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten --pass-arg=post-emscripten-side-module -O3 --low-memory-unused --pass-arg=directize-initial-contents-immutable --no-stack-ir liblib.so -o liblib.so --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_dlfcn_i64 (test_core.core3.test_dlfcn_i64) ... FAIL
cache:INFO: generating system asset: symbol_lists/6053d9d2446de80f81043197aff4daee096a3d0d.json... (this will be cached in "/usr/ports/devel/emscripten/work/emscripten-3.1.64/cache/symbol_lists/6053d9d2446de80f81043197aff4daee096a3d0d.json" for subsequent builds)
cache:INFO:  - ok
Unknown option '--no-stack-ir'
em++: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir test_i64_binding.wasm -o test_i64_binding.wasm --mvp-features --enable-bulk-memory --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_embind_i64_binding (test_core.core3.test_embind_i64_binding) ... FAIL
cache:INFO: generating system asset: symbol_lists/e081026254e72058f61e0b7616b4ae9bb64abec2.json... (this will be cached in "/usr/ports/devel/emscripten/work/emscripten-3.1.64/cache/symbol_lists/e081026254e72058f61e0b7616b4ae9bb64abec2.json" for subsequent builds)
cache:INFO:  - ok
Unknown option '--no-stack-ir'
emcc: error: '/usr/local/bin/wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir test_em_js_i64.wasm -o test_em_js_i64.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 1)
None
None
test_em_js_i64 (test_core.core3.test_em_js_i64) ... FAIL

DONE: combining results on main thread

test_dlfcn_i64 (test_core.core3.test_dlfcn_i64) ... FAIL
test_double_i64_conversion (test_core.core3.test_double_i64_conversion) ... skipped 'is_wasm2js : tests 64-bit conversions'
test_dylink_i64 (test_core.core3.test_dylink_i64) ... FAIL
test_dylink_i64_b (test_core.core3.test_dylink_i64_b) ... FAIL
test_dylink_i64_b_reversed (test_core.core3.test_dylink_i64_b_reversed) ... FAIL
test_dylink_i64_c (test_core.core3.test_dylink_i64_c) ... FAIL
test_dylink_i64_c_bigint (test_core.core3.test_dylink_i64_c_bigint) ... FAIL
test_dylink_i64_c_bigint_reversed (test_core.core3.test_dylink_i64_c_bigint_reversed) ... FAIL
test_dylink_i64_c_reversed (test_core.core3.test_dylink_i64_c_reversed) ... FAIL
test_dylink_i64_invoke (test_core.core3.test_dylink_i64_invoke) ... FAIL
test_dylink_i64_invoke_bigint (test_core.core3.test_dylink_i64_invoke_bigint) ... FAIL
test_dylink_i64_reversed (test_core.core3.test_dylink_i64_reversed) ... FAIL
test_em_js_i64 (test_core.core3.test_em_js_i64) ... FAIL
test_embind_i64_binding (test_core.core3.test_embind_i64_binding) ... FAIL
test_embind_i64_val (test_core.core3.test_embind_i64_val) ... FAIL
test_i64 (test_core.core3.test_i64) ... skipped 'is_wasm2js : test shifts etc. on 64-bit integers'
test_i64_2 (test_core.core3.test_i64_2) ... skipped 'is_wasm2js : test shifts etc. on 64-bit integers'
test_i64_3 (test_core.core3.test_i64_3) ... skipped 'is_wasm2js : test shifts etc. on 64-bit integers'
test_i64_4 (test_core.core3.test_i64_4) ... skipped 'is_wasm2js : test shifts etc. on 64-bit integers'
test_i64_7z (test_core.core3.test_i64_7z) ... skipped 'is_wasm2js : test 64-bit math'
test_i64_b (test_core.core3.test_i64_b) ... skipped 'is_wasm2js : test shifts etc. on 64-bit integers'
test_i64_cmp (test_core.core3.test_i64_cmp) ... skipped 'is_wasm2js : test shifts etc. on 64-bit integers'
test_i64_cmp2 (test_core.core3.test_i64_cmp2) ... skipped 'is_wasm2js : test shifts etc. on 64-bit integers'
test_i64_double (test_core.core3.test_i64_double) ... skipped 'is_wasm2js : test unions of i64 and double'
test_i64_i16 (test_core.core3.test_i64_i16) ... skipped 'is_wasm2js : test 64-bit math with short values'
test_i64_invoke_bigint (test_core.core3.test_i64_invoke_bigint) ... FAIL
test_i64_llabs (test_core.core3.test_i64_llabs) ... FAIL
test_i64_precise (test_core.core3.test_i64_precise) ... skipped 'is_wasm2js : test 64-bit math'
test_i64_precise_needed (test_core.core3.test_i64_precise_needed) ... skipped 'is_wasm2js : test 64-bit multiply'
test_i64_precise_standalone (test_core.core3.test_i64_precise_standalone) ... skipped 'is_wasm2js : test 64-bit math'
test_i64_qdouble (test_core.core3.test_i64_qdouble) ... skipped 'is_wasm2js : test 64-bit/double conversions'
test_i64_umul (test_core.core3.test_i64_umul) ... skipped 'is_wasm2js : test 64-bit multiply'
test_i64_varargs (test_core.core3.test_i64_varargs) ... skipped 'is_wasm2js : tests va_arg() with i64 params'
test_i64_zextneg (test_core.core3.test_i64_zextneg) ... FAIL
test_js_library_i64_params (test_core.core3.test_js_library_i64_params) ... FAIL
test_js_library_i64_params_bigint (test_core.core3.test_js_library_i64_params_bigint) ... FAIL
test_longjmp_i64_emscripten (test_core.core3.test_longjmp_i64_emscripten) ... FAIL
test_longjmp_i64_wasm (test_core.core3.test_longjmp_i64_wasm) ... FAIL
test_longjmp_i64_wasm_exnref (test_core.core3.test_longjmp_i64_wasm_exnref) ... FAIL

======================================================================
FAIL: test_dlfcn_i64 (test_core.core3.test_dlfcn_i64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/local/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 86, in decorated
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 2986, in test_dlfcn_i64
    self.build_dlfcn_lib('liblib.c')
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 2908, in build_dlfcn_lib
    self.run_process(cmd)
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/common.py", line 1557, in run_process
    self.fail(f'subprocess exited with non-zero return code({e.returncode}): `{shared.shlex_join(cmd)}`')
  File "/usr/local/lib/python3.11/unittest/case.py", line 703, in fail
    raise self.failureException(msg)
AssertionError: subprocess exited with non-zero return code(1): `/usr/ports/devel/emscripten/work/emscripten-3.1.64/emcc liblib.c -o liblib.so -sNO_DEFAULT_TO_CXX -sSIDE_MODULE -Wclosure -Werror -Wno-limited-postlink-optimizations -O3`

======================================================================
FAIL: test_dylink_i64 (test_core.core3.test_dylink_i64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/local/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/common.py", line 730, in resulting_test
    return func(self, *args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 99, in decorated
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 4322, in test_dylink_i64
    self.dylink_test(r'''
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 4001, in dylink_test
    return self.dylink_testf(main, side, expected, main_module=main_module, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 4035, in dylink_testf
    out_file = self.build(side, js_outfile=(side_suffix == 'js'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/common.py", line 1220, in build
    self.run_process(cmd, stderr=self.stderr_redirect if not DEBUG else None)
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/common.py", line 1557, in run_process
    self.fail(f'subprocess exited with non-zero return code({e.returncode}): `{shared.shlex_join(cmd)}`')
  File "/usr/local/lib/python3.11/unittest/case.py", line 703, in fail
    raise self.failureException(msg)
AssertionError: subprocess exited with non-zero return code(1): `/usr/ports/devel/emscripten/work/emscripten-3.1.64/emcc liblib.c -o liblib.wasm -sNO_DEFAULT_TO_CXX -sSIDE_MODULE -Wclosure -Werror -Wno-limited-postlink-optimizations -O3`

======================================================================
FAIL: test_dylink_i64_b (test_core.core3.test_dylink_i64_b)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/local/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/common.py", line 730, in resulting_test
    return func(self, *args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 99, in decorated
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 119, in decorated
    f(self, *args, **kwargs)
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 4340, in test_dylink_i64_b
    self.dylink_test(r'''
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 4001, in dylink_test
    return self.dylink_testf(main, side, expected, main_module=main_module, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/test_core.py", line 4035, in dylink_testf
    out_file = self.build(side, js_outfile=(side_suffix == 'js'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/common.py", line 1220, in build
    self.run_process(cmd, stderr=self.stderr_redirect if not DEBUG else None)
  File "/usr/ports/devel/emscripten/work/emscripten-3.1.64/test/common.py", line 1557, in run_process
    self.fail(f'subprocess exited with non-zero return code({e.returncode}): `{shared.shlex_join(cmd)}`')
  File "/usr/local/lib/python3.11/unittest/case.py", line 703, in fail
    raise self.failureException(msg)
AssertionError: subprocess exited with non-zero return code(1): `/usr/ports/devel/emscripten/work/emscripten-3.1.64/emcc liblib.c -o liblib.wasm -sNO_DEFAULT_TO_CXX -sENVIRONMENT=web,node,shell -sSIDE_MODULE -Wclosure -Werror -Wno-limited-postlink-optimizations -O3`
```

Version: 3.1.64
llvm-19
FreeBSD 14.1

**Comment by kripken** [comment] 2024-08-20 17:32
This is caused by using an older binaryen version, where wasm-opt does not yet have that recent option. Check how you installed emscripten. If you installed binaryen manually, you should install a more recent version. (If you use the emsdk, it should automatically fetch proper versions of everything, automatically.)

**Comment by yurivict** [comment] 2024-08-20 22:43
The test failures were with the latest binaryen-118 released in July 8th, 2024.

**Comment by sbc100** [comment] 2024-08-20 23:18
Emscripten, in general, depends on tip-of-tree binaryen rather than any specific release.

Specifically, for emscripten 3.1.64 it looks like you would need binaryen from a8066e6618b93ea101e82b64690b9b62d7562609: https://chromium.googlesource.com/emscripten-releases/+/fd61bacaf40131f74987e649a135f1dd559aff60%5E%21/#F0.

This reversion is 51 commits ahead of the binaryen 118 release.

Has using the official binaryen releases worked for you in the past?   IIRC never something that we have officially supported.   The idea, I believe, is that packagers should bundle pinned version of both LLVM and binaryen along with emscripten for each release.

**Comment by yurivict** [comment] 2024-08-20 23:23
> The idea, I believe, is that packagers should bundle pinned version of both LLVM and binaryen along with emscripten for each release.

It would be very difficult because particular llvm revisions might not build easily.

I suggest that you should really stick to the last release versions of llvm and binaryen to facilitate porting and distribution of emscripten.

**Comment by sbc100** [comment] 2024-08-21 00:00
We have discussed that in the past, and there is an active discussion here: https://github.com/emscripten-core/emscripten/issues/11362.

But for now, I'm afraid, the status quo is that emscripten release is only guaranteed to to work with specific pinned versions of llvm and binaryen.

**Comment by sbc100** [comment] 2024-09-03 21:50
Closing as duplicate of #22249 which itself is already closed.

If you would like to continue the discussion about supporting sable versions of llvm/binaryen that is probably best to do in #11362.

**Closed by sbc100** 2024-09-03 21:50 UTC
