### ISSUE TITLE
emit-tsd does not take into account MODULARIZE + WASM_ASYNC_COMPILATION

### ISSUE THREAD

**Issue by starball5** [emscripten-core/emscripten#21794] opened 2024-04-21 23:35 UTC
**Version of emscripten/emsdk:**
3.1.57

the .d.ts file generated with `--emit-tsd` does not take into account `WASM_ASYNC_COMPILATION` with `MODULARIZE`. Regardless of value, it wraps the return value of the function with `Promise<>`. This doesn't really matter for the use-case with `await` syntax, since `await` doesn't care if the value to await is a `Promise` or not, but when the .d.ts file leads someone to think they can use `.then`, this is a problem.

**Comment by brendandahl** [comment] 2024-04-22 20:13
Duplicate of #21760

**Closed by brendandahl** 2024-04-22 20:13 UTC
