### ISSUE TITLE
[SIMD] wasm_v8x16_shuffle fails to generate i18x16.shuffle with same indices

### ISSUE THREAD

**Issue by huningxin** [emscripten-core/emscripten#9340] opened 2019-08-28 03:21 UTC
### Test case
[`v_load_deinterleave`](https://docs.opencv.org/master/df/d91/group__core__hal__intrin.html#gafd8e859406c66bb5b7d901473265119b) is a  OpenCV.js universal intrinsic that is used by popluar image processing kernels,  for example color conversion [`cvtColor`](https://docs.opencv.org/master/d8/d01/group__imgproc__color__conversions.html#ga397ae87e1288a81d2363b61574eb8cab).

By being inspired by [its SSE2 implementation](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_sse.hpp#L1871), the proposal of WASM SIMD implementation is like
```c++
inline v128_t wasm_unpacklo_i8x16(v128_t a, v128_t b) {
    // expect punpcklbw
    return wasm_v8x16_shuffle(a, b, 0,16,1,17,2,18,3,19,4,20,5,21,6,22,7,23);
}

inline v128_t wasm_unpackhi_i64x2(v128_t a, v128_t b) {
    // expect punpckhqdq
    return wasm_v8x16_shuffle(a, b, 8,9,10,11,12,13,14,15,24,25,26,27,28,29,30,31);
}

__attribute__((noinline))
inline void v_load_deinterleave(const unsigned char* ptr, __u8x16& a, __u8x16& b, __u8x16& c)
{
    v128_t t00 = wasm_v128_load(ptr);
    v128_t t01 = wasm_v128_load(ptr + 16);
    v128_t t02 = wasm_v128_load(ptr + 32);

    v128_t t10 = wasm_unpacklo_i8x16(t00, wasm_unpackhi_i64x2(t01, t01));
    v128_t t11 = wasm_unpacklo_i8x16(wasm_unpackhi_i64x2(t00, t00), t02);
    v128_t t12 = wasm_unpacklo_i8x16(t01, wasm_unpackhi_i64x2(t02, t02));

    v128_t t20 = wasm_unpacklo_i8x16(t10, wasm_unpackhi_i64x2(t11, t11));
    v128_t t21 = wasm_unpacklo_i8x16(wasm_unpackhi_i64x2(t10, t10), t12);
    v128_t t22 = wasm_unpacklo_i8x16(t11, wasm_unpackhi_i64x2(t12, t12));

    v128_t t30 = wasm_unpacklo_i8x16(t20, wasm_unpackhi_i64x2(t21, t21));
    v128_t t31 = wasm_unpacklo_i8x16(wasm_unpackhi_i64x2(t20, t20), t22);
    v128_t t32 = wasm_unpacklo_i8x16(t21, wasm_unpackhi_i64x2(t22, t22));

    a = wasm_unpacklo_i8x16(t30, wasm_unpackhi_i64x2(t31, t31));
    b = wasm_unpacklo_i8x16(wasm_unpackhi_i64x2(t30, t30), t32);
    c = wasm_unpacklo_i8x16(t31, wasm_unpackhi_i64x2(t32, t32));
}
```

### Expected result
In particular, we expect `wasm_v8x16_shuffle(a, b, 0,16,1,17,2,18,3,19,4,20,5,21,6,22,7,23)` could generate `i8x16.shuffle 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23` that matches [`kX64S8x16UnpackLow` pattern in V8](https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/compiler/backend/x64/instruction-selector-x64.cc#L2877) that generates `punpcklbw` instruction. Similarly, we expect `wasm_v8x16_shuffle(a, b, 8,9,10,11,12,13,14,15,24,25,26,27,28,29,30,31)` could generate `i8x16.shuffle 8 9 10 11 12 13 14 15 24 25 26 27 28 29 30 31` that matches [kX64S64x2UnpackHigh pattern in V8](https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/compiler/backend/x64/instruction-selector-x64.cc#L2857) that generates `punpckhqdq`  instruction.

### Actual result
However, it turns out emscripten compiles the above code to different `v8x16.shuffle` wasm ops that fails to match the pattern and leads V8 to generate slow `pshufb` with memory operands.

The wasm-dis output is
```
(func $v_load_deinterleave\28unsigned\20char\20const*\2c\20unsigned\20char\20vector\5b16\5d&\2c\20unsigned\20char\20vector\5b16\5d&\2c\20unsigned\20char\20vector\5b16\5d&\29 (; 10 ;) (type $7) (param $0 i32) (param $1 i32) (param $2 i32) (param $3 i32)
  (local $4 v128)
  (local $5 v128)
  (local $6 v128)
  (local $7 v128)
  (local $8 v128)
  (v128.store
   (local.get $1)
   (v8x16.shuffle 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23
    (local.tee $7
     (v8x16.shuffle 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23
      (local.tee $8
       (v8x16.shuffle 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23
        (local.tee $6
         (v8x16.shuffle 0 24 1 25 2 26 3 27 4 28 5 29 6 30 7 31
          (local.tee $4
           (v128.load align=1
            (local.get $0)
           )
          )
          (local.tee $5
           (v128.load offset=16 align=1
            (local.get $0)
           )
          )
         )
        )
        (v8x16.shuffle 8 9 10 11 12 13 14 15 0 0 0 0 0 0 0 0
         (local.tee $4
          (v8x16.shuffle 8 16 9 17 10 18 11 19 12 20 13 21 14 22 15 23
           (local.get $4)
           (local.tee $7
            (v128.load offset=32 align=1
             (local.get $0)
            )
           )
          )
         )
         (local.get $4)
        )
       )
      )
      (v8x16.shuffle 8 9 10 11 12 13 14 15 0 0 0 0 0 0 0 0
       (local.tee $6
        (v8x16.shuffle 8 16 9 17 10 18 11 19 12 20 13 21 14 22 15 23
         (local.get $6)
         (local.tee $5
          (v8x16.shuffle 0 24 1 25 2 26 3 27 4 28 5 29 6 30 7 31
           (local.get $5)
           (local.get $7)
          )
         )
        )
       )
       (local.get $4)
      )
     )
    )
    (v8x16.shuffle 8 9 10 11 12 13 14 15 0 0 0 0 0 0 0 0
     (local.tee $5
      (v8x16.shuffle 8 16 9 17 10 18 11 19 12 20 13 21 14 22 15 23
       (local.get $8)
       (local.tee $4
        (v8x16.shuffle 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23
         (local.get $4)
         (v8x16.shuffle 8 9 10 11 12 13 14 15 0 0 0 0 0 0 0 0
          (local.get $5)
          (local.get $4)
         )
        )
       )
      )
     )
     (local.get $4)
    )
   )
  )
  (v128.store
   (local.get $2)
   (v8x16.shuffle 8 16 9 17 10 18 11 19 12 20 13 21 14 22 15 23
    (local.get $7)
    (local.tee $4
     (v8x16.shuffle 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23
      (local.get $6)
      (v8x16.shuffle 8 9 10 11 12 13 14 15 0 0 0 0 0 0 0 0
       (local.get $4)
       (local.get $4)
      )
     )
    )
   )
  )
  (v128.store
   (local.get $3)
   (v8x16.shuffle 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23
    (local.get $5)
    (v8x16.shuffle 8 9 10 11 12 13 14 15 0 0 0 0 0 0 0 0
     (local.get $4)
     (local.get $4)
    )
   )
  )
 )
```

In particular, the `v8x16.shuffle 8,9,10,11,12,13,14,15,0,0,0,0,0,0,0,0`, `v8x16.shuffle 8,16,9,17,10,18,11,19,12,20,13,21,14,22 15 23`, `v8x16.shuffle 0,24,1,25,2,26,3,27,4,28,5,29,6,30,7,31` lead V8 to generate slow `pshufb` with memory operands.

**Comment by tlively** [comment] 2019-08-28 21:28
This is a tricky issue. This transformation is being applied in LLVM's final optimizations before code generation. The shuffle masks are being combined to reduce the total number of shuffle instructions, but LLVM does not realize that by reducing the number of shuffles it will ultimately produce worse code. To allow your code to work, we will probably have to implement a new wasm-specific shuffle builtin function that will be opaque to such optimizations. That new builtin function would then be used to implement `wasm_v8x16_shuffle`.

I also experimented with solving this problem using inline (web)assembly in the C code, but that had some issues. Essentially the inline assembly was too opaque to LLVM, so the output module was not valid.

Out of curiosity, are you implementing code paths tuned to ARM instructions as well?

**Comment by huningxin** [comment] 2019-08-29 06:59
@tlively , thanks for your comments. Basically, I need a way that generates exact WASM op, e.g. `v8x16.shuffle` with certain mask. However, it turns out `wasm_v8x16_shuffle` doesn't guarantee that. So do you know any other ways? You also mentioned inline webassembly is not a right answer, is it?

> Out of curiosity, are you implementing code paths tuned to ARM instructions as well?

According to [the neon optimization of OpenCV](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_neon.hpp#L1418), it uses `vld3q_s8` to implement `v_load_deinterleave`. However, I didn't find a equivalent wasm simd op. (Did I miss anything?) So I'd leverage the shuffle ops first. But I am now somehow blocked by finding a way to generate exact wasm simd shuffle ops.

**Comment by tlively** [comment] 2019-08-29 18:28
@huningxin. Currently there is no way to do this. I am working on a fix upstream in LLVM and Emscripten so that the code you've written will lower as expected, so you won't need to do anything except update emscripten once the fix is in. I will update this issue with my progress.

**Comment by huningxin** [comment] 2019-08-30 02:13
great, thanks @tlively .

**Comment by tlively** [comment] 2019-08-30 03:26
The LLVM/clang patch is https://reviews.llvm.org/D66983 and the corresponding emscripten patch is #9350.

**Comment by gnzlbg** [comment] 2019-10-17 08:12
> In particular, we expect wasm_v8x16_shuffle(a, b, 0,16,1,17,2,18,3,19,4,20,5,21,6,22,7,23) could generate i8x16.shuffle 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23 

Since LLVM does not guarantee that this happens, and this is not really guaranteed for any hardware intrinsic on any programming language, this expectation is incorrect. If you need this guarantee, the language feature you are looking for is called "inline assembly", and that guarantees that the exact same WASM you write will be generated by the backend.

What the hardware intrinsics guarantee is that they have those semantics, in this case, the same as those of performing that shuffle. For example, if by using the intrinsics LLVM would be evaluating your code at compile-time, not emitting any WASM instructions for this, you wouldn't be opening this issue 😆 

So what's happening here is that LLVM is optimizing two shuffle instructions into one, making your program faster and smaller for the WASM abstract machine. The issue is that V8 is dropping the ball by generating bad code for it. A different WASM->NATIVE code generator could do better, and if you open a V8 bug, maybe a future V8 version could do better too.

Does this make sense to you?

**Comment by gnzlbg** [comment] 2019-10-17 22:14
> Well, combining the shuffles does make the program smaller, but without reasoning about the underlying platform it is impossible to know whether the program would become faster or slower.

The underlying platform is WASM.

> The WebAssembly specification does not make any mention of the relative expected performance of different instructions

Neither do most ISAs. Compilers use heuristics for this.

> So LLVM is doing this shuffle combine based on unfounded assumptions and probably should not be doing it.

The combined operation would be faster on WABT than the uncombined one. In fact, the uncombined operation would be twice as slow as the combined one on WABT.

**Comment by gnzlbg** [comment] 2019-10-17 22:15
I suppose that this means that you disagree that this is a V8 performance bug then ? Is there a V8 bug report for this that concluded that ?

**Comment by tlively** [comment] 2019-10-17 22:34
There is no V8 bug report I know of for this issue. Whether V8 would consider lowering a single shuffle into a combination of multiple shuffles is an interesting question that I do not know the answer to, but I'm skeptical of calling it a bug if they don't because there is a design decision to be made about how much code to put into optimizing shuffles.

**Comment by gnzlbg** [comment] 2019-10-18 00:42
It would be fair for V8 to decide that generating sub-optimal x86 instructions for this mask is an acceptable trade-off for their engine. But that answer would already convey that they consider the current performance of the code that LLVM generates acceptable.

**Comment by huningxin** [comment] 2019-10-19 02:32
> Since LLVM does not guarantee that this happens, and this is not really guaranteed for any hardware intrinsic on any programming language (e.g. the Intel SEE or ARM NEON ones), this expectation is incorrect.

My expectation comes from using Intel SSE intrinsics that indicate the corresponding instruction. For example, [`_mm_shuffle_epi8`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=1383,5196,5143,5152,5152&text=_mm_shuffle_epi8%2520) indicates `pshufb`.

**Comment by gnzlbg** [comment] 2019-10-19 09:12
@huningxin 

> My expectation comes from using Intel SSE intrinsics that indicate the corresponding instruction. For example, _mm_shuffle_epi8 indicates pshufb.

Those instructions are "examples" of what the compiler might generate. Not even the intel compiler commits to generating that. For example, `_mm_add_epi32` says in that website that its instruction is a `padd`, but this example:

```c
__m128 foo() { return _mm_add_epi32(_mm_set1_epi32(1), _mm_set1_epi32(1)); }
```

does not generate a `padd` in the Intel compiler, or clang, or gcc, or any other (proof: https://gcc.godbolt.org/z/a7Zvl5). So if the claim that the intrinsic documentation requires that, then all those compilers have a bug. As a user of those compilers, if they were to generate a `padd` here, I would fill a compiler bug. In the same vein, if LLVM were to generate multiple shuffles here, I would fill in a compiler bug as well. In other words, the instructions that the Intel intrinsics guide documents are "examples" of what the compiler might generate, but the compiler is not required to generate those. The intrinsics documentation has an "operational semantics" specification of what an intrinsic does, and that's the only thing the spec requires (in this case, that it adds two vectors). Which instruction the compiler then uses for that, is up to the compiler. In this case, the instruction can be constant folded, so no instruction is necessary. Intel, GCC, Clang, ... offer an "inline assembly" feature that lets you tell the compiler: "generate a padd" here, and then these optimizations are not performed.

Does that make sense?

**Comment by huningxin** [comment] 2019-11-20 06:20
I happened to measure the slow down of `v_load_deinterleave` by applying @tlively 's patch

> The LLVM/clang patch is https://reviews.llvm.org/D66983 and the corresponding emscripten patch is #9350.

The wasm test case is https://github.com/huningxin/emscripten-wasm-test/blob/master/v_load_deinterleave_wasm.cc. I also measure the native sse performance by same version of clang in emscripten. The sse test case is https://github.com/huningxin/emscripten-wasm-test/blob/master/v_load_deinterleave_sse.cc

Here are result on my machine with i7-8700 CPU @3.2GHz. The test is run by v8 7.8.0 @8567ac2.

| compiler | elapsed time (second) |
|----------------|-------------------------------|
| vanilla 1.38.42 | 7.927000 |
| patched 1.38.42  |  1.01000 |
| clang 10.0.0 @edfaee0 | 0.919862 |

It turns out 7.9X slow down for me.

**Comment by omnisip** [comment] 2020-09-15 18:12
That's significant.

**Comment by tlively** [comment] 2021-09-21 23:43
This was fixed upstream.

**Closed by tlively** 2021-09-21 23:43 UTC
Labels: SIMD, wontfix
