### ISSUE TITLE
this is a re-open of "emscripten does not work with cygwin #1516"

### ISSUE THREAD

**Issue by jlmalet** [emscripten-core/emscripten#3947] opened 2015-12-02 11:50 UTC
I got the same issue but in a different way : 
I tried at first to use the cygwin's CLang but since node.js can't be compiled into cygwin I ended to install a full emscripten in /cygdrive/c/Program Files/Emscripten/emscripten/1.35.0/emcc

in ~/.emscriptem

```
# this helps projects using emscripten find it
EMSCRIPTEN_ROOT = 'c:\Program Files\Emscripten\emscripten\1.35.0' # directory
LLVM_ROOT = 'c:\Program Files\Emscripten\clang\e1.35.0_64bit' # directory
```

now time to run....

```
$ emcc
WARNING:root:did not see a source tree above or next to the LLVM root directory (guessing based on directory of c:\Program Files\Emscripten\clang\e1.35.0_64bit/llc), could not verify version numbers match
INFO:root:(Emscripten: Running sanity checks)
module.js:340
    throw err;
    ^

Error: Cannot find module 'C:\cygdrive\c\Program Files\Emscripten\emscripten\1.35.0\src\hello_world.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
Checking JS engine ['/cygdrive/c/Program Files/nodejs/node'] failed. Check ~/.emscripten. Details: Expected the command ['/cygdrive/c/Program Files/nodejs/node', '/cygdrive/c/Program Files/Emscripten/emscripten/1.35.0/src/hello_world.js'] to finish with return code 0, but it returned with code 1 instead! Output:
CRITICAL:root:The JavaScript shell used for compiling (['/cygdrive/c/Program Files/nodejs/node']) does not seem to work, check the paths in ~/.emscripten
```

first some strange things... that seems to be not related...

```
Error: Cannot find module 'C:\cygdrive\c\Program Files\Emscripten\emscripten\1.35.0\src\hello_world.js'
```

why is C:\ added?

anyway the main issue is here :

```
 ['/cygdrive/c/Program Files/nodejs/node', '/cygdrive/c/Program Files/Emscripten/emscripten/1.35.0/src/hello_world.js']
```

which should be

```
 ['/cygdrive/c/Program Files/nodejs/node', 'c:/Program Files/Emscripten/emscripten/1.35.0/src/hello_world.js']
```

and that's it!!!!
1. emscriptem seems to detect that it is in a cygwin environment since all path are translated to the standard cygwin path
2. node must always be run as a windows executable, not a cygwin one (unless it's path is configured as a cygwin path.. ie beginning with a "/"
3. not sure about this, but cygwin can work perfectly with both cygwin and windows path. for example

```
cd 'c:\Program Files\'; #works correcly
ls 'C:\Program Files\Emscripten\emscripten\1.35.0\src\hello_world.js'
C:\Program Files\Emscripten\emscripten\1.35.0\src\hello_world.js; #ok also
```

=> either consider node as a windows program, or don't detect we are in cygwin and apply windows path everywhere if we are on a windows installation....
you might have a look at http://stackoverflow.com/questions/13162372/using-absolute-unix-paths-in-windows-with-python

**Comment by jlmalet** [comment] 2015-12-02 17:01
I put some "solution" on this thread...
https://github.com/kripken/emscripten/issues/1516

**Comment by jlmalet** [comment] 2015-12-02 17:02
to make it work...

install the full emscripten windows package found here : 
https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html  "Emscripten SDK Offline Installer"

then create a script (I called it emcc) with the following code : 
```
#!/bin/sh
IFS=$'\n'
i=0
while [ $# -gt 0 ]; do
        if [ -f "$1" ] || [ -d "$1" ]; then
                arg[$i]="$(cygpath -w $1)"
        else
                arg[$i]=$1
        fi
        i=$((i+1))
        shift
done
${WINPYTHON} $(cygpath -w $(which emcc))  "${arg[@]}"
````

run it once
edit ~/.emscripten file

change (as you see I made all the binaries point to the EMSCRIPTEN_ROOT installed version
````
EMSCRIPTEN_ROOT = os.path.expanduser(os.getenv('EMSCRIPTEN') or 'C:\\Program Files\\Emscripten\\emscripten\\1.35.0') # directory
LLVM_ROOT = os.path.expanduser(os.getenv('LLVM') or 'C:\\Program Files\\Emscripten\\clang\\e1.35.0_64bit') # directory

NODE_JS = os.path.expanduser(os.getenv('NODE') or 'C:\\Program Files\\Emscripten\\node\\4.1.1_64bit\\bin\\node.exe') # executable
SPIDERMONKEY_ENGINE = [os.path.expanduser(os.getenv('SPIDERMONKEY') or 'C:\\Program Files\Emscripten\spidermonkey\37.0.1_64bit\\js.exe')] # executable
````

now run 
````
./emcc hello_world.c
 /cygdrive/c/Program\ Files/Emscripten/node/4.1.1_64bit/bin/node.exe a.out.js
hello, world!

````

**Comment by jlmalet** [comment] 2015-12-02 17:05
as you see, all the problem is from the python... as usual ;) 

anyway a good way to make it work without path issue, is to change to the directory containing the js file and call node.exe from there.... as you see in the last run I called it from my home directory without any issue... so yes node.exe is runable from cygwin, but it can only understand windows path...

**Comment by jlmalet** [comment] 2015-12-02 17:13
another solution is to call the provided .bat files.... seems to work and to use the python provided in the sdk

**Comment by rlavalle** [comment] 2016-07-26 23:24
Another workaround, is adding a directory junction on windows to make C:\cygdrive\c points back to C:\

i.e.
```
C:\cygdrive>mklink /d /j c c:\
Junction created for c <<===>> c:\
```

**Comment by treytencarey** [comment] 2018-08-09 15:26
Kind of crazy that 3 years later, this is still an issue.

Anyways, I tried jlmalet's solution to build OpenSSL for Emscripten, and it failed.

In Cygwin, the EMSCRIPTEN_ROOT in ~./emscripten must be /cydrive/c/…, so after changing it to that path and then running with the new emcc script (provided by jlmalet above), I get the reverse error "Incorrect EMSCRIPTEN_ROOT in config file" which is expecting C:/. So if I edit ~./emscripten again to be the C:/ path, then emscripten expects /cygdrive/c/… to run.

Now I'm stuck in an infinite loop of "Use cygdrive. No, use C:/. No, use cygdrive."
mklink created the c shortcut directory, but also doesn't solve my issue.


It seems emscripten is totally broken on Windows. MSYS does not work, command prompt does not work, and Cygwin does not work.

**Comment by kripken** [comment] 2018-08-09 16:36
The `Incorrect EMSCRIPTEN_ROOT in config file` error was a recent regression - it is fixed in 1.38.11.

**Comment by treytencarey** [comment] 2018-08-09 17:09
Thanks, although this error remains unchanged:

> module.js:538
>     throw err;
>     ^
> 
> Error: Cannot find module 'C:\cygdrive\c\emsdk\emscripten\1.38.11\src\hello_world.js'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Function.Module.runMain (module.js:676:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3
> INFO:root:Checking JS engine ['c:/emsdk/node/8.9.1_64bit/bin/node.exe'] failed. Check your config file. Details: Expected the command ['c:/emsdk/node/8.9.1_64bit/bin/node.exe', '/cygdrive/c/emsdk/emscripten/1.38.11/src/hello_world.js'] to finish with return code 0, but it returned with code 1 instead! Output:
> WARNING:root:did not see a source tree above or next to the LLVM root directory (guessing based on directory of c:/emsdk/clang/e1.38.11_64bit/llc), could not verify version numbers match
> INFO:root:(Emscripten: Running sanity checks)
> ERROR:root:The JavaScript shell used for compiling (['c:/emsdk/node/8.9.1_64bit/bin/node.exe']) does not seem to work, check the paths in C:\Users\Admin\.emscripten
> make[1]: *** [Makefile:779: crypto/aes/aes-x86_64.o] Error 1
> make[1]: Leaving directory '/cygdrive/c/Users/Admin/Desktop/WorldofHello/libs/openssl'
> make: *** [Makefile:171: all] Error 2

**Comment by treytencarey** [comment] 2018-08-10 21:34
C:\cygdrive\c is not a thing. It should be \cygdrive\c for Cygwin. I don't see why C: is being appended to the beginning.

Here are the contents:

> import os
> LLVM_ROOT='C:/emsdk/clang/e1.38.11_64bit'
> EMSCRIPTEN_NATIVE_OPTIMIZER='C:/emsdk/clang/e1.38.11_64bit/optimizer.exe'
> BINARYEN_ROOT='C:/emsdk/clang/e1.38.11_64bit/binaryen'
> NODE_JS='C:/emsdk/node/8.9.1_64bit/bin/node.exe'
> PYTHON='C:/emsdk/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe'
> JAVA='C:/emsdk/java/8.152_64bit/bin/java.exe'
> EMSCRIPTEN_ROOT='C:/emsdk/emscripten/1.38.11'
> SPIDERMONKEY_ENGINE = ''
> V8_ENGINE = ''
> TEMP_DIR = 'c:/users/admin/appdata/local/temp'
> COMPILER_ENGINE = NODE_JS
> JS_ENGINES = [NODE_JS]

**Comment by kripken** [comment] 2018-08-12 21:34
I don't know enough about windows or cygwin to debug this, but looks like the paths in the config file are correct, and the bad `C:\cygdrive` comes from somewhere else. Maybe that's node.js confused in a cygwin environment? Or maybe python `abspath` adds a `C:`. The python stack trace might help debug it.

**Closed** 2019-09-25 22:21 UTC
Labels: windows, wontfix
