### ISSUE TITLE
Modules with EXPORT_ES6=1 do not work in NodeJS

### ISSUE THREAD

**Issue by ibdafna** [emscripten-core/emscripten#15022] opened 2021-09-10 20:17 UTC
Hi team,

Emscripten will throw an error when attempting to instantiate modules build with EXPORT_ES6=1:

```javascript
const dataModel = await createWasmDataModel()
```

```javascript
 if (!(typeof process === "object" && typeof require === "function")) throw new Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");
```

My Makefile configuration:
```Makefile
build:
	em++ \
	--bind \
	 ${SRC_DIR}/main.cpp \
	-o ${SRC_DIR}/${MODEL_NAME}.js \
	-s MODULARIZE=1 \
	-s EXPORT_ES6=1 \
	-s USE_ES6_IMPORT_META=1 \
	-s 'EXPORT_NAME="createWasmDataModel"' \
	-s ALLOW_MEMORY_GROWTH=1 \
	-fsanitize=address \
	-std=c++17
```

I'm happy to take a look if someone can point me in the right direction. Many thanks!

**Comment by sbc100** [comment] 2021-09-10 22:32
Does node not define both `require` and `process` the mode you are using?

**Comment by curiousdannii** [comment] 2021-09-11 22:34
EXPORT_ES6 is still almost useless: https://github.com/emscripten-core/emscripten/issues/11792

**Comment by lithdew** [comment] 2021-09-13 12:12
> Does node not define both `require` and `process` the mode you are using?

Ran into the same issue as well. In cases where NodeJS is running in ES Module mode (as opposed to CommonJS mode), `require` is undefined as modules may only be imported via. the `import` statement.

I'm not sure what command-line flag may be used to force Node to run in ES Module mode, though including `"type": "module",` in a package.json forces any NodeJS scripts that are run under npm/yarn to operate in ES Module mode.

To take into account NodeJS running in ES Module mode, it may be better to have the check be:

```js
if (!(typeof process === "object" && (!require || typeof require === "function")))
```

**Comment by kripken** [comment] 2021-09-13 16:29
cc @RReverser

**Comment by sbc100** [comment] 2021-09-13 16:41
I've got a fix in flight

**Comment by RReverser** [comment] 2021-09-13 17:59
I think this is a duplicate of https://github.com/emscripten-core/emscripten/issues/11792. There are a lot of checks / issues necessary for both to work.

**Comment by RReverser** [comment] 2021-09-16 18:54
I'll close this issue in favour of #11792.

**Closed by RReverser** 2021-09-16 18:54 UTC
