### ISSUE TITLE
Closure: `variable require is undeclared` (regression since `2.0.23`)

### ISSUE THREAD

**Issue by StarWitch** [emscripten-core/emscripten#14486] opened 2021-06-18 20:27 UTC
### Stacktrace

```
 "/Users/aliced/Code/emsdk/node/14.15.5_64bit/bin/node" /Users/aliced/Code/emsdk/upstream/emscripten/tools/acorn-optimizer.js /var/folders/j9/lpk9tn816_v8fffzybq3wz140000gn/T/tmprpy83sxd.js applyDCEGraphRemovals --closureFriendly
 "/Users/aliced/Code/emsdk/node/14.15.5_64bit/bin/node" /Users/aliced/Code/emsdk/upstream/emscripten/tools/acorn-optimizer.js /var/folders/j9/lpk9tn816_v8fffzybq3wz140000gn/T/emscripten_temp_04wmh4_m/taisei.js.pp.js.jso.js.jso.js AJSDCE --closureFriendly
building:ERROR: Closure compiler run failed:

building:ERROR: tmph5lzeko1.js:195:4: ERROR - [JSC_UNDEFINED_VARIABLE] variable require is undeclared
  195|     require("fs").readFile(packageName, function(err, contents) {
           ^^^^^^^

1 error(s), 0 warning(s)

em++: error: closure compiler failed (rc: 1): /Users/aliced/Code/emsdk/node/14.15.5_64bit/bin/node --max_old_space_size=8192 /Users/aliced/Code/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --language_in ECMASCRIPT_2020 --language_out NO_TRANSPILE --emit_use_strict=false --externs tmpnk87kqug.js --js_output_file tmp7e7stvls.cc.js --js tmph5lzeko1.js the error message may be clearer with -g1 and EMCC_DEBUG=2 set
FAILED: src/taisei.html src/taisei.wasm src/taisei.js 
/Users/aliced/Code/emsdk/upstream/emscripten/em++ /Users/aliced/Code/dev-taisei/taisei.upstream/build/src/libtaisei-full.a --pre-js ../emscripten/preamble.js --pre-js resources/bundle_gfx.js --pre-js resources/bundle_misc.js --pre-js resources/bundle_bgm.js --pre-js resources/bundle_sfx.js --shell-file ../emscripten/shell.html -v -s STRICT=1 -Os -s ALLOW_MEMORY_GROWTH=1 -s 'DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=["$autoResumeAudioContext"]' -s ENVIRONMENT=web -s EXIT_RUNTIME=0 -s 'EXPORTED_FUNCTIONS=["_main", "_vfs_sync_callback"]' -s 'EXPORTED_RUNTIME_METHODS=["ccall"]' -s FILESYSTEM=1 -s FORCE_FILESYSTEM=1 -s GL_POOL_TEMP_BUFFERS=0 -s GL_PREINITIALIZED_CONTEXT=1 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0 -s INITIAL_MEMORY=268435456 -s LZ4=1 -s MAX_WEBGL_VERSION=2 -s MIN_WEBGL_VERSION=2 -s MODULARIZE=0 -s WASM=1 -s LLD_REPORT_UNDEFINED -lGL -lwebgl.js -legl.js -lidbfs.js -lexports.js -s ASYNCIFY -Os -g0 -s ASSERTIONS=0 -s GL_TRACK_ERRORS=0 --closure 1 -o src/taisei.html
ninja: build stopped: subcommand failed.
```

### Relevant Links

See the following GitHub Action failure, running on Ubuntu: https://github.com/taisei-project/taisei/runs/2861465639

You can see the linker flags we set here (ignore the flags set under `if em_debug` as those are not used in our CI): https://github.com/taisei-project/taisei/blob/8fed29ca683b156cb3f6832a9bb2a9000b96cf32/src/meson.build#L163

Here is the `meson` machine file: https://github.com/taisei-project/taisei/blob/master/misc/ci/emscripten-build-test-ci.ini

Relevant section of our CI: https://github.com/taisei-project/taisei/blob/8fed29ca683b156cb3f6832a9bb2a9000b96cf32/.github/workflows/main.yml#L198

### Replicate

To replicate locally on the project itself, you will need `meson`.

Change `PATH_TO_EMSDK` below to reflect the correct path as an *absolute* path. Also, macOS users will need to use `gsed` (installed through Homebrew, etc). (Alternatively, set the `toolchain` variable inside `misc/ci/emscripten-build-test-ci.ini` to the *absolute* path to your `emsdk` installation, i.e: `toolchain = '/path/to/emsdk/upstream/emscripten/'` )

```bash
git clone https://github.com/taisei-project/taisei.git
cd taisei; git submodule update --init --recursive
sed -i "s+toolchain = ''+toolchain = 'PATH_TO_EMSDK/upstream/emscripten/'+g" misc/ci/emscripten-build-test-ci.ini # or gsed
meson setup build/ --cross-file=misc/ci/emscripten-build-test-ci.ini -Dbuild.cpp_std=gnu++14
meson compile -C build/
```

Tried with `tot` and it failed to compile as well. Reverting to `2.0.23` fixes this error.

If there is a new flag we have to add somewhere, please let us know.

----

As an aside, and I'll try to say this as politely as I can, Emscripten is easily the highest-burden platform we on the Taisei team support. It feels as if each minor version of Emscripten has made our builds fail in new and "interesting" ways, without much insight into why without spending hours digging into it, and despite our Emscripten support code not changing at all. We want to continue to support it, but it is so high-maintenance as to be a huge drag on our time and energy as an open source volunteer-run game project.

To illustrate this: we currently have *two* tests in our CI stack. One runs a "pinned" version of Emscripten (currently, `2.0.21`) and another runs with the `latest` Emscripten. It has become routine for minor versions of Emscripten to break our builds, and the `latest` test is set as `continue-on-error: true` as we expect it to fail often due to this. Perhaps we're using Emscripten in a completely unorthodox way, but I don't think that's the case, and it's usually the linking phase that has random issues like the one above.

While I recognize I am an outsider, and thus have no visibility into the inner machinations of this project, I highly recommend focusing on improving testing and communication around the closure compiler and any changes that might arrive in it, if that isn't already underway.

**Comment by kripken** [comment] 2021-06-18 20:57
This particular issue with closure is odd. It is true that `require` is undefined there, and I can see what PR added that code (#11785), but

1. When I build files locally that use that code, I can see it passing through closure without error.
2. There are many other places in the code that use `require` in this way, that is, that check "are we node" and then use `require` if so, and we have not had issues with this in the past - it seemed like closure was smart enough to not break on it. And there is no other way to write such optional-node code.

So I am not sure what changed in your CI or in your project.

One possibility is a different closure version perhaps - did you modify the default one emcc uses? If that's not it, then it might be a closure compiler bug. We don't have much connection to the work in that project, we just use it. But perhaps we should file a bug report. For that, can you build with `EMCC_DEBUG=1` in the env? Then you'll get something like `/tmp/emscripten_temp/emcc-15-postclean.js` as the last temp JS file before it runs closure and crashes. If you can attach that I can investigate it and file an issue.

Separately from that, you may want to just set `IGNORE_CLOSURE_COMPILER_ERRORS`. That will prevent future issues as well, and is fine to do if you don't want to use closure as an error checking system.

About the general issues with breakage - sorry about that. In general, we do receive feedback on breakage from time to time, but your project does seem to be suffering from far more than others, so that is odd. One thing I'd recommend is running tests on `tot` builds - bugs you file on that can be fixed before they reach a release.

**Comment by StarWitch** [comment] 2021-06-18 21:12
Attached is the file output by `EMCC_DEBUG=1`: [emcc-15-postclean.js.tar.gz](https://github.com/emscripten-core/emscripten/files/6679379/emcc-15-postclean.js.tar.gz)

Besides that, there's no code difference between the two to have caused this. I can do the following and reproduce it:

```bash
./emsdk install 2.0.23 && ./emsdk activate 2.0.23
cd /path/to/taisei
rm -rf build/ 
meson setup build/ --cross-file=misc/ci/emscripten-build-test-ci.ini -Dbuild.cpp_std=gnu++14
meson compile -C build/
```

... which compiles correctly, as expected. 

Switching versions and not changing the code of our project at all, however, does not work:

```bash
./emsdk install 2.0.24 && ./emsdk activate 2.0.24
cd /path/to/taisei
rm -rf build/ 
meson setup build/ --cross-file=misc/ci/emscripten-build-test-ci.ini -Dbuild.cpp_std=gnu++14
meson compile -C build/
```

This results in a failure.

As for building with `tot`, we could do that, but I think it would place an ever greater strain on us to evaluate each build error to determine if it was a code regression that went unnoticed or merely a quirk of `tot` being so "bleeding edge" (i.e: it has already been noticed and is getting fixed). I'm willing to set up some sort of automated report in our CI that can send build failures to whoever might be interested in them, but further investigation work on our part would be a bit too much of a burden.

**Comment by sbc100** [comment] 2021-06-18 21:45
Ah, the issue with `-s ENVIRONMENT=web` .. we not pass the node files from `third_party/closure-compiler/node-externs/` in that case.

Perhaps we can somehow `ifdef` the code in the output of file_package.py?  Is that allowed?

Regardless, do we think is a good idea to have closure run with limited externs like that?  It seems like its a good way to catch slipups like this where the code could be smaller, but I'm not sure that is the role that closure plays in our toolchain.  WDYT?

**Comment by kripken** [comment] 2021-06-18 22:07
@StarWitch 

That makes sense. If it were possible to notify us of build failures, that might be a good start. One thing that would make that effective is if it would only notify us of build failures when emcc is upgraded (i.e., to only see relevant errors). Also, an easy way to run the CI with a different emcc would be good (that might be as easy as us forking your repo and modifying the script to do `emsdk install SPECIFIC_HASH`). If we can do those two things then I'd be interested to try to see how that goes.

@sbc100 

Good catch! Yes, the issue is the combination of the environment flag with that change. And the underlying issue is that the file packager doesn't have ifdefing. We need to add that, I think - I'll look into it.

**Comment by Akaricchi** [comment] 2021-06-18 23:05
Re ifdefing in the file packager: I think this might be another good reason to move most of its functionality into regular library code (subject to CDE), and have it only generate the file lists and some minimal code that calls into the library. The other good reason for this is that when multiple packages are used (such as in Taisei) you end up with *a lot* of generated code duplication.

**Comment by sbc100** [comment] 2021-06-18 23:22
I like that idea a lot.  We might still need to two different modes, one for emscripten-embedded and one for external/standalone usage.

**Comment by StarWitch** [comment] 2021-06-19 03:11
@kripken I'm willing to assist in any way I can to help things get more stable. Taisei's CI already tracks caching of specific versions of `emsdk`, so I can have it rigged to only notify when the version (or checkout hash with `tot`) changes and the build fails. This could also be separated out and run once a week on its own, not bound to our pushes to `master`, so it doesn't get spammy.  I can also have a `workflow_dispatch` section to manually run on specific versions if desired.

Hopefully we'll only need this for a couple of months until the problem areas are identified and fixed once and for all. Just let me know how you'd like it to be set up.

**Comment by kripken** [comment] 2021-06-21 22:33
@StarWitch Ok, that sounds worth trying. If you can get something set up that shows build errors on new emsdk `tot` builds, I can keep an eye on that, and let's see how that goes. If it prevents regressions that could be great. (I don't follow the part about once a week - the benefit, I think, would be from running it on the newest `tot` build constantly, to catch errors as soon as they happen.)

Meanwhile this specific issue will be fixed in #14501

**Closed** 2021-06-21 22:34 UTC

**Comment by StarWitch** [comment] 2021-06-22 16:20
@kripken Sounds good. How would you like to be notified of these failures, then?

**Comment by kripken** [comment] 2021-06-22 20:41
@StarWitch To keep it simple, if there's a page I can visit, I can do that once a day for a while to see how things go?

**Comment by StarWitch** [comment] 2021-07-02 16:55
@kripken Sorry for the wait, I was pretty busy during the month of June.

Here's the link to the workflow that performs a test build against `tot`. It's set to run with merges to our default branch, and once every Friday (in the case we don't merge any code during a given week): https://github.com/taisei-project/taisei/actions/workflows/emscripten-experimental.yml

As an aside, the bump from version `2.0.24` to `2.0.25` failed to compile with a new error, which required that we add `-s ALLOW_UNIMPLEMENTED_SYSCALLS=1`, as per this: https://github.com/emscripten-core/emscripten/pull/14491

**Comment by kripken** [comment] 2021-07-02 17:39
@StarWitch If it runs on merges to your default branch, does that mean it tests new changes to your code together with a new emscripten `tot` at the same time?

About `ALLOW_UNIMPLEMENTED_SYSCALLS`, that was indeed a breaking change in strict mode. Strict mode is expected to have such breakage from time to time, the same as building with all warnings as errors as compilers add new warnings. (If you prefer fewer such errors, perhaps avoid strict mode?)

**Comment by sbc100** [comment] 2021-07-02 17:42
As a followup to @kripken's comment about STRICT mode.   Another way to avoid those errors (aside from to remove STRICT or to add ALLOW_UNIMPLEMENTED_SYSCALLS) would be track down an remove the usage of the unimplemented syscalls within your codebase.  The code that is calling these syscalls is most likely not useful/usable under emscripten do if you want to reduce your codesize to a minimum you could modify it to avoid making those syscalls at all.   Not necessary but just FYI

**Comment by Akaricchi** [comment] 2021-07-02 19:38
> About `ALLOW_UNIMPLEMENTED_SYSCALLS`, that was indeed a breaking change in strict mode. Strict mode is expected to have such breakage from time to time, the same as building with all warnings as errors as compilers add new warnings. (If you prefer fewer such errors, perhaps avoid strict mode?)

IIRC I enabled strict mode because at the time, it also had some desirable effect on the generated code that wasn't available through other options… I really can't recall what it was, though. `'use string;'` in JS, perhaps? Either way, seems like that reason is no longer relevant, as STRICT seems to mostly act as a master switch for a bunch of options now. In that case it's indeed a good idea to drop it.

> As a followup to @kripken's comment about STRICT mode. Another way to avoid those errors (aside from to remove STRICT or to add ALLOW_UNIMPLEMENTED_SYSCALLS) would be track down an remove the usage of the unimplemented syscalls within your codebase. The code that is calling these syscalls is most likely not useful/usable under emscripten do if you want to reduce your codesize to a minimum you could modify it to avoid making those syscalls at all. Not necessary but just FYI

I have not tried to track it down yet, but I'm honestly at a loss at what could *possibly* reference `chroot`, of all things, in Taisei or any of its dependencies… just, what the hell?

**Comment by StarWitch** [comment] 2021-07-02 20:34
> @StarWitch If it runs on merges to your default branch, does that mean it tests new changes to your code together with a new emscripten `tot` at the same time?

Yes and no. We still have the two separate checks for Emscripten (for now), with one pinned to `2.0.25` and another running against `tot`. The one I linked only runs against `tot`, and will only run if the `main.yml` workflow succeeds - this way it won't run if we push something bad to `master`. 

Generally speaking, we do the standard feature branches/PR dance to make sure that `master` is always in a known-good state, and we run against `2.0.25` in every commit in a PR, as seen here: https://github.com/taisei-project/taisei/actions/runs/991259369

**Comment by sbc100** [comment] 2021-07-02 20:35
`STRICT` is a superset of a bunch of options that change over time: https://github.com/emscripten-core/emscripten/blob/dc2b03472093fd1a7a5b127e39af83253de061b9/src/settings.js#L1023-L1036

I would like to continue to recommend to those who want to get ahead of the changes we are planning enable by default in emscripten one day, but, as @kripken says, it will occasionally require a little extra work on upgrades.    Adding `ALLOW_UNIMPLEMENTED_SYSCALLS` in this case seems reasonable.

I'm not seeing any other reference to `chroot` here.. @Akaricchi where are you getting that info from?    If you want to track down where a given symbol reference is coming from you try, for example, `-Wl,--trace-symbols=chroot` and wasm-ld should tell you why its being included.

**Comment by kripken** [comment] 2021-07-13 18:26
Thanks @StarWitch , I think I understand. Ok, I'll try to check that CI once a day or so for a while, and see how that goes.

**Comment by kripken** [comment] 2021-12-09 15:49
I've been keeping an eye on a tab with that CI for five months now, and have not seen a single failure, so I think things are fairly stable? I'm going to close that tab, but please let me know if there is any breakage!

**Comment by StarWitch** [comment] 2021-12-10 20:32
The builds seem to have stabilized, yep. I'm going to run a build against the latest release tag of `emsdk` and let you know if there are any major issues.

Thank you for staying on top of this, it means a lot.

**Comment by StarWitch** [comment] 2021-12-15 16:09
Tested it with `3.0.0` and everything seems fine. Thank you for your support, and I'm glad things have settled down a bit.
