### ISSUE TITLE
EMSCRIPTEN_KEEPALIVE doesn't work with WebAssembly backend

### ISSUE THREAD

**Issue by Kagami** [emscripten-core/emscripten#6233] opened 2018-02-12 21:34 UTC
```
$ llc --version
LLVM (http://llvm.org/):
  LLVM version 7.0.0svn
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: sandybridge

  Registered Targets:
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

```
$ cat 1.c
#include <emscripten.h>
EMSCRIPTEN_KEEPALIVE int add(int a, int b) {
  return a + b;
}
```

```
$ emcc 1.c -s WASM=1 -O3 -o 1.js                                 
$ wasm-dis 1.wasm | grep export 
<nothing>
```

```
$ emcc 1.c -s WASM=1 -O3 -s "EXPORTED_FUNCTIONS=['_add']" -o 1.js
$ wasm-dis 1.wasm | grep export                                  
 (export "add" (func $0))
```

**Comment by kripken** [comment] 2018-02-12 21:46
Makes sense. How this works in asm.js and asm2wasm is the backend exports anything marked with llvm.used, and the EMSCRIPTEN_KEEPALIVE macro applies that attribute.

Does the wasm backend have a mechanism to say "export this"? If so the macro should use that.

**Comment by dschuff** [comment] 2018-02-13 00:26
What's the current difference between using `EMSCRIPTEN_KEEPALIVE` in the source vs exporting the function from the command line?

**Comment by kripken** [comment] 2018-02-13 00:37
No difference, both export the function and keep it alive (the two concepts are not really differentiated, there was a proposal a while back to allow keeping something alive without exporting it, but it didn't get traction).

**Comment by Kagami** [comment] 2018-02-13 13:51
WebAssembly studio [uses](https://github.com/wasdk/WebAssemblyStudio/blob/master/templates/empty_c/src/main.c)

```
#define WASM_EXPORT __attribute__((visibility("default")))
```

though I'm not sure how that works. cc @mbebenita

**Comment by Kagami** [comment] 2018-02-13 16:42
Seems like `EMCC_EXPERIMENTAL_USE_LLD=1` requires both visiblity attribute and `EXPORTED_FUNCTIONS`. Is this documented somewhere?

**Comment by Kagami** [comment] 2018-02-13 17:34
Created #6245 just in case.

**Comment by kripken** [comment] 2018-12-12 21:49
I ran into this again now (in  #7654). This is a big difference between the wasm backend and asm2wasm that feels like it should be a high priority to fix.

The issue is that if the user exports a function, we make sure it is kept alive through all optimizations. Users can export functions either using the EXPORTED_FUNCTIONS commandline option, or EMSCRIPTEN_KEEPALIVE in the source; in both cases the user is expressing a request to export the function so the user can call it later. They should be equivalent.

But in the wasm backend path, EMSCRIPTEN_KEEPALIVE just creates a wasm export for it, which metadce can eliminate. We need to not just create the export, but note that the user wants that function exported.

We can't do this in wasm-emscripten-finalize because it doesn't have the extra info - it just has a regular wasm export at that stage, the user's intention is lost by then. It seems like wasm-ld must be involved? cc @sbc100

**Comment by sbc100** [comment] 2018-12-12 22:33
This will hopefully be fixed once we figure out a way to preserve this attribute: https://github.com/WebAssembly/tool-conventions/issues/64

**Comment by dhdaines** [comment] 2022-04-26 14:48
This appears to still be broken, was it closed because of inactivity?  My emcc version:

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8 (3ff7eff373d31d8c0179895165462019221f192e)

**Comment by sbc100** [comment] 2022-04-26 15:28
I believe this is now working.    The actual export from the wasm module will be minified, but Module['_add'] will get bound to it correctly.

I just verified this using the above example:

```
$ ./emcc 1.c -s WASM=1 -O3 -o 1.js
$ wasm2wat 1.wasm | grep export 
  (export "a" (memory 0))
  (export "b" (func 0))
  (export "c" (func 1))
  (export "d" (table 0)))
$ clang-format 1.js  > formatted.js
$ grep -C2 _add formatted.js 
var _add = Module["_add"] =
    function() { return (_add = Module["_add"] = Module["asm"]["c"]).apply(null, arguments) };
```

Here you can see Module['_add'] getting  bound the export `c` from the wasm module.  The `_add` export on the wasm moudle was minified to `c` to reduce the size of the wasm and JS files, but the function is preserved and exported.

So I think this issue can be closed.

**Comment by dhdaines** [comment] 2022-04-27 01:45
Ah, actually my use case is a bit more complicated.  I am linking with a static library. The exported functions with EMSCRIPTEN_KEEPALIVE that are in the .a file are being removed from the wasm, while the ones in separate .o or .c files in the final link command are being kept alive.  You can see this by changing the example above to compile 1.c into a static library and then linking it (it doesn't really matter what's in 2.c):

```
$ emcc -c 1.c
$ emcc -c 2.c
$ emar rcs lib1.a 1.o
$ emcc lib1.a 2.o -s WASM=1 -o 1a.js
$ emcc 1.o 2.o -s WASM=1 -o 1c.js
$ wasm-dis 1a.wasm  | grep "export.*add"
$ wasm-dis 1c.wasm  | grep "export.*add"
 (export "add" (func $1))
```

**Comment by sbc100** [comment] 2022-04-27 18:33
Ah yes, that is an artifact of how `.a` archives work.  Symbols that live in `.a` archives are only included if some symbol from the object file is needed by the linker, otherwise the entire `.o` file will not be included.

So in this case you would either need to:

1. Include the object file in question by referencing a symbol from it in your build
2. Use `--whole-archive`/ `--no-whole-archive` around the library to force the linker to include all objects.
3. Use a command line flag just as `-u` or `-sEXPORTED_FUNCTIONS` to explicitly pull in the symbol from the command line.

**Comment by dhdaines** [comment] 2022-04-27 18:47
Ah, thank you for the explanation - I hadn't thought of that.  Presumably, the linker is only able to see symbols referenced from C code and not from --pre-js / --post-js?  In any case it seems that maybe there isn't so much a bug here as a somewhat surprising behaviour that should just be documented somewhere - as you just did :)

I will try --whole-archive since presumably dead code optimization will still get run afterwards.

**Comment by sbc100** [comment] 2022-04-27 18:49
yes even with `--whole-archive/--no-whole-archive` you will still get DCE and only the needed symbols will be included.  The main differences is when object files that contain static constructors and/or EMSCRIPTEN_KEEPALIVE and/or `attribute(used)`

**Closed by sbc100** 2022-04-27 18:49 UTC
Labels: help wanted

**Comment by kg** [comment] 2022-10-11 21:26
Not sure if it is appropriate to comment this here, but you should really think about updating EMSCRIPTEN_KEEPALIVE with `__attribute__(retain)` in addition to `used`, otherwise various functions will get silently stripped out by the linker. It's awkward and mysterious to have to do

```
#undef EMSCRIPTEN_KEEPALIVE
#define EMSCRIPTEN_KEEPALIVE __attribute__((used)) __attribute((retain))
```

to avoid getting mystery runtime errors.

**Comment by sbc100** [comment] 2022-10-11 21:54
Are you sure `__attribute__((used))` is not enough?    The linker should never strip a symbol that is build with `__attribute__((used))`.  

Are you building with the emscripten triple?   There is a slight difference between the emscripten triple and other triples in this respect:   https://github.com/llvm/llvm-project/blob/60e4af7ab8e64cec3c55e927a72cb06de0bb0c79/llvm/lib/MC/WasmObjectWriter.cpp#L1790-L1795

I've honestly never header of `retain` but I don't think that attribute makes it as far as the object format (or the linker).  Can you give an example of where you have found it useful/needed?

**Comment by kg** [comment] 2022-10-11 22:17
I moved some working code out of a .c file that had cross dependencies with other .c files in the application, into a new .c file. I confirmed that emscripten.h was being included and that the code was being built (`#error` would fail the build, etc) and that I was using `EMSCRIPTEN_KEEPALIVE`, and I hadn't changed any code, just moved it. At runtime post-build, cwrap was not returning a `Function` for the C functions I had moved. There was nothing special about their signatures.

Adding `retain` as above fixed it instantly. From the clang documentation I looked at, what that attribute does is prevent linker GC. I think what happened is that since the new .c file had no internal dependencies and was only exporting C functions to be used by JS, the linker GCd all the "unused" functions. I think if the user has `EMSCRIPTEN_KEEPALIVE`d some code, it never makes sense for the linker to remove it.

**Comment by sbc100** [comment] 2022-10-11 22:25
Yes `EMSCRIPTEN_KEEPALIVE` should prevent the linker from GC'ing the function (because it actually exports it.. so it is used in that sense).

What I'm confused about is how `retain` could possibly have worked, since IIUC that is an ELF-only attribute and completely ignored by the wasm object format (its not part of the format at all).   Are you you you didn't change something else as well as adding retain? 

The only time `EMSCRIPTEN_KEEPALIVE` cannot work is when the object file is not loaded out of the an ar archive file.  But in that case there is no attribute that would help since the object file not being read at all (and therefore no symbol attributes are read).  The only solution that problem is to use something like `-Wl,--whole-archive`.. or to explicitly export the symbol on the command line.

If you are sure that `retain` did have the effect you say it did then my only guess would be that something is happening in LTO maybe?  Where you using lto object files when you saw this effect?

**Comment by kg** [comment] 2022-10-11 22:34
I'll do some more experimenting and see if I can figure out what's going on here if retain shouldn't be working and let you know if I figure it out, thanks.

**Comment by kg** [comment] 2022-10-12 22:55
Yeah, it turns out a change I previously failed to hit ctrl+s on was responsible here, and retain doesn't work for wasm like you said even though the docs suggest it will. There doesn't appear to be a way to make `EMSCRIPTEN_KEEPALIVE` do what it would ideally do here, so you have to manually create a cross-file dependency. Oh well :( Sorry for wasting your time!

**Comment by sbc100** [comment] 2022-10-12 23:29
Is that the problem that the object file in question is in a `.a` archive and not otherwise referenced?

**Comment by kg** [comment] 2022-10-12 23:37
The file wasn't otherwise referenced, yeah, and there are .a archives involved in our build pipeline so I'm pretty sure it's in one. I don't think it's realistic for me to change our compiler settings to work around it, I suspect it would make our binaries bigger. In this case at least it wasn't too nasty to move code around to keep the file referenced in the right circumstances.

It might be worth updating the [documentation](https://emscripten.org/docs/api_reference/emscripten.h.html#c.EMSCRIPTEN_KEEPALIVE) to mention this limitation to how it works, but I don't know how common it actually is for people to hit this problem.
