### ISSUE TITLE
Does upstream LLVM backend support C++ exceptions?

### ISSUE THREAD

**Issue by forderud** [emscripten-core/emscripten#9533] opened 2019-09-28 20:28 UTC
Apologies for posting a newbie question, but I'm struggling to make C++ exceptions work after switching to the "upstream" LLVM backend. I've already registered an issue on https://github.com/trzecieu/emscripten-docker/issues/50, but was then asked to contact Emscripten directly.

Are there any known issues or limitations related to C++ exceptions in the "upstream" backend?

**Comment by kripken** [comment] 2019-09-28 20:36
There are no known limitations there, no - all our C++ exceptions tests pass with the upstream backend, and there are no open issues.

Do you have a testcase I can take a look at?

**Comment by forderud** [comment] 2019-09-28 20:41
Thanks for your quick response @kripken . Then it's likely something wrong with my build setup.

Closing this issue now. Will create a new issue if my problem persist after examining my build setup and I need to come back with a reproducer.

**Comment by Krelborn** [comment] 2019-11-08 10:43
@forderud did you figure out what the problem was? I've got exactly the same problem after switching to the upstream compiler. So far I've not been able to put together a reproducible test case outside of our code base.

**Comment by forderud** [comment] 2019-11-08 10:51
No, I'm still struggling with the same problem. My work-around so far have been to tweak my code base to _almost_ no longer rely on exceptions. This works fine for prototyping, but will not be viable for a final release.

**Comment by Krelborn** [comment] 2019-11-08 11:01
OK good to know I'm not the only one. I have a large legacy codebase so not having exception handling is definitely out of the question. Will investigate some more and post if I get anywhere.

**Comment by forderud** [comment] 2019-11-08 11:40
Reopening the issue, since no longer appear to be a local problem.

**Comment by kripken** [comment] 2019-11-08 18:29
One possible issue is that codegen in the wasm backend is during compile time, see the codegen and exceptions section in these docs (fairly new, sorry it wasn't documented before!),

https://emscripten.org/docs/compiling/WebAssembly.html?highlight=disable_exception_catching#backends

**Comment by Krelborn** [comment] 2019-11-11 09:16
That was the issue. Turning on exception catching for the compile stage of our build fixes the issue.

That said, I'm seeing new problems in both our WASM and ASM.JS build products, so we're not quite there yet. Currently tweaking the compiler settings further to see if I can figure out what's going on.

**Comment by VirtualTim** [comment] 2020-01-30 04:10
Sounds like the issue was resolved by the comment by kripken. Closing.

**Closed by VirtualTim** 2020-01-30 04:10 UTC
