### ISSUE TITLE
Compilation error with -sUSE_SDL_TTF=2 and -fwasm-exceptions

### ISSUE THREAD

**Issue by lingyuncai** [emscripten-core/emscripten#20214] opened 2023-09-08 09:40 UTC
**Version of emscripten/emsdk:**
3.1.44

**Failing command line in full:**
`emcc test_sdl_ttf.cpp -sUSE_SDL=2 -sUSE_SDL_TTF=2 -fwasm-exceptions --embed-file LiberationSansBold.ttf -o index.html`

The above command would run successfully without `-fwasm-exceptions` option.

**Full link command and output with `-v` appended:**

```bash
ports:INFO: retrieving port: sdl2_ttf from https://github.com/libsdl-org/SDL_ttf/archive/release-2.20.2.zip
ports:INFO: unpacking port: sdl2_ttf
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libSDL2_ttf.a... (this will be cached in "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2_ttf.a" for subsequent builds)
 "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc" -c /home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/cache/ports/sdl2_ttf/SDL_ttf-release-2.20.2/SDL_ttf.c -o /home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/cache/ports-builds/sdl2_ttf/SDL_ttf.c.o -g -sSTRICT -Werror -O2 -I/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/cache/ports/sdl2_ttf/SDL_ttf-release-2.20.2 -DTTF_USE_HARFBUZZ=1 -sUSE_SDL=2 -sUSE_FREETYPE -sUSE_HARFBUZZ
Traceback (most recent call last):
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc.py", line 4437, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc.py", line 4430, in main
    ret = run(args)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc.py", line 1287, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc.py", line 3091, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc.py", line 3069, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc.py", line 3003, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc.py", line 1024, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/tools/ports/__init__.py", line 419, in add_cflags
    port.get(Ports, settings, shared)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/tools/ports/freetype.py", line 111, in get
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/tools/cache.py", line 139, in get_lib
    return get(name, *args, **kwargs)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/tools/cache.py", line 157, in get
    with lock(shortname):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/tools/cache.py", line 61, in lock
    acquire_cache_lock(reason)
  File "/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libfreetype.a)
emcc: error: Subprocess 1/1 failed (returned 1)! (cmdline: /home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/emcc -c /home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/cache/ports/sdl2_ttf/SDL_ttf-release-2.20.2/SDL_ttf.c -o /home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/cache/ports-builds/sdl2_ttf/SDL_ttf.c.o -g -sSTRICT -Werror -O2 -I/home/lingyuncai/work/wasm-study/emsdk-3.1.44/upstream/emscripten/cache/ports/sdl2_ttf/SDL_ttf-release-2.20.2 -DTTF_USE_HARFBUZZ=1 -sUSE_SDL=2 -sUSE_FREETYPE -sUSE_HARFBUZZ)

```

## Note.
- When compiling sdl2_ttf library, it tries to get `libfreetype.a` instead of `libfreetype-wasm-sjlj.a` that was built.
- This issue happened at a clean cache environment - no `cache` folder under `emsdk/upstream/emscripten` or no `libfreetype.a` file was generated previously.
- The test file is as below.
```cpp
// test_sdl_ttf.cpp
// This is modified from test/browser/test_sdl_ttf.c file

#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <cstdlib>
#include <iostream>
#include <stdexcept>

SDL_Window *window;
SDL_Renderer *renderer;
TTF_Font *font;

using namespace std;

void render()
{
    static SDL_Color colorA = { 0xff, 0x99, 0x00, 0xff };
    static SDL_Color colorB = { 0x11, 0xff, 0xff, 0xff };
    static SDL_Rect upperRect = {0, 0, 640, 240};
    static SDL_Rect lowerRect = {0, 240, 640, 240};

    SDL_Surface *helloSurface = TTF_RenderText_Shaded(font, "hello", colorA, colorB);
    SDL_Surface *worldSurface = TTF_RenderText_Shaded(font, "world", colorB, colorA);
    SDL_Texture *helloTexture = SDL_CreateTextureFromSurface(renderer, helloSurface);
    SDL_Texture *worldTexture = SDL_CreateTextureFromSurface(renderer, worldSurface);

    SDL_SetRenderDrawColor(renderer, 0xcc, 0xcc, 0xcc, 0xff);
    SDL_RenderClear(renderer);
    SDL_RenderCopy(renderer, helloTexture, NULL, &upperRect);
    SDL_RenderCopy(renderer, worldTexture, NULL, &lowerRect);
    SDL_RenderPresent(renderer);

    SDL_FreeSurface(helloSurface);
    SDL_FreeSurface(worldSurface);
    SDL_DestroyTexture(helloTexture);
    SDL_DestroyTexture(worldTexture);
}

int main()
{
    SDL_Init(SDL_INIT_VIDEO);
    TTF_Init();
    SDL_CreateWindowAndRenderer(640, 480, 0, &window, &renderer);
    font = TTF_OpenFont("LiberationSansBold.ttf", 40);
    if (font == nullptr) {
        throw runtime_error("TTF_OpenFont: " + string(TTF_GetError()));
    }
    render();
}
```

**Comment by sbc100** [comment] 2023-09-08 19:27
I think this is a duplicate of #20204

**Comment by hedwigz** [comment] 2023-09-08 20:37
Interesting 🤔

**Comment by sbc100** [comment] 2023-11-10 21:34
Closing as duplicate of #20204

**Closed by sbc100** 2023-11-10 21:34 UTC
