### ISSUE TITLE
console.log message are lost when running with node + pthreads

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#14804] opened 2021-08-05 00:58 UTC
I noticed this when running in PROXY_TO_PTHREAD mode.   If I use printf(), I see all my message... if I use `console.log` (or `out`) I only see the very first of the log messages.

**Comment by juj** [comment] 2021-08-05 13:18
Hmm, console.log()s should always come through, unless the main thread is blocked/hung(?). Not quite sure about `out()`.

We used to have a manual postMessage-based console.log override to avoid an old SAB-based deadlock "bug" (a non-specced behavior of forward progress interaction between browser APIs and SAB locking that used to be non-observable before SAB) in Firefox and Edge, but I don't think that has existed in a long time.

**Comment by juj** [comment] 2021-08-05 15:26
Maybe the issue is due to this? https://github.com/emscripten-core/emscripten/blob/d35de0bf3572dfe9759ac3c7e56b9ce5983f68ac/src/worker.js#L77

**Comment by sbc100** [comment] 2021-08-05 16:40
> Hmm, console.log()s should always come through, unless the main thread is blocked/hung(?). Not quite sure about `out()`.
> 
> We used to have a manual postMessage-based console.log override to avoid an old SAB-based deadlock "bug" (a non-specced behavior of forward progress interaction between browser APIs and SAB locking that used to be non-observable before SAB) in Firefox and Edge, but I don't think that has existed in a long time.

This issue I think might be something specific to the way node does workers.

**Comment by sbc100** [comment] 2021-08-05 16:42
> Maybe the issue is due to this?
> 
> https://github.com/emscripten-core/emscripten/blob/d35de0bf3572dfe9759ac3c7e56b9ce5983f68ac/src/worker.js#L77

I saw that too, but no, this relates to code in the module itself, not in worker.js.   It also applies equally to `out` and `console.log`.. which makes me think it specific to how node worker use the console.   

I will confirm whether this issue is specific to node.   I think it is.

**Comment by kripken** [comment] 2021-11-25 00:13
Reopening as this is not actually fixed, just worked around.

Looking into this, if I build this:
```cpp
#include <emscripten.h>
int main() {
  EM_ASM({
    console.log("test");
    console.log("test");
    console.log("test1");
    console.log("test2");
    console.log("test3");
  });
}
```
with `./emcc a.cpp -pthread -s PROXY_TO_PTHREAD  -O3 --profiling -s EXIT_RUNTIME` then I can see the problem: it prints out "test" once and that's it. However:
* If I remove EXIT_RUNTIME then it logs out everything (and then hangs since we don't exit).
* If I use ASYNCIFY and add `emscripten_sleep(0)` then I do get more logging, and also proper exiting.

My conclusion from the above is that node proxies `console.log` in a way that requires us to return to the main event loop for it to work reliably. If we exit the thread and shut down then we never really return to the main event loop, except very briefly, and that's apparently not enough - node doesn't wait for any pending messages to get through before it quits.

Complicating this is the fact that node **does** always log out the first `console.log`. I wonder if they have some kind of special-casing there, either literally of `console.log` (i.e., having a special buffer for a single logging that doesn't go through the usual mechanism - nice for debugging) or of messages (i.e., maybe they do handle at least the first pending message from a worker before shutting down - maybe necessary for some internal reason).

Given this, there are possible workarounds. We could add a turn of the event loop during shutdown, say by wrapping `exit()` in a setTimeout. I also experimenting with proxying `exit` to the main thread. These methods make the logging seem to work, but I'm not sure it's deterministic. In any case they have downsides, so I'm not sure we should consider them.

I opened a node.js issue here: https://github.com/nodejs/node/issues/40961 Hopefully they will have more info.

**Comment by kripken** [comment] 2021-11-29 21:00
A possible workaround mentioned there is not calling `exit` on workers, but leaving it to the main thread. As mentioned in the last comment I experimented with that but was unsure if it made sense. But maybe it does actually. To do it, we can't proxy synchronously to the main thread, though (as it would block the logging messages), so we'd need to send an async message to exit, and meanwhile stop running code in the worker, I guess by throwing the exception to unwind the call stack + marking the ABORT variable. That could be worth experimenting with.

**Comment by sbc100** [comment] 2023-05-24 23:12
The code in the above comment now seems to print all the messages.. so I guess this has been fixed somehow and we can close this once again?

**Comment by kripken** [comment] 2023-05-24 23:29
I tested and this remains broken in node 14 but is fixed in node 15+. The node.js issue however remains open, and the reduced testcase there still fails... so it seems some combination of a fix in node + a change over here is what works around the problem...

**Closed by kripken** 2023-05-24 23:29 UTC

**Comment by sbc100** [comment] 2025-05-15 22:25
FWIW, the reduced test code is now fixed in node v24.  But I think we should keep out workaround in place for a while longer.
