### ISSUE TITLE
Interesting code generated for 8 bit stuff

### ISSUE THREAD

**Issue by waywardmonkeys** [emscripten-core/emscripten#3231] opened 2015-03-06 07:59 UTC
I noticed that our code base has 375 instances of this construct: `someVar << 24 >> 24`

That seemed interesting to me, so I took a particularly interesting case:

``` javascript
  while (1) {
   $50 = $51;
   $52 = HEAP8[$50 >> 0] | 0;
   if (!($52 << 24 >> 24 == 9 | $52 << 24 >> 24 == 13 | $52 << 24 >> 24 == 10 | $52 << 24 >> 24 == 32)) break;
   $51 = $50 + 1 | 0;
  }
```

That comes from this LLVM code:

``` llvm
  %48 = phi i32 [ %52, %.critedge.i3 ], [ %46, %44 ]
  %49 = inttoptr i32 %48 to i8*
  %50 = load i8* %49, align 1, !tbaa !21
  switch i8 %50, label %_ZN9rapidjson14SkipWhitespaceINS_19GenericStringStreamINS_4UTF8IcEEEEEEvRT_.exit4 [
    i8 32, label %.critedge.i3
    i8 10, label %.critedge.i3
    i8 13, label %.critedge.i3
    i8 9, label %.critedge.i3
  ]
```

Which comes from this C++:

``` c++
    while (s.Peek() == ' ' || s.Peek() == '\n' || s.Peek() == '\r' || s.Peek() == '\t')
        s.Take();
```

I don't understand why the `<< 24 >> 24` is needed in this case. We're loading from HEAP8, so we already know that it is an 8 bit value.  Also, if that was needed, why does that have to happen 4 times?

Here are some of the other lines in our generated JS where this happens:

``` js
     if ($30 << 24 >> 24 != $31 << 24 >> 24) break;
   if ($66 << 24 >> 24 != $67 << 24 >> 24) break;
      if ($30 << 24 >> 24 != $31 << 24 >> 24) break;
     if ($66 << 24 >> 24 != $67 << 24 >> 24) break;
     if ($34 << 24 >> 24 != $35 << 24 >> 24) break;
     if ($62 << 24 >> 24 != $63 << 24 >> 24) break;
    if ($29 << 24 >> 24 != $30 << 24 >> 24) break;
    if ($57 << 24 >> 24 != $58 << 24 >> 24) break;
      if ($30 << 24 >> 24 != $31 << 24 >> 24) break;
     if ($66 << 24 >> 24 != $67 << 24 >> 24) break;
   HEAP32[$arg >> 2] = ($38 & 255) << 24 >> 24;
   HEAP32[$arg + 4 >> 2] = ((($38 & 255) << 24 >> 24 | 0) < 0) << 31 >> 31;
        if ((HEAP8[$$014$i$i$i >> 0] | 0) == $69 << 24 >> 24) {
  if (!($16 << 24 >> 24 == 9 | $16 << 24 >> 24 == 13 | $16 << 24 >> 24 == 10 | $16 << 24 >> 24 == 32)) break;
   if (!($34 << 24 >> 24 == 9 | $34 << 24 >> 24 == 13 | $34 << 24 >> 24 == 10 | $34 << 24 >> 24 == 32)) break;
   if (!($52 << 24 >> 24 == 9 | $52 << 24 >> 24 == 13 | $52 << 24 >> 24 == 10 | $52 << 24 >> 24 == 32)) break;
    if ($29 << 24 >> 24 != $30 << 24 >> 24) break;
   if ($14 << 24 >> 24 == 32) {
   if ((($14 << 24 >> 24) + -9 | 0) >>> 0 < 5) {
    if ($26 << 24 >> 24 == 32) $56 = $32; else if ((($26 << 24 >> 24) + -9 | 0) >>> 0 < 5) $56 = $32; else {
     if ($27 << 24 >> 24 != $28 << 24 >> 24) break;
   if ((HEAP8[$s$013 >> 0] | 0) == ($c & 255) << 24 >> 24) {
 L6 : do if ((label | 0) == 5) if ($$lcssa) if ((HEAP8[$s$0$lcssa >> 0] | 0) == ($c & 255) << 24 >> 24) {
    if ((HEAP8[$s$13 >> 0] | 0) == ($c & 255) << 24 >> 24) {
 if (!($typeCount << 24 >> 24)) {
  $19 = $18 << 24 >> 24 != 0;
  $19 = $18 << 24 >> 24 != 0;
 $19 = $18 << 24 >> 24 != 0;
    if ($31 << 24 >> 24 != $32 << 24 >> 24) break;
     if ($35) if ((HEAP8[$35 + 17 >> 0] | 0) == $attributeType << 24 >> 24) break L2;
 if ($14 << 24 >> 24 != 0 | ($0 | 0) == 0) {
  $25 = $24 << 24 >> 24 == 0;
 $25 = $24 << 24 >> 24 == 0;
  $13 = ($10 << 24 >> 24) + ($codepoint$09 << 4) | 0;
  do if (($10 + -48 << 24 >> 24 & 255) < 10) $codepoint$1 = $13 + -48 | 0; else {
   if (($10 + -65 << 24 >> 24 & 255) < 6) {
   if (($10 + -97 << 24 >> 24 & 255) >= 6) {
   if ($25 << 24 >> 24 != $26 << 24 >> 24) break;
   if ($15 << 24 >> 24 != $16 << 24 >> 24) break;
  if ($0 << 24 >> 24 == 32) {
   if ((($0 << 24 >> 24) + -9 | 0) >>> 0 < 5) {
 if (($0 << 24 >> 24 | 0) == 43) {
 } else if (($0 << 24 >> 24 | 0) == 45) {
 if ((($8 << 24 >> 24) + -48 | 0) >>> 0 < 10) {
   $15 = ($n$03 * 10 | 0) + 48 - ($14 << 24 >> 24) | 0;
   if ((($14 << 24 >> 24) + -48 | 0) >>> 0 >= 10) {
  if ($8 << 24 >> 24 == 2) {
  if (!($8 << 24 >> 24)) {
  } else if ($8 << 24 >> 24 != 1) {
  $$count$0 = ((HEAP8[(HEAP32[$6 >> 2] | 0) + 48 >> 0] | 0) == $role << 24 >> 24 & 1) + $count$01 | 0;
```

**Comment by waywardmonkeys** [comment] 2015-03-06 08:09
There's some missing constant folding too ...

````js
   if (($10 + -65 << 24 >> 24 & 255) < 6) {
   if (($10 + -97 << 24 >> 24 & 255) >= 6) {
````

**Comment by waywardmonkeys** [comment] 2015-03-06 08:09
cc: @chadaustin

**Comment by waywardmonkeys** [comment] 2015-03-06 09:35
This doesn't just happen with ``24``:

````js
      $187 = _i64Add($184 | 0, (($184 | 0) < 0) << 31 >> 31 | 0, $178 | 0, tempRet0 | 0) | 0;
````

and:

````
 if ($28 << 16 >> 16 != 200) {
````

but those are much less common ...

**Comment by waywardmonkeys** [comment] 2015-03-06 09:39
One of the cases with ``16`` is this in LLVM IR:

````llvm
  %230 = call zeroext i16 @_ZNK9northstar14VertexIterator13getBoneWeightEj(%"class.northstar::VertexIterator"* %vertexIterator, i32 %boneSlotIndex.01.i) #32
  %231 = icmp eq i16 %230, 0
````

**Comment by kripken** [comment] 2015-03-09 18:01
`x << 24 >> 24` is a sign extend of an 8-bit value to 32-bit. The same with 31 is a sign extend of a boolean, etc.

Can you perhaps make a standalone C testcase? Would help to figure this out.

Meanwhile, my first guess is that the switch code needs 32-bit ints, so it sign-extends the input, but not in a way that does it only once and stores to a temp variable. But that seems odd. Another possibility is that this is the result of  the aggressive eliminator, which will happily produce such repeated code, in order to avoid temporary variables.

**Comment by sunfishcode** [comment] 2015-03-09 23:45
Standalone C++ testcase for the switch problem:

```
#include <stdio.h>
signed char buffer[2300];
int main(int argc, char *argv[])
{
    if (buffer[argc] == ' ' || buffer[argc] == '\n' || buffer[argc] == '\r' || buffer[argc] == '\t')
           printf("hello whitespace\n");
}
```

The problem is in fastcomp. fastcomp's code for switches calls getValueAsCastParenStr for each case when !UseSwitch.

**Comment by kripken** [comment] 2015-03-10 01:04
I see, thanks. Ok, sounds like the solution for the switch issue could be a pass that moves all switches to be on i32s, by extending i1, i8 and i16 values to that.

I wonder though how useful it would be. The main problem is only when the switch is implemented using ifs, which is when LLVM tells us "switch" but we decide "nah" (because it's small, or sparse). This is likely rare.

**Comment by sunfishcode** [comment] 2015-03-10 03:11
I'm testing https://github.com/sunfishcode/emscripten/commit/aab7a8fdc12b02f9b66ed92261fe45952759ea70 to catch the << 24 >> 24 & 255 case.

**Comment by sunfishcode** [comment] 2015-03-11 00:06
This patch is now checked into incoming.

**Closed** 2019-09-07 05:40 UTC
Labels: fastcomp, performance, wontfix
