### ISSUE TITLE
Bug report: Streaming Download in Fetch API does not match its define in document

### ISSUE THREAD

**Issue by michaelkyang** [emscripten-core/emscripten#6013] opened 2018-01-02 09:01 UTC
Hi 

I try to use EMSCRIPTEN_FETCH_STREAM_DATA but found this issue.
fetch->numBytes equals to zero in progress cb and memory increase continuously always.
That does not follow chunk download purpose of  EMSCRIPTEN_FETCH_STREAM_DATA.
Please fix it.
__________________________________________________________________________
If the application does not need random seek access to the file, but is able to process the file in a streaming manner, it can use the EMSCRIPTEN_FETCH_STREAM_DATA flag to stream through the bytes in the file as they are downloaded. If this flag is passed, the **downloaded data chunks** are passed into the onprogress() callback in coherent file sequential order. See the following snippet for an example.

```cpp
void downloadProgress(emscripten_fetch_t *fetch) {
  printf("Downloading %s.. %.2f%%s complete. HTTP readyState: %d. HTTP status: %d.\n"
    "HTTP statusText: %s. Received chunk [%llu, %llu[\n",
    fetch->url, fetch->totalBytes > 0 ? (fetch->dataOffset + fetch->numBytes) * 100.0 / fetch->totalBytes : (fetch->dataOffset + fetch->numBytes),
    fetch->totalBytes > 0 ? "%" : " bytes",
    fetch->readyState, fetch->status, fetch->statusText,
    fetch->dataOffset, fetch->dataOffset + fetch->numBytes);

  // Process the partial data stream fetch->data[0] thru fetch->data[fetch->numBytes-1]
  // This buffer represents the file at offset fetch->dataOffset.
  for(size_t i = 0; i < fetch->numBytes **( always 0 )** ; ++i)
    ; // Process fetch->data[i];
}

int main() {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);
  strcpy(attr.requestMethod, "GET");
  **attr.attributes = EMSCRIPTEN_FETCH_STREAM_DATA;**
  attr.onsuccess = downloadSucceeded;
  attr.onprogress = downloadProgress;
  attr.onerror = downloadFailed;
  attr.timeoutMSecs = 2*60;
  emscripten_fetch(&attr, "myfile.dat");
}
```

**Comment by juj** [comment] 2018-01-03 12:38
There exists a test `browser.test_fetch_stream_file` in https://github.com/kripken/emscripten/blob/incoming/tests/fetch/stream_file.cpp that tests the behavior. Running that locally passes for me, and seems to be getting the bytes in chunks. That one uses

```
attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY | EMSCRIPTEN_FETCH_APPEND | EMSCRIPTEN_FETCH_STREAM_DATA;
```

does that work?

**Comment by froydnj** [comment] 2018-02-06 19:45
@michaelkyang Does @juj's suggestion work?

@juj, would it be reasonable to change [the example](http://kripken.github.io/emscripten-site/docs/api_reference/fetch.html#streaming-downloads) in the docs to more closely resemble `test_fetch_stream_file`?

**Comment by juj** [comment] 2018-02-09 11:02
> @juj, would it be reasonable to change the example in the docs to more closely resemble test_fetch_stream_file?

Yeah, I think we should change the docs from `attr.attributes = EMSCRIPTEN_FETCH_STREAM_DATA;` to `attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY | EMSCRIPTEN_FETCH_APPEND | EMSCRIPTEN_FETCH_STREAM_DATA;` on this one, though would be good to hear from @michaelkyang if that works for him?

The intent with these multiple flags is that one could either stream to memory or stream to IndexedDB, or "stream to void" just to upload, or to perform some other side effect on a remote web server.

**Comment by michaelkyang** [comment] 2018-02-22 07:48
@juj Thank you for the suggestion. I have tried steam_file.cpp in tests_set and still failed to get a nonzero value for fetch->numBytes in onprogress( ). I wonder how did you pass this test on your side.
Is there anything related with server setting such as server must be able to accept ByteRange request or other else?

BTW: I would like to use this API to streaming data like libcurl.  Processing fetch->numBytes data in onprogress( ) and then discard them.

**Comment by juj** [comment] 2018-02-22 14:35
> I wonder how did you pass this test on your side.

I'm running the test with `python tests/runner.py browser.test_fetch_stream_file` in the Emscripten root directory. Running that test prints for me

```
Downloading.. 0.10% complete. Received chunk [0, 131072[
Downloading.. 9.08% complete. Received chunk [131072, 12189696[
Downloading.. 26.89% complete. Received chunk [12189696, 36085760[
Downloading.. 100.00% complete. Received chunk [36085760, 134217728[
Finished downloading 134217728 bytes
Data checksum: A7F8E858
```

**Comment by juj** [comment] 2018-02-22 14:36
> Is there anything related with server setting such as server must be able to accept ByteRange request or other else?

No, the request is done in full, without byte range requests necessary. If one wants to do range requests, those can be done manually by setting the request headers.

**Comment by michaelkyang** [comment] 2018-02-23 02:45
I can get your result only with Firefox 58.0.2 on Win7, but still failed
with Chrome Version 64.0.3282.186 (Official Build) (64-bit)  on Win7.
Does FETCH APIs for streaming have different performance in different
browser or platform?

2018-02-22 22:35 GMT+08:00 juj <notifications@github.com>:

**Comment by VirtualTim** [comment] 2019-05-16 03:02
Dupe of #7090.

**Closed** 2020-05-22 05:44 UTC
Labels: wontfix
