### ISSUE TITLE
Wide character support in emscripten

### ISSUE THREAD

**Issue by TZBH** [emscripten-core/emscripten#6427] opened 2018-04-05 10:57 UTC
I'm new to emscripten, so maybe I'm not getting something, but:
I understand JavaScript uses 16bit unsigned integers to represent characters, C++ supports wide characters (whether Windows flavour - 16bit or Unix - 32 bit), while emscripten seems to use utf8 by default.
This looks to be inconvenient/inefficient (conversion and copy is required rather than just copy), especially that string manipulations on C++ side would typically require conversion to wchar_t/wstring anyway.
Is there any easy way to configure emscripten/webidl to generate glue using 16 bit wchar_t instead of using utf8?

I understand wchar_t in emscripten defaults to 32 bit, but it can be changed to 16 bit by using EMMAKEN_CFLAGS=-fshort-wchar.
How do I build emscripten using this setting? Setting this for the project only will not link as the code will have different wchar_t definition than the libraries.

**Comment by curiousdannii** [comment] 2018-04-06 01:18
Your C++ can use `char32_t` and then when you want to get text out of the compiled code into JS you can use [`UTF32ToString`](http://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html#UTF32ToString). If you need to send a string to the compiled code, use `stringToUTF32`.

**Comment by TZBH** [comment] 2018-04-08 08:14
Thanks for your reply.

I know I can do it manually, I can even change the whole glue code or use my own.
But first I'd rather concentrate on functionality of my code and use what’s available (provided it can do what I need) at this stage and second I’d like to understand what's the reason behind using utf8.

Thus I’m looking for an explanation and info if this can be configured/modified easily in a way that would let me take advantage of future updates without redoing most of the work each time new version is released.

BTW. I'm not planning to use embind. I understand embind and WebIDL are equivalent and I find WebIDL approach much cleaner.

**Comment by aheejin** [comment] 2018-04-08 09:01
If you want to build your program using `-fshort-wchar`, the problem is all of libraries have to be built with the same flag, which can be done by modifying emscripten scripts and rebuild all the libraries but I don't think you can do it with a single flag. See comments in #6336.

**Comment by TZBH** [comment] 2018-04-08 10:16
I tried doing it. I've added CFLAGS += -fshort-wchar in config.mak and run embulider.py build all, but it still did not want to link.

**Comment by juj** [comment] 2018-04-08 13:36
> I understand JavaScript uses 16bit unsigned integers to represent characters

This is true, JavaScript strings are encoded with UTF16-LE. (little endian)

> C++ supports wide characters (whether Windows flavour - 16bit or Unix - 32 bit)

This is true, though perhaps a slight bit ambiguous. C++ standard supports wide characters, and in Emscripten by default, wide characters are 32-bit in size, just like in GCC and Clang. However the bitness does not yet state the encoding, i.e. because wide strings by default compile to 32-bit, it does not yet specify what the encoding of these strings would have to be. `std::wstring` does not much care, it is just 32-bit character units. When compiling with `-fshort-wchar`, the units in `std::wstring` are then instead 16-bit character units, but C++ standard does not say what the encoding would be.

When one prints to console with `wprintf` or `std::wcout`, that is when one cares, and the semantic is then defined by the currently set locale for wide characters and not a C/C++ spec. This locale is set in the environment variable `LC_UNI_CTYPE`. Though I believe libstdc++ may be ignoring this at present, and just assume that when printing with 32-bit wide strings, they must be UTF32-LE, and when with 16-bit wide strings, they must be UTF16-LE.

Likewise, `std::string`, `std::cout` and `printf` do not place a meaning to what the 8-bit units stored in them is at compile time, but it is the runtime locale `LC_CTYPE` that defines the encoding of these when one is printing to console. We currently hardcode this to mean UTF-8, and don't understand any other 8-bit encodings such as Latin-1 or ISO-8859-* at all. (and probably won't care to, since those are somewhat old and usually mostly of historical interest)

Now, the WebIDL binder is a different story, and I think that one just has not been developed with encodings in mind, and it may have been hardcoded to assume that all strings on the heap are UTF-8. I think a PR to improve the WebIDL binder to enable multiple encoded string types such as ascii, UTF-8, UTF16-LE and UTF32-LE would be cool, and one could then define string types in individual interfaces to be able to specify which type of encoding a given string parameter to a function expects.

> This looks to be inconvenient/inefficient (conversion and copy is required rather than just copy),

I'd assume that like ~95% of the overhead of converting strings from the HEAP over to high level JS strings will be in the JS engine side string allocation code itself, and the UTF32 or UTF8 -> UTF16 conversion time is insignificant in comparison to the JS string object and per-character memory space allocation cost. This is because the conversion is done streaming on the fly while the JS string is being created. (although, not so with WebIDL binder yet if it doesn't support different string encodings)

Given that WebIDL binder currently assumes all strings are UTF-8, they will go through this line to be converted to JS strings: https://github.com/kripken/emscripten/blob/incoming/src/preamble.js#L440 . If WebIDL binder was improved to allow assuming UTF-16 in some entry points, they would marshal through this line instead: https://github.com/kripken/emscripten/blob/incoming/src/preamble.js#L608 . I remember benchmarking the perf difference of strings a couple of years back, but don't remember to have seen large discrepancies between the two.

In either case, adding support to WebIDL to be able to specify at function signature level that a string would be UTF-16 or UTF-32 would be a great feature to add - PRs there would be very welcome.

**Comment by TZBH** [comment] 2018-04-09 18:26
Thank you for detailed answer. 
I do understand bitness and encoding are 2 different things, but I would think UTF16-LE would be the natural choice for the emscripten environment. If at the beginning (passing string to web assembly) and end (return or output) you need UTF16, I do not see much point using utf8 or utf32 in between. 
Thus going back to my original questions, what do I need to do to compile the whole environment with -fshort-wchar?
Based on your comments I understand the main issue related to WebIDL is limited implementation so far. So how do I submit PR then?

As for the printing to console, that’s not the only time I would expect the encoding to matter. E.g. things like changing case/sorting/regular expressions/etc. would be dependent on encoding/locale and from what I can see require conversion of UTF8 to wchar_t as the utf8 in emscripten does not support e.g. toupper (at least for the characters I’ve tried). Similarly most of string processing is much more convenient on fixed width characters.
Besides I believe C++ code that needs to convert from utf8 to Unicode and back all over the place could be quite error prone and I’d prefer to avoid it (especially when using streams) and stick to one type of strings/characters. The performance aspect as usual will depend on the amount of conversions done and I'm including conversions within web assembly.

**Closed** 2019-09-26 02:10 UTC
Labels: wontfix
