### ISSUE TITLE
Module arguments are ignored when using non-default export name and manually packaged pre-js

### ISSUE THREAD

**Issue by Daimona** [emscripten-core/emscripten#22757] opened 2024-10-17 02:10 UTC
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.69 (c55ff404dbe1eb9f263c48b584d5ba627224763a)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 50866e84d1da8462aeb96607bf6d9e5bbd5869c5)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /srv/emsdk/upstream/bin
```

I'm using emscripten to compile PHP for an application that lets you run PHP in your browser. You can find all the code in https://github.com/Daimona/demo. [build.sh](https://github.com/Daimona/demo/blob/2e8f2d2903081d03ae84b11ffcf1e9773e7fec74/build.sh) is the relevant build file. As can be seen there, I'm using `--pre-js` to preload a manually-packaged file, and I'm using `PHP` as custom export name. This part works just fine. I'm then loading the generated php.js script, along with more application logic that you can find in [demo.js](https://github.com/Daimona/demo/blob/2e8f2d2903081d03ae84b11ffcf1e9773e7fec74/static/demo.js). There, I'm configuring certain module properties (like `print` and `printErr`) when calling the `PHP` exported function. However, these options do not take effect, and the default options (for example, printing to the console) are used instead. On closer inspection, the generated php.js starts with:

```
var PHP = (() => {
    var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;

    return (
        function(moduleArg = {}) {
            var moduleRtn;

            var Module = moduleArg;
            var readyPromiseResolve, readyPromiseReject;
            var readyPromise = new Promise((resolve, reject) => {
                readyPromiseResolve = resolve;
                readyPromiseReject = reject
            });
            var ENVIRONMENT_IS_WEB = true;
            var ENVIRONMENT_IS_WORKER = false;
            var ENVIRONMENT_IS_NODE = false;
            var Module = typeof PHP != "undefined" ? PHP : {};
```

where `moduleArg`, which contains my custom options, is assigned to `Module`, but then `Module` is immediately overridden below, because it's checking whether `PHP` exists, not `Module`.

**Comment by sbc100** [comment] 2024-10-17 19:04
Looks like a bug yes.  Can you share the full list of link flags you are using here?

**Comment by sbc100** [comment] 2024-10-17 19:32
Looking at the code it looks like `var Module = typeof PHP != "undefined" ? PHP : {};` and `var Module = moduleArg;` should be mutually exclusive.  In your case I think you should see the later only since you are building with `MODULARIZE`.

**Comment by sbc100** [comment] 2024-10-17 21:36
I can't reproduce that using a simple program.   When I build a hello world program like that I don't see `var Module = typeof PHP != "undefined" ? PHP : {};` in the generated code:

```
$ emcc --minify=0 -O3 --llvm-lto 2 -sENVIRONMENT=web -sEXTRA_EXPORTED_RUNTIME_METHODS=ccall -sMODULARIZE=1 -sEXPORT_NAME="'PHP'" -sTOTAL_MEMORY=134217728  -sASSERTIONS=0 -sINVOKE_RUN=0  -sFORCE_FILESYSTEM=1 -sERROR_ON_UNDEFINED_SYMBOLS=0  ~/test/hello.c
$ grep PHP a.out.js 
var PHP = (() => {
  module.exports = PHP;
  define([], () => PHP);
```

Here we only have three occurrences of PHP in the generated code, the first one on the very first line and then the second two at the very end.

Can you add `--minify=0` (to preserve comments and formatting) and then attach the generated JS file?

**Comment by sbc100** [comment] 2024-10-17 21:37
BTW, to `EXPORTED_FUNCTIONS` and `EXTRA_EXPORTED_RUNTIME_METHODS` you don't need to use quotes or brackets you can just use a simple comma separated list (e.g `-sEXPORTED_FUNCTIONS=foo,bar,baz`)

**Comment by Daimona** [comment] 2024-10-17 22:00
> I can't reproduce that using a simple program. When I build a hello world program like that I don't see `var Module = typeof PHP != "undefined" ? PHP : {};` in the generated code:
> 
> ```
> $ emcc --minify=0 -O3 --llvm-lto 2 -sENVIRONMENT=web -sEXTRA_EXPORTED_RUNTIME_METHODS=ccall -sMODULARIZE=1 -sEXPORT_NAME="'PHP'" -sTOTAL_MEMORY=134217728  -sASSERTIONS=0 -sINVOKE_RUN=0  -sFORCE_FILESYSTEM=1 -sERROR_ON_UNDEFINED_SYMBOLS=0  ~/test/hello.c

Note that the `--pre-js` is required to reproduce this bug. In one of my experiments, I replaced the [manual packaging above](https://github.com/Daimona/demo/blob/2e8f2d2903081d03ae84b11ffcf1e9773e7fec74/build.sh#L123) and `--pre-js` with just a `--preload-file` and the issue went away. I hinted at that in the issue title but forgot to mention it explicitly. I can reproduce with semi-empty files like so:

```
$ echo "int main() {}" > test1.c
$ echo "int test() { return 42; }" > test2.c
$ sh $EMSDK/upstream/emscripten/tools/file_packager test.data --preload test2.c --js-output=test2.js --export-name='PHP'
$ emcc --minify=0 -O3 --llvm-lto 2 -sENVIRONMENT=web -sEXTRA_EXPORTED_RUNTIME_METHODS=ccall -sMODULARIZE=1 -sEXPORT_NAME="'PHP'" -sTOTAL_MEMORY=134217728  -sASSERTIONS=0 -sINVOKE_RUN=0  -sFORCE_FILESYSTEM=1 -sERROR_ON_UNDEFINED_SYMBOLS=0 --pre-js test2.js test1.c -o test.js
```

And:

```
$ head -42 test.js

var PHP = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

// include: shell.js
// The Module object: Our interface to the outside world. We import
// and export values on it. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(moduleArg) => Promise<Module>
// 3. pre-run appended it, var Module = {}; ..generated code..
// 4. External script tag defines var Module.
// We need to check if Module already exists (e.g. case 3 above).
// Substitution will be replaced with actual code on later stage of the build,
// this way Closure Compiler will not mangle it (e.g. case 4. above).
// Note that if you want to run closure, and also to use Module
// after the generated code, you will need to define   var Module = {};
// before the code. Then that object will be used in the code, and you
// can continue to use Module afterwards as well.
var Module = moduleArg;

// Set up the promise that indicates the Module is initialized
var readyPromiseResolve, readyPromiseReject;

var readyPromise = new Promise((resolve, reject) => {
  readyPromiseResolve = resolve;
  readyPromiseReject = reject;
});

// Determine the runtime environment we are in. You can customize this by
// setting the ENVIRONMENT setting at compile time (see settings.js).
var ENVIRONMENT_IS_WEB = true;

var ENVIRONMENT_IS_WORKER = false;

// --pre-jses are emitted after the Module integration code, so that they can
// refer to Module (if they choose; they can also define Module)
// include: /srv/demo/test2.js
var Module = typeof PHP != "undefined" ? PHP : {};
```

I'm also realizing now that another solution could be to drop `--export-name='PHP'` entirely from the file_packager invocation. My code was working fine with emsdk 2.0.21, but of course that doesn't mean it hasn't been wrong the whole time ;)

**Comment by sbc100** [comment] 2024-10-17 22:05
Ah I see, its file packager issue.    Sounds like `--preload-file` is the way to go!

**Comment by Daimona** [comment] 2024-10-17 22:25
> Ah I see, its file packager issue. Sounds like `--preload-file` is the way to go!

Unfortunately I can't use that because... Something to do with licensing, I don't remember what exactly. But on the bright side, I can live without the custom export name, so I ditched that!

I'm unclear about whether I'm supposed to use the same export name for the file packager, or if this is actually intended behaviour. Maybe, if it's intended, it could be mentioned in the [docs](https://emscripten.org/docs/porting/files/packaging_files.html#packaging-using-the-file-packager-tool).

**Comment by sbc100** [comment] 2024-10-18 19:03
I think the point of `--export-name` in the file_packager command would be for if the generated code was run outside the module.  If the code is run inside the module (i.e.e via `--pre-js`) then you would not want/use this argument.

**Comment by sbc100** [comment] 2024-10-18 19:03
I think we can probably close this issue now.

**Closed by sbc100** 2024-10-18 19:03 UTC

**Comment by Daimona** [comment] 2024-10-18 20:37
> I think the point of `--export-name` in the file_packager command would be for if the generated code was run outside the module. If the code is run inside the module (i.e.e via `--pre-js`) then you would not want/use this argument.

That makes sense to me! Could it be documented somewhere, e.g. in file_packager.py?

**Comment by sbc100** [comment] 2024-10-18 20:44
Yes, we should probably update the docs.

Looking at the code it looks like the expectation is that if you use file packager directly then the generated code is expected to live outside of the emscripten module and not included using  `--pre-js`.   See https://github.com/emscripten-core/emscripten/blob/bdde3cd337ed4ac72a641f862b5371048e049946/tools/file_packager.py#L601-L607.  It looks like unless you run with `--from-emcc` you will get the extra `var Module =..` thing which you don't need/want.   I guess we could rename `--from-emcc` to `--embedded` or `--as-pre-js`?

**Comment by Daimona** [comment] 2024-10-18 22:44
> Looking at the code it looks like the expectation is that if you use file packager directly then the generated code is expected to live outside of the emscripten module and not included using `--pre-js`.

That's odd, because back then I followed the file_packager + pre-js directly from [the docs](https://emscripten.org/docs/tools_reference/emcc.html#emcc-preload-file):

> You should then put the output of the file packager in an emcc --pre-js, so that it executes before your main compiled code.

And actually, that would probably have to be update as well.
