### ISSUE TITLE
[SIMD] '__builtin_wasm_sqrt_f32x4' needs target feature unimplemented-simd128

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [emscripten-core/emscripten#9399] opened 2019-09-06 02:51 UTC
`wasm_f32x4_sqrt` is not in the wasm intrin `__wasm_unimplemented_simd128__` tag, but I got the error when use it with the latest LLVM backend: 
```
error: '__builtin_wasm_sqrt_f32x4' needs target feature unimplemented-simd128
```
I found in [wasm intrin test](https://github.com/emscripten-core/emscripten/blob/a8fda44606024aa3a13d9513c8e5acd63f750668/tests/test_wasm_intrinsics_simd.c#L510), `wasm_f32x4_sqrt` is just under the `__wasm_unimplemented_simd128__` tag.
What's the status with it?

**Comment by tlively** [comment] 2019-09-06 23:30
V8 merged support for this instruction earlier this week in https://chromium-review.googlesource.com/c/v8/v8/+/1765442. I haven't updated the toolchain yet, so for now it remains gated on `-munimplemented-simd128`. It should have been behind an `#ifdef __wasm_unimplemented_simd128__` in the intrinsics header as well, but it's probably not worth fixing now since I will update it to be enabled by `-msimd128` soon.

**Comment by Wenzhao-Xiang** [comment] 2019-09-08 17:39
Sounds good, Thanks!

**Comment by tlively** [comment] 2019-09-10 20:18
Ah, actually the commit I linked above implements division, not sqrt. I don't think V8 has implemented sqrt after all. For now it remains intended behavior that sqrt does not work without -munimplemented-simd128.

**Comment by englercj** [comment] 2019-10-11 03:29
Just hit this as well, any word on sqrt support or fixing the intrinsics header? Looks like `wasm_f32x4_qfma` and `wasm_f32x4_qfms` are similar in that they are not guarded in the header, but are guarded in the tests.

**Closed** 2021-03-19 23:56 UTC
Labels: SIMD, wontfix
