### ISSUE TITLE
Change off_t to 64-bit to support large files (in WORKERFS partial reads, and elsewhere)

### ISSUE THREAD

**Issue by dattaz** [emscripten-core/emscripten#5250] opened 2017-05-26 22:04 UTC
I got a int overflow with files > 2 147 483 647 , using workerfs (using file object).

Here is a code to reproduct : https://gist.github.com/dattaz/62254df7b8f3d6453d87218020efbca5

And here is the output from console
![Output from console](https://cloud.githubusercontent.com/assets/6572195/26514090/da015e12-426f-11e7-80b6-58e1c6d4e079.png)

**Comment by mossroy** [comment] 2018-09-23 08:53
Version 1.38.12 of emscripten seems to have the same issue.
Is there a 2GB file limit in emscripten workerfs or does it come from another layer?
I have the same behavior with Firefox 62 and Chromium 69.

**Comment by kripken** [comment] 2018-09-24 00:00
In practice JS VMs limit typed arrays to 2GB, so the emscripten FS code doesn't try to support any more.

**Comment by mossroy** [comment] 2018-09-26 12:06
Thanks a lot for you answer @kripken , and for that amazing piece of software.

We're trying to use emscripten and workerfs to read small parts of very big files (for example full archives of wikipedia) for project www.kiwix.org.
We don't need to read the whole file and put it in memory. And workerfs does not seem to do that when we read some bytes in it.

I'm sorry that I don't know the internals of emscripten/workerfs : why does the maximum size of a typed array imply a maximum file size that can be accessed through workerfs?

**Comment by kripken** [comment] 2018-09-28 22:18
I think reading a small part of a big file should work (unless you are hitting a bug in the browser). However, what worries me in emscripten's code is setting up WORKERFS - if you give it the big file as a typed array, it's going to hit the browser typed array limit.

**Comment by mossroy** [comment] 2018-09-30 06:58
The files are passed as File javascript objects, and mounted through WORKERFS. We do not use typed arrays ourself, and never read the whole file in memory (it can be much too large).

@dattaz already implemented a prototype that reads files using a C library called libzim : https://dattaz.github.io/libzim_wasm/file_api/index.html
It can be tested with ZIM files coming from : 
https://download.kiwix.org/zim/wikipedia/?C=S;O=D
It works perfectly fine with small files (browser console shows a few titles contained in the file), but fails with files larger than 2GB.

**Comment by kripken** [comment] 2018-09-30 18:00
Interesting - I'm not sure how browsers implement File objects. But it's possible they don't have the 2GB limitation.

I think at this point we just need to debug the workerfs code to see where things go wrong. It's in `src/library_workerfs.js`, and is not very long. Specifically, look at the `read: ` function, maybe add some debug statements in there to see that the parameters arrive ok, and then what happens in the browser calls to `slice` and `readAsArrayBuffer`. Also worth checking this in multiple browsers, as not all may have the same arbitrary 2GB limitation.

**Comment by dattaz** [comment] 2018-10-01 19:29
src/library_workerfs.js work good,
but it's seems than offset (off_t) is on 32 bit https://github.com/kripken/emscripten/blob/incoming/src/library_syscall.js#L700 
And on system part, we have a "TODO" : https://github.com/kripken/emscripten/blob/incoming/system/lib/fetch/asmfs.cpp#L1125

**Comment by kripken** [comment] 2018-10-03 02:53
Thanks, that makes sense, we need to define `off_t` as 64-bit for this to work. Historically, the issue is that 64-bit operations were very slow in JS and asm.js, and typed arrays are limited to 2GB anyhow as mentioned above, so we just set it to 32-bit. But it should be fine to switch that now since wasm has proper i64s. I think, but we'd need to investigate, whether that switch would be backwards compatible.

**Comment by sbc100** [comment] 2019-10-07 22:32
This was fixed in #8467

**Closed by sbc100** 2019-10-07 22:32 UTC
Labels: help wanted, wontfix

**Comment by jazarforcite** [comment] 2020-12-08 22:43
Hello @kripken were you able to get past the 2gb limit on FS write file? I'm trying to store large files in the browser using emscripten and idbfs support but it seems that the file system uses typed arrays with a 2GB limit in most browsers.

**Comment by kripken** [comment] 2020-12-09 17:30
@jazarforcite I have not tested this myself.
