### ISSUE TITLE
SDL_TFF port not building in windows

### ISSUE THREAD

**Issue by iambpn** [emscripten-core/emscripten#14321] opened 2021-05-28 05:14 UTC
SDL_TFF ends with error while building it. it may be because of HARFBUZZ dependency. I have gone through some threads and rechecked my problem and found out that HARFBUZZ dependency is the problem. Do any body knows the fix to this.  By the way i am using cmake version 3.20.2, emcc version 2.0.21-git 

Here is the error messages:
```
cl : command line warning D9002: ignoring unknown option '-g' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\harfbuzz.vcxproj]

cl : command line warning D9002: ignoring unknown option '-g' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\harfbuzz.vcxproj]
  ucdn.c
  harfbuzz.vcxproj -> C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\Debug\libharfbuzz.a
  Building Custom Rule C:/Emscripten/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5/CMakeLists.txt
cl : command line warning D9002: ignoring unknown option '-fno-rtti' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\hb-ot-tag.vcxproj]
  hb-ot-tag.cc
cl : command line warning D9002: ignoring unknown option '-fno-exceptions' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\hb-ot-tag.vcxproj]
cl : command line warning D9002: ignoring unknown option '-g' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\hb-ot-tag.vcxproj]
LINK : warning LNK4044: unrecognized option '/Bsymbolic-functions'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\hb-ot-tag.vcxproj]
LINK : warning LNK4044: unrecognized option '/-default-obj-ext'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\hb-ot-tag.vcxproj]
LINK : fatal error LNK1104: cannot open file '.obj' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\hb-ot-tag.vcxproj]
  Building Custom Rule C:/Emscripten/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5/CMakeLists.txt
cl : command line warning D9002: ignoring unknown option '-fno-rtti' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\main.vcxproj]
  main.cc
cl : command line warning D9002: ignoring unknown option '-fno-exceptions' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\main.vcxproj]
cl : command line warning D9002: ignoring unknown option '-g' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\main.vcxproj]
LINK : warning LNK4044: unrecognized option '/Bsymbolic-functions'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\main.vcxproj]
LINK : warning LNK4044: unrecognized option '/-default-obj-ext'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\main.vcxproj]
LINK : fatal error LNK1104: cannot open file '.obj' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\main.vcxproj]
  Building Custom Rule C:/Emscripten/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5/CMakeLists.txt
cl : command line warning D9002: ignoring unknown option '-fno-rtti' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-buffer-serialize.vcxproj
]
  test-buffer-serialize.cc
cl : command line warning D9002: ignoring unknown option '-fno-exceptions' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-buffer-serialize.v
cxproj]
cl : command line warning D9002: ignoring unknown option '-g' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-buffer-serialize.vcxproj]
LINK : warning LNK4044: unrecognized option '/Bsymbolic-functions'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-buffer-serialize.
vcxproj]
LINK : warning LNK4044: unrecognized option '/-default-obj-ext'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-buffer-serialize.vcx
proj]
LINK : fatal error LNK1104: cannot open file '.obj' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-buffer-serialize.vcxproj]
  Building Custom Rule C:/Emscripten/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5/CMakeLists.txt
cl : command line warning D9002: ignoring unknown option '-fno-rtti' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-size-params.vcxproj]
cl : command line warning D9002: ignoring unknown option '-fno-exceptions' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-size-params.vcxpro
j]
  test-size-params.cc
cl : command line warning D9002: ignoring unknown option '-g' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-size-params.vcxproj]
LINK : warning LNK4044: unrecognized option '/Bsymbolic-functions'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-size-params.vcxpr
oj]
LINK : warning LNK4044: unrecognized option '/-default-obj-ext'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-size-params.vcxproj]
LINK : fatal error LNK1104: cannot open file '.obj' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-size-params.vcxproj]
  Building Custom Rule C:/Emscripten/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5/CMakeLists.txt
cl : command line warning D9002: ignoring unknown option '-fno-rtti' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-test.vcxproj]
  test.cc
cl : command line warning D9002: ignoring unknown option '-fno-exceptions' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-test.vcxproj]
cl : command line warning D9002: ignoring unknown option '-g' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-test.vcxproj]
LINK : warning LNK4044: unrecognized option '/Bsymbolic-functions'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-test.vcxproj]
LINK : warning LNK4044: unrecognized option '/-default-obj-ext'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-test.vcxproj]
LINK : fatal error LNK1104: cannot open file '.obj' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-test.vcxproj]
  Building Custom Rule C:/Emscripten/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5/CMakeLists.txt
cl : command line warning D9002: ignoring unknown option '-fno-rtti' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-would-substitute.vcxproj
]
  test-would-substitute.cc
cl : command line warning D9002: ignoring unknown option '-fno-exceptions' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-would-substitute.v
cxproj]
cl : command line warning D9002: ignoring unknown option '-g' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-would-substitute.vcxproj]
LINK : warning LNK4044: unrecognized option '/Bsymbolic-functions'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-would-substitute.
vcxproj]
LINK : warning LNK4044: unrecognized option '/-default-obj-ext'; ignored [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-would-substitute.vcx
proj]
LINK : fatal error LNK1104: cannot open file '.obj' [C:\Emscripten\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz\test-would-substitute.vcxproj]
Traceback (most recent call last):
  File "C:\Emscripten\emsdk\upstream\emscripten\emcc.py", line 3690, in <module>
    sys.exit(main(sys.argv))
  File "C:\Emscripten\emsdk\upstream\emscripten\emcc.py", line 3683, in main
    ret = run(args)
  File "C:\Emscripten\emsdk\upstream\emscripten\emcc.py", line 1073, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "contextlib.py", line 79, in inner
  File "C:\Emscripten\emsdk\upstream\emscripten\emcc.py", line 2401, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "C:\Emscripten\emsdk\upstream\emscripten\emcc.py", line 2389, in compile_source_file
    cmd = get_clang_command(input_file)
  File "C:\Emscripten\emsdk\upstream\emscripten\emcc.py", line 2330, in get_clang_command
    return get_compiler(use_cxx(src_file)) + get_cflags(options, state.orig_args) + compile_args + [src_file]
  File "C:\Emscripten\emsdk\upstream\emscripten\emcc.py", line 889, in get_cflags
    system_libs.add_ports_cflags(cflags, settings)
  File "C:\Emscripten\emsdk\upstream\emscripten\tools\system_libs.py", line 1907, in add_ports_cflags
    port.get(Ports, settings, shared)
  File "C:\Emscripten\emsdk\upstream\emscripten\tools\ports\harfbuzz.py", line 72, in get
    return [shared.Cache.get_lib(get_lib_name(settings), create, what='port')]
  File "C:\Emscripten\emsdk\upstream\emscripten\tools\cache.py", line 134, in get_lib
    return self.get(name, *args, **kwargs)
  File "C:\Emscripten\emsdk\upstream\emscripten\tools\cache.py", line 162, in get
    creator(cachename)
  File "C:\Emscripten\emsdk\upstream\emscripten\tools\ports\harfbuzz.py", line 66, in create
    shared.run_process(['cmake', '--build', build_path, '--target', 'install'])
  File "C:\Emscripten\emsdk\upstream\emscripten\tools\shared.py", line 98, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['cmake', '--build', 'C:\\Emscripten\\emsdk\\upstream\\emscripten\\cache\\ports-builds\\harfbuzz', '--target', 'install']' returned non-zero exit status 1.
```

**Comment by sbc100** [comment] 2021-05-28 14:28
I think this is a duplicate of https://github.com/emscripten-core/emscripten/issues/14027

**Comment by vkaytsanov** [comment] 2021-05-30 16:32
You could use dirty fix to replace the contents of the files with https://github.com/emscripten-core/emscripten/pull/14095

**Closed** 2021-06-03 00:40 UTC
