### ISSUE TITLE
Invalid assertion in acorn-optimizer - firebaseui web sdk

### ISSUE THREAD

**Issue by JakubGortychHG** [emscripten-core/emscripten#21594] opened 2024-03-22 11:11 UTC
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.56 (cf90417346b78455089e64eb909d71d091ecc055)
I checked 3.1.54 as well.

**Failing command line in full:**
The following exception is thrown when compiling code with -Os

```
Error: /tmp/emscripten_temp_ldsqe925/SuperSampleApp.release.jso1.js:47247: expected Indentifier but found AssignmentPattern (use EMCC_DEBUG_SAVE=1 to preserve temporary inputs)
    at assertAt (file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:30:11)
    at traverse (file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:437:13)
    at traverse (file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:430:15)
    at Object.VariableDeclarator (file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:442:9)
    at c (file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:92:20)
    at recursiveWalk (file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:94:5)
    at file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:90:38
    at maybeChild (file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:54:7)
    at Array.forEach (<anonymous>)
    at visitChildren (file:///mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs:64:15)
em++: error: '/mnt/c/emsdk/node/16.20.0_64bit/bin/node /mnt/c/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs /tmp/emscripten_temp_ldsqe925/SuperSampleApp.release.jso1.js AJSDCE minifyWhitespace -o /tmp/emscripten_temp_ldsqe925/SuperSampleApp.release.jso2.js' failed (returned 1)
```

https://github.com/emscripten-core/emscripten/blob/047b82506d6b471873300a5e4d1e690420b582d0/tools/acorn-optimizer.js#L437

The issue is happening while using firebaseui npm package version 6.1.0
The issue is similar to https://github.com/emscripten-core/emscripten/issues/21359

**To reproduce the issue create the following files:**

a.cpp:
```

int main()
{
	return 0;
}
```
package.json:
```

{
	"devDependencies": {
		"firebaseui" : "6.1.0",
                "webpack": "^5.74.0",
                "webpack-cli": "^4.10.0"
	}
}
```
webpack.config.js:

```
path = require('path');

module.exports = env => {
	return {
		entry: path.resolve(__dirname, 'index.js'),
		output: {
			filename: 'all.js',
			path: __dirname
		},
		mode: 'production',
		resolve: {
			modules: [path.resolve(__dirname, 'node_modules')],
			extensions: ['.tsx', '.ts', '.js']
		}
	}
}
```
index.js:

```
import * as firebaseui from 'firebaseui'

```

Then run the following commands:

```
npm install
node_modules/.bin/webpack
emcc a.cpp -O2 --pre-js all.js
```

**Comment by sbc100** [comment] 2024-03-22 21:14
OK to close this one as a duplicate of #21359

**Comment by JakubGortychHG** [comment] 2024-03-25 07:41
I guess it's ok to close it @sbc100

**Closed** 2024-03-25 15:45 UTC
