### ISSUE TITLE
No tool or SDK found by name 'sdk-upstream-incoming-64bit'.

### ISSUE THREAD

**Issue by cucibala** [emscripten-core/emscripten#13556] opened 2021-02-24 10:05 UTC
![image](https://user-images.githubusercontent.com/48320342/108984030-726ab800-76ca-11eb-821e-34b14bab12cb.png)
in Mac OS X 11.0.1 i can't install sdk .i have try "./emsdk install latest",but it not work

**Comment by sbc100** [comment] 2021-02-26 02:11
You aren't by any chance using one of those new arm-base macOS machine are you?

**Comment by PeterHiber** [comment] 2021-02-26 07:09
We are also having this problem. Macbook Air M1 indeed, no arm support yet?

**Comment by sbc100** [comment] 2021-02-26 15:22
Indeed not.  If you want to use emsdk on arm hardware you would either need to build from source or run everything in emulation mode (I believe others have had some success doing the latter but it might require a patch to emsdk).

**Comment by sbc100** [comment] 2021-02-26 15:23
Closing as duplicate of https://github.com/emscripten-core/emsdk/issues/671.   If this is a different issue we can re-open.

**Closed by sbc100** 2021-02-26 15:23 UTC
