### ISSUE TITLE
Linking in Freetype causing LLVM Abort

### ISSUE THREAD

**Issue by kjlubick** [emscripten-core/emscripten#15528] opened 2021-11-15 18:16 UTC
I'm currently working on building CanvasKit using Bazel. [As of Friday](https://skia-review.googlesource.com/c/skia/+/470682), I was able to build a barebones version of CanvasKit using emscripten 2.0.32. It could draw using WebGL, but most other features were disabled (including text).

Today, I've been adding rules to build Freetype, but I ran into an LLVM abort when Bazel got to the linking step. I tried some earlier versions of Emscripten and got some different results. I've linked the stack traces below

2.0.32 - abort 
```
bazelisk build :canvaskit-wasm --compilation_mode dbg --spawn_strategy=local \
	--gpu_backend=gl_backend --with_gl_standard=webgl_standard \
	--include_codec=jpeg_codec --include_codec=png_codec --include_codec=webp_codec \
	--include_codec=gif_codec --include_fontmgr=custom_embedded_fontmgr
INFO: Analyzed target //modules/canvaskit:canvaskit-wasm (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/kjlubick/skia/skia/modules/canvaskit/BUILD.bazel:129:10: Linking modules/canvaskit/canvaskit failed: (Exit 1): emcc_link.sh failed: error executing command external/emsdk/emscripten_toolchain/emcc_link.sh @bazel-out/wasm-dbg-ST-360af5540d44/bin/modules/canvaskit/canvaskit-2.params
wasm-ld: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = lld::wasm::DefinedFunction, Y = const lld::wasm::Symbol]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
 #0 0x00007f774c555883 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-14git.so+0x19a2883)
 #1 0x00007f774c55371e llvm::sys::RunSignalHandlers() (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-14git.so+0x19a071e)
 #2 0x00007f774c555d4f SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f774eadb8e0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x138e0)
 #4 0x00007f774a5c1e71 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3ce71)
 #5 0x00007f774a5ab536 abort (/lib/x86_64-linux-gnu/libc.so.6+0x26536)
 #6 0x00007f774a5ab41f (/lib/x86_64-linux-gnu/libc.so.6+0x2641f)
 #7 0x00007f774a5ba7f2 (/lib/x86_64-linux-gnu/libc.so.6+0x357f2)
 #8 0x0000000000703f0f lld::wasm::ObjFile::calcNewValue(llvm::wasm::WasmRelocation const&, unsigned long, lld::wasm::InputChunk const*) const (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/execroot/skia/external/emscripten_bin_linux/bin/wasm-ld+0x703f0f)
 #9 0x0000000000700ca5 lld::wasm::InputChunk::relocate(unsigned char*) const (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/execroot/skia/external/emscripten_bin_linux/bin/wasm-ld+0x700ca5)
#10 0x00000000007409db lld::wasm::CustomSection::writeTo(unsigned char*) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/execroot/skia/external/emscripten_bin_linux/bin/wasm-ld+0x7409db)
#11 0x000000000072f06d void std::__2::__function::__policy_invoker<void ()>::__call_impl<std::__2::__function::__default_alloc_func<void llvm::parallel::detail::parallel_for_each<std::__2::__wrap_iter<lld::wasm::OutputSection**>, lld::wasm::(anonymous namespace)::Writer::writeSections()::$_0>(std::__2::__wrap_iter<lld::wasm::OutputSection**>, std::__2::__wrap_iter<lld::wasm::OutputSection**>, lld::wasm::(anonymous namespace)::Writer::writeSections()::$_0)::'lambda'(), void ()> >(std::__2::__function::__policy_storage const*) Writer.cpp:0:0
#12 0x00007f774c4d497e void std::__2::__function::__policy_invoker<void ()>::__call_impl<std::__2::__function::__default_alloc_func<llvm::parallel::detail::TaskGroup::spawn(std::__2::function<void ()>)::$_0, void ()> >(std::__2::__function::__policy_storage const*) Parallel.cpp:0:0
#13 0x00007f774c4d38f6 llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work(llvm::ThreadPoolStrategy, unsigned int) Parallel.cpp:0:0
#14 0x00007f774c4d398d void* std::__2::__thread_proxy<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()> >(void*) Parallel.cpp:0:0
#15 0x00007f774ead0eae start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8eae)
#16 0x00007f774a682a5f __clone (/lib/x86_64-linux-gnu/libc.so.6+0xfda5f)
emcc: error: '/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/execroot/skia/external/emscripten_bin_linux/bin/wasm-ld -o bazel-out/wasm-dbg-ST-360af5540d44/bin/modules/canvaskit/canvaskit.wasm bazel-out/wasm-dbg-ST-360af5540d44/bin/modules/canvaskit/_objs/canvaskit/canvaskit_bindings.o bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libskcms.a bazel-out/wasm-dbg-ST-360af5540d44/bin/libskia-core.a bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libwuffs.a bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/liblibwebp.a bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/liblibjpeg-turbo.a bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libfreetype2.a bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/liblibpng.a bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libzlib.a -L/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lembind-rtti --no-whole-archive -lGL-webgl2 -lal -lhtml5 -lprintf_long_double -lstubs-debug -lc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -ldlmalloc -lc_rt_wasm -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --export-if-defined=emscripten_stack_get_end --export-if-defined=emscripten_stack_get_free --export-if-defined=emscripten_stack_init --export-if-defined=stackSave --export-if-defined=stackRestore --export-if-defined=stackAlloc --export-if-defined=__wasm_call_ctors --export-if-defined=__errno_location --export-if-defined=malloc --export-if-defined=free --export-if-defined=saveSetjmp --export-if-defined=setThrew --export-if-defined=emscripten_main_thread_process_queued_calls --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-table -z stack-size=5242880 --initial-memory=134217728 --no-entry --max-memory=2147483648 --global-base=1024' failed (received SIGABRT (-6))
Target //modules/canvaskit:canvaskit-wasm failed to build
```
2.0.20 - LLVM crash
```
bazelisk build :canvaskit-wasm --compilation_mode dbg --gpu_backend=gl_backend --with_gl_standard=webgl_standard             --include_codec=jpeg_codec --include_codec=png_codec --include_codec=webp_codec                --include_codec=gif_codec --include_fontmgr=custom_embedded_fontmgr --sandbox_base=/dev/shm
INFO: Analyzed target //modules/canvaskit:canvaskit-wasm (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/kjlubick/skia/skia/BUILD.bazel:151:11: Compiling src/core/SkBlurMask.cpp failed: (Exit 1): emcc.sh failed: error executing command external/emsdk/emscripten_toolchain/emcc.sh '--sysroot=external/emscripten_bin_linux/emscripten/cache/sysroot' -fdiagnostics-color -fno-exceptions -fno-strict-aliasing -funsigned-char ... (remaining 53 arguments skipped)
 
Use --sandbox_debug to see verbose messages from the sandbox
fatal error: error in backend: missing indirect function table symbol
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /dev/shm/bazel-sandbox.9a2ef7fb3512ffb45d1c1794d70e28b5d93593da99d132c43dc222830e7aeac3/linux-sandbox/2298/execroot/skia/external/emscripten_bin_linux/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=20 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=external/emscripten_bin_linux/emscripten/cache/sysroot -fdiagnostics-color -fno-exceptions -fno-strict-aliasing -funsigned-char -no-canonical-prefixes -std=gnu++17 -nostdinc -nostdinc++ -fno-omit-frame-pointer -g -O0 -Wall -DSK_FREETYPE_MINIMUM_RUNTIME_VERSION=(((FREETYPE_MAJOR)<<24)|((FREETYPE_MINOR)<<16)|((FREETYPE_PATCH)<<8)) -DSK_HAS_ANDROID_CODEC -DSK_DEBUG -DSK_GL -DSK_SUPPORT_GPU=1 -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_HAS_WUFFS_LIBRARY -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -iquote . -iquote bazel-out/wasm-dbg-ST-360af5540d44/bin -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/wuffs -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/zlib -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/libwebp -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/libjpeg-turbo -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/freetype2 -isystem third_party/externals/libpng -isystem bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/externals/libpng -isystem third_party/libpng -isystem bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libpng -iwithsysroot/include/c++/v1 -iwithsysroot/include/compat -iwithsysroot/include -isystem external/emscripten_bin_linux/lib/clang/14.0.0/include -MD -MF bazel-out/wasm-dbg-ST-360af5540d44/bin/_objs/skia-core/SkBlurMask.d -c -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -Werror src/core/SkBlurMask.cpp -o bazel-out/wasm-dbg-ST-360af5540d44/bin/_objs/skia-core/SkBlurMask.o
1.	<eof> parser at end of file
2.	Code generation
 #0 0x00007f8722503733 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x1942733)
 #1 0x00007f872250156e llvm::sys::RunSignalHandlers() (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x194056e)
 #2 0x00007f8722502aad llvm::sys::CleanupOnSignal(unsigned long) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x1941aad)
 #3 0x00007f8722432663 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x00007f87224325df llvm::CrashRecoveryContext::HandleExit(int) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x18715df)
 #5 0x00007f87224fdac7 llvm::sys::Process::Exit(int, bool) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x193cac7)
 #6 0x0000000000214a10 llvm::DenseMapBase<llvm::DenseMap<llvm::AliasSetTracker::ASTCallbackVH, llvm::AliasSet::PointerRec*, llvm::AliasSetTracker::ASTCallbackVHDenseMapInfo, llvm::detail::DenseMapPair<llvm::AliasSetTracker::ASTCallbackVH, llvm::AliasSet::PointerRec*> >, llvm::AliasSetTracker::ASTCallbackVH, llvm::AliasSet::PointerRec*, llvm::AliasSetTracker::ASTCallbackVHDenseMapInfo, llvm::detail::DenseMapPair<llvm::AliasSetTracker::ASTCallbackVH, llvm::AliasSet::PointerRec*> >::destroyAll() cc1_main.cpp:0:0
 #7 0x00007f8722442712 llvm::report_fatal_error(llvm::Twine const&, bool) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x1881712)
 #8 0x00007f87224425e6 (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x18815e6)
 #9 0x00007f8723d60806 (anonymous namespace)::WasmObjectWriter::recordRelocation(llvm::MCAssembler&, llvm::MCAsmLayout const&, llvm::MCFragment const*, llvm::MCFixup const&, llvm::MCValue, unsigned long&) WasmObjectWriter.cpp:0:0
#10 0x00007f8723d0ce78 llvm::MCAssembler::handleFixup(llvm::MCAsmLayout const&, llvm::MCFragment&, llvm::MCFixup const&) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x314be78)
#11 0x00007f8723d0d38e llvm::MCAssembler::layout(llvm::MCAsmLayout&) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x314c38e)
#12 0x00007f8723d0dab6 llvm::MCAssembler::Finish() (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x314cab6)
#13 0x00007f8722eb5ea2 llvm::AsmPrinter::doFinalization(llvm::Module&) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x22f4ea2)
#14 0x00007f87226848d5 llvm::FPPassManager::doFinalization(llvm::Module&) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x1ac38d5)
#15 0x00007f872267d825 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x1abc825)
#16 0x00007f871f7be1d6 (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) BackendUtil.cpp:0:0
#17 0x00007f871f7b89ba clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x265c9ba)
#18 0x00007f871fae2d99 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) CodeGenAction.cpp:0:0
#19 0x00007f871e7db634 clang::ParseAST(clang::Sema&, bool, bool) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x167f634)
#20 0x00007f87200c2510 clang::FrontendAction::Execute() (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x2f66510)
#21 0x00007f87200396ca clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x2edd6ca)
#22 0x00007f872013babc clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x2fdfabc)
#23 0x00000000002146f4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/dev/shm/bazel-sandbox.9a2ef7fb3512ffb45d1c1794d70e28b5d93593da99d132c43dc222830e7aeac3/linux-sandbox/2298/execroot/skia/external/emscripten_bin_linux/bin/clang+++0x2146f4)
#24 0x000000000021211d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#25 0x00007f871fd1b162 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) Job.cpp:0:0
#26 0x00007f8722432577 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libLLVM-13git.so+0x1871577)
#27 0x00007f871fd1acb7 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x2bbecb7)
#28 0x00007f871fce5fc8 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x2b89fc8)
#29 0x00007f871fce62c7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x2b8a2c7)
#30 0x00007f871fd00511 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/home/kjlubick/.cache/bazel/_bazel_kjlubick/9f1b700a32b289109ed0a336ee98974a/external/emscripten_bin_linux/bin/../lib/libclang-cpp.so.13git+0x2ba4511)
#31 0x00000000002119e6 main (/dev/shm/bazel-sandbox.9a2ef7fb3512ffb45d1c1794d70e28b5d93593da99d132c43dc222830e7aeac3/linux-sandbox/2298/execroot/skia/external/emscripten_bin_linux/bin/clang+++0x2119e6)
#32 0x00007f871ce5de4a __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x27e4a)
#33 0x000000000020ed2a _start (/dev/shm/bazel-sandbox.9a2ef7fb3512ffb45d1c1794d70e28b5d93593da99d132c43dc222830e7aeac3/linux-sandbox/2298/execroot/skia/external/emscripten_bin_linux/bin/clang+++0x20ed2a)
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 642df18f1437b1fffea2343fa471aebfff128c6e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /dev/shm/bazel-sandbox.9a2ef7fb3512ffb45d1c1794d70e28b5d93593da99d132c43dc222830e7aeac3/linux-sandbox/2298/execroot/skia/external/emscripten_bin_linux/bin
clang++: note: diagnostic msg: 
********************
 
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/SkBlurMask-95350e.cpp
clang++: note: diagnostic msg: /tmp/SkBlurMask-95350e.sh
clang++: note: diagnostic msg: 
 
********************
emcc: error: '/dev/shm/bazel-sandbox.9a2ef7fb3512ffb45d1c1794d70e28b5d93593da99d132c43dc222830e7aeac3/linux-sandbox/2298/execroot/skia/external/emscripten_bin_linux/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=20 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=external/emscripten_bin_linux/emscripten/cache/sysroot -fdiagnostics-color -fno-exceptions -fno-strict-aliasing -funsigned-char -no-canonical-prefixes -std=gnu++17 -nostdinc -nostdinc++ -fno-omit-frame-pointer -g -O0 -Wall -DSK_FREETYPE_MINIMUM_RUNTIME_VERSION=(((FREETYPE_MAJOR)<<24)|((FREETYPE_MINOR)<<16)|((FREETYPE_PATCH)<<8)) -DSK_HAS_ANDROID_CODEC -DSK_DEBUG -DSK_GL -DSK_SUPPORT_GPU=1 -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_HAS_WUFFS_LIBRARY -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -iquote . -iquote bazel-out/wasm-dbg-ST-360af5540d44/bin -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/wuffs -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/zlib -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/libwebp -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/libjpeg-turbo -Ibazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/_virtual_includes/freetype2 -isystem third_party/externals/libpng -isystem bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/externals/libpng -isystem third_party/libpng -isystem bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libpng -iwithsysroot/include/c++/v1 -iwithsysroot/include/compat -iwithsysroot/include -isystem external/emscripten_bin_linux/lib/clang/14.0.0/include -MD -MF bazel-out/wasm-dbg-ST-360af5540d44/bin/_objs/skia-core/SkBlurMask.d -c -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -Werror src/core/SkBlurMask.cpp -o bazel-out/wasm-dbg-ST-360af5540d44/bin/_objs/skia-core/SkBlurMask.o' failed (70)
Target //modules/canvaskit:canvaskit-wasm failed to build
```

2.0.13 - Errors about missing symbols (the type of error I was expecting to have to fix. WAI, it seems)

If anyone is interested in reproducing, they should be able to install bazelisk, check out Skia, apply [PS 2 of this CL](https://skia-review.googlesource.com/c/skia/+/471636), and run `make bazel_canvaskit_debug` from //modules/canvaskit.

@sbc100

**Comment by sbc100** [comment] 2021-11-15 20:33
I wonder if there is any way you could package up all the the linker inputs so that I can repro without having to re-produce your setup which fairly complex?

It looks like i would need the following files:

bazel-out/wasm-dbg-ST-360af5540d44/bin/modules/canvaskit/_objs/canvaskit/canvaskit_bindings.o     
bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libskcms.a 
bazel-out/wasm-dbg-ST-360af5540d44/bin/libskia-core.a
bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libwuffs.a 
bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/liblibwebp.a
bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/liblibjpeg-turbo.a 
bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libfreetype2.a
bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/liblibpng.a
bazel-out/wasm-dbg-ST-360af5540d44/bin/third_party/libzlib.a

Alternatively if you wanted to try to debug I think it would require a build of llvm that contains debug tracing so that `-Wl,-mllvm,-debug`.   I normally combine that flag with `-Wl,--threads=1` to find out which symbol is causing such a crash.

**Comment by kjlubick** [comment] 2021-11-15 21:12
I will get those files to you.

**Comment by kjlubick** [comment] 2021-11-29 13:45
Friendly ping on this, have you gotten those files?

**Comment by sbc100** [comment] 2021-12-02 01:57
I reproduced the issue and have a fix in flight.

The issue seems to be related to the fact the `sk_free` is not defined.   If you include that symbol does the issue go away?  

It also looks like the issue is specific to debug info.  If you link without `-g` does the issue also go away?

**Comment by kjlubick** [comment] 2021-12-02 13:29
Trying again with version 2.0.32
 - Adding in the .cpp file that implements sk_free: Compile and Link works w/o error
 - Removing -g (i.e. with a release/opt build): Compile succeeds, Link gives proper error about symbol undefined.

Thanks for digging into that error!

**Comment by sbc100** [comment] 2021-12-02 16:29
LLVM-side fix is in https://reviews.llvm.org/D114921

**Closed** 2021-12-02 16:40 UTC
