### ISSUE TITLE
Glibc not found

### ISSUE THREAD

**Issue by WafflePersonThing** [emscripten-core/emscripten#8274] opened 2019-03-08 21:42 UTC
[emsdk]# emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.28
/root/emsdk/clang/e1.38.28_64bit/clang++: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
/root/emsdk/clang/e1.38.28_64bit/clang++: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/emsdk/clang/e1.38.28_64bit/clang++)
shared:ERROR: '/root/emsdk/clang/e1.38.28_64bit/clang++ --version' failed (1)

**Comment by kripken** [comment] 2019-03-08 23:10
glibc is not part of emscripten - it would need to be ported to this platform. See https://emscripten.org/docs/compiling/Building-Projects.html#using-libraries

**Comment by tesch1** [comment] 2019-11-21 16:38
@WafflePersonThing did you install a binary package of emscripten on an older OS perhaps?  I'm also having this problem on CentOS 7 - which only has GLIBCXX_3.4.19, but the binary packages require GLIBCXX_3.4.21.

**Comment by sbc100** [comment] 2019-11-21 16:54
According to https://en.wikipedia.org/wiki/CentOS, CentOS 7 was released in July 2014.  That quite a long time ago now.

We currently build the emsdk binaries on Ubuntu Xenial (16.04).   I'm not sure its worth the effort to support much old linux distro, but if there are enough users we could consider it.

**Comment by tesch1** [comment] 2019-11-21 17:33
Yeah, but I'm actually on CentOS7.7 which according to that page was released 17 September 2019.  Lots of people are still on this line, as RHEL8 only came out earlier this year.

In any case, I would be more than happy to build my own, I just cant figure out how to!  ie, how would I build the equivalent of installing 1.39.3?  I'd like to just do `./emsdk build sdk-1.39.3-64bit` or something like that.  The [instructions](https://emscripten.org/docs/building_from_source/index.html) send me down a blackhole of building stuff separately from various other projects (whose instructions aren't really all that great), and while it may indeed work, looks like I'll need to figure out how all the pieces fit together and what all the correct paths and env variables should be even after everything is built... it would be great if I could just reproduce the binary sdk with a few short commands.

`./emsdk install sdk-master-64bit` builds a bunch of stuff, but it doesn't work.

**Comment by sbc100** [comment] 2019-11-21 17:36
Oh, for distros released this year we certainly *do* want to support them.  I'll see if I can figure out why binaries built with 2016 ubuntu don't work on 2019 centos.   it seems a little odd to me.

**Comment by tesch1** [comment] 2019-11-21 20:44
Dunno, they just do it that way.
The docs are a bit sparse.  Got it to build with `./emsdk install sdk-master-64bit` instead of `master`  -- would have though that was an unstable thing to do, but it looks like master is over a year old.

**Comment by tesch1** [comment] 2019-12-17 16:16
btw, this is likely a duplicate of #6252

the above command no longer works, see #10063

**Comment by sbc100** [comment] 2019-12-18 22:07
Yes seems like dup.  Closing in favor of #6252

**Closed by sbc100** 2019-12-18 22:07 UTC
