### ISSUE TITLE
Emscripten 1.39.19 miscompiles lcms2

### ISSUE THREAD

**Issue by kleisauke** [emscripten-core/emscripten#11596] opened 2020-07-09 10:17 UTC
Since version 1.39.19, compiling lcms2 with Emscripten crashes in the LLVM backend. The crash happens in `LoopVectorizationCostModel::computeMaxVF`.

Reproduction
```bash
mkdir lcms2
curl -Ls https://downloads.sourceforge.net/project/lcms/lcms/2.11/lcms2-2.11.tar.gz | tar xzC lcms2 --strip-components=1
cd lcms2
emconfigure ./configure --host=wasm32-unknown-linux --prefix=$PWD/inst --enable-static --disable-shared --disable-dependency-tracking \
 --without-jpeg --without-tiff --without-zlib
emmake make install
```

<details>
 <summary>Crash details</summary>

```
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=19 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/emsdk/upstream/emscripten/system/include -Xclang -isystem/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/emsdk/upstream/emscripten/system/include/SSE -Xclang -isystem/emsdk/upstream/emscripten/cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -D__EMSCRIPTEN_PTHREADS__=1 -DPACKAGE_NAME="lcms2" -DPACKAGE_TARNAME="lcms2" -DPACKAGE_VERSION="2.11" -DPACKAGE_STRING="lcms2 2.11" -DPACKAGE_BUGREPORT="" -DPACKAGE_URL="" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_FUNC_ATTRIBUTE_VISIBILITY=1 -DHAVE_PTHREAD=1 -DHasTHREADS=1 -I. -I../include -I../include -O3 -fno-rtti -fno-exceptions -fvisibility=hidden -c -pthread -pthread cmspack.c -Xclang -isystem/emsdk/upstream/emscripten/system/include/SDL -c -o cmspack.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'Function Pass Manager' on module 'cmspack.c'.
4.	Running pass 'Loop Vectorization' on function '@UnrollDoubleTo16'
 #0 0x00007f686663b514 PrintStackTraceSignalHandler(void*) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x7f2514)
 #1 0x00007f68666390fe llvm::sys::RunSignalHandlers() (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x7f00fe)
 #2 0x00007f686663a6bd llvm::sys::CleanupOnSignal(unsigned long) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x7f16bd)
 #3 0x00007f68665697d3 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x7207d3)
 #4 0x00007f686656990c CrashRecoverySignalHandler(int) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x72090c)
 #5 0x00007f6865e35730 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12730)
 #6 0x00007f686225b7bb raise (/lib/x86_64-linux-gnu/libc.so.6+0x377bb)
 #7 0x00007f6862246535 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22535)
 #8 0x00007f686224640f (/lib/x86_64-linux-gnu/libc.so.6+0x2240f)
 #9 0x00007f6862254102 (/lib/x86_64-linux-gnu/libc.so.6+0x30102)
#10 0x00007f6867797b4d (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x194eb4d)
#11 0x00007f6867797f64 llvm::LoopVectorizationCostModel::computeMaxVF(unsigned int, unsigned int) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x194ef64)
#12 0x00007f68677a3b28 llvm::LoopVectorizationPlanner::plan(unsigned int, unsigned int) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x195ab28)
#13 0x00007f68677aee4d llvm::LoopVectorizePass::processLoop(llvm::Loop*) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x1965e4d)
#14 0x00007f68677b2135 llvm::LoopVectorizePass::runImpl(llvm::Function&, llvm::ScalarEvolution&, llvm::LoopInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::BlockFrequencyInfo&, llvm::TargetLibraryInfo*, llvm::DemandedBits&, llvm::AAResults&, llvm::AssumptionCache&, std::function<llvm::LoopAccessInfo const& (llvm::Loop&)>&, llvm::OptimizationRemarkEmitter&, llvm::ProfileSummaryInfo*) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x1969135)
#15 0x00007f68677b71d8 (anonymous namespace)::LoopVectorize::runOnFunction(llvm::Function&) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x196e1d8)
#16 0x00007f6866797f24 llvm::FPPassManager::runOnFunction(llvm::Function&) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x94ef24)
#17 0x00007f6866798208 llvm::FPPassManager::runOnModule(llvm::Module&) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x94f208)
#18 0x00007f6866798934 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x94f934)
#19 0x00007f6863df4a1f clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x1872a1f)
#20 0x00007f6864103096 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x1b81096)
#21 0x00007f6862e83513 clang::ParseAST(clang::Sema&, bool, bool) (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x901513)
#22 0x00007f686491d9d3 clang::FrontendAction::Execute() (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x239b9d3)
#23 0x00007f68648b6ba3 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x2334ba3)
#24 0x00007f6864990422 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x240e422)
#25 0x0000000000410f01 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/emsdk/upstream/bin/clang+0x410f01)
#26 0x000000000040f0bc (/emsdk/upstream/bin/clang+0x40f0bc)
#27 0x00007f686456d1e2 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x1feb1e2)
#28 0x00007f68665696e7 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/emsdk/upstream/bin/../lib/libLLVM-11git.so+0x7206e7)
#29 0x00007f686456c7dd clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x1fea7dd)
#30 0x00007f686453a63b clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x1fb863b)
#31 0x00007f686453aa27 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x1fb8a27)
#32 0x00007f6864553c38 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/emsdk/upstream/bin/../lib/libclang-cpp.so.11git+0x1fd1c38)
#33 0x000000000040ea63 main (/emsdk/upstream/bin/clang+0x40ea63)
#34 0x00007f686224809b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409b)
#35 0x000000000040be6a _start (/emsdk/upstream/bin/clang+0x40be6a)
clang-11: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 7bf299c8d8d59304fb821f8811618cdeb1d1f1fd)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /emsdk/upstream/bin
clang-11: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-11: note: diagnostic msg: /tmp/cmspack-795f86.c
clang-11: note: diagnostic msg: /tmp/cmspack-795f86.sh
clang-11: note: diagnostic msg: 

********************
emcc: error: '/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=19 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/emsdk/upstream/emscripten/system/include -Xclang -isystem/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/emsdk/upstream/emscripten/system/include/SSE -Xclang -isystem/emsdk/upstream/emscripten/cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -D__EMSCRIPTEN_PTHREADS__=1 -DPACKAGE_NAME="lcms2" -DPACKAGE_TARNAME="lcms2" -DPACKAGE_VERSION="2.11" -DPACKAGE_STRING="lcms2 2.11" -DPACKAGE_BUGREPORT="" -DPACKAGE_URL="" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_FUNC_ATTRIBUTE_VISIBILITY=1 -DHAVE_PTHREAD=1 -DHasTHREADS=1 -I. -I../include -I../include -O3 -fno-rtti -fno-exceptions -fvisibility=hidden -c -pthread -pthread cmspack.c -Xclang -isystem/emsdk/upstream/emscripten/system/include/SDL -c -o cmspack.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (254)
make[1]: Leaving directory '/src/build/deps/lcms2/src'
make[1]: *** [Makefile:525: cmspack.lo] Error 1
make: *** [Makefile:476: install-recursive] Error 1
make: make install
```
</details>

(I don't have an account on https://bugs.llvm.org/, so I reported it here)

Crash happens with Emscripten 1.39.19 and the tip-of-tree build (`7d917c3f8806cd4839280af152031aa432176e44`, at time of writing). Note that version 1.39.18 compiles this project without problems.

**Comment by kripken** [comment] 2020-07-09 13:55
Sounds like an LLVM regression, yes.

cc @aheejin @tlively 

@kleisauke if you can simplify this that could speed up the process. From the stack trace it looks like a single invocation of `clang` is what crashes, during compilation, so providing just that single input file + the emcc command would be best.  You can find it by building with `make VERBOSE=1`, and you can reduce a source file + headers into a single source file with no headers by running `emcc -E`.

**Comment by kleisauke** [comment] 2020-07-09 14:03
Here's a reduced test case:
```c
#define T_FLAVOR(s) (((s) >> 13) & 1)
#define T_PLANAR(p) (((p) >> 12) & 1)
#define T_DOSWAP(e) (((e) >> 10) & 1)
#define T_CHANNELS(c) (((c) >> 3) & 15)
#define T_BYTES(b) ((b)&7)

unsigned char *UnrollDoublesToFloat(unsigned int inputFormat, float wIn[],
                                    unsigned char *accum, unsigned int Stride) {
    unsigned int nChan = T_CHANNELS(inputFormat);
    unsigned int DoSwap = T_DOSWAP(inputFormat);
    unsigned int Reverse = T_FLAVOR(inputFormat);
    unsigned int Planar = T_PLANAR(inputFormat);
    double v;
    unsigned int i, start = 0;
    double maximum = 1.0;

    Stride /= T_BYTES(inputFormat);

    for (i = 0; i < nChan; i++) {
        unsigned int index = DoSwap ? (nChan - i - 1) : i;

        if (Planar)
            v = (double)((double *)accum)[(i + start) * Stride];
        else
            v = (double)((double *)accum)[i + start];

        v /= maximum;

        wIn[index] = (float)(Reverse ? 1.0 - v : v);
    }

    if (Planar)
        return accum + sizeof(double);
    else
        return accum + (nChan) * sizeof(double);
}
```

```bash
emcc -O2 unroll.c
```

I also noticed this assertion failure:
```
clang: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:4941: bool llvm::LoopVectorizationCostModel::runtimeChecksRequired(): Assertion `Legal->getLAI()->getSymbolicStrides().empty() && "Specializing for stride == 1 under -Os/-Oz"' failed.
```
Commit https://github.com/llvm/llvm-project/commit/7bf299c8d8d59304fb821f8811618cdeb1d1f1fd might be relevant here(?).

**Comment by aheejin** [comment] 2020-07-09 20:17
Looks like that commit is indeed the cause. Someone already filed a bug for it: https://bugs.llvm.org/show_bug.cgi?id=46652

**Comment by kleisauke** [comment] 2020-07-10 14:41
It looks like this assertion failure will be fixed with https://reviews.llvm.org/D83470.

**Comment by aheejin** [comment] 2020-07-12 21:28
https://github.com/llvm/llvm-project/commit/82a5157ff1650e3366f7a9c619269766ad1d5e93 has been landed.

**Closed by aheejin** 2020-07-12 21:28 UTC
