### ISSUE TITLE
shared:ERROR: '/home/Emscripten/emsdk/upstream/bin/clang++ --version' failed (1)

### ISSUE THREAD

**Issue by Anonsmd** [emscripten-core/emscripten#10139] opened 2020-01-02 02:50 UTC
when i run the command "emcc -v" face below error
![image](https://user-images.githubusercontent.com/39185568/71649917-8d9f9900-2d4d-11ea-96a0-3b3a43b62e0a.png)

I hava alreagy install clang,but solve this problem,Any solution?

**Comment by embeddedt** [comment] 2020-01-05 18:39
Looks like `clang` is built expecting a newer host version of the C++ standard library. Are you using an older Linux distribution?

**Comment by sbc100** [comment] 2020-01-08 22:39
I think this is duplicate of https://github.com/emscripten-core/emscripten/issues/6252

**Closed by sbc100** 2020-01-08 22:39 UTC
