### ISSUE TITLE
LLVM Backend Performance Measurement

### ISSUE THREAD

**Issue by jgravelle-google** [emscripten-core/emscripten#5671] opened 2017-10-16 18:25 UTC
Before using the wasm backend by default, we should have a sense of what the performance looks like relative to the asm2wasm path.

**Comment by kripken** [comment] 2019-04-04 00:57
Float128 has now been fixed in https://github.com/emscripten-core/emscripten/pull/8348.

Comparing code size to fastcomp now, the wasm backend is smaller on every single benchmark but 2 out of 21, especially on the smaller ones thanks to the iprintf opts, 25% smaller on fannkuch, for example, but also big wins on some larger ones, like 7% on poppler, 11% smaller on sqlite, 14% smaller on zlib.

Looking into the 2 where we are larger (primes-nocheck and lzma).

**Comment by kripken** [comment] 2019-04-04 18:41
Attached are some perf numbers. Overall the upstream backend does better, in particular on the larger benchmarks, but there are a few exceptions I'll look more into.

![backend_perf](https://user-images.githubusercontent.com/173661/55580050-84a26e00-56ce-11e9-876a-00c53b70c4c3.png)

**Comment by sbc100** [comment] 2019-04-04 18:44
Very exciting news!

I'm also close (I think) to having dynamic linking working....  fastcomp's
days are numbered (hopefully in the double digits).

**Comment by kripken** [comment] 2019-04-04 22:34
On LZMA we are slightly bigger and slower. A large difference between the two is that the inlining decisions look quite different, so perhaps it's just that LLVM's heuristics there changed over time, in ways that happen to be bad for this one test.

**Comment by kripken** [comment] 2019-04-05 00:49
On fasta we are slower because of trapping float to int - LLVM emits code to prevent a trap around it. It sounds like this could be optimized in LLVM, but once we get nontrapping the problem goes away (once all browsers have it). So this may be a regression we just live with for a while?

**Comment by kripken** [comment] 2019-04-05 17:59
Fasta can be made fast with https://github.com/emscripten-core/emscripten/pull/8403

**Comment by kripken** [comment] 2019-04-05 18:28
The linpack slowdown was mostly noise. Improvements in #8404

**Closed** 2020-04-11 21:12 UTC
Labels: wontfix
