### ISSUE TITLE
__stdio_read calls __wasi_fd_read with iovec of len == 0

### ISSUE THREAD

**Issue by jerbob92** [emscripten-core/emscripten#19244] opened 2023-04-25 07:00 UTC
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)

Given the following code: https://github.com/emscripten-core/emscripten/blob/main/system/lib/libc/musl/src/stdio/__stdio_read.c#L7

The first item of the iov might have a len of 0, the original code handles that like this:
```
	cnt = iov[0].iov_len ? syscall(SYS_readv, f->fd, iov, 2)
		: syscall(SYS_read, f->fd, iov[1].iov_base, iov[1].iov_len);
```
If the first item has a `iov_len` larger than 0, use `readv`, if not, only use the second item directly in `read`.

But the code that Emscripten added will always pass through both `iov`, possibly passing one with a length of 0, this might cause undefined behaviour in runtimes, since it's not well defined what it should do when it sees a length of 0. 

wasi-libc solved it like this: https://github.com/WebAssembly/wasi-libc/blob/main/libc-top-half/musl/src/stdio/__stdio_read.c#L20

Where read will create a new iov with just one item:
https://github.com/WebAssembly/wasi-libc/blob/main/libc-bottom-half/cloudlibc/src/libc/unistd/read.c

And readv just passed the iov on to `__wasi_fd_read`:
https://github.com/WebAssembly/wasi-libc/blob/main/libc-bottom-half/cloudlibc/src/libc/sys/uio/readv.c#L33

Might be a better solution for Emscripten too? 

For now the issue was fixed on the runtime (Wazero) side: https://github.com/tetratelabs/wazero/pull/1402
But I still wanted to open this ticket to check with you what should be expected, since other runtimes might also have issues with this.

**Comment by kripken** [comment] 2023-04-25 16:50
I don't understand, sorry. Return early from what, exactly?

That wazero fix looks right to me: if an iov has length 0, skip it. An iov with length 0 can appear anywhere AFAIK, and that is the only sensible behavior I can think of for such a thing...

**Comment by kripken** [comment] 2023-04-25 16:52
(Are you saying that wazero used to assume a len of 0 meant it should ignore all iovs after it? That old behavior sounds wrong to me, if so. Unless I've missed something in the posix or wasi specs, which is definitely possible...)

**Comment by kripken** [comment] 2023-04-25 23:09
I see. I believe that if 0 were a special indicator of an error then it would be mentioned as such in the spec. As (AFAIK) it isn't, it's just another number. I agree a 0-sized iov is odd, but so is sending 100 consecutive iovs of length 1 instead of 1 of length 100, for example. They should all still be handled in the same way, with no special casing.

I do see your point that avoiding an iov of size 0 could avoid bugs in VMs, and sometimes it's good to be more cautious than the spec requires. But if that has a code size downside then it might not be worth it, since it might link in more code to use two syscalls here. Worth measuring, and maybe there are better ways to avoid the issue while reducing size.

(This is the first report I've seen of this problem, so AFAIK it isn't an issue in other VMs. But maybe it's just that my intuition differs from yours as to what the natural syscall implementation is, so I could be wrong.)

**Comment by sbc100** [comment] 2023-04-26 00:54
The WASI behaviour actually comes from upstream musl..so perhaps there is some reason to avoid zero sized in iovec elements when calling linux's pread, but I can't see any docs on that.

I guess if there there no code size regression we might as well do what wasi-libc and stick close to upstream musl... but including `read` in addition to `readv` seems like it would have at least some codesize effect.

**Comment by jerbob92** [comment] 2023-04-27 09:06
> I see. I believe that if 0 were a special indicator of an error then it would be mentioned as such in the spec.

I don't think so, almost nothing is defined in the docs. Any details are currently built into wasi-testsuite and feels more like "all compilers/VMs implemented it like this, so this will be the way it should work".

> I agree a 0-sized iov is odd, but so is sending 100 consecutive iovs of length 1 instead of 1 of length 100, for example. They should all still be handled in the same way, with no special casing

Except for that the first wouldn't actually be handled by upstream musl, it would be ignored.

> (This is the first report I've seen of this problem, so AFAIK it isn't an issue in other VMs. But maybe it's just that my intuition differs from yours as to what the natural syscall implementation is, so I could be wrong.)

I have compiled multiple tools into Webassembly with Emscripten and this is the first time this error occurred, so it also has to do with how the application does file operations it seems.

What if we would do the following? (untested)

```
	if (__wasi_syscall_ret(__wasi_fd_read(f->fd, iov[0].iov_len ? (struct __wasi_iovec_t*)iov : ((struct __wasi_iovec_t*)iov) + sizeof(iovec), iov[0].iov_len ? 2 : 1, &num))) {
		num = -1;
	}
```

**Comment by kripken** [comment] 2023-04-27 20:27
@jerbob92 

> What if we would do the following?

I didn't check the pointer math but the approach looks reasonable to me, as it avoids linking in another syscall (and just a few more bytes to check for what to send is probably fine, as it also saves a tiny amount of work). Would you like to open a PR?

**Comment by sbc100** [comment] 2023-04-28 01:26
The issue has already been fixed in wazero, right?  Why would still need to change anything here?

**Comment by jerbob92** [comment] 2023-05-01 06:57
> What do you mean by "wouldn't actually be handled by upstream musl, it would be ignored." 

I'm talking about `__stdio_read` specifically, yes it creates two iovs, but it only uses both of them if the first one is not 0.

>  The issue has already been fixed in wazero, right? Why would still need to change anything here?

Like I said in the initial issue: "But I still wanted to open this ticket to check with you what should be expected, since other runtimes might also have issues with this."

Just wanted to make sure that the implementation makes sense and to prevent future issues with other runtimes. Emscripten doesn't necessarily have to change anything, but I feel it would make more sense to replicate the original behavior of musl __stdio_read.

**Comment by sbc100** [comment] 2023-05-01 16:41
> Just wanted to make sure that the implementation makes sense and to prevent future issues with other runtimes. Emscripten doesn't necessarily have to change anything, but I feel it would make more sense to replicate the original behavior of musl __stdio_read.

I'm afraid I don't see any compelling reason to do that.  Whatever reason musl had to prefer the non-"v" version of the read system call don't apply here (AFAICT) since we don't have the non-"v" version in WASI at all.

**Closed** 2023-05-01 19:02 UTC
