### ISSUE TITLE
Out of memory  iOS 16.4

### ISSUE THREAD

**Issue by Alexufo** [emscripten-core/emscripten#19144] opened 2023-04-06 16:26 UTC
We updated from iOS 16.2 to 16.4 and get `Out Of memory` in console from emscripten generated js code. We have localized the problem.

Try to put this part of code in safari iOS 16.4 console to reproduce:

```js
      wasmMemory = new WebAssembly.Memory({
                          "initial": 205520896 / 65536,
                          "maximum": 2147483648 / 65536,
                          "shared": true
                      });
```
Try to set shared : false and WebAssembly will be created successfully.

**Comment by kripken** [comment] 2023-04-06 16:34
What is the error in the dev console when shared is true?

Perhaps the issue is Safari doesn't support growing shared memories, though the [bug tracker](https://bugs.webkit.org/show_bug.cgi?id=218693) suggests it should.

I don't have a Mac or iPhone but people with either that can try that code to the see the error would be helpful.

Either way, though, as this is specific to WebKit we should open a bug and move discussion to there.

**Comment by Alexufo** [comment] 2023-04-06 18:02
> What is the error in the dev console when shared is true?
Out Of memory

**Comment by yunku2002** [comment] 2023-04-14 08:13
Halving the maximum works as a band-aid fix for me : )

**Comment by yunku2002** [comment] 2023-04-14 08:23
I am on iOS 16.0, by the way, and these people seem to face the same issue https://github.com/godotengine/godot/issues/70621.

**Comment by mithrendal** [comment] 2023-04-15 12:11
I am facing this too when using shared mem … issue is not only in 16.x but also in iOS15.x … while Safari MacOS has no problem to get the memory … workaround so far is using fixed mem size and no auto grow

**Comment by dr-matt** [comment] 2024-09-23 17:52
FYI - for us this issue is fixed in ios / safari 18.

**Closed** 2024-09-23 19:37 UTC
