### ISSUE TITLE
`-s MODULARIZE=1` does not work with pthreads

### ISSUE THREAD

**Issue by surma** [emscripten-core/emscripten#7448] opened 2018-11-03 14:39 UTC
`-s MODULARIZE=1` doesn’t seem to work with pthreads. 

It compiles with no warning or errors, it loads and spawns workers. But and then pthread-main.js starts throwing errors. The compiler should catch this.

<img width="685" alt="screen shot 2018-11-03 at 2 38 58 pm" src="https://user-images.githubusercontent.com/234957/47953487-3bf75500-df76-11e8-85b9-ba9f857d98ee.png">

**Comment by kripken** [comment] 2018-11-04 19:59
Thanks @surma, after looking into this, the issue is that `pthread-main.js` (the script `new Worker` is called with) overrides things in the global namespace before loading the main JS, such as `ENVIRONMENT_IS_PTHREAD`. In modularize mode the main JS is in a function scope, so those are not picked up.

Opened #7450 to show an error for that.

Fixing this should not be too hard, we should move the customizations in pthread-main.js into the normal JS, and leave pthread-main.js with just the loading of the main JS, with `Module.inPthread` or something like that set to true, so that the normal JS knows to apply those customizations.

**Comment by jakogut** [comment] 2018-11-20 20:06
@juj Which branch implements this? I'd be happy to give it a test.

**Comment by kripken** [comment] 2018-11-20 21:55
@juj - is that code ready to be submitted now? I think all the other PRs have landed.

**Comment by briangavin** [comment] 2018-12-14 13:42
Any progress on this issue?

**Comment by VirtualTim** [comment] 2019-02-01 08:02
@juj What's going on with this issue? Is there any eta on when your patch should be merged?

**Comment by juj** [comment] 2019-02-01 08:59
> @juj What's going on with this issue? Is there any eta on when your patch should be merged?

You can follow the patch PR at #7667.

**Comment by niklasf** [comment] 2019-02-14 15:27
@juj Thank you very much for all your work here.

When creating a second instance of a module it fails with `Uncaught TypeError: Cannot set property '_stdin' of undefined` near code like:

```
        var _stdin;
        if (ENVIRONMENT_IS_PTHREAD)
            _stdin = PthreadWorkerInit._stdin;
        else
            PthreadWorkerInit._stdin = _stdin = 1036288;
```

**Comment by brion** [comment] 2019-02-14 15:43
@niklasf I've got a test case for that on https://github.com/emscripten-core/emscripten/pull/8035 -- the ENVIRONMENT_IS_PTHREAD var leaks into global state, causing some of the logic to get confused on the second run.

Should get fixed up soon; as a workaround, you can run `delete window.ENVIRONMENT_IS_PTHREAD` before your second instantiation.

**Comment by niklasf** [comment] 2019-06-23 11:51
Looks like this has been fixed, possibly via https://github.com/emscripten-core/emscripten/pull/8306.

**Comment by kripken** [comment] 2019-06-24 18:24
Thanks @niklasf - yes, this has been fixed. May have been https://github.com/emscripten-core/emscripten/pull/7667 too.

**Closed by kripken** 2019-06-24 18:24 UTC
