### ISSUE TITLE
Emulating 64-bit longs

### ISSUE THREAD

**Issue by httpdigest** [emscripten-core/emscripten#3369] opened 2015-04-19 11:14 UTC
I have a question regarding 64-bit integers. As I understand those have no corresponding data type in JavaScript and a 64-bit floating point double is the closest that we can get there.

The Emscripten Wiki http://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html#code-that-compiles-but-might-run-slowly as well as the issue https://github.com/kripken/emscripten/issues/103 mentions 64-bit integer arithmetic being emulated and therefore running slower than native 64-bit integer arithmetic would be had there been support in JavaScript for it and had it been implemented via hardware arithmetic operations in the browsers.

The Wiki does not seem to mention, though, that emulation can produce incorrect results or in which cases exactly incorrect results would occur.
One example would be when printing out LLONG_MAX via printf and %lld. This will give a value that has the least significant three decimal digits rounded to zero.
Is "printing" a long value the only issue here whereas arithmetics would still be performed/emulated correctly by Emscripten's generated code?
Or would for large long values computations also yield rounded results because they might be based on double arithmetic?

So the question is, in which circumstance would a program observe incorrect results when using long long in C?
I guess, one answer would be "A program observes an incorrect 64-bit long value whenever that value needs to go trough native JavaScript functions which are not compiled via Emscripten, where it would then be converted to a double."
Is this correct?

Given this, could fprint'ing a C 64-bit integer value then instead be done by first C-toString'ing that real 64-bit long value and handing that string to the JavaScript native print function?

**Comment by kripken** [comment] 2015-04-20 18:24
Any incorrectness would definitely be a bug, that should be filed and fixed. Even printf of longs should work (and does as far as I know).

But it is very possible bugs exist in the printf layer in particular. Below that, pure computation has been fuzzed fairly heavily, so I'm confident in it.

**Comment by geekbeast** [comment] 2015-08-06 18:57
We're hitting a bug where C++ computations are consistently off in a 100% reproducible way. Should we create a new issue or just update this one?

**Comment by RobinZ16** [comment] 2015-08-06 22:47
Following up to the error that @geekbeast mentioned:
We actually realized that our bug was due to how emscripten handle unsigned long and unsigned long longs in different ways.

The code below produces the strange behavior of setting both the n-th and (32+n)-th bit to `1`. This is fixed by changing `ul` -> `ull`. This behavior isn't exhibited when running with the g++ compiler.

Version:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.34.4
clang version 3.7.0 
Target: x86_64-apple-darwin14.4.0
Thread model: posix
INFO     root: (Emscripten: Running sanity checks)
```

Code:
```c++
unsigned long long x = 0ull;
unsigned int n = 5; //let n be between 0 and 63
x |= (1ul << (n & 63ul));
```

**Comment by kripken** [comment] 2015-08-07 00:49
Is your native system 64-bit?

`ul` is a long, which on a 32-bit platforms is generally 32-bit, but on 64-bit platforms would be generally 64-bit. You must indeed use `ull` (long long) to get a 64-bit integer on both 32 and 64-bit platforms.

If you build with `-m32` on your native system, I think you'll see the same behaior as emscripten.

**Comment by howpenghui** [comment] 2015-08-07 04:48
The native system is 64 bit.

**Comment by juj** [comment] 2015-08-07 06:32
Tested building this application

	#include <stdio.h>
	#include <stdlib.h>
	#include <emscripten.h>

	unsigned int __attribute__((noinline)) foo() { return emscripten_random() < -10 ? 0 : 5; }

	int main()
	{
		unsigned long long x = 0ull;
		unsigned int n = foo(); //let n be between 0 and 63
		x |= (1ul << (n & 63ul));
		printf("%llu\n", x);
	}

with `em++ a.cpp -o a.html -O3`, and it prints out 32 when run.

My hunch is that you are dealing with an unaligned 64-bit quantity in your program. Try building with `-s SAFE_HEAP=1` to add assertion checks to detect and abort in such scenarios.

**Closed** 2019-09-07 03:41 UTC
Labels: wontfix
