### ISSUE TITLE
wasm-ld emits invalid wasm with bitcode inputs that disagree between function types, one of whom is variadic

### ISSUE THREAD

**Issue by vargaz** [emscripten-core/emscripten#8770] opened 2019-06-09 07:45 UTC
Version: 1.38.34-upstream
Test file:
```
char mmap ();

int
main ()
{
	return mmap ();
}
```
This is the test file generated by AC_CHECK_FUNCS(mmap)

This fails with:
```
(source emsdk_env.sh && emconfigure emcc -o conftest -s WASM_OBJECT_FILES=0 -s WASM=1 mmap.c)
```
The failure is:
```
[parse exception: attempted pop from empty stack / beyond block start boundary at 515 (at 0:515)]
Fatal: error in parsing input
shared:ERROR: '/Users/vargaz/git/wasm/sdks/builds/toolchains/emsdk/upstream/bin/wasm-emscripten-finalize /tmp/emscripten_temp_2Buyyd/conftest.wasm -o /tmp/emscripten_temp_2Buyyd/conftest.wasm.o.wasm --detect-features --global-base=1024 --initial-stack-pointer=5243904' failed (1)
shared:ERROR: Configure step failed with non-zero return code: 1.  Command line: emcc -o conftest -s WASM_OBJECT_FILES=0 -s WASM=1 mmap.c at /Users/vargaz/git/wasm/sdks/builds
```

**Comment by kripken** [comment] 2019-06-09 17:35
Thanks @vargaz . I can confirm this happens, and is specific to the wasm backend using bitcode object files.

Simplified STR:
```
emcc -s WASM_OBJECT_FILES=0 mmap.c
```

@sbc100 - this looks like a wasm-ld issue with linking bitcode. mmap is normally defined with params `i32, i32, i32, i32, i32, i64` and that is the signature mentioned in libc.bc. The test file here defines it with no params, so in LLVM IR it's `declare signext i8 @mmap(...)`. Then wasm-ld emits a wasm that has a confusion between the two, e.g. wabt says
```
a.out.wasm:0000203: error: type mismatch in call, expected [i32, i32, i32, i32, i32, i64] but got []
```

**Comment by sbc100** [comment] 2019-06-10 12:44
Interesting.. its seems to only happen with "--lto-O0".   Normally what happens (and what happens at lto-O2) is that llvm would generates a call to dummy function called `__mmap_bitcast_invalid` which would trap at runtime.

**Comment by sbc100** [comment] 2019-08-21 00:23
Fix is in https://reviews.llvm.org/D66508

**Closed** 2019-08-21 22:37 UTC
