### ISSUE TITLE
Non-default EXPORT_NAME breaks node+pthreads even when MODULARIZE=0

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#15586] opened 2021-11-19 23:26 UTC
This doesn't seem to be explained in the docs, but setting EXPORT_NAME to a non-default value seems to break node+pthreads, even when it's done without setting the MODULARIZE flag.

When compiling this file:
```
int main() {}
```
using
```
emcc -pthread -s EXPORT_NAME=foo -s PROXY_TO_PTHREAD test.cc
```
and running using
```
node --experimental-wasm-threads --experimental-wasm-bulk-memory a.out.js
```
it fails with
```
worker.js onmessage() captured an uncaught exception: ReferenceError: __filename is not defined
pthread sent an error! undefined:undefined: __filename is not defined
pthread sent an error! undefined:undefined: __filename is not defined

a.out.js:160
      throw ex;
      ^
ReferenceError [Error]: __filename is not defined
    at eval (eval at importScripts (a.out.worker.js:38:16), <anonymous>:34:13)
    at eval (<anonymous>)
    at importScripts (a.out.worker.js:38:16)
    at self.onmessage (a.out.worker.js:101:9)
    at MessagePort.<anonymous> (a.out.worker.js:24:5)
```

I understand I could avoid changing the EXPORT_NAME when using node, but this requirement is not explained anywhere, and the obscure error message doesn't help.

**Comment by rbenet** [comment] 2022-05-06 16:25
FWIW, This seems like a duplicate of  #14140

**Comment by sbc100** [comment] 2022-06-07 23:21
Closing as dup

**Closed by sbc100** 2022-06-07 23:21 UTC
