### ISSUE TITLE
-sWASM_BIGINT generates mutually incompatible setValue/getValue() impls

### ISSUE THREAD

**Issue by sgbeal** [emscripten-core/emscripten#17322] opened 2022-06-27 09:38 UTC
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.13 (531257621816c200bc7c3be53129494afd029aec)
clang version 15.0.0 (https://github.com/llvm/llvm-project 5c6ed60c517c47b25b6b25d8ac3666d0e746b0c3)
Target: wasm32-unknown-emscripten
Thread model: posix
```

When building with `-sWASM_BIGINT`, the impls of `getValue()` and `setValue()` are inconsistent in how they handle i64 values:

```js
  function getValue(ptr, type = 'i8') {
...
        case 'i64': return Number(HEAP64[((ptr)>>3)]);
...
    }

  function setValue(ptr, value, type = 'i8') {
...
        case 'i64': HEAP64[((ptr)>>3)] = BigInt(value); break;
...
    }
```

Note the `Number(...)` wrapper around `getValue()`'s impl.

That discrepancy leads to i64 _return_ values working fine but i64 output pointer parameters (which are necessarily fetched via `getValue()`) to be silently mangled. That, in turn, leads to developers spending half a day scratching their head wondering why their output parameters behave differently than their `return` values ;). For example, from C:

```c
int64_t foo( int64_t * arg ){
  *arg = 9007199254740991 /* == JS Number.MAX_SAFE_INTEGER */ * 2;
  return *arg;
}
```

will result, JS-side, in two different values for the return result and the output pointer.

The following workaround "works for me," but only because i use `--post-js` and thus have code-/scope-level access to overwrite `getValue()`:

```js
    if(Module['HEAP64']){
        const oldGetVal = getValue;
        getValue = Module['getValue'] = function(ptr,type='i8'){
            return ('i64'===type)
                ? Module['HEAP64'][ptr>>3]
                : oldGetVal(ptr,type);
        };
    }
```

That "works for me" with no issues so far, but having to overwrite `getValue()` that way is less than ideal and completely infeasible for clients who don't use `--post-js` to inject such a kludge.

Please consider removing the `Number(...)` wrapper from the i64 part of the `getValue()` impl. Whether or not it should be simply removed or replaced with `BigInt(...)` is unclear. Simply removing it works for me, but that admittedly somewhat surprises me.

**Comment by kripken** [comment] 2022-06-27 23:18
Good catch. I agree, we should remove that `Number` cast. A PR would be welcome!

**Comment by sgbeal** [comment] 2022-06-28 00:24
> A PR would be welcome!

As a long-time developer for [the Fossil SCM](https://fossil-scm.org) i avoid git _like the plague_, doing nothing with it more advanced than cloning, and wouldn't even know where to begin to create a PR ;).

**Comment by kripken** [comment] 2022-06-28 17:23
Heh, ok @sgbeal :smile: 

I took a minute to look into this. Looks like `getValue` just uses `{{{ makeGetValue }}}`, so fixing that (removing the cast to Number there on a bigint) might fix a more general bug. That is, right now with WASM_BIGINT reading an `i64` returns a JS number, silently. I pushed a job to CI to see if any tests break by changing that, and looks like `other.test_memory64` fails, as well as many wasm64 tests like `wasm64.test_zero_struct_varargs`. So the fix isn't that simple, and someone would need to look into the details more - we seem to be depending on the automatic conversion to Number somewhere.

cc @sbc100

**Comment by sgbeal** [comment] 2022-06-28 20:36
> we seem to be depending on the automatic conversion to Number somewhere.

i was afraid that might be the case. Thank you for looking into, though! For the time being my local workaround is working just fine, but i don't have an existing code base which it risks break. That local fix is only possible, though, for people who use `--post-js` because that's the only way that they can overwrite the scope-local copy of `getValue`. Thus it "really should" be fixed upstream, even if doing so requires (due to backwards compatibility constraints) a compile-time flag or something similar to enable the bigint-friendly behavior.

**Comment by sbc100** [comment] 2022-06-29 09:11
I think the correct fix is in #17341

**Comment by merceyz** [comment] 2022-06-29 11:52
Seems like a duplicate of https://github.com/emscripten-core/emscripten/issues/16272

**Comment by sbc100** [comment] 2022-06-29 11:55
Ah yes, thanks for pointing that out.  Closing as dup of #16272.

**Closed by sbc100** 2022-06-29 11:55 UTC
Labels: good first bug, help wanted, JavaScript
