### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14576] opened 2021-07-01 07:22 UTC
We are using Emscripten to decode and  the stream. When playing at the remote end, we will report an error `Maximum call stack size exceeded`，how to solve the problem ? memcpy must be smaller than 8192 ?

**Comment by kripken** [comment] 2021-07-01 17:48
The call stack is the stack used by the VM for calls, which includes locals. So a large number of calls (a very deep recursion, for example) or calls to functions with very many local variables, can cause this.

If the problem isn't infinite recursion, then this is very rare, and usually fixed by optimizing the wasm (as unoptimized wasm uses far more locals).

**Closed** 2021-08-05 06:29 UTC
