### ISSUE TITLE
Optimization (O1 or O2) is failing in threading

### ISSUE THREAD

**Issue by sylvestre** [emscripten-core/emscripten#2697] opened 2014-08-21 06:54 UTC
With emscripten 1.22.1, nodejs 0.10.29~dfsg-1 and llvm/clang 3.4:

```
./emcc -O1 foo2.cpp -o hello.html
clang: warning: argument unused during compilation: '-nostdinc++'
INFO     root: =======================================
INFO     root: bootstrapping relooper...
INFO     root:   bootstrap phase 1
clang: warning: argument unused during compilation: '-nostdinc++'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 380, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())
```

Breaking the build manually shows:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
ERROR    root: bootstrapping relooper failed. You may need to manually create relooper.js by compiling it, see src/relooper/emscripten
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
Traceback (most recent call last):
  File "/home/sylvestre/dev/debian/pkg-llvm/emscripten/emscripten-1.22.1/emscripten.py", line 1490, in <module>
Traceback (most recent call last):
  File "./emcc", line 1646, in <module>
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
    _main(environ=os.environ)
  File "/home/sylvestre/dev/debian/pkg-llvm/emscripten/emscripten-1.22.1/emscripten.py", line 1478, in _main
    racquire()
KeyboardInterrupt
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/sylvestre/dev/debian/pkg-llvm/emscripten/emscripten-1.22.1/tools/shared.py", line 1457, in emscripten
    temp_files.run_and_clean(lambda: main(
  File "/home/sylvestre/dev/debian/pkg-llvm/emscripten/emscripten-1.22.1/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/home/sylvestre/dev/debian/pkg-llvm/emscripten/emscripten-1.22.1/emscripten.py", line 1486, in <lambda>
    jsrun.timeout_run(Popen(cmdline, stdout=PIPE), None, 'Compiling')
  File "/home/sylvestre/dev/debian/pkg-llvm/emscripten/emscripten-1.22.1/tools/jsrun.py", line 14, in timeout_run
    out = proc.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 791, in communicate
    DEBUG_CACHE=DEBUG_CACHE,
  File "/home/sylvestre/dev/debian/pkg-llvm/emscripten/emscripten-1.22.1/emscripten.py", line 1364, in main
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
Process PoolWorker-3:
Traceback (most recent call last):
    shared.Building.ensure_relooper(relooper)
  File "/home/sylvestre/dev/debian/pkg-llvm/emscripten/emscripten-1.22.1/tools/shared.py", line 1709, in ensure_relooper
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    1/0
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
ZeroDivisionError: integer division or modulo by zero
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    racquire()
KeyboardInterrupt
    return recv()
KeyboardInterrupt
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
KeyboardInterrupt
```

**Comment by lockie** [comment] 2015-06-16 20:58
Looks like debian packaging issue; got exactly the same error trying to compile ffmpeg using debian unstable packages, both with and without optimization turned on. Compiling emscripten from source resolved the issue.

**Comment by acterhd** [comment] 2015-09-05 18:02
How to fix?

**Comment by andrewchambers** [comment] 2015-09-07 04:06
This is happening for me with the ubuntu emscripten package.

**Comment by acterhd** [comment] 2015-09-07 12:53
I installed from archive and works.

**Comment by sylvestre** [comment] 2015-09-08 07:59
Yep, until the emscripten llvm backend (fastcomp) is merged into llvm, emscripten should not be used on Debian or Ubuntu.

**Comment by juj** [comment] 2015-09-08 14:53
There is no reason to not use Emscripten on Ubuntu or Debian. A Ubuntu 14.04 box is used by the Emscripten unit test farm to test Emscripten functionality on Linux. The official recommended way to install Emscripten on all Linuxes is to use the Emscripten SDK and have it build and set up the necessary components from source. We do not recommend using the different packages from package managers, since they are often out of date.

**Comment by sylvestre** [comment] 2015-09-08 15:08
sorry, my bad. I meant the debian & ubuntu packages (FYI, I am the maintainer of emscripten on these distros)

**Comment by davidzchen** [comment] 2015-09-30 07:35
What are the plans to bring the Ubuntu/Debian packages up to date? Is the plan still wait for fastcomp to be merged into llvm first? If so, what is the timeline for that?

It's not ideal to not be able to use the package from the package managers.

**Comment by kripken** [comment] 2015-09-30 20:51
Most of emscripten's fastcomp backend will probably be replaced by the new WebAssembly backend in development in upstream LLVM. I don't think there is a timeline yet for when that will be usable.

**Comment by mnuzzolilo** [comment] 2016-05-12 03:08
Same thing happening to me as of May 2016

**Comment by mavidser** [comment] 2016-07-13 07:43
Has anyone found any way around this?

**Comment by mnuzzolilo** [comment] 2016-07-13 07:59
I was only able to build my modules using a mac. Linux and Windows both failed for whatever reason.

**Comment by juj** [comment] 2016-07-13 15:04
Any chance someone would have a reproducible STR for this? (exact steps starting from `git clone`)

**Comment by hiemal** [comment] 2016-10-12 20:31
The issue happened after upgrading to 14.04. Seems like a debian packaging issue

**Comment by juj** [comment] 2016-10-13 16:04
Does this occur on the test suite on latest incoming? The installation steps would be

    git clone https://github.com/juj/emsdk.git
    cd emsdk
    ./emsdk install sdk-incoming-64bit
    ./emsdk activate sdk-incoming-64bit
    source ./emsdk_env.sh
    cd emscripten/incoming
    export EMSCRIPTEN_BROWSER=/path/to/firefox/nightly/firefox
    export JIT_OPTION_asmJSAtomicsEnable=true
    python tests/runner.py browser.test_pthread_*

**Comment by arank** [comment] 2017-04-05 00:34
Any way to solve this yet?

**Closed** 2019-09-06 15:41 UTC
Labels: wontfix
