### ISSUE TITLE
switching to the LLVM backend gives code that throws at runtime with TypeError: m[p[14305]] is not a function

### ISSUE THREAD

**Issue by lovasoa** [emscripten-core/emscripten#10617] opened 2020-03-01 21:33 UTC
I am currently trying to port [sql.js](https://github.com/kripken/sql.js) to the latest LLVM backend of emscripten.

One of the issues that I encountered is that files generated with `-s WASM=0` and optimizations enabled generate code that fails at runtime with `TypeError: m[p[14305]] is not a function` ([see full compilation and runtime logs](https://github.com/kripken/sql.js/runs/478283449)).
The file is compiled with 
```
emcc \
    --memory-init-file 0 \
    -s RESERVED_FUNCTION_POINTERS=64 \
    -s ALLOW_TABLE_GROWTH=1 \
    -s EXPORTED_FUNCTIONS=@src/exported_functions.json \
    -s EXTRA_EXPORTED_RUNTIME_METHODS=@src/exported_runtime_methods.json \
    -s SINGLE_FILE=0 \
    -s NODEJS_CATCH_EXIT=0 \
    -s INLINING_LIMIT=50 \
    -O3 -flto --llvm-lto 1 --closure 1 \
    -s WASM=0 \
    out/sqlite3.bc out/extension-functions.bc \ 
    --pre-js src/api.js \
    -o dist/sql-asm.js
```

The issue can be reproduced on the [emsdk-1.39 branch of sql.js](https://github.com/kripken/sql.js/tree/emsdk-1.39)

When compiled without optimizations (with `emcc --memory-init-file 0 -s RESERVED_FUNCTION_POINTERS=64 -s ALLOW_TABLE_GROWTH=1 -s EXPORTED_FUNCTIONS=@src/exported_functions.json -s EXTRA_EXPORTED_RUNTIME_METHODS=@src/exported_runtime_methods.json -s SINGLE_FILE=0 -s NODEJS_CATCH_EXIT=0 -s INLINING_LIMIT=10 -s ASSERTIONS=1 -O1 -s WASM=0 out/sqlite3.bc out/extension-functions.bc --pre-js src/api.js -o dist/sql-asm-debug.js
`), the error disappears.

**Comment by lovasoa** [comment] 2020-03-01 21:43
Removing ` -flto --llvm-lto 1 --closure 1` and adding `-s ASSERTIONS=1`, I get the following slightly more informative error : 

```
ophir@ordophir:~/Developpement/sql.js$ emcc --memory-init-file 0 -s RESERVED_FUNCTION_POINTERS=64 -s ALLOW_TABLE_GROWTH=1 -s EXPORTED_FUNCTIONS=@src/exported_functions.json -s EXTRA_EXPORTED_RUNTIME_METHODS=@src/exported_runtime_methods.json -s SINGLE_FILE=0 -s NODEJS_CATCH_EXIT=0 -s INLINING_LIMIT=50 -O3 -s ASSERTIONS=1 -s WASM=0 out/sqlite3.bc out/extension-functions.bc --pre-js src/api.js -o dist/sql-asm.js
ophir@ordophir:~/Developpement/sql.js$ mv dist/sql-asm.js out/tmp-raw.js
ophir@ordophir:~/Developpement/sql.js$ cat src/shell-pre.js out/tmp-raw.js src/shell-post.js > dist/sql-asm.js
ophir@ordophir:~/Developpement/sql.js$ node test/test_database.js asm
failed to asynchronously prepare wasm: ReferenceError: Ea is not defined
ReferenceError: Ea is not defined
ReferenceError: Ea is not defined
Error: ReferenceError: Ea is not defined
    at Object.Module.onAbort (/home/ophir/Developpement/sql.js/dist/sql-asm.js:40:20)
    at abort (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:13409)
    at /home/ophir/Developpement/sql.js/dist/sql-asm.js:150:15308
Error: abort(ReferenceError: Ea is not defined) at Error
    at jsStackTrace (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:16484)
    at stackTrace (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:16652)
    at abort (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:13502)
    at /home/ophir/Developpement/sql.js/dist/sql-asm.js:150:15308
Error: abort(ReferenceError: Ea is not defined) at Error
    at jsStackTrace (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:16484)
    at stackTrace (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:16652)
    at abort (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:13502)
    at /home/ophir/Developpement/sql.js/dist/sql-asm.js:150:15308
/home/ophir/Developpement/sql.js/dist/sql-asm.js:150
)(asmLibraryArg,wasmMemory,wasmTable);return{"exports":exports}},instantiate:function(binary,info){return{then:function(ok){ok({"instance":new WebAssembly.Instance(new WebAssembly.Module(binary,info))});return{catch:function(){}}}}},RuntimeError:Error};wasmBinary=[];if(typeof WebAssembly!=="object"){abort("No WebAssembly support found. Build with -s WASM=0 to target JavaScript instead.")}function setValue(ptr,value,type,noSafe){type=type||"i8";if(type.charAt(type.length-1)==="*")type="i32";switch(type){case"i1":HEAP8[ptr>>0]=value;break;case"i8":HEAP8[ptr>>0]=value;break;case"i16":HEAP16[ptr>>1]=value;break;case"i32":HEAP32[ptr>>2]=value;break;case"i64":tempI64=[value>>>0,(tempDouble=value,+Math_abs(tempDouble)>=1?tempDouble>0?(Math_min(+Math_floor(tempDouble/4294967296),4294967295)|0)>>>0:~~+Math_ceil((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)],HEAP32[ptr>>2]=tempI64[0],HEAP32[ptr+4>>2]=tempI64[1];break;case"float":HEAPF32[ptr>>2]=value;break;ca

Error: abort(Error: abort(ReferenceError: Ea is not defined) at Error
    at jsStackTrace (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:16484)
    at stackTrace (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:16652)
    at abort (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:13502)
    at /home/ophir/Developpement/sql.js/dist/sql-asm.js:150:15308) at Error
    at jsStackTrace (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:16484)
    at stackTrace (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:16652)
    at process.abort (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:13502)
    at process.emit (events.js:209:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
    at process.abort (/home/ophir/Developpement/sql.js/dist/sql-asm.js:150:13533)
    at process.emit (events.js:209:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
```

**Comment by sbc100** [comment] 2020-03-02 02:52
Looks like this is a wasm2js issue?  Does remove `-s WASM=0` make the issue go away?

**Comment by lovasoa** [comment] 2020-03-02 07:53
Yes, as mentioned above, the issue occurs only with WASM=0 and optimisations switched on.

**Comment by kripken** [comment] 2020-03-04 21:58
Trying to reproduce this:

 * `out/sqlite3.bc out/extension-functions.bc` don't exist on that branch, but I managed to build them with `make make out/sqlite3.bc out/extension-functions.bc` - is that correct?
 * I now have `dist/sql-asm.js`, and if I do `nodejs dist/sql-asm.js` nothing is printed, is that expected? (did I fail to reproduce the problem, or am I running it wrong?)

**Comment by lovasoa** [comment] 2020-03-04 22:20
Hello @kripken, and thank you very much for investigating this bug !
You can look at the [CI output](https://github.com/sql-js/sql.js/runs/478283449) for the exact list of steps to reproduce the bug. Starting from the clean repository sources : 

  1. Run `make dist/sql-asm.js`
  2. Run `node test/all.js asm`

**Comment by kripken** [comment] 2020-03-04 23:35
Hmm, when I do those commands I get
```
$ make dist/sql-asm.js
make: 'dist/sql-asm.js' is up to date.

$ node test/all.js asm
/usr/local/google/home/azakai/Dev/sql.js/test/load_sql_lib.js:6
    return initSqlJs().then((sql)=>{
           ^

TypeError: initSqlJs is not a function
```

**Comment by kripken** [comment] 2020-03-04 23:37
Perhaps you can make a small script that does all the building process (make commands, + that emcc command I want to debug, in the right order, + the testing command)? I basically just want a command to run where I can see if it worked, and can modify the emcc flags easily.

**Comment by lovasoa** [comment] 2020-03-05 11:09
> `TypeError: initSqlJs is not a function`

Oh, that is strange. initSqlJs is supposed to be defined if you generated `dist/sql-asm.js` with the makefile. But the `make: 'dist/sql-asm.js' is up to date.` seems to indicate that you did not start from a clean state...

Here is the script to run at the root of the repo : 

```
make # Compiles all files and makes the necessary concatenations
npm i # installs javascript test dependencies
node test/test_database.js asm # Launches a single test of the dist/sql-asm.js
```

This should allow you to reproduce the bug. Then, if you want to fiddle with emscripten compilation flags, you can run : 

```
emcc --memory-init-file 0 -s RESERVED_FUNCTION_POINTERS=64 -s ALLOW_TABLE_GROWTH=1 -s EXPORTED_FUNCTIONS=@src/exported_functions.json -s EXTRA_EXPORTED_RUNTIME_METHODS=@src/exported_runtime_methods.json -s SINGLE_FILE=0 -s NODEJS_CATCH_EXIT=0 -s INLINING_LIMIT=50 -O2 -s ASSERTIONS=1 -s WASM=0 out/sqlite3.bc out/extension-functions.bc --pre-js src/api.js -o out/tmp-raw.js && cat src/shell-pre.js out/tmp-raw.js src/shell-post.js > dist/sql-asm.js
```

and then relaunch the test with 

```
node test/test_database.js asm
```

**Comment by lovasoa** [comment] 2020-03-06 10:08
Indeed , I just launched a build with emscripten tip-of-tree and [here are the results](https://github.com/sql-js/sql.js/runs/489870250?check_suite_focus=true). It works. 
Was there a specific change between the latest release and the tip-of-tree that may have fixed this ?

**Comment by lovasoa** [comment] 2020-03-06 12:36
Do you have an estimate for the date of next release ? Since emscripten-core/emscripten#10616 was fixed in master too, sql.js should be able to switch to the LLVM backend as soon as the next version is released.

**Comment by jpharvey** [comment] 2020-03-06 14:05
I have been having similar problems. With tot it is now working with -O2. With -O3 i get 
`Possible Unhandled Promise Rejection: TypeError: "o[r[((r[(F >> 2)] + 24) >> 2)]] is not a function"
    qh http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:21
    L9 http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:33
    KDb http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:37
    Lsj http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:101
    ___wasm_call_ctors http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    func http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    callRuntimeCallbacks http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    initRuntime http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    doRun http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    run http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    runCaller http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    removeRunDependency http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    receiveInstance http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    receiveInstantiatedSource http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:115
    handle http://127.0.0.1:8081/js/ptc/thingview/libthingview.js:1
`

and with -Os it claimed it ran out of stack space. Increasing the stack to 8Mb it was running but i think was in an infinite loop somewhere. 
The wasm versions with the same compiler flags run fine. This is a large commercial project so not sure how to get a test case to you since all the smaller versions of the code work fine.

**Comment by kripken** [comment] 2020-03-06 17:44
@lovasoa I suspect the fix might be #10522

We just tagged 1.39.9 right now, which includes that.

@jpharvey A few things you can check on your side, if you can't provide a testcase: build with `-s SAFE_HEAP`, and/or `-s ASSERTIONS`, and/or [sanitizers](https://emscripten.org/docs/debugging/Sanitizers.html). Or, if nothing else, building with `--profiling` (to get func names) and adding manual printfs in the source (that looks like a bad function pointer call, so finding what's going on with the pointer might show something).

**Comment by lovasoa** [comment] 2020-03-07 22:56
[sql.js now uses the latest emscripten](https://github.com/sql-js/sql.js/commit/1e7b28fa8f9e2919a6325e3a3814364adc88332e). Thank you !

**Comment by kripken** [comment] 2020-03-07 23:07
@lovasoa Great! I think we can close this then.

Did you notice if code size or performance changed, btw?

**Closed by kripken** 2020-03-07 23:07 UTC

**Comment by lovasoa** [comment] 2020-03-08 00:35
I didn't try to benchmark performance, but here are the file size results : 

```
Archive:  sql.js.fastcomp.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
       71  03-06-2020 14:37   .gitignore
 18957605  03-06-2020 14:37   sql-asm-debug.js
  3099139  03-06-2020 14:37   sql-asm-memory-growth.js
  3097789  03-06-2020 14:37   sql-asm.js
   305942  03-06-2020 14:37   sql-wasm-debug.js
  1708590  03-06-2020 14:37   sql-wasm-debug.wasm
    52602  03-06-2020 14:37   sql-wasm.js
  1487062  03-06-2020 14:37   sql-wasm.wasm
 18960010  03-06-2020 14:37   worker.sql-asm-debug.js
  3100194  03-06-2020 14:37   worker.sql-asm.js
   308347  03-06-2020 14:37   worker.sql-wasm-debug.js
    55007  03-06-2020 14:37   worker.sql-wasm.js
---------                     -------
 51132358                     12 files
```

```
   Archive:  sql.js.llvm.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
       71  03-06-2020 18:17   .gitignore
 10762807  03-06-2020 18:17   sql-asm-debug.js
  2620303  03-06-2020 18:17   sql-asm-memory-growth.js
  2615881  03-06-2020 18:17   sql-asm.js
   292473  03-06-2020 18:17   sql-wasm-debug.js
  1190796  03-06-2020 18:17   sql-wasm-debug.wasm
    52834  03-06-2020 18:17   sql-wasm.js
  1157661  03-06-2020 18:17   sql-wasm.wasm
 10765212  03-06-2020 18:17   worker.sql-asm-debug.js
  2618286  03-06-2020 18:17   worker.sql-asm.js
   294878  03-06-2020 18:17   worker.sql-wasm-debug.js
    55239  03-06-2020 18:17   worker.sql-wasm.js
---------                     -------
 32426441                     12 files
```

So it looks like we have
 - a 20% file size decrease on `sql-wasm.wasm`, from 1.5 Mb to 1.2 Mb, and
 - a 15% file size decrease on `sql-asm.js`, from 3.1 Mb to 2.6 Mb
 🎉

**Comment by kripken** [comment] 2020-03-08 17:03
Nice!
