### ISSUE TITLE
 wasm-ld: error: unable to find library -lc

### ISSUE THREAD

**Issue by craigmayhew** [emscripten-core/emscripten#9807] opened 2019-11-08 12:04 UTC
Hello, I'm unsure where to begin debugging this - any pointers much appreciated.
This has followed advice from https://github.com/emscripten-core/emscripten/issues/9798#issuecomment-551339189 and now runs into this new error.
The source code is here if needed: https://github.com/craigmayhew/golem-tasks/tree/master/gwasm/compression

```
golem-tasks/gwasm/compression on  master [!?] is 📦 v0.1.0 via 🦀 v1.40.0-nightly 
❯ cd /mnt/c/Users/user/Documents/GitHub/emsdk/

emsdk on  master via 🐍 v2.7.15+ 
❯ ./emsdk install 1.38.46-upstream
Installing SDK 'sdk-releases-upstream-c89919d252f7cea00d944bdf3bd630cd3c7e7388-64bit'..
Installing tool 'releases-upstream-c89919d252f7cea00d944bdf3bd630cd3c7e7388-64bit'..
Downloading: /mnt/c/Users/user/Documents/GitHub/emsdk/zips/c89919d252f7cea00d944bdf3bd630cd3c7e7388-wasm-binaries.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/c89919d252f7cea00d944bdf3bd630cd3c7e7388/wasm-binaries.tbz2, 162547484 Bytes
Unpacking '/mnt/c/Users/user/Documents/GitHub/emsdk/zips/c89919d252f7cea00d944bdf3bd630cd3c7e7388-wasm-binaries.tbz2' to '/mnt/c/Users/user/Documents/GitHub/emsdk/upstream'
Done installing tool 'releases-upstream-c89919d252f7cea00d944bdf3bd630cd3c7e7388-64bit'.
Installing tool 'node-12.9.1-64bit'..
Downloading: /mnt/c/Users/user/Documents/GitHub/emsdk/zips/node-v12.9.1-linux-x64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.9.1-linux-x64.tar.xz, 13918928 Bytes
Unpacking '/mnt/c/Users/user/Documents/GitHub/emsdk/zips/node-v12.9.1-linux-x64.tar.xz' to '/mnt/c/Users/user/Documents/GitHub/emsdk/node/12.9.1_64bit'
Done installing tool 'node-12.9.1-64bit'.
Done installing SDK 'sdk-releases-upstream-c89919d252f7cea00d944bdf3bd630cd3c7e7388-64bit'.

emsdk on  master via 🐍 v2.7.15+ took 1m42s 
❯ ./emsdk activate 1.38.46-upstream
Writing .emscripten configuration file to user home directory /home/user/
Backing up old Emscripten configuration file in /home/user/.emscripten.old
The Emscripten configuration file /home/user/.emscripten has been rewritten with the following contents:

LLVM_ROOT = '/mnt/c/Users/user/Documents/GitHub/emsdk/upstream/bin'
BINARYEN_ROOT = '/mnt/c/Users/user/Documents/GitHub/emsdk/upstream'
EMSCRIPTEN_ROOT = '/mnt/c/Users/user/Documents/GitHub/emsdk/upstream/emscripten'
NODE_JS = '/mnt/c/Users/user/Documents/GitHub/emsdk/node/12.9.1_64bit/bin/node'
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.

   /mnt/c/Users/user/Documents/GitHub/emsdk:/mnt/c/Users/user/Documents/GitHub/emsdk/upstream/emscripten:/mnt/c/Users/user/Documents/GitHub/emsdk/node/12.9.1_64bit/bin

Set the following tools as active:
   releases-upstream-c89919d252f7cea00d944bdf3bd630cd3c7e7388-64bit
   node-12.9.1-64bit


emsdk on  master via 🐍 v2.7.15+ 
❯ source ./emsdk_env.sh
Setting environment variables:
EMSDK = /mnt/c/Users/user/Documents/GitHub/emsdk


emsdk on  master via 🐍 v2.7.15+ 
❯ cd /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/

golem-tasks/gwasm/compression on  master [!?] is 📦 v0.1.0 via 🦀 v1.40.0-nightly 
❯ cargo clean

golem-tasks/gwasm/compression on  master [!?] is 📦 v0.1.0 via 🦀 v1.40.0-nightly 
❯ cargo rustc --target=wasm32-unknown-emscripten --release --verbose -- -C link-args="-s BINARYEN_ASYNC_COMPILATION=0 -s USE_PTHREADS=1"
   Compiling libc v0.2.65
   Compiling pkg-config v0.3.17
   Compiling cc v1.0.47
     Running `rustc --crate-name build_script_build /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.65/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=dbbcf18afd1636cb -C extra-filename=-dbbcf18afd1636cb --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/build/libc-dbbcf18afd1636cb -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --cap-lints allow`
     Running `rustc --crate-name pkg_config /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.17/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=a179eacd4c58977f -C extra-filename=-a179eacd4c58977f --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --cap-lints allow`
     Running `rustc --edition=2018 --crate-name cc /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.47/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=47682c48c3de49aa -C extra-filename=-47682c48c3de49aa --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --cap-lints allow`
     Running `/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/build/libc-dbbcf18afd1636cb/build-script-build`
     Running `rustc --crate-name libc /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.65/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=74cf29fa13e4ad9f -C extra-filename=-74cf29fa13e4ad9f --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps --target wasm32-unknown-emscripten -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --cap-lints allow --cfg freebsd11 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN`
   Compiling lzma-sys v0.1.15
     Running `rustc --edition=2018 --crate-name build_script_build /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/lzma-sys-0.1.15/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=4b9042f7fcf432c5 -C extra-filename=-4b9042f7fcf432c5 --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/build/lzma-sys-4b9042f7fcf432c5 -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --extern cc=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps/libcc-47682c48c3de49aa.rlib --extern pkg_config=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps/libpkg_config-a179eacd4c58977f.rlib --cap-lints allow`
     Running `/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/build/lzma-sys-4b9042f7fcf432c5/build-script-build`
     Running `rustc --edition=2018 --crate-name lzma_sys /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/lzma-sys-0.1.15/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=18b7b3cf0f7b02e1 -C extra-filename=-18b7b3cf0f7b02e1 --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps --target wasm32-unknown-emscripten -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --extern libc=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/liblibc-74cf29fa13e4ad9f.rmeta --cap-lints allow -L native=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/build/lzma-sys-8285bba2889fc469/out -l static=lzma`
   Compiling xz2 v0.1.6
     Running `rustc --crate-name xz2 /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/xz2-0.1.6/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=d0c025bbb4d0dc74 -C extra-filename=-d0c025bbb4d0dc74 --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps --target wasm32-unknown-emscripten -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --extern lzma_sys=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/liblzma_sys-18b7b3cf0f7b02e1.rmeta --cap-lints allow -L native=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/build/lzma-sys-8285bba2889fc469/out`
   Compiling compression v0.1.0 (/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression)
     Running `rustc --edition=2018 --crate-name compression src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C 'link-args=-s BINARYEN_ASYNC_COMPILATION=0 -s USE_PTHREADS=1' -C metadata=a10e35ce4f475702 --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps --target wasm32-unknown-emscripten -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --extern xz2=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/libxz2-d0c025bbb4d0dc74.rlib -L native=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/build/lzma-sys-8285bba2889fc469/out`
error: linking with `emcc` failed: exit code: 1
  |
  = note: "emcc" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.0.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.1.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.10.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.11.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.12.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.13.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.14.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.15.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.2.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.3.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.4.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.5.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.6.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.7.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.8.rcgu.o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.9.rcgu.o" "-o" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"_rust_eh_personality\"]" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.3qmpbohzzn7ergx9.rcgu.o" "-O3" "--memory-init-file" "0" "-g0" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps" "-L" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps" "-L" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/build/lzma-sys-8285bba2889fc469/out" "-L" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/libxz2-d0c025bbb4d0dc74.rlib" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/liblzma_sys-18b7b3cf0f7b02e1.rlib" "/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/liblibc-74cf29fa13e4ad9f.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libstd-3dbe579904fbccbe.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libpanic_unwind-1f28113e3cabf146.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libhashbrown-1d571a23e43c22e2.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_std_workspace_alloc-715539682a8f65bc.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libbacktrace-91a5ceef68c6ea62.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_demangle-0dae21a0280e35c1.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libunwind-cb80fc0778a00db3.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libcfg_if-e8471076907d728c.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/liblibc-2f0c44e2ccbc4584.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/liballoc-955c0e5036a23d55.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_std_workspace_core-825ae32895b6427e.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libcore-2f7ed48dc9819ce8.rlib" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libcompiler_builtins-88cd82a8320809f8.rlib" "-l" "c" "-s" "BINARYEN_ASYNC_COMPILATION=0" "-s" "USE_PTHREADS=1" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1" "-s" "ASSERTIONS=1" "-s" "ABORTING_MALLOC=0" "-Wl,--fatal-warnings"
  = note: emcc:WARNING: WASM_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see http://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#codegen-effects
          cache:INFO: generating system library: libc-mt.a... (this will be cached in "/home/user/.emscripten_cache/wasm-obj/libc-mt.a" for subsequent builds)
          cache:INFO:  - ok
          cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/home/user/.emscripten_cache/wasm-obj/libcompiler_rt.a" for subsequent builds)
          cache:INFO:  - ok
          cache:INFO: generating system library: libc-wasm.a... (this will be cached in "/home/user/.emscripten_cache/wasm-obj/libc-wasm.a" for subsequent builds)
          cache:INFO:  - ok
          cache:INFO: generating system library: libc++abi-mt.a... (this will be cached in "/home/user/.emscripten_cache/wasm-obj/libc++abi-mt.a" for subsequent builds)
          cache:INFO:  - ok
          cache:INFO: generating system library: libc-extras.a... (this will be cached in "/home/user/.emscripten_cache/wasm-obj/libc-extras.a" for subsequent builds)
          cache:INFO:  - ok
          cache:INFO: generating system library: libdlmalloc-mt.a... (this will be cached in "/home/user/.emscripten_cache/wasm-obj/libdlmalloc-mt.a" for subsequent builds)
          cache:INFO:  - ok
          cache:INFO: generating system library: libpthread-mt.a... (this will be cached in "/home/user/.emscripten_cache/wasm-obj/libpthread-mt.a" for subsequent builds)
          cache:INFO:  - ok
          cache:INFO: generating system library: libc_rt_wasm.a... (this will be cached in "/home/user/.emscripten_cache/wasm-obj/libc_rt_wasm.a" for subsequent builds)
          cache:INFO:  - ok
          wasm-ld: error: unable to find library -lc
          shared:ERROR: '/mnt/c/Users/user/Documents/GitHub/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_eyE02n/compression.wasm --allow-undefined --lto-O0 -L/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.0.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.1.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.10.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.11.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.12.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.13.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.14.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.15.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.2.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.3.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.4.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.5.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.6.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.7.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.8.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.compression.51fs4c9m-cgu.9.rcgu.o /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/compression.3qmpbohzzn7ergx9.rcgu.o -L/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps -L/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps -L/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/build/lzma-sys-8285bba2889fc469/out -L/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/libxz2-d0c025bbb4d0dc74.rlib /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/liblzma_sys-18b7b3cf0f7b02e1.rlib /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/liblibc-74cf29fa13e4ad9f.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libstd-3dbe579904fbccbe.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libpanic_unwind-1f28113e3cabf146.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libhashbrown-1d571a23e43c22e2.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_std_workspace_alloc-715539682a8f65bc.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libbacktrace-91a5ceef68c6ea62.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_demangle-0dae21a0280e35c1.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libunwind-cb80fc0778a00db3.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libcfg_if-e8471076907d728c.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/liblibc-2f0c44e2ccbc4584.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/liballoc-955c0e5036a23d55.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_std_workspace_core-825ae32895b6427e.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libcore-2f7ed48dc9819ce8.rlib /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libcompiler_builtins-88cd82a8320809f8.rlib -lc --fatal-warnings -L/mnt/c/Users/user/Documents/GitHub/emsdk/upstream/emscripten/system/local/lib -L/mnt/c/Users/user/Documents/GitHub/emsdk/upstream/emscripten/system/lib -L/home/user/.emscripten_cache/wasm-obj /home/user/.emscripten_cache/wasm-obj/libc-mt.a /home/user/.emscripten_cache/wasm-obj/libcompiler_rt.a /home/user/.emscripten_cache/wasm-obj/libc-wasm.a /home/user/.emscripten_cache/wasm-obj/libc++abi-mt.a /home/user/.emscripten_cache/wasm-obj/libc-extras.a /home/user/.emscripten_cache/wasm-obj/libdlmalloc-mt.a /home/user/.emscripten_cache/wasm-obj/libpthread-mt.a /home/user/.emscripten_cache/wasm-obj/libc_rt_wasm.a --import-memory --import-table --shared-memory -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export rust_eh_personality --export malloc --export free --export setThrew --export __errno_location --export fflush --export emscripten_get_global_libc --export __pthread_tsd_run_dtors --export _register_pthread_ptr --export pthread_self --export __emscripten_pthread_data_constructor --export memalign --export __cxa_is_pointer_type --export __cxa_can_catch --export htonl --export htons --export ntohs --export _get_environ -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (1)
          

error: aborting due to previous error

error: could not compile `compression`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name compression src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C 'link-args=-s BINARYEN_ASYNC_COMPILATION=0 -s USE_PTHREADS=1' -C metadata=a10e35ce4f475702 --out-dir /mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps --target wasm32-unknown-emscripten -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps -L dependency=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/release/deps --extern xz2=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/deps/libxz2-d0c025bbb4d0dc74.rlib -L native=/mnt/c/Users/user/Documents/GitHub/golem-tasks/gwasm/compression/target/wasm32-unknown-emscripten/release/build/lzma-sys-8285bba2889fc469/out` (exit code: 1)

golem-tasks/gwasm/compression on  master [!?] is 📦 v0.1.0 via 🦀 v1.40.0-nightly took 1m18s 
❯
```

**Comment by sbc100** [comment] 2019-11-08 18:53
So the problem is that you are specifying `-lc` on the command line.  You should instead let emscripten at the C library.  In this case because you are building `USE_PTHREAD=1` emscripten is building and linking `libc-mt.a` rather then `libc.a`.

So even if it could find libc here you would end up linking two copies of libc, which would be bad.

**Comment by kripken** [comment] 2019-11-08 20:38
Maybe it's rust passing in the `-c`? cc @tlively as this sounds familiar.

**Comment by craigmayhew** [comment] 2019-11-09 16:33
This might be a rust limitation, or at the very least me misunderstand how to compile this. Recommend closing issue.

**Comment by tlively** [comment] 2019-11-11 01:09
I would like to figure out why Rust is passing `-lc` in the first place and fix that. Or alternatively, @sbc100 would it be reasonable for Emscripten to accept `-lc` and possibly ignore it?

**Comment by sbc100** [comment] 2019-11-11 20:38
In this case I think the correct thing to do is stop passing `-lc`.   Unless you are also passing `-nostdlib` or something add `-lc` should not be needed.

**Comment by tlively** [comment] 2020-11-11 00:55
Closing this issue as there doesn't appear to be any actionable takeaways.

**Closed by tlively** 2020-11-11 00:55 UTC
Labels: Rust integration, wontfix

**Comment by trsh** [comment] 2022-11-21 10:55
@craigmayhew did u manage to get around this issue?

**Comment by craigmayhew** [comment] 2022-11-26 21:56
@trsh I don't believe I did. I've just checked my projects commits and don't see any "fix" or documentation updates after I created this github issue. Unfortunately I haven't worked on the project where I found the issue for about 3 years so it's also not fresh in my mind! If/when I find more time I will try to compile it again and see if the issue is still present.

Hope you find a solution.
