### ISSUE TITLE
SDL2's SDL_Mixer is capable of playing wav through Mix_LoadMUS with G++, but not with em++.

### ISSUE THREAD

**Issue by MichaelMacha** [emscripten-core/emscripten#11655] opened 2020-07-16 05:01 UTC
To provide context, I'm learning SDL2 through a set of tutorials, but compiling each tutorial with emcc or em++ instead of gcc or g++. Specifically, the [Lazy Foo'](https://lazyfoo.net/tutorials/SDL/index.php) tutorials. On lesson 21, he goes on to describe SDL2's Mixer library, and compiled with g++, the program successfully runs a wav file, on repeat, as music.

I have verified this with g++ and the same source code.

However, when I compile the program through em++, the wav file will fail to load, with the message "Unrecognized music format". (Note that this problem is independent of the traditional issues with Chrome and SDL2's Mixer, which were already solved with a snippet of Javascript.)

I am unaware of any compiler flags that would convince em++ to enable WAV as a media type, and it doesn't seem to need them when compiling to the desktop, so after a day of research I'm convinced this is some kind of a bug. Playback failed on Chrome and Firefox, until I converted the wav to an ogg and loaded it as such; in which case, music playback did start working. SDL2 appears to support wav, but through emscripten it does not.
[sdl2_mixer_test.tar.gz](https://github.com/emscripten-core/emscripten/files/4929356/sdl2_mixer_test.tar.gz)

I'm currently compiling by hand, instead of using a make file, and my command is:

```
$ em++ ./audio.cpp -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lpng --use-preload-plugins -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 -s SDL2_IMAGE_FORMATS='["bmp", "png"]' -s LLD_REPORT_UNDEFINED --preload-file assets --profiling -o bin/audio.js
```

I'm currently using Linux Mint 19.04.
Output of `emcc -v` follows.
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.19
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 7bf299c8d8d59304fb821f8811618cdeb1d1f1fd)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/michael/src/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
```

As stated, my workaround is to simply store music in, at worst, an OGG, which is both doable and probably what I would do anyway. This bug is a little weird though.

**Comment by kripken** [comment] 2020-07-17 21:29
#11577 may help here, new support is being added there.

**Comment by pudinha** [comment] 2020-07-18 13:50
Strange, I don't see a way to disable WAV support without deliberately modifying the port script. Neither before nor after my PR.

I can confirm that the WAV playback test does work correctly for me:
```
./tests/runner.py browser.test_sdl2_mixer_wav
```
even if I build it manually with `em++` like this:
```
cp sdl2_mixer_wav.c sdl2_mixer_wav.cc
cp sounds/the_entertainer.wav sound.wav
em++ \
	-s USE_SDL=2 \
	-s USE_SDL_MIXER=2 \
	--preload-file sound.wav \
	-D'REPORT_RESULT(x)'='((void*)0)' \
	-o sdl2_mixer_wav.html \
	sdl2_mixer_wav.cc
ruby -run -e httpd . -p 9090 & \
	(sleep 5; firefox localhost:9090/sdl2_mixer_wav.html)
```

**Comment by pudinha** [comment] 2020-07-18 14:19
I can also confirm that LazyFoo's lesson 21 does indeed crash as described by OP. So there's something happening there...

**Comment by pudinha** [comment] 2020-07-18 14:55
The issue is that SDL2_mixer needs to be built with `-DMUSIC_WAV` to be able to `MixLoadMUS("file.wav")`, even though it can `Mix_LoadWAV("file.wav")` without it.

@kripken should I submit a patch together with #11577, or wait until it's merged?

**Comment by kripken** [comment] 2020-07-20 18:02
Interesting, good find @pudinha !

I think a separate PR is better where possible. In any case I see that PR was merged anyhow, so looks like we have to in this case. Please mark the new PR as fixing this issue. Thanks!

**Closed** 2020-08-10 20:20 UTC
