### ISSUE TITLE
"Fatal: Module::addGlobal: gimport$121 already exists" when linking use emscripten 2.0.7

### ISSUE THREAD

**Issue by bluesfdw** [emscripten-core/emscripten#13227] opened 2021-01-11 10:11 UTC
Using emscripten 2.0.7,  the build got a linking error: `Fatal: Module::addGlobal: gimport$121 already exists 
em++: error: '/home/david/dev/autocad/bin/Fabric_WebDebugAsmjs32/refs/emsdk/upstream/bin/wasm-opt --strip-dwarf --safe-heap --strip-debug --strip-producers tests.wasm -o tests.wasm -g --mvp-features --enable-mutable-globals' failed (1)`

The build command line is:
`em++ -std=c++17 -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR -s MAIN_MODULE=2 -s DEMANGLE_SUPPORT=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s EVAL_CTORS=0 -s ASSERTIONS=2 -s SAFE_HEAP=1 -s DISABLE_EXCEPTION_CATCHING=0 -s TOTAL_MEMORY=218103808 -s DEMANGLE_SUPPORT=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s NO_EXIT_RUNTIME=0 -lnodefs.js --memory-init-file 1  -O1 -s INLINING_LIMIT=1 --profiling -s ERROR_ON_UNDEFINED_SYMBOLS=1 -flto -s WASM_OBJECT_FILES=0 -fPIC ./test-main.cpp.o ./test-property_tree_operations.cpp.o ./test1.bc  --pre-js "unittest-pre-js.js" `

1. Removing  --profiling or -s SAFE_HEAP=1 fixes this issue.  
2. The other projects without using dynamic linking also can not reproduce this error.
3. I cannot reproduce this on emscripten 2.0.8.

I tried to dump the wasm file before wasm-opt, the symbol gimport$121 sounds points to **__stack_pointer** of import table.

Please advise how to fix this build issue.
many thanks!

**Comment by sbc100** [comment] 2021-01-11 11:58
I wonder if this might be fixed by https://github.com/WebAssembly/binaryen/pull/3390?

You might be need to try the very latest SDK release (2.0.12) so get that change.

**Comment by sbc100** [comment] 2021-01-11 11:58
Oh way.. you say you can't reproduce on 2.0.8?  So presumably that means its been fixed already?

**Comment by bluesfdw** [comment] 2021-01-12 12:56
yes, it sound it got fixed in 2.0.8 but we cannot upgrade emscripten to 2.0.8 as It caused other build issues - (llvm memorySSA crash)

**Comment by sbc100** [comment] 2021-01-12 13:33
We don't really have any way to fix older releases in emscripten.  Making new releases is how we deliver fixes, so given that we have already fixed this issue I'm not sure what else we can do.   Is there some other thing you were expecting?

**Closed** 2021-04-06 14:34 UTC
