### ISSUE TITLE
Incorrect CC vs CXX detection

### ISSUE THREAD

**Issue by fta2012** [emscripten-core/emscripten#4522] opened 2016-08-27 18:33 UTC
After adding a flag along the lines of `--embed-file blah.m@blah.m` my code no longer compiled.

I believe the bug is from this line:
https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/emcc.py#L322
Which sets `use_cxx = False` if _any_ arguments end with '.m' or some other c/objc endings.

**Comment by kripken** [comment] 2016-08-28 17:39
I think you are correct, that's the bug. We should reorder the logic and set `use_cxx` based on `input_files` which is lower down, and is the actual set of input files.

Should be pretty simple if you or someone else wants to do this, although it also requires moving some other python around from a quick glance.

**Comment by Benny-** [comment] 2016-10-02 20:56
I'm on it.

**Comment by Benny-** [comment] 2016-10-03 16:49
I could not reproduce this problem using the example below.

```bash
echo "// blah.m content" > blah.m
./emcc --embed-file blah.m@blah.m tests/hello_world.cpp
```

**Comment by Benny-** [comment] 2016-10-03 16:54
On a related note I executed the following lines
```bash
rm "blah.m" # Ensure the embed file does not exist
./emcc --embed-file blah.m@blah.m tests/hello_world.cpp
```

And got as output:
```
Warning: blah.m@blah.m does not exist, ignoring.
Nothing to do!
```

No output file was generated if the embed file didn't exist.

Is this the error this issue is about? The fix for this lies somewhere else.

**Comment by kripken** [comment] 2016-10-03 17:10
@Benny-: I think to reproduce the problem, it must be a file that *needs* to be compiled as C++. A cpp file that compiles ok as either C or C++ would not hit the bug. @fta2012, is that right? Can you perhaps provide a full testcase if not?

**Comment by Benny-** [comment] 2016-10-03 21:07
I modified the test file a bit to use exclusive c++ constructs like namespaces and the `<<` operator. It still compiles using `./emcc --embed-file blah.m@blah.m tests/hello_world.cpp`. A testcase from @fta2012 is much appreciated.

```c++
#include<iostream>

class Test {}; // This will fail in C mode

using namespace std;

int main()
{
    cout << "Hello World" << endl;
}
```

**Comment by fta2012** [comment] 2016-10-04 05:19
Hmm the problem might be specific to embind then. Using your example:

```
./emcc --bind --embed-file blah.m@blah.m tests/hello_world.cpp
```

I get this error:

```
In file included from /home/fta/Desktop/external/emsdk_portable/emscripten/incoming/system/lib/embind/bind.cpp:1:
In file included from /home/fta/Desktop/external/emsdk_portable/emscripten/incoming/system/include/emscripten/bind.h:10:
In file included from /home/fta/Desktop/external/emsdk_portable/emscripten/incoming/system/include/emscripten/val.h:4:
/home/fta/Desktop/external/emsdk_portable/emscripten/incoming/system/include/emscripten/wire.h:24:5: error: 
      unknown type name 'constexpr'
    constexpr bool has_unbound_type_names = true;
    ^
```

But same code compiles just by changing the extension of the embed file:

    ./emcc --bind --embed-file blah.m@blah.txt tests/hello_world.cpp

(Problem also seems to go away if you set `-std=c++11` or `-std=c++1z` so I can no longer repro it on the [project](https://github.com/fta2012/ccv-js/blob/master/Makefile) I originally hit this bug with)

**Comment by fta2012** [comment] 2016-10-04 05:21
Just a note, it's not just `.m` files. Any c extension will trigger the same compilation error:

    ./emcc --bind --embed-file blah.m@blah.c tests/hello_world.cpp

**Closed** 2020-04-25 03:30 UTC
Labels: good first bug
