### ISSUE TITLE
CMake Error emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message): Failed to fetch compiler version information with command "'/home/%user%/emsdk/upstream/emscripten/emcc' -v"

### ISSUE THREAD

**Issue by aisnote** [emscripten-core/emscripten#18410] opened 2022-12-21 05:26 UTC
**cmake version 3.16.3**

**_part of build script:_**

```
cd ${EMSDK_PATH}

./emsdk install latest
./emsdk activate latest
source emsdk_env.sh

export PATH="${EMSDK_PATH}/upstream/bin:$PATH"
```

CMake Error at /home/%user%/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message): Failed to fetch compiler version information with command "'/home/%user%/emsdk/upstream/emscripten/emcc' -v"

HW0016385:**_~/emsdk/upstream/emscripten/cmake/Modules$ '/home/elliot/emsdk/upstream/emscripten/emcc' -v_**

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) **2.0.10**
clang version 12.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 445289aa63e1b82b9eea6497fb2d0443813a9d4e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/%user%/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

**Comment by aisnote** [comment] 2022-12-21 05:28
@sbc100 Could you help to check?  thanks a lot.

![image](https://user-images.githubusercontent.com/1201634/208828461-9da6a6f5-2180-48d7-a641-77763afe440e.png)

**Comment by sbc100** [comment] 2022-12-21 15:37
What is reported when you run `/home/elliot/emsdk/upstream/emscripten/emcc -v`?

**Comment by sbc100** [comment] 2022-12-21 15:38
BTW you don't need to specify `-DCAMKE_TOOLCHAIN_FILE` when using `emcmake`.. it adds that for you.

**Comment by aisnote** [comment] 2022-12-21 17:50
> 

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.10
clang version 12.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 445289aa63e1b82b9eea6497fb2d0443813a9d4e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/%user%/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@MX32
Selected multilib: .;@m64

**Comment by aisnote** [comment] 2022-12-21 17:51
> BTW you don't need to specify `-DCAMKE_TOOLCHAIN_FILE` when using `emcmake`.. it adds that for you.

I removed this from the build script, still meet the same issue. 

BTW, If I used emcc 3.10 version, it will not have this issue.
Thanks.

**Comment by sbc100** [comment] 2022-12-21 19:45
> > 
> 
> emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.10 clang version 12.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 445289aa63e1b82b9eea6497fb2d0443813a9d4e) Target: x86_64-unknown-linux-gnu Thread model: posix InstalledDir: /home/%user%/emsdk/upstream/bin Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9 Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9 Candidate multilib: .;@m64 Candidate multilib: 32;@m32 Candidate multilib: x32;@MX32 Selected multilib: .;@m64

Does `%user%` actually appear in the output there, or did you modify it?

What does `where emcc` say?

**Comment by sbc100** [comment] 2022-12-21 19:46
> > BTW you don't need to specify `-DCAMKE_TOOLCHAIN_FILE` when using `emcmake`.. it adds that for you.
> 
> I removed this from the build script, still meet the same issue.
> 
> BTW, If I used emcc 3.10 version, it will not have this issue. Thanks.

Can you find out which version this started failing with:  https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by aisnote** [comment] 2022-12-21 23:39
> 

I modified the username for post here.

**Comment by aisnote** [comment] 2022-12-21 23:42
> What does `where emcc` say?

I did not add emcc path to the system env.  I just set that in my build script like:

```shell
EMSDK_PATH=/home/$username/emsdk
# EMSDK_PATH=/home/$username/emsdk-3.1.20

cd ${EMSDK_PATH}

./emsdk install latest
./emsdk activate latest
source emsdk_env.sh
```

**Comment by aisnote** [comment] 2022-12-21 23:57
anything I need to add to system's $PATH like below:
export PATH="${EMSDK_PATH}/upstream/bin:$PATH"

**Comment by sbc100** [comment] 2022-12-22 01:25
`source emsdk_env.sh` should add emcc to your PATH. 

If you can run `emcmake` then you should also be able to run `emcc` because they are in the same path.

Can you add `emcc --version` to your build script right before the `emcmake` call?

**Comment by sbc100** [comment] 2022-12-22 01:27
> anything I need to add to system's $PATH like below: export PATH="${EMSDK_PATH}/upstream/bin:$PATH"

Actually `upstream/bin` doesn't need to be in your PATH to use emscripten but `upstream/emscripten` does.  emsdk_env should add the later but not the former.   

If you use emsdk_env should don't need to do any PATH modification yourself.  If you choose not to use emsdk_env you can do the modifications yourself.  Think of it as an "either or".

**Comment by aisnote** [comment] 2022-12-22 01:39
**help from emcc-2.0.10:** 
"-v"
   Turns on verbose output.

   This will pass "-v" to *Clang*, and also enable "EMCC_DEBUG" to
   generate intermediate files for the compiler's various stages. It
   **will also run Emscripten's internal sanity checks on the** toolchain,
   etc.

   Tip:

     "emcc -v" is a useful tool for diagnosing errors. It works with
     or without other arguments.


**and emcc-3.1.20 --help** 

"-v"
   [general] Turns on verbose output.

   This will print the internal sub-commands run by emscripten as well
   as "-v" to *Clang*.

   Tip:

     "emcc -v" is a useful tool for diagnosing errors. It works with
     or without other arguments.

**Comment by aisnote** [comment] 2022-12-22 01:42
> Can you add `emcc --version` to your build script right before the `emcmake` call?

yes. it can run and the output is:

```
emcc (Emscripten gcc/clang-like replacement) 2.0.10 (28b1af76755d0950cab70f3e33432d9c10916236)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by aisnote** [comment] 2022-12-22 01:45
emcc -v output as below, **_possible it caused the sanity check failed?_**

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.10
clang version 12.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 445289aa63e1b82b9eea6497fb2d0443813a9d4e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/elliot/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)

**Comment by sbc100** [comment] 2022-12-22 01:46
So the next step is to fine out why you can run `emcc -v`.. but apparently cmake cannot.  Can you look in the cmake output directory for the the cmake log file to see what `emcc -v` might have failed.

(I don't think its related to the `Running sanity checks` lines)

**Comment by aisnote** [comment] 2022-12-22 01:52
_cmake_compiler_result = No such file or directory
_cmake_compiler_output =
_cmake_compiler_output1 =
CMake Error at /home/elliot/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:139 (message):
  Failed to fetch compiler version information with command
  "'/home/elliot/emsdk/upstream/emscripten/emcc' -v"! Process returned with
  error code No such file or directory.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:3 (project)


![image](https://user-images.githubusercontent.com/1201634/209037684-a401270b-fc6d-408f-ace7-eff34ceb1ba2.png)

**Comment by aisnote** [comment] 2022-12-22 01:54
supose _cmake_compiler_result should be 0, but actually is:
```
_cmake_compiler_result = No such file or directory
```

**Comment by aisnote** [comment] 2022-12-22 01:55
> /home/elliot/emsdk/upstream/emscripten/emcc' -v

and this path is existed.

**Comment by sbc100** [comment] 2022-12-22 01:57
I seems like its saying that `/home/elliot/emsdk/upstream/emscripten/emcc` doesn't exist .. but IIRC it does exist.  This seems rather odd.  

Perhaps you could add `set -x` near the top of the `emcc` shell script (after the #! line) to see if its maybe having trouble finding python?

**Comment by aisnote** [comment] 2022-12-22 04:40
+ PYTHON=
+ [ -z  ]
+ which python3
+ PYTHON=/usr/bin/python3
+ [ -z /usr/bin/python3 ]
+ [ -z /usr/bin/python3 ]
+ exec /usr/bin/python3 /home/elliot/emsdk/upstream/emscripten/emcc.py --version
emcc (Emscripten gcc/clang-like replacement) 2.0.10 (28b1af76755d0950cab70f3e33432d9c10916236)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by aisnote** [comment] 2022-12-22 04:42
cmake version 3.16.3 is mine. Any specific cmake version required?

**Comment by aisnote** [comment] 2022-12-22 05:36
> I seems like its saying that `/home/elliot/emsdk/upstream/emscripten/emcc` doesn't exist .. but IIRC it does exist. This seems rather odd.

I think from the cmake, the path is existed. Just the RESULT_VARIABLE is not right as tested.

```
execute_process(COMMAND "/home/elliot/emsdk/upstream/emscripten/emcc" "-v" RESULT_VARIABLE _cmake_compiler_result_path)

message("_cmake_compiler_result_path2 = ${_cmake_compiler_result_path}")  
```

And from my build script, the result is:
```
shared:INFO: (Emscripten: Running sanity checks)
emcc: error: no input files
_cmake_compiler_result_path2 = 1
```

**Comment by sbc100** [comment] 2022-12-22 11:42
emcc should not print `emcc: error: no input files` if `-v is given so maybe the `-v` is not getting passed correctly?

I will try with 3.16.3  locally to see if I can reproduce.

**Comment by sbc100** [comment] 2022-12-22 12:28
I tried with 3.16.3 and it works fine for me.  I added this line to the platform file just to be sure:

```
  message(STATUS "_cmake_compiler_result: ${_cmake_compiler_result}")  
```

```
../emcmake cmake-3.16.3-Linux-x86_64/bin/cmake ../test/cmake/static_lib
configure: cmake-3.16.3-Linux-x86_64/bin/cmake ../test/cmake/static_lib -DCMAKE_TOOLCHAIN_FILE=/usr/local/google/home/sbc/dev/wasm/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/local/google/home/sbc/dev/wasm/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
-- _cmake_compiler_result: 0
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/sbc/dev/wasm/emscripten/tmp
```

Note the ` _cmake_compiler_result: 0` line.

**Comment by sbc100** [comment] 2022-12-22 12:30
Wait, where is emscripten 2.0.10 coming from?  That version if very old.  Are you trying to use the version?

**Comment by sbc100** [comment] 2022-12-22 12:31
Perhaps your emsdk checkout needs to be updated?

**Comment by aisnote** [comment] 2022-12-22 16:58
> Wait, where is emscripten 2.0.10 coming from? That version if very old. Are you trying to use the version?

since some my code is old and only can be compile with this 2.0.10 version.

This is how I get the emsdk:
```
git clone -b 2.0.10 git@github.com:emscripten-core/emsdk.git

cd ${EMSDK_PATH}

./emsdk install latest
./emsdk activate latest
source emsdk_env.sh
```

**Comment by sbc100** [comment] 2022-12-22 17:24
Can you try doing it this way:

```
$ git checkout origin/main
$ ./emsdk install 2.0.10
$ ./emsdk activate 2.0.10
$ source emsdk_env.sh
```

I tried installing 2.0.10 and using cmake 3.16.3 and everything worked fine.

**Comment by aisnote** [comment] 2022-12-22 17:39
> Can you try doing it this way:
> 
> ```
> $ git checkout origin/main
> $ ./emsdk install 2.0.10
> $ ./emsdk activate 2.0.10
> $ source emsdk_env.sh
> ```
> 
> I tried installing 2.0.10 and using cmake 3.16.3 and everything worked fine.

same problem.
```
shared:INFO: (Emscripten: Running sanity checks)
shared:INFO: (Emscripten: Running sanity checks)
emcc: error: no input files
_cmake_compiler_result_path2 = 1
shared:INFO: (Emscripten: Running sanity checks)
emcc: error: no input files
_cmake_compiler_result_path3 = 1
_cmake_compiler_result_TEST = No such file or directory
_cmake_compiler_output_TEST =
_cmake_compiler_output1_TEST =
CMake Error at /home/elliot/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message):
  Failed to fetch compiler version information with command
  "'/home/elliot/emsdk/upstream/emscripten/emcc' -v"! Process returned with
  error code 1.
```

**Comment by aisnote** [comment] 2022-12-22 17:50
> I tried with 3.16.3 and it works fine for me. I added this line to the platform file just to be sure:

Yes. Before I used 3.1.20. It worked well. 

because **emcc.3.1.20 -v** seems did not go to do sanity check but emcc.2.0.10 will do the sanity check, the outputs are different as below, is this the root cause?

**emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.20** (5d878c99921ec247d34fb26a20b5a13d60d69e93)
clang version 16.0.0 (https://github.com/llvm/llvm-project 75767a0f9a926641edbef08e31ec2148ff45da67)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/elliot/emsdk-3.1.20/upstream/bin


**emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.10**
clang version 12.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 445289aa63e1b82b9eea6497fb2d0443813a9d4e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/elliot/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
**shared:INFO: (Emscripten: Running sanity checks)**

**Comment by sbc100** [comment] 2022-12-22 17:54
This is very strange.  That exact same thing works fine for me:

```
$ emcmake ~/bin/cmake-3.16.3-Linux-x86_64/bin/cmake .
configure: /usr/local/google/home/sbc/bin/cmake-3.16.3-Linux-x86_64/bin/cmake . -DCMAKE_TOOLCHAIN_FILE=/usr/local/google/home/sbc/dev/wasm/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/local/google/home/sbc/dev/wasm/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.29-git (057bc5534f59266328efed4c1e79640e15dc2bd1)
clang version 16.0.0 (https://github.com/llvm/llvm-project.git a9fe30a1f1808f8f68ffbaecf9c11c8419491851)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/google/home/sbc/dev/wasm/llvm-build/bin
_cmake_compiler_result_path2 = 0
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.29-git (057bc5534f59266328efed4c1e79640e15dc2bd1)
clang version 16.0.0 (https://github.com/llvm/llvm-project.git a9fe30a1f1808f8f68ffbaecf9c11c8419491851)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/google/home/sbc/dev/wasm/llvm-build/bin
_cmake_compiler_result_path3 = 0
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/sbc/dev/wasm/emscripten
```

**Comment by sbc100** [comment] 2022-12-22 17:57
I don't think the sanity check is related.. the compiler should not be saying `emcc: error: no input files` it should just be printing the version into.

Can you try running the same command with EMCC_DEBUG=1 set?

**Comment by sbc100** [comment] 2022-12-22 17:59
Works for me even with 2.0.10 and with the sanity check message showing:

```
((2.0.10)) $ ./emcmake ~/bin/cmake-3.16.3-Linux-x86_64/bin/cmake .
configure: /usr/local/google/home/sbc/bin/cmake-3.16.3-Linux-x86_64/bin/cmake . -DCMAKE_TOOLCHAIN_FILE=/usr/local/google/home/sbc/dev/wasm/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/usr/local/google/home/sbc/dev/wasm/emsdk/node/14.18.2_64bit/bin/node"
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.10
clang version 16.0.0 (https://github.com/llvm/llvm-project.git a9fe30a1f1808f8f68ffbaecf9c11c8419491851)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/google/home/sbc/dev/wasm/llvm-build/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
emcc: warning: LLVM version appears incorrect (seeing "16.0", expected "12.0") [-Wversion-check]
shared:INFO: (Emscripten: Running sanity checks)
_cmake_compiler_result_path2 = 0
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.10
clang version 16.0.0 (https://github.com/llvm/llvm-project.git a9fe30a1f1808f8f68ffbaecf9c11c8419491851)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/google/home/sbc/dev/wasm/llvm-build/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
emcc: warning: LLVM version appears incorrect (seeing "16.0", expected "12.0") [-Wversion-check]
shared:INFO: (Emscripten: Running sanity checks)
_cmake_compiler_result_path3 = 0
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/sbc/dev/wasm/emscripten
```

**Comment by aisnote** [comment] 2022-12-22 18:06
with EMCC_DEBUG=1

```
shared:DEBUG: successfully executed /home/elliot/emsdk/upstream/bin/clang --version
shared:DEBUG: sanity file up-to-date but check forced: /home/elliot/emsdk/upstream/emscripten/cache/sanity.txt
shared:DEBUG: successfully executed /home/elliot/emsdk/node/14.18.2_64bit/bin/node --version
shared:DEBUG: successfully executed /home/elliot/emsdk/upstream/bin/llc --version
shared:INFO: (Emscripten: Running sanity checks)
shared:DEBUG: successfully executed /home/elliot/emsdk/node/14.18.2_64bit/bin/node -e console.log("hello")
shared:DEBUG: sanity file up-to-date but check forced: /home/elliot/emsdk/upstream/emscripten/cache/sanity.txt
shared:DEBUG: successfully executed /home/elliot/emsdk/node/14.18.2_64bit/bin/node --version
shared:DEBUG: successfully executed /home/elliot/emsdk/upstream/bin/llc --version
shared:INFO: (Emscripten: Running sanity checks)
shared:DEBUG: successfully executed /home/elliot/emsdk/node/14.18.2_64bit/bin/node -e console.log("hello")
emcc: error: no input files
_cmake_compiler_result_path2 =
OUTPUT_VARIABLE =
```

**Comment by sbc100** [comment] 2022-12-22 18:11
Hmm.. that doesn't help much actually.  Can you edit `emcc.py` and look for `def run` around line 765 and add `print(args)` as the first line of that function?

**Comment by sbc100** [comment] 2022-12-22 18:12
Actually is there some output missing?  I was expecting to see something like this line as one of the first lines:

```
emcc:WARNING: invocation: ./emcc.py -v  (in /usr/local/google/home/sbc/dev/wasm/emscripten)
```

**Comment by aisnote** [comment] 2022-12-22 18:18
['/home/elliot/emsdk/upstream/emscripten/emcc.py', '-v']
shared:DEBUG: successfully executed /home/elliot/emsdk/upstream/bin/clang --version

**Comment by aisnote** [comment] 2022-12-22 18:18
> ['/home/elliot/emsdk/upstream/emscripten/emcc.py', '-v']

from **print(args)**

**Comment by sbc100** [comment] 2022-12-22 18:22
And is that the out from when run withing cmake?   If that is the output then I can't see how `emcc: error: no input files` could be printed.

Can you include the full output generated from withing cmake (the one that end with "no input files") and with EMCC_DEBUG=1.. can you include all the output of the emcmake command?

**Comment by aisnote** [comment] 2022-12-22 18:22
> I was expecting to see something like this line as one of the first lines:

```
emcc:WARNING: invocation: /home/elliot/emsdk/upstream/emscripten/emcc.py --version +  --js-library /mnt/c/Users
```

**Comment by sbc100** [comment] 2022-12-22 18:23
Ah, do you have `EMCC_CFLAGS` set in your environment?  That could explain this problem.

**Comment by aisnote** [comment] 2022-12-22 18:23
> can you include all the output of the emcmake command?

```
['/home/elliot/emsdk/upstream/emscripten/emcc.py', '-v']
shared:DEBUG: successfully executed /home/elliot/emsdk/upstream/bin/clang --version
shared:DEBUG: sanity file up-to-date but check forced: /home/elliot/emsdk/upstream/emscripten/cache/sanity.txt
shared:DEBUG: successfully executed /home/elliot/emsdk/node/14.18.2_64bit/bin/node --version
shared:DEBUG: successfully executed /home/elliot/emsdk/upstream/bin/llc --version
shared:INFO: (Emscripten: Running sanity checks)
shared:DEBUG: successfully executed /home/elliot/emsdk/node/14.18.2_64bit/bin/node -e console.log("hello")
shared:DEBUG: sanity file up-to-date but check forced: /home/elliot/emsdk/upstream/emscripten/cache/sanity.txt
shared:DEBUG: successfully executed /home/elliot/emsdk/node/14.18.2_64bit/bin/node --version
shared:DEBUG: successfully executed /home/elliot/emsdk/upstream/bin/llc --version
shared:INFO: (Emscripten: Running sanity checks)
shared:DEBUG: successfully executed /home/elliot/emsdk/node/14.18.2_64bit/bin/node -e console.log("hello")
emcc: error: no input files
_cmake_compiler_result_path3 = 1
_cmake_compiler_result_TEST = No such file or directory
_cmake_compiler_output_TEST =
_cmake_compiler_output1_TEST =
CMake Error at /home/elliot/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message):
  Failed to fetch compiler version information with command
  "'/home/elliot/emsdk/upstream/emscripten/emcc' -v"! Process returned with
  error code 1.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:31 (project)

```

**Comment by aisnote** [comment] 2022-12-22 18:24
![image](https://user-images.githubusercontent.com/1201634/209202000-9bbef3d4-638a-4299-8eee-5cd0620d36e2.png)

**Comment by sbc100** [comment] 2022-12-22 18:25
Can you try printing `args` on line 832.. it should just contain `-v` which means the block on line 833 should run which means the compiler should exit early.

**Comment by aisnote** [comment] 2022-12-22 18:29
> Ah, do you have `EMCC_CFLAGS` set in your environment? That could explain this problem.

  print(f"832 = {args}")
  
  if len(args) == 1 and args[0] == '-v': # -v with no inputs


```
832 = ['-v', '--js-library', '/mnt/c/
```

**Comment by aisnote** [comment] 2022-12-22 18:31
> Ah, do you have `EMCC_CFLAGS` set in your environment? That could explain this problem.

I do set this flag **EMCC_CFLAGS**

like below:

```
export EMCC_CFLAGS=" ${MERGE_JS_FILE
```

**Comment by sbc100** [comment] 2022-12-22 18:37
Ok, thats the problem then.  `EMCC_CFLAGS` should be ignored when `emcc -v` is run on its own.  This was fixed in #15785 which made it into 3.0.1.  

I think this means that running `emcmake` with `EMCC_CFLAGS` set prior to 3.0.1 doesn't work I'm afraid.

BTW, is there some reason you are using `EMCC_CFLAGS` rather then any of the normal way to add cflags using cmake?

**Comment by aisnote** [comment] 2022-12-22 18:41
> BTW, is there some reason you are using `EMCC_CFLAGS` rather then any of the normal way to add cflags using cmake?

I dont remember clear. But I can try to add via cmake cflags to try. 

Thanks for your help. Now cmake file is ok.
let me try to build to see.

**Comment by aisnote** [comment] 2022-12-22 18:52
so many errors. any idea?

![image](https://user-images.githubusercontent.com/1201634/209206255-65d8bbd2-7514-4352-8570-f1123c117bc9.png)

**Comment by sbc100** [comment] 2022-12-22 18:56
Perhaps we can close this issue and open another since that seems like a different problem?

Can you show include the full link command when you show link errors like that?   And can you include whether this issue occurs with latest emcc?

**Comment by aisnote** [comment] 2022-12-22 19:03
sure, let me open another issue. thanks again and very appreciated.

**Closed** 2022-12-22 19:04 UTC
