### ISSUE TITLE
Error while compiling tests in simde library

### ISSUE THREAD

**Issue by M-HT** [emscripten-core/emscripten#20250] opened 2023-09-14 14:47 UTC
When compiling simd-everywhere/simde#1060 using emscripten it fails.
Error log (and other details) are available here: https://github.com/simd-everywhere/simde/actions/runs/6172090486/job/16751643532?pr=1060#step:8:1076

**Comment by mr-c** [comment] 2023-09-26 07:16
@tlively Any hints here?

**Comment by mr-c** [comment] 2023-09-26 07:17
`unexpected runtime library name: exp10f`

**Comment by mr-c** [comment] 2023-09-26 07:25
Also fails for `latest` https://github.com/simd-everywhere/simde/actions/runs/6309342167/job/17129079064?pr=1060#step:8:1079

**Comment by mr-c** [comment] 2023-09-26 08:38
I can confirm that we don't get an error with 3.1.45, but we do with 3.1.46, `tot`, and `latest`

**Comment by kripken** [comment] 2023-09-26 17:39
If this is a regression between 3.1.45 and 3.1.46, please bisect to find out where it broke:

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

If you can't bisect using those instructions please provide a small and simple standalone testcase and I can try to find time to do it.

**Comment by M-HT** [comment] 2023-09-27 15:18
It compiles with this build: `./emsdk install 5f06439dd7b2d5a0e65112e631f60bde9d4d2b74`, but fails with the next one: `./emsdk install 778bb67ab7a77481be16f3316dbb56a1f5f3481a`.

**Comment by mr-c** [comment] 2023-09-27 15:42
Here's how to test the problematic file, instead of compiling everything: 

```
git clone https://github.com/simd-everywhere/simde.git
cd simde
mkdir emscripten-build
cd emscripten-build
meson setup --optimization 2 --cross-file ../docker/cross-files/emscripten64.cross ..
meson compile -j1 --verbose -- test/x86/svml-emul-c`
```

**Comment by kripken** [comment] 2023-10-02 19:38
Thanks for the bisection @M-HT , then this seems to be the breaking roll:

```
commit 778bb67ab7a77481be16f3316dbb56a1f5f3481a
Author: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Date:   Sat Sep 9 23:39:48 2023 +0000

    Roll llvm-project from eea232da827a to 18b67243550a (10 revisions)
    
    https://chromium.googlesource.com/external/github.com/llvm/llvm-project.git/+log/eea232da827a..18b67243550a
    
    2023-09-09 Jam) Marukawa [OpenMP][VE] Support OpenMP runtime on VE
    2023-09-09 i@tianshilei.me [Clang][OpenMP] Emit unroll directive w/o captured stmt (#65862)
    2023-09-09 joker.eph@gmail.com Fix MLIR integration test that requires ARM SVE to reproduce
    2023-09-09 vitalybuka@google.com [NFC][sanitizer] Return nullptr from PlatformDemangle
    2023-09-09 vitalybuka@google.com [NFC][sanitizer] Clarify nullability of Symbolizer::Demangle result
    2023-09-09 vitalybuka@google.com [NFC][sanitizer] Return nullptr instead of 0
    2023-09-09 joker.eph@gmail.com Switch MLIR to use the internal LIT shell by default  (#65415)
    2023-09-09 bjoern@hazardy.de [clang-format] BreakBeforeNoexceptSpecifier option added (#65808)
    2023-09-09 Matthew.Arsenault@amd.com clang: Add __builtin_exp10* and use new llvm.exp10 intrinsic
    2023-09-09 eymenunay@outlook.com [jitlink][rtdyld][checker] Re-apply 4b17c81d5a5 with fixes.
```

Unfortunately none of those seems obviously related to the crash trace which involves `WebAssemblyAsmPrinter::getOrCreateWasmSymbol`. But perhaps I'm missing something that LLVM people could see? cc @sbc100

**Comment by tlively** [comment] 2023-10-05 19:18
It's definitely this commit: 
```
2023-09-09 [Matthew.Arsenault@amd.com](mailto:Matthew.Arsenault@amd.com) clang: Add __builtin_exp10* and use new llvm.exp10 intrinsic
```
I'm sure these intrinsics are lowered to runtime functions like `exp10f` by default, and our LLVM backend doesn't know what to do with them.

**Comment by ashleynh** [comment] 2023-10-20 00:59
A fix: https://github.com/llvm/llvm-project/pull/69661

**Comment by ashleynh** [comment] 2023-10-20 19:20
Merged

**Closed by ashleynh** 2023-10-20 19:20 UTC
Labels: SIMD

**Comment by mr-c** [comment] 2023-10-20 21:01
Thank you @ashleynh ! When can we expect a fixed `tot` emsdk build?

**Comment by tlively** [comment] 2023-10-21 00:24
It should be in `tot` as of about an hour ago.

**Comment by mr-c** [comment] 2023-10-21 07:06
> It should be in `tot` as of about an hour ago.

with `sdk-releases-b1e14a8e92c943c2b246b4c6b4b692a63f4bbaa1-64bit` I get a (new?) failure:
```
Assertion `!ToFreeze && "freeze() not called with ToFreeze being set"' failed.`
```

To test locally, use [the same recipe as before](https://github.com/emscripten-core/emscripten/issues/20250#issuecomment-1737651272).

```
[1010/3548] /opt/emsdk/upstream/emscripten/emcc -Itest/x86/avx-native-c.js.p -Itest/x86 -I../test/x86 -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -Wno-unsafe-buffer-usage -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -MD -MQ test/x86/avx-native-c.js.p/avx.c.o -MF test/x86/avx-native-c.js.p/avx.c.o.d -o test/x86/avx-native-c.js.p/avx.c.o -c ../test/x86/avx.c
FAILED: test/x86/avx-native-c.js.p/avx.c.o 
/opt/emsdk/upstream/emscripten/emcc -Itest/x86/avx-native-c.js.p -Itest/x86 -I../test/x86 -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -Wno-unsafe-buffer-usage -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -MD -MQ test/x86/avx-native-c.js.p/avx.c.o -MF test/x86/avx-native-c.js.p/avx.c.o.d -o test/x86/avx-native-c.js.p/avx.c.o -c ../test/x86/avx.c
clang: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1096: (anonymous namespace)::ScalarizationResult::~ScalarizationResult(): Assertion `!ToFreeze && "freeze() not called with ToFreeze being set"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/opt/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -Itest/x86/avx-native-c.js.p -Itest/x86 -I../test/x86 -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g3 -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -Wno-unsafe-buffer-usage -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -MD -MQ test/x86/avx-native-c.js.p/avx.c.o -MF test/x86/avx-native-c.js.p/avx.c.o.d -c ../test/x86/avx.c -o test/x86/avx-native-c.js.p/avx.c.o
1.	<eof> parser at end of file
2.	Optimizer
 #0 0x00007f4146ed82a8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x1cd82a8)
 #1 0x00007f4146ed5d6e llvm::sys::RunSignalHandlers() (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x1cd5d6e)
 #2 0x00007f4146ed763e llvm::sys::CleanupOnSignal(unsigned long) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x1cd763e)
 #3 0x00007f4146e168b6 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x00007f4144c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f4144c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x00007f4144c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x00007f4144c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x00007f4144c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #9 0x00007f4144c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x00007f4148701364 (anonymous namespace)::VectorCombine::run()::$_0::operator()(llvm::Instruction&) const VectorCombine.cpp:0:0
#11 0x00007f41486febb5 llvm::VectorCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x34febb5)
#12 0x00007f41498155dd llvm::detail::PassModel<llvm::Function, llvm::VectorCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilder.cpp:0:0
#13 0x00007f41470bfba0 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x1ebfba0)
#14 0x00007f414c7e1e2d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) BackendUtil.cpp:0:0
#15 0x00007f41488188fb llvm::CGSCCToFunctionPassAdaptor::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x36188fb)
#16 0x00007f414981a3cd llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::CGSCCToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) PassBuilder.cpp:0:0
#17 0x00007f4148813886 llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x3613886)
#18 0x00007f41484ba59d llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) Inliner.cpp:0:0
#19 0x00007f4148816ba7 llvm::DevirtSCCRepeatedPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x3616ba7)
#20 0x00007f41484baced llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::DevirtSCCRepeatedPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) Inliner.cpp:0:0
#21 0x00007f4148815651 llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x3615651)
#22 0x00007f41484baa6d llvm::detail::PassModel<llvm::Module, llvm::ModuleToPostOrderCGSCCPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) Inliner.cpp:0:0
#23 0x00007f41470be7a0 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x1ebe7a0)
#24 0x00007f41484b7639 llvm::ModuleInlinerWrapperPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x32b7639)
#25 0x00007f4149806a0d llvm::detail::PassModel<llvm::Module, llvm::ModuleInlinerWrapperPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) PassBuilder.cpp:0:0
#26 0x00007f41470be7a0 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x1ebe7a0)
#27 0x00007f414c7d937a (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::__2::unique_ptr<llvm::raw_pwrite_stream, std::__2::default_delete<llvm::raw_pwrite_stream>>&, std::__2::unique_ptr<llvm::ToolOutputFile, std::__2::default_delete<llvm::ToolOutputFile>>&) BackendUtil.cpp:0:0
#28 0x00007f414c7d0fb7 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__2::unique_ptr<llvm::raw_pwrite_stream, std::__2::default_delete<llvm::raw_pwrite_stream>>) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x2bd0fb7)
#29 0x00007f414cc00747 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) CodeGenAction.cpp:0:0
#30 0x00007f414b406136 clang::ParseAST(clang::Sema&, bool, bool) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x1806136)
#31 0x00007f414d3f60df clang::FrontendAction::Execute() (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x37f60df)
#32 0x00007f414d368cbd clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x3768cbd)
#33 0x00007f414d480393 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x3880393)
#34 0x0000562532a1d7ca cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/emsdk/upstream/bin/clang+0x147ca)
#35 0x0000562532a1b1aa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#36 0x00007f414cfd87d9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__2::optional<llvm::StringRef>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>*, bool*) const::$_0>(long) Job.cpp:0:0
#37 0x00007f4146e165f6 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/emsdk/upstream/bin/../lib/libLLVM-18git.so+0x1c165f6)
#38 0x00007f414cfd8062 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__2::optional<llvm::StringRef>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>*, bool*) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x33d8062)
#39 0x00007f414cf958f3 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x33958f3)
#40 0x00007f414cf95e8e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__2::pair<int, clang::driver::Command const*>>&, bool) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x3395e8e)
#41 0x00007f414cfb7d9f clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__2::pair<int, clang::driver::Command const*>>&) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.18git+0x33b7d9f)
#42 0x0000562532a1a40a clang_main(int, char**, llvm::ToolContext const&) (/opt/emsdk/upstream/bin/clang+0x1140a)
#43 0x0000562532a29cd1 main (/opt/emsdk/upstream/bin/clang+0x20cd1)
#44 0x00007f4144c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#45 0x00007f4144c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#46 0x0000562532a16faa _start (/opt/emsdk/upstream/bin/clang+0xdfaa)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 18.0.0 (https://github.com/llvm/llvm-project 7e3d1103e6e7a7fa9b5f50222732e734d171bc86)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /opt/emsdk/upstream/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/avx-f4da1a.c
clang: note: diagnostic msg: /tmp/avx-f4da1a.sh
clang: note: diagnostic msg: 

********************
emcc: error: '/opt/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/opt/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -Itest/x86/avx-native-c.js.p -Itest/x86 -I../test/x86 -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g3 -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -Wno-unsafe-buffer-usage -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -MD -MQ test/x86/avx-native-c.js.p/avx.c.o -MF test/x86/avx-native-c.js.p/avx.c.o.d -c ../test/x86/avx.c -o test/x86/avx-native-c.js.p/avx.c.o' failed (returned 1)

```

https://github.com/simd-everywhere/simde/actions/runs/6595876656/job/17921341438?pr=1089

**Comment by mr-c** [comment] 2023-10-21 07:21
Since the issue with our `svml` sources has gone away and it is a new error message, I made a new issue: https://github.com/emscripten-core/emscripten/issues/20505

**Comment by tlively** [comment] 2023-10-21 07:34
This looks like an upstream LLVM bug that is not specifically related to Emscripten or WebAssembly. Can you also file a bug at https://github.com/llvm/llvm-project? Hopefully someone will pick it up quickly.

**Comment by mr-c** [comment] 2023-10-21 08:05
I git-bisected it to https://chromium.googlesource.com/emscripten-releases/+/edf0eb77a0d7fc83c4d363befce5b327bde89a79 a.k.a. https://chromium.googlesource.com/external/github.com/llvm/llvm-project.git/+log/740ee00a4c1d..f70963c69d02

**Comment by mr-c** [comment] 2023-10-21 09:12
@tlively okay, I opened https://github.com/llvm/llvm-project/issues/69820
