### ISSUE TITLE
I complie two c file to wasm file ,but result is same 

### ISSUE THREAD

**Issue by pumpkindev** [emscripten-core/emscripten#8521] opened 2019-04-30 07:55 UTC
math.c
`#include<stdio.h>
int add (int x, int y) {
  return x + y;
}
int  square (int x) {
  return x * x;
}
`
math.wasm
`(module
  (type $t0 (func))
  (import "env" "__memory_base" (global $env.__memory_base i32))
  (func $__post_instantiate (type $t0)
    get_global $env.__memory_base
    set_global $g1
    get_global $g1
    i32.const 5242880
    i32.add
    set_global $g2)
  (global $g1 (mut i32) (i32.const 0))
  (global $g2 (mut i32) (i32.const 0))
  (export "__post_instantiate" (func $__post_instantiate)))
`

and f.c
`int fibonacci(int num)
{
        if (num <= 0) return 0;
        if (num == 1 || num == 2) return 1;
        int fn = 1,        fn1 = 1,        fn2 = fn + fn1;
        for (int i = 4; i <= num; i++)
    {
                fn = fn1;
                fn1 = fn2;
                fn2 = fn1 + fn;          
    }
        return fn2;
}
`
f.wasm
`(module
  (type $t0 (func))
  (import "env" "__memory_base" (global $env.__memory_base i32))
  (func $__post_instantiate (type $t0)
    get_global $env.__memory_base
    set_global $g1
    get_global $g1
    i32.const 5242880
    i32.add
    set_global $g2)
  (global $g1 (mut i32) (i32.const 0))
  (global $g2 (mut i32) (i32.const 0))
  (export "__post_instantiate" (func $__post_instantiate)))
`

f.wasm is equal math.wasm
I use `emcc math.c -Os -s WASM=1 -s SIDE_MODULE=1 -o math.wasm`
I want export c function and js use it ,

**Comment by sbc100** [comment] 2019-04-30 17:46
Duplicate of #8522?

**Closed by sbc100** 2019-04-30 17:46 UTC
