### ISSUE TITLE
wasm-sourcemap takes exceedingly long on large input

### ISSUE THREAD

**Issue by Keno** [emscripten-core/emscripten#9101] opened 2019-07-29 04:13 UTC
When linking large wasm files, wasm-sourcemap can easily dominate the total time for the final link, exceeding all other stages of the process. For example with the following .o file (https://drive.google.com/open?id=1vO3s78ODAsABWOVLAuhGOfy1JJeFHk6D):

```
$ time emcc --source-map-base https://localhost:8888 -o wat.js nsysimg/text.o

real	0m2.661s
user	0m0.939s
sys	0m0.537s
$ time emcc -g4 --source-map-base https://localhost:8888 -o wat.js nsysimg/text.o
(no output file specified, not emitting output)

real	2m46.990s
user	2m46.239s
sys	0m1.973s
```

For the actual link I want to do, the total time is about 6 minutes, 5 minutes and 30s of which are spent in wasm-sourcemap.

**Comment by kripken** [comment] 2019-07-29 19:52
I think this is a duplicate of #8948?

**Comment by Keno** [comment] 2019-07-29 20:49
Probably in root cause (the method is inefficient), though I don't care about memory usage at all. My build machine has terabytes of it.

**Comment by kripken** [comment] 2019-07-29 21:26
Fair enough, yeah. I renamed the other issue to focus on speed as well. The rewrite discussed there should fix both.

**Closed by kripken** 2019-07-29 21:26 UTC
